### ISSUE TITLE
[docs] please document `appState` usage and purpose

### ISSUE THREAD

**Issue by peterblazejewicz** [auth0/auth0.js#1002]
### Description

From time to time the questions about `appState` opaque local object surface here or on the support forum:
https://community.auth0.com/t/pass-custom-parameters-on-auth0-login-redirect/19075
https://github.com/auth0/auth0.js/issues/662
They are used in the sample code already:
https://auth0.com/docs/quickstart/spa/vuejs#create-an-authentication-service

It could be beneficial to either add the as a note to the docs itself or even change the JDoc to incorporate optional parameter description

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

Thanks!

**Comment by luisrudge** [comment]
I think it's a good idea to add to our jsdocs. Do you want to send a PR with this? 🎉

**Comment by peterblazejewicz** [comment]
done, thanks!

**Comment by luisrudge** [comment]
Thanks for the PR!
