### ISSUE TITLE
webAuth.login does not call error callback on blocked user

### ISSUE THREAD

**Issue by jaimesangcap** [auth0/auth0.js#1003]
When logging in user by using below code. I expect the error callback to be called on the following case:

- When logging in with incorrect username or password (working with 401 response)
- When logging in with correct credentials BUT BLOCKED User (not working, callback function not being called)

```
webAuth.login(
        {
          realm: AUTH_REALM,
          username: e.username,
          password: e.password
        },
        (err, authResult) => {
          // 401 error
        }
      )

```

### Environment

- Version of Auth0.js used: `"auth0-js": "^9.10.2",`
- Browser and OS version(s) affected: `Chrome Version 75.0.3770.100 (Official Build) (64-bit)` & OSX Mojave 10.14.2
- Additional libraries or browser extensions being used that might affect behavior:

### Reproduction

1. Assuming you have the correct `WebAuth` config
```
const params = Object.assign(
  {
    domain: config.auth0Domain,
    clientID: config.clientID,
    redirectUri: config.callbackURL,
    responseType: 'code',
    // required on custom domain setup
    overrides: {
      __tenant: config.auth0Tenant,
      __token_issuer: config.authorizationServer.issuer
    }
  },
  config.internalOptions
)

export const webAuth = new WebAuth(params)

```

2. Then call the `login` function with the correct username/password and realm of BLOCKED user.
```
webAuth.login(
        {
          realm: AUTH_REALM,
          username: e.username,
          password: e.password
        },
        (err, authResult) => {
          // should have 401 unauthorized error
        }
      )
```
3. You should received 401 error. (But current behaviour returns 200)

**Comment by luisrudge** [comment]
`webAuth.login`, by default, uses a redirect based flow, which means you'll get the error in your callback page. If you want to use a non-redirect flow, you can try adding `popup:true` to your options. Although the option is called `popup`, it currently uses an iframe, so there will be no popups visible 😬
