### ISSUE TITLE
[docs] JSDoc form DbConnection.signup does not contain entry for `username`

### ISSUE THREAD

**Issue by peterblazejewicz** [auth0/auth0.js#1005]
It seems `username` field of the signup options is not directly documented in the JSDoc, but only in the public docs, which list the field:
https://auth0.com/docs/libraries/auth0js/v9#signup
while the method JSDoc omits it completely:
https://github.com/auth0/auth0.js/blob/cee609cca97eefaa60818bd9b34e16685cf94276/src/authentication/db-connection.js#L21-L3
(I was looking into the api checking something, not into the public docs).
Is there an intent to modify the JSDoc?
Thanks!

**Comment by luisrudge** [comment]
Ops! We probably forgot to document that. Do you want to send us a PR with this? Thanks! 🎉

**Comment by peterblazejewicz** [comment]
sure thing!
