### ISSUE TITLE
superagent 3.8.3 breaks with modern babel -- please upgrade to 4.0.0+

### ISSUE THREAD

**Issue by jsoref** [auth0/auth0.js#1041]
### Description

A recent upgrade to @angular-devkit/build-angular pulls in a newer version of babel which is incompatible w/ superagent 3.8.3.

### Prerequisites

* [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).
* [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
* [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).
* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
* [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: 9.11.3
- Browser and OS version(s) affected:
- Additional libraries or browser extensions being used that might affect behavior: @babel 7.5.5

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippets or a sample project that reproduces the bug

`app.module.ts`:
```ts
import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { AppComponent } from "./app.component";
import WebAuth from "auth0-js";

function definescallback() {
    let webAuth = new WebAuth();
      webAuth.checkSession = function(args, callback) {
        callback(null, {
        });
      };
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

`app.component.ts`:
```ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html"
})
export class AppComponent {
}
```
`app.component.html`:
```html
```
(yes, it's an empty file, included for completeness)

- Log files (redact/remove sensitive information)
```
ng build "--prod" "--aot"
chunk {0} runtime-es2015.85f895af57b038f1e5b4.js (runtime) 2.82 kB [entry] [rendered]
chunk {1} main-es2015.03eade8e969e89d5dd78.js (main) 158 kB [initial] [rendered]
chunk {2} polyfills-es2015.bddaaad9393df6b3e306.js (polyfills) 64 kB [initial] [rendered]
chunk {3} polyfills-es5-es2015.9decb68ea6d8d0b61645.js (polyfills-es5) 222 kB [initial] [rendered]
Date: 2019-09-18T17:57:41.560Z - Hash: c211984ed4e733c82dda - Time: 17459ms
Generating ES5 bundles for differential loading...
An unhandled exception occurred: dist/main-es2015.03eade8e969e89d5dd78.js: Unexpected reserved word 'arguments' (1:146424)

> 1 | (window.webpackJsonp=window.webpackJsonp||[]).push([[1],{0:function(module,exports,__webpack_require__)
```

- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by markmakes** [comment]
Having the same issue with a brand new angular app and adding auth0-js package, importing it into a service and using:

new auth0.WebAuth()

**Comment by markmakes** [comment]
I did find that updating the browserslist like [suggested here](https://stackoverflow.com/questions/56197896/how-to-turn-off-differential-loading-in-angular-v8) works, but then this just removes the benefit of differential loading.

**Comment by jsoref** [comment]
I need to look into working on this again. Maybe in January

**Comment by stevehobbsdev** [comment]
@jsoref 👋 any update on this?

**Comment by gragland** [comment]
Looks like this is preventing auth0.js from working inside Netlify functions. A downstream dependency `formidable` hijacks `require` causing things to break.

See issue: https://github.com/netlify/netlify-lambda/issues/64#issuecomment-429625359

**Comment by jsoref** [comment]
I won't be able to look into this until May. Sorry.

**Comment by gragland** [comment]
@jsoref No worries. For future reference, this is only an issue if transpiling with Webpack. In my case I was using `netlify-lambda` to transpile. I worked around the issue by just not transpiling my server code.

**Comment by stevehobbsdev** [comment]
The associated PR here has been closed. If this is something you're still interested in pursuing, please feel free to re-raise.
