### ISSUE TITLE
auth0-js 9.8+ not compatible with Angular 8.2.7

### ISSUE THREAD

**Issue by IanParkison** [auth0/auth0.js#1047]
Steps: 
1) Clone https://github.com/auth0-blog/angular-auth0-aside and configure env auth0 fields.
2) Run "ng update @angular/cli @angular/core" to update to Angular 8.2.7.
3) Now run "ng build --prod", you should receive "Unexpected reserved word ‘arguments’" in the es2015 main. A dev build will succeed however.

I spent an entire day tracking down exactly where in my project the 'arguments' error was coming from. I narrowed it down to the auth0-js library integration. The repo mentioned above is a good test as it is a very small project, which makes it easy to eliminate outside variables. In auth0-js, I see there is a variable named 'arguments' in the Authentication function in index.js.

**Comment by luisrudge** [comment]
Hi @IanParkison. Thanks for reporting this. I found [this issue](https://github.com/angular/angular-cli/issues/15580) in the angular repo and I think it's totally related to the bug you're seeing. The angular team released a new version of `@angular-devkit/build-angular@0.803.6` that supposedly has a fix for this. Can you try this and report back what you find?

**Comment by IanParkison** [comment]
I updated my Angular project to version 8.2.8, which also updated the @angular-devkit to the version you mentioned. This resolved the issue and everything builds as expected.
