### ISSUE TITLE
Logout not working in Internet Explorer, localhost

### ISSUE THREAD

**Issue by dauledk** [auth0/auth0.js#1048]
### Description

We are running an angular SPA. Logout works flawlessly, but not in IE11 localhost. Here we are automatically logged in again! Konrad from the community sent me here, after creating a [post in the auth0 community](https://community.auth0.com/t/logout-not-working-in-internet-explorer-localhost/31843).

### Reproduction

Use the Auth0.js logout() method, running Internet Explorer 11 on localhost.
Our code looks like this:

```typescript
const options: auth0.LogoutOptions = {
    clientID: "<our-client-id>",
    returnTo: "http://localhost:4200/login",
};
this.auth0.logout(options);
```
We have a reauthenticate guard running before visiting /login (to protect people from typing their password to often). However in IE on localhost, auth0 always seems to be able to login theese users, despite we just used the `logout()` method. The guard simply uses `this.auth0.checkSession`. But again, it even works in IE when not running on localhost 🤷🏻‍♂️

### Environment

> Please provide the following:

- **Version of this library used:** 9.10.2
- **Version of the platform or framework used, if applicable:** Angular 8
- **Other relevant versions (language, server software, OS, browser):** IE11 only

**Comment by luisrudge** [comment]
@dauledk are you correctly redirected to the /logout endpoint?

**Comment by dauledk** [comment]
I think we need a clean Angular project to reproduce this in, because currently our application crashes on IE localhost when I try log out (so I can't answer your question). I will create a small application so you can reproduce the error if you wan't?

**Comment by stevehobbsdev** [comment]
@dauledk Sharing a small, reproducable sample app that also fails in the scenario you describe. would be most helpful! Let us know when you have one we can look at 👍

**Comment by lbalmaceda** [comment]
Inactive and community post closed. Feel free to reopen if the issue persists and you were able to create the sample repro app.
