### ISSUE TITLE
Cookies com.auth0.auth.* have no secure flag

### ISSUE THREAD

**Issue by GaryFreeman** [auth0/auth0.js#1050]
### Description

Cookies created after calling to WebAuth.authorize method have no secure flag when using https protocol.

### Reproduction

1. Call WebAuth.authorize method.
2. It will create cookie that starts with "com.auth0.auth".
3. Even if you are using https protocol, there is no secure flag on cookie.

### Environment

> Please provide the following:

- **Version of this library used:** 9.11.3
- **Version of the platform or framework used, if applicable:** Angular 8.2.8

**Comment by joshcanhelp** [comment]
@GaryFreeman - The cookie that it's setting with that name is just a nonce/state value, something that's not important to protect and only used be Auth0.js. We set the cookie, attach the value to the authorize URL, redirect, then check the value when it comes back. There's nothing in that value that's sensitive and it's not meant to be sent anywhere. 

I'll close this for now but let me know if you have any other questions here.

**Comment by jgautheron** [comment]
@joshcanhelp - Even though no critical data is stored, for some security audits, any cookie that is not secured will be a problem. Any chance we could add the option to add the `secure` flag to the cookies?

**Comment by andrewphahn** [comment]
This is an issue for us after having penetration test done as @jgautheron stated. It seems like a simple fix, would it be possible to address this?

**Comment by 5sp** [comment]
@joshcanhelp, this has been a blocking issue for us with pen test. Same as @andrewphahn and @jgautheron  mentioned above.
Any ideas how to avoid/bypass this issue?

**Comment by stevehobbsdev** [comment]
We can probably do something like what we do here in [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js/blob/5bf5292366e19d7a72b001f831b344b05cfcbaa5/src/storage.ts#L30-L35), we we set the `secure` attribute if you're using the HTTPS scheme - does this work?

**Comment by 5sp** [comment]
> We can probably do something like what we do here in [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js/blob/5bf5292366e19d7a72b001f831b344b05cfcbaa5/src/storage.ts#L30-L35), we we set the `secure` attribute if you're using the HTTPS scheme - does this work?

@stevehobbsdev, this looks like a great solution.
From what I can see currently, `com.auth0.auth*`, `co/verifier*` and `authToken` are affected.

**Comment by stevehobbsdev** [comment]
I've raised #1158 that should fix this, will be included in the next release 👍

**Comment by NikitaKoren** [comment]
@stevehobbsdev great job! When is next release is scheduled for?

**Comment by stevehobbsdev** [comment]
@NikitaKoren We don't have a schedule as such, but there is a piece of work in flight that we want to put into the release as well. I anticipate being able to do a release early next week.
