### ISSUE TITLE
Social microsoft login, force select account dialog

### ISSUE THREAD

**Issue by deemaagog** [auth0/auth0.js#1052]
### Description

Hi. I'm trying to implement social login with microsoft. The problem select account dialog doesn't appear if I have 1 microsoft account remembered in browser. I discovered prompt property, it works for google, but not for microsoft. How do I force select account dialog? Thanks in advance

### Reproduction

auth0.authorize({
      connection: 'windowslive', 
      prompt: 'select_account',
})

### Environment

> Please provide the following:

- **Version of this library used: 9.11.3**
- **Other relevant versions (language, server software, OS, browser): Chrome, Edge**

**Comment by stevehobbsdev** [comment]
Hi @deemaagog, to achieve this you need to look into [passing parameters to identity providers](https://auth0.com/docs/connections/pass-parameters-to-idps#static-parameters), but you have to use the Auth0 API to first configure your Windows Live social connection with this parameter (either statically or dynamically. Currently there's no way to specify this data from either the management dashboard or through Auth0.js.

Let me know if the linked article helps you or if you have any further questions.

**Comment by stevehobbsdev** [comment]
Hi again @deemaagog, hold off making any changes for the moment, there may be an issue that's preventing this from working. Having an internal discussion about it.

**Comment by stevehobbsdev** [comment]
@deemaagog We've found an issue specific to the Windows Live social connection where the `prompt` parameter isn't being passed through correctly. Unfortunately I don't have a timeline for when it will be fixed, but I will report back as soon as I know anything more.

Thanks for reporting the issue! 💪

**Comment by cahman** [comment]
Hi @stevehobbsdev !

Is there any updates regarding this?

Thanks

Christoffer

**Comment by stevehobbsdev** [comment]
@cahman Yes - the server should now support sending this prompt value through, there was no change needed on the SDK side I don't think. Please let me know if that's still not working for you.
