### ISSUE TITLE
parseHash depends on window

### ISSUE THREAD

**Issue by antony** [auth0/auth0.js#1067]
### Description

despite not requiring it (since the hash data is passed in), parseHash has a dependency on window which generates warnings / causes errors when used in an environment which doesn't have a `window` global, such as an SSR environment.

I'm trying to build a [Sapper](https://sapper.svelte.dev) starter, which renders pages on the server-side before it renders on the client-side (for speed, PWA, device compatibility, etc), and uses the same code for both.

What happens is the dependency on window causes the page to render a 500 on the server, and generate console warnings, even though the SPA part quickly takes over and the code works.

### Reproduction

It's difficult to provide a repro without a full project, but removing the dependency on window (and any browser specific globals) will fix the issue.

I'm willing to provide a demo project if required.

### Environment

- Latest auth0.js version v9.12.1
- Sapper 0.27.9 / Svelte 3.16.5

**Comment by stevehobbsdev** [comment]
@antony Yes a demo project would be great if you can provide one. Thanks for your patience in us getting back to you after the holidays.

**Comment by osdiab** [comment]
i'm moving my company's site onto next.js, and a little worried about this - will report if i experience this issue.

**Comment by stevehobbsdev** [comment]
@osdiab We have [an SDK specifically for Next.js](https://github.com/auth0/nextjs-auth0), does this help to alleviate concerns?

**Comment by osdiab** [comment]
Hmmm... maybe, but I am also worried now since we don’t use universal login at my company - we currently are on create-react-app, and we made our own login flow that isn’t on the Auth0 domain that just call the Auth0 api directly using Auth0.JS at the moment.

What I’m worried about is mostly that there aren’t any examples as far as I can tell that do what we’re doing at the moment; so I’ll try to figure it out how I’d translate what we have going to the nextJS setup, but guessing that we’re not going to get much support from Auth0 since we’ve strayed from the path of Universal Login. Wish us luck lol

**Comment by osdiab** [comment]
Yeah looking into it most likely scenario is we stick with this library but only dynamically import it with ssr: false. The nextJS library seems specifically for universal login with no bindings for us to handle things manually. Unfortunate given how bloated the bundle size of this library is but it is what it is.

**Comment by antony** [comment]
Disabling SSR for your application at arbitrary points isn't a wonderful thing to do.

Since the architecture of NextJS is very similar to Sapper, perhaps [my blog](https://enzy.org/blog/integrating-auth0-with-sapper) about how to integrate Auth0 in SSR mode with Sapper might be of use to you.

**Comment by osdiab** [comment]
@antony thanks for the suggestion but we don’t redirect to Auth0’s website for login, which in my opinion is even more jarring than disabling SSR for a dependency. Your example also seems to be based on that.

Also after scanning the Auth0 spa library that also forces you down the universal auth path. Guess we’ll be sticking with this after all. Oh well, it is what it is, hope it works as I hope.

**Comment by stevehobbsdev** [comment]
> Also after scanning the Auth0 spa library that also forces you down the universal auth path

Unfortunately, as you've discovered, Auth0 SPA SDK does not support embedded login (what you're trying to do) and it is not on the roadmap. Auth0.js or another custom solution is your best option here - sorry to be the bearer of bad news!
