### ISSUE TITLE
Make __clock property public

### ISSUE THREAD

**Issue by denkoleda** [auth0/auth0.js#1069]
Currently auth0.js relies on `new Date()` as defaultClock which makes user unable to sign in if their local machine clock is out of sync. Here is response from the example app:
![image](https://user-images.githubusercontent.com/58406206/71702941-41745780-2e26-11ea-8b6c-129455bc6e9b.png)

As well if client's machine time is far in future then expiration check fails:
![image](https://user-images.githubusercontent.com/58406206/71703378-5356fa00-2e28-11ea-9d37-4c644dd030fb.png)

For test purposes inside the project `__clock` option used. I assume this is private property since it is not mentioned in the documentation and can be changed in any time so we cannot rely on it in our project.

My suggestion is to make this option public and available for the library users so we can rely not on the client machine time but on our server time.

I'm currently working on the PR to make `__clock` public and rename it to `clock`. What do you think about it?

**Comment by denkoleda** [comment]
Created PR with changes https://github.com/auth0/auth0.js/pull/1070

**Comment by lbalmaceda** [comment]
Hi @denkoleda 
The property is private for a reason. It's only meant to be used on the tests, for asserting date-checks of the ID token validation logic. 

The issue you described above is a clock-sync issue between the computer where your app is running and the Auth0 server (issuer of the token). For this, the `WebAuth` constructor accepts a `leeway` property [in the options](https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L73-L77) which is the clock skew or tolerance your app will accept to avoid these issues. By default, this value is set to `60` seconds (check the latest version and changelog). But if this value is not enough for your use case, feel free to adjust it to increase that time window.

I'll close this issue and the PR, but let's keep the discussion here.

**Comment by denkoleda** [comment]
Hi @lbalmaceda, sorry for the long response time. I'm aware of the `leeway` option but the issue is in the fact that we rely on the client time for checking **expired / issued ahead of time** states and nothing can stop user from setting their own machine time for example 2 hour behind and if you have 1 hour token expiration time like we do then user will be unable to login because he will have expired token based on the local time check.

Can you please add some details why the `__clock` property cannot be made public or what is the best way to handle situation that I've described above?
