### ISSUE TITLE
SameSite cookie attribute changes

### ISSUE THREAD

**Issue by lukelengl** [auth0/auth0.js#1072]
With the [upcoming SameSite cookie attribute changes coming to Chrome 80 (and other browsers)](https://community.auth0.com/t/samesite-cookie-attribute-changes-are-here/34564), are there any changes that we need to make if we are using auth0.js?

**Comment by stevehobbsdev** [comment]
I don't believe so, no. The cookies that Auth0.js sets and uses will still be read OK despite the changes to samesite, and the cookies set by `auth0.com` (which are sent when you use `checkSession`, for example) already have the samesite changes applied to them.

**Comment by danielmariz** [comment]
Even though I'm getting the warning from chrome after using checkSession method.
Warning:
` 
A cookie associated with a cross-site resource at https://login.quicksense.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
`

currently using the latests auth0-js version.
Does someone knows how to get rid of this warning of when a new version is coming up to fix this?

**Comment by stevehobbsdev** [comment]
@danielmariz Just to confirm as it's not clear from your comment, but does `https://login.quicksense.org` point to an Auth0 tenant with a custom domain, or are you using Auth0.js with another IdP?

If it's the former, Auth0 also emits a legacy cookie without the samesite attribute for older browsers that don't support it. This is probably what the warning is about in that case. There's nothing we can do from the SDK side as it's a much wider Auth0 server thing, but also unfortunately necessary for legacy browser support.

**Comment by danielmariz** [comment]
I'm testing checkSession method to updated the accessToken and getting that warning  on chrome Version 80.0.3987.122.
`login.quicksense.org` is the auth0 domain, is a SPA going straight to the auth0 without a server side middleware.

I use a custom form with `webAuth.redirect.loginWithCredentials`
and `webAuth.parseHash` to handle the redirect after that.

but the warning pops out only when I request `webAuth.checkSession` which I need to do after around 24 hours to renew the accessToken we need on our back end apis so they won't return 401.

**Comment by stevehobbsdev** [comment]
@danielmariz As long as things are working now with Chrome 80 and the samesite flags turned on (which they should be by default) then you are good to go.

**Comment by Sbphillips19** [comment]
@stevehobbsdev I am still getting this warning and half the time I can't create an account and it sits at a white screen now:

`A cookie associated with a cross-site resource at http://auth0.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details`

I just updated my version of auth0 and am still getting this issue.  Where do I set the cookie?

> "auth0-js": "^9.12.2"

Version of chrome:

> Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by stevehobbsdev** [comment]
@Sbphillips19 You will still see this warning as we set a legacy cookie for older browsers that do not support the SameSite attribute. As long as everything is working as intended with your login flow, there is no need to worry. However, this is all to do with Auth0 server and nothing that the SDK can fix.

> half the time I can't create an account and it sits at a white screen now

Please tell me more about this - what steps are you going through that might allow me to try and reproduce? Do you have a repro set up that I can look and to try and debug?

**Comment by Sbphillips19** [comment]
I don't have a repo but basically my callback hangs on authorize about 50% of the time only in localhost.   It just says pending and it never pops open the authorize modal

**Comment by stevehobbsdev** [comment]
Are you getting any errors in the browser's developer console? Also, are you getting any errors in your [Auth0 Dashboard](https://manage.auth0.com/#/logs) which might help us debug this?

**Comment by Sbphillips19** [comment]
No errors in the auth0 dashboard.  I am not getting errors, the request just sits at pending.

**Comment by Sbphillips19** [comment]
Again it's just that one environment.  For some reason it seems to be happening less often now, but still definitely is happening
