### ISSUE TITLE
Required parameter `nonce` is not in @types/auth0-js

### ISSUE THREAD

**Issue by aryzing** [auth0/auth0.js#1075]
### Description

The `nonce` parameter is not in the types, but apparently required by `WebAuth`.

### Reproduction

If I include prop `nonce` below, I get a TS error (saying it should not be there). If I don't include it, I get a runtime error saying that `nonce` is a required param.

```
import { WebAuth } from 'auth0-js';

// later in file
    new WebAuth({
        domain: config.AUTH_DOMAIN,
        clientID: config.AUTH_CLIENT_ID,
        redirectUri: config.AUTH_REDIRECT_URI,
        audience: config.AUTH_AUDIENCE,
        responseType: constants.AUTH_RESPONSE_TYPE,
        scope: constants.AUTH_SCOPE,
        nonce: 'example_nonce' 
    });
```

### Environment

- **Version of this library used:**
@types/auth0-js: v9.12.3
auth0-js: v9.12.2
- **Version of the platform or framework used, if applicable:**
Node LTS (12.14.1)
Jest 24
babel 7.8.x

**Comment by stevehobbsdev** [comment]
@aryzing Have you got a stack trace from that error? We don't have any object validation on that property so I'm curious as to where it's being thrown. Do you get the error as soon as you try to create the object, or at some point later?

**Comment by stevehobbsdev** [comment]
@aryzing Apologies for the delay in response and in investigating this.

You want to supply the `nonce` parameter to the `authorize()` function, not on the `WebAuth` constructor as it's very specific to the authorize request.

Hopefully you've managed to troubleshoot this by now though - sorry again for the delay!

**Comment by dpistoleKUBRA** [comment]
I ran into this same error using `client.buildAuthorizeUrl`. It seems like the issue is that the `nonce` option is marked as optional in the `@types/auth0-js` package [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/auth0-js/index.d.ts#L831), but is required as per the assertion [here](https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js#L163).
