### ISSUE TITLE
Check the render method of 'Context.Consumer'

### ISSUE THREAD

**Issue by bergdaniel** [auth0/auth0.js#1076]
### Description

When navigating directly to a page when authenticated the setIsAuthenticated function fails. Using the sample code from https://auth0.com/docs/quickstart/spa/react, react-auth0-spa.js.

### Reproduction

Use sample code from https://auth0.com/docs/quickstart/spa/react (react-auth0-spa.js). Navigate directly to a page that is authentication protected/required. E.g. paste the URL into the browser and create a new GET-request. http://localhost:3000/protected-url.

Error:

_Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Context.Consumer`.
_
react-auth0-spa.js:32

<img width="462" alt="issue" src="https://user-images.githubusercontent.com/3921798/73388116-ef620d00-42d1-11ea-92da-e299557673bc.png">

### Environment

Version 1.6.3 of @auth0/auth0-spa-js.
Chrome 79.0.3945.130.

**Comment by bpirtle** [comment]
I'm seeing this also. Any workarounds?

**Comment by stevehobbsdev** [comment]
@bergdaniel Unfortunately I can't reproduce this here. If you're still seeing this, could you please raise this with a small repro project on the [`auth0-spa-js` SDK](https://github.com/auth0/auth0-spa-js)?

This repository is for a different SDK which is not relevant to your problem.
