### ISSUE TITLE
StorageHandler Failover Ordering

### ISSUE THREAD

**Issue by TopGunCoder** [auth0/auth0.js#1078]
### Description

While debugging an issue related to https://github.com/auth0/auth0.js/issues/1077 I noticed a potential issue with `StorageHandler`. The default behaviour is to start with `CookieStorage`, if that fails, the storage fails over immediately to `DummyStorage`.
See [the failover code ](19e9b5384e50) to see where this failover decision happens.

In our case this caused our `renewAuth` call to fail with '`state` does not match.'. Which I think would have happened if the storage failed and the state could not be retrieved.

### Expected Behaviour

Looking at the code I would assume that the intention was for:
- `StorageHandler` to start with either `LocalStorage` or `CookieStorage`(depending on whether [__tryLocalStorageFirst](https://github.com/auth0/auth0.js/blob/60f26b7fa811603633d11653843d51ce0c5b95b2/src/helper/storage/handler.js#L9) is set)
- then fail over to the other storage if that first storage type ends up failing.
- Finally it would resort to Dummy storage if neither of those end up working out.

### Reproduction
The easiest way to see this behaviour is to [go to the specs](https://github.com/auth0/auth0.js/blob/cee609cca97eefaa60818bd9b34e16685cf94276/test/helper/storage-handler.test.js#L150-L163)
There you can see that it is expected for us to failover in this order:`LocalStorage` > `CookieStorage` > `DummyStorage`.
So if we start on `CookieStorage` we go straight to `DummyStorage`.

If you want to see this in the wild you can use `Chrome Version 79.0.3945.130`(Official build). Then turn on [chrome://flags/#enable-experimental-web-platform-features](chrome://flags/#enable-experimental-web-platform-features).
Calling `renewAuth` in this context fails to save the cookie, then fails over to `DummyStorage`
For a more detailed account see https://github.com/auth0/auth0.js/issues/1077

### Environment
- **Version of this library used:** `v9.12.2`

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @TopGunCoder - are you still seeing this or is it something you've managed to fix/workaround yourself? #1077 mentions that parts of their app are being served in an iframe, does that scenario align with yours?

Turning on the experimental web platform features flag isn't ideal as it's not representative - what exact feature is being enabled there that would cause this issue?
