### ISSUE TITLE
CORS login via auth0-js.login() - does not send “rules” errors to callback

### ISSUE THREAD

**Issue by salvoravida** [auth0/auth0.js#1080]
CORS login via auth0-js.login() - does not send “rules” errors to callback

Hi,
i use auth0-hjs CORS login
```jsx
  auth.login(
    {
      realm: process.env.AUTH0_CONNECTION,
      username,
      password,
      state,
    },
    callback
  );
```
the problem is that if i have a Rules like “force email verification” on my dashboard,
i cannot get the error “please verify email” in this callback, instead, CORS login is fine,
and i have to “get” the error on NEXT redirect to my /callback .

Instead others errors, like Username or email not valid are visibled on the callback, without handle redirection!

the custom rules is 
```jsx
function (user, context, callback) {
if (!user.email_verified) {
return callback(new UnauthorizedError(‘Please verify your email before logging in.’));
} else {
return callback(null, user, context);
}
}
```

**Comment by salvoravida** [comment]
no one @ auth0 can reply please?

it seems a deprecated project! :D

**Comment by lbalmaceda** [comment]
@salvoravida 👋 can you post the response you get from the server on this scenario?

**Comment by salvoravida** [comment]
@lbalmaceda 
when you do login via CORS, normally you will get the login error like this
WITHOUT need to redirect!

URL: https://domain.eu.auth0.com/co/authenticate
Request Method: POST
Status Code: 403
{"error":"access_denied","error_description":"Wrong email or password."}

BUT if the login error is from a "Rule" like 

```
function (user, context, callback) {
if (!user.email_verified) {
return callback(new UnauthorizedError(‘Please verify your email before logging in.’));
} else {
return callback(null, user, context);
}
}
```

Then the error is not reported soon on the first CORS POST
URL: https://domain.eu.auth0.com/co/authenticate
Request Method: POST
Status Code: 200

but only on the callback url cal!!

I think this is a bug of CORS login

**Comment by stevehobbsdev** [comment]
Apologies for not providing a response here sooner @salvoravida.

The reason you're seeing the error come back from the different endpoint is down to when Rules actually run. When you perform a CORS login with a valid user, a login ticket is being created when is then used when the `/authorize` endpoint is called, and this is where the rules are actually executed; after authentication takes place.

Effectively for the purposes of this conversation, the rules aren't executed on the CORS call, but on the subsequent authz call. This is why you're seeing custom errors being returned in a different place.

This is not something we have plans to change at the moment, and is a server issue. Therefore, I'll close this issue for now.
