### ISSUE TITLE
`user_metadata` vs. `userMetadata` in signup options

### ISSUE THREAD

**Issue by peterblazejewicz** [auth0/auth0.js#1081]
- auth0.js v9.*

Which version of the user metadata property when signing up shuld be more visible for developers? `user_metadata` as here:
https://auth0.com/docs/libraries/auth0js/v9#signup
or `userMetadata` as documented here:
https://github.com/auth0/auth0.js/blob/master/src/authentication/db-connection.js#L29

At the end both are corret as I believe they are aliased and merged:
https://github.com/auth0/auth0.js/blob/master/src/authentication/db-connection.js#L53

I could amend the JSDocs to stay in sync with current public facing docs,
Thanks!

**Comment by lbalmaceda** [comment]
@peterblazejewicz I can't answer on why both are accepted, I'm guessing is because of some backward compat issue we might have run into in the past. 

I don't think we have a preference either. But I agree docs should clearly point one to avoid confusion.

**Comment by peterblazejewicz** [comment]
Let you folks decide, thx for the info!

**Comment by stevehobbsdev** [comment]
Thanks for raising this @peterblazejewicz!
