### ISSUE TITLE
auth0.js 8 TypeError: IdTokenVerifier is not a constructor in Webpack build

### ISSUE THREAD

**Issue by jedwards1211** [auth0/auth0.js#1082]
### Description

I'm bundling my client-side code that uses auth0.js with Webpack 3.
When I call `WebAuth.handleAuthentication()`, I get the following error:

```
index.js:253 Uncaught (in promise) TypeError: IdTokenVerifier is not a constructor
    at Auth.WebAuth.validateToken (index.js:253)
    at Auth.WebAuth.validateAuthenticationResponse (index.js:196)
    at Auth.WebAuth.parseHash (index.js:160)
    at Auth.handleAuthentication (Auth.js:69)
```

Looking into the problem, `web-auth/index.js` does `var IdTokenVerifier = require('idtoken-verifier')`.
The problem is, Webpack resolves this to the ESM build of `idtoken-verifier`, which exports `{default: IdTokenVerifier}`, instead of CommonJS exporting the class.

Hence this regression occurred whenever the ESM build was introduced into `idtoken-verifier`.

auth0.js 9 doesn't have this issue because it does `import IdTokenVerifier from 'idtoken-verifier'` instead of `require`.  But 8 needs to be fixed.

### Reproduction

Run `WebAuth.handleAuthentication` within a Webpack bundle.

### Environment

> Please provide the following:

- **Version of this library used:** 8.12.3
- **Version of the platform or framework used, if applicable:** N/A
- **Other relevant versions (language, server software, OS, browser):** N/A
- **Other modules/plugins/libraries that might be involved:** `idtoken-verifier` 1.5.1, webpack 3

**Comment by lbalmaceda** [comment]
Thanks for the detailed report. Could it be that the solution relies on the Webpack 3 configuration of your application?

**Comment by jedwards1211** [comment]
I don't know if there's a way to work around this in Webpack 3 or 4

**Comment by stevehobbsdev** [comment]
@jedwards1211 Is there anything blocking you from upgrading `auth0.js` to 9, given that you already know that it works?

**Comment by jedwards1211** [comment]
know that what works?
We probably don't have budget for the amount of time this upgrade will take unfortunately, as long as we're able to keep using v8.  It's a small customer that will likely be hit hard by the coronavirus shutdowns.
The Changelog for v9 says "If you are using a Hosted Login Page, keep using Auth0.js v8."  Is that still correct?
We currently redirect to the login page Auth0 provides, that's what hosted login page means right?
We don't use Lock.  The migration guide says "Use the custom domain when instantiating Lock" Does that mean we have to use Lock in v9?  Otherwise I would have expected the guide to say "If you're using lock, then..."

**Comment by stevehobbsdev** [comment]
@jedwards1211 Apologies, I had hastily assumed from the following that it was something you had tried:

> auth0.js 9 doesn't have this issue because it does import IdTokenVerifier from 'idtoken-verifier' instead of require

Are you doing anything to work around the issue currently? As this change to `idtoken-verifier` came in with [`1.3.0`](https://github.com/auth0/idtoken-verifier/commit/9464ac2875f93f729fb159ec626ef607c76d005e) - can you try installing this into your app and pinning it to `1.1.0` to see if that solves your issue, at least temporarily?

In the meantime I'll investigate the possibility of patching 8 with this change and upgrading `idtoken-verifier` appropriately.

**Comment by jedwards1211** [comment]
Yeah sorry I didn't clarify, I did workaround by pinning `idtoken-verifier`

**Comment by adamjmcgrath** [comment]
@jedwards1211 you could make webpack resolve the `main` field (the cjs file) by adding an alias to your webpack config:

```js
resolve: {
    alias: {
        'idtoken-verifier': require.resolve('idtoken-verifier')
    }
}
```

**Comment by stevehobbsdev** [comment]
Closing this for now. @jedwards1211 if the above ☝️ has not solved your issue and you require more help, please feel free to continue the discussion.

**Comment by umerali523** [comment]
> @jedwards1211 you could make webpack resolve the `main` field (the cjs file) by adding an alias to your webpack config:
> 
> ```js
> resolve: {
>     alias: {
>         'idtoken-verifier': require.resolve('idtoken-verifier')
>     }
> }
> ```

Hi , I don't have webpack config in my project is there anyother alternative or file where i could add the above mentioned lines to resolve this issue ?

**Comment by stevehobbsdev** [comment]
@umerali523 what is it that you're using to build/bundle your app that uses auth0.js?
