### ISSUE TITLE
Verified Linkedin Signup doesn´t work

### ISSUE THREAD

**Issue by tomasyaya** [auth0/auth0.js#1087]
Hello there.

I'm currently doing a LinkedIn signup through auth0.

For this, I have created my LinkedIn app and such. Inside my auth0 apps. when I go to social providers and test the LinkedIn signup it works (only with not verified attributes) but when I wanna use basic profile says that something went wrong. My LinkedIn is verified, I can see it in my developer platform. If I toggle between with or without basic profile attribute clicked then it goes from working to not working and so on.

Could you suggest me what can I be doing wrong? Should I refresh the client's secret? 

Thank you

**Comment by lbalmaceda** [comment]
Hi @tomasyaya. I don't know the answer but I'm guessing it might be related to using LinkedIn developer keys in your connection configuration. A quick search takes me to this article explaining the new 2.0 Sign-in API. Can you double-check the configuration is correct? https://auth0.com/docs/migrations/guides/linkedin-api-deprecation

**Comment by tomasyaya** [comment]
Thank you very much.

I will have a look!!

Yaya Tomas
011 155 763 3535

**Comment by stevehobbsdev** [comment]
Let us know how you get on, and feel free to continue the conversation @tomasyaya !
