### ISSUE TITLE
is SAML Protocol supported

### ISSUE THREAD

**Issue by sivagao** [auth0/auth0.js#1089]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

I use this repo to implement the new universal login for our application. however when i want to incorporate the zendesk into our system(using saml Protocol), the repo seems don't implement this like the lock.js（which is used in Auth0's classic. the classic login can make zendesk's saml work)

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Can I have some more detail on the problems you're seeing? What does this mean?:

> the repo seems don't implement this like the lock.js

Are you using the "New" login experience vs. Classic (Lock) here? Lock actually uses this library under the hood, so if Lock is _working_ for you I'd suggest the problem might lie elsewhere.

**Comment by sivagao** [comment]
Yes. we already used new login experience for our SaaS application. but when we want to integrate the zendesk as our support system , we encounter an issue. because zendesk use SAML Protocol, which don't be supported in auth0.js.

**Comment by stevehobbsdev** [comment]
> when we want to integrate the zendesk as our support system , we encounter an issue

@sivagao what's the issue you're seeing? Are you getting an error anywhere? Is there anything in the Logs panel in your [Auth0 Dashboard](https://manage.auth0.com/#/logs) that can help debug this?

**Comment by sivagao** [comment]
@stevehobbsdev I already fixed my code for SAML. thanks. I composed extra parameters from location.search for auth0

```js
{
                    connection: 'google-oauth2',
                    RelayState: queries.RelayState,
                    SAMLRequest: queries.SAMLRequest,
                    brand_id: queries.brand_id,
                    sso: true,
                    protocol: 'samlp',
                }
```
