### ISSUE TITLE
Update docs with more negative path example

### ISSUE THREAD

**Issue by airmanx86** [auth0/auth0.js#109]
I was trying to do the following redirect auth and handle wrong password or email situation. When not providing any callback, the error can only be caught by handling `window.onerror`...

```
  //trigger login with a db connection
  $('.login-dbconn').click(function () {
    auth0.login({
      connection: 'db-conn',
      username:   $('.username').val(),
      password:   $('.password').val(),
    });
  });
```

But if I provide a callback like below, It changed to single page app auth and failed to do the redirect login if the email and password is valid...

```
function (err, profile, id_token, access_token) {}
```

At the end after digging into source code / debugging through the library, it turns out that I need to provide a callback like below with exactly one argument.

```
function (err) {}
```

Knowing that there is already an issue filed about checking callback arguments
https://github.com/auth0/auth0.js/issues/26

And potentially a new API is coming, would it be possible to at least improve the documentation a little bit on negative path handling? It would save a lot of hours of debugging for very simple things like this.

**Comment by chill117** [comment]
@airmanx86 Thank you!!

**Comment by hzalaz** [comment]
Closing this one. We are reworking the library in v8 to make it explicit if you use popup and how to handle errors
