### ISSUE TITLE
Adding Promise Support to Auth0.js

### ISSUE THREAD

**Issue by XxX-MLGNoob-XxX** [auth0/auth0.js#1095]
I was wondering if there were any plans to support Promises? I've never been a big fan of callbacks, and I've gotten rather acquainted with async/awaits and then/catches. Many well-known libraries support promises, and it would be awesome to use them with auth0.js.

**Comment by adamjmcgrath** [comment]
Hi @XxX-MLGNoob-XxX - thanks for raising this

It's unlikely that we'll add Promise support to Auth0.js - but we have a new SDK that uses promises, which I encourage you to check out: https://github.com/auth0/auth0-spa-js
