### ISSUE TITLE
PKCE support in auth0.js

### ISSUE THREAD

**Issue by tmk555** [auth0/auth0.js#1101]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Implement PKCE flow in SPA with embedded login using auth0.js

### Describe the ideal solution

Use PKCE because of its more secure nature inherent from its token issue flow. Using PKCE flow allows us to get rid off URL length issue because of id/access token in URL fragments.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by stevehobbsdev** [comment]
Thanks for raising. We have no plans currently to implement PKCE support in Auth0.js - the recommendation is to use [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js), which does have support for PKCE.

**Comment by chingham** [comment]
Auth0 SPA SDK does not support Embedded Login (for custom UI)
How to use PKCE with Embedded Login ? None of your libraries support this ?

**Comment by stevehobbsdev** [comment]
Hi @chingham, no our SPA libraries do not support this library currently. However, you are able to use the Universal Login Page and the Custom Login Page template to customize your experience if you wish. Read more here: https://auth0.com/docs/universal-login/classic-experience/customization-classic

If you'd like to, the best place to register your feedback about this would be https://auth0.com/feedback.

Thanks.
