### ISSUE TITLE
Issue with callback in Gatsby

### ISSUE THREAD

**Issue by atmollohan** [auth0/auth0.js#1102]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description
I am working on my first gatsby site and decided to use Auth0 as my authentication service becasue I had heard good things about the way it integrates with gatsby. I followed this blog: https://auth0.com/blog/securing-gatsby-with-auth0/ and everything worked great as I was working great on desktop chrome. I noticed that there was a weird bug when I opened the site on my phone and tried to log in. It would bring me to the Auth0 page where I could authenticate fine and redirect to my callback page. On mobile the app gets stuck here waiting for the authentication to finish.

Here is a link to my repo: https://github.com/L-Town-FC/we-roast

This is the output of my gatsby info:
System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 3.7.7 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
  npmPackages:
    gatsby: ^2.20.12 => 2.21.19
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.3.2 => 2.4.3
    gatsby-plugin-antd: ^2.2.0 => 2.2.0
    gatsby-plugin-dark-mode: ^1.1.1 => 1.1.2
    gatsby-plugin-less: ^3.2.0 => 3.2.1
    gatsby-plugin-manifest: ^2.3.7 => 2.4.2
    gatsby-plugin-mdx: ^1.2.6 => 1.2.6
    gatsby-plugin-offline: ^3.1.5 => 3.2.1
    gatsby-plugin-react-helmet: ^3.2.1 => 3.3.1
    gatsby-plugin-sharp: ^2.5.3 => 2.6.2
    gatsby-plugin-typography: ^2.4.3 => 2.5.1
    gatsby-remark-images: ^3.3.1 => 3.3.1
    gatsby-source-contentful: ^2.3.2 => 2.3.3
    gatsby-source-filesystem: ^2.2.2 => 2.3.1
    gatsby-transformer-remark: ^2.7.4 => 2.8.7
    gatsby-transformer-sharp: ^2.4.3 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.11.15

I have already tried resetting the mobile devices safari and chrome but I still see the same issue.

I have also tried tearing everything down and rebuilding but the result is the same.

The callback page calls a handleAuthentication function which then sets the session and should reroute the user to the /app/profile page. 

Is this a common issue on iphones? If someone could take a look at this for me that would be super appreciated! Sam, who wrote the article and I have been discussing this issue and he told me to open the issue here so that it can be tracked here is a link to the discussion: https://community.auth0.com/t/securing-gatsby-with-auth0/24389/74 

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction
The issue is kind of hard to reproduce because it only happens on mobile devices. 
I am hosting the site on surge currently and the url is https://weroast.surge.sh/
You can see that when you go to it on a computer the login functionality works fine but as soon as you open it in mobile it gets stuck in the callback page.

### Environment

I included my gatsby info above but here is a link to my package.json too:
https://github.com/L-Town-FC/we-roast/blob/dev/package.json

> Please provide the following:

- "auth0-js": "^9.13.2"

**Comment by stevehobbsdev** [comment]
Hi @atmollohan, I couldn't see it called out specifically in your issue but you mentioned Safari - are you testing this on an iOS device?

If so, [we've seen something similar previously](https://community.auth0.com/t/sign-in-with-apple-universal-login-in-swift-results-in-a-blank-page/32517/21) which we believe to be an iOS bug. They've since fixed this in version 13.4.

Can you validate your iOS version to see if you might be affected?

**Comment by atmollohan** [comment]
@stevehobbsdev I just updated my phone and checked on safari and chrome. It is the same result as before. I wonder if there’s some flag that I need to pass in the SDK to make sure that auth0 knows what my app is trying to do. It seems like everything goes fine until the callback

**Comment by adamjmcgrath** [comment]
@atmollohan I've tested on Android and your login seems to work fine. If you can get your phone hooked up to a dev console and share the network and console output's we might be able to help you debug

**Comment by atmollohan** [comment]
@adamjmcgrath Oh really I just assumed that if it didnt work on my phone it didnt work on any mobile devices. I never tested with an android I've always just used my iPhone x. When you say it worked fine do you mean it returned you the the profile page or it just returned you to the site and stuck you in a loading page. On my phone it returns me to my site but gets stuck and shows a "loading" page. I wonder if this issue is only applicable to IOS. Do you know if its possible to see the network tab in chrome on IOS. I know you can look at the console log but am not sure about any of the other developer tools

**Comment by adamjmcgrath** [comment]
@atmollohan I was able to login to your profile page and see my user info.

I'm not to familiar with the ways of the iPhone, but you should be able to debug mobile safari in safari mac dev tools

**Comment by atmollohan** [comment]
@adamjmcgrath I'm surprised it worked on your android. I have been also constantly pushing up changes so it could have to do with caching on mobile devices. I have been regularly clearing my iphone's chrome and safari cache so that it always pulls the latest. I have gotten the profile page to load a handful of times but cant seem to get anything consistent. Every time my site bounces you two the auth0 domain my mac's dev tools close so its hard to capture any valuable logs. I wish there were a better way to debug this. On auth0's logs it says that the login was successful each time which makes sense. I think that something in the SDK is getting hung up in ios browsers.

**Comment by atmollohan** [comment]
@adamjmcgrath So I ended up redoing my login using@auth0/auth0-spa-js instead of auth0-js and everything seems to work now. Thanks for looking into this for me!
