### ISSUE TITLE
popup.passwordlessVerify makes a request to non-existent endpoint

### ISSUE THREAD

**Issue by majelbstoat** [auth0/auth0.js#1104]
### Description

I am building a custom embedded login form using auth0-js. (I can't use auth0-spa-js because it doesn't support embedded passwordless login.) The design is one that does not involve redirects.

I start a passwordless auth session with `client.passwordlessStart` and receive a code by email. I then use that code in a call to popup.passwordlessVerify:

```ts
const accessToken = await new Promise<Auth0Result>((resolve, reject) => {
          client.popup.passwordlessVerify(
            {
              type: 'email',
              connection: 'email',
              email,
              verificationCode,
            },
            (err: Auth0Error | null, result: Auth0Result) => {
              if (err) return reject(err)
              resolve(result)
            }
          )
        })
```

I expect that this should do something analogous to `popup.authorize()` and give me an id token that I can do something with.

Instead, the SDK makes a request to `oauth/ro`, which as far as I can see, has been deprecated since 2017, and removed since 2018. The response is a 404 error.

The latest community update I've seen is from 2018, stating passwordless was going to move to oauth/token: 

https://community.auth0.com/t/passwordless-oauth-ro-replacement/11951/5

Passwordless can clearly be done with Auth0 even for new tenants, as Auth0 Lock does it. Can this function be fixed to call the right endpoint, please?

### Environment

- **Version of this library used:** auth0-js v9

**Comment by jbuffin** [comment]
I'm giving this a +1 as well. I would like to do passwordless with the same flow as I have with social but I'm stuck redirecting the main window. I have a custom embedded form but `popup.passwordlessVerify()` does not work at all so I have to have 2 different flows for passwordless and social.

**Comment by majelbstoat** [comment]
@jbuffin if it helps, I just wrote a server side endpoint using auth0's server sdk which accepted a verification code and exchanged it for a token, and then just called my same local sign-in stuff using that token. Rough sketch:

```go
        var accessToken string
	var err error
	if in.VerificationCode != "" && in.Email != "" {
		accessToken, err = s.auth0.VerifyPasswordlessCode(ctx, in.Email, in.VerificationCode)
		if err != nil {
			return nil, errors.Unauthenticated("Failed to verify code")
		}
	} else if in.AccessToken != "" {
		accessToken = in.AccessToken
	} else {
		return nil, errors.BadRequest("Either accessToken, or verificationCode and email, must be supplied")
	}

	auth0, err := s.auth0.GetProfile(ctx, accessToken)
	if err != nil {
		return nil, errors.Wrap(err, "Failed to load profile")
	}
```

**Comment by jbuffin** [comment]
@majelbstoat While this kind of solution would work, I want to keep this fully OAuth compliant and don't want to proxy any requests through my servers. Otherwise, I could just set up my own OAuth service with IdentityServer. I'm using Auth0 so I don't have to do any of that and also so I don't have to ever have access to user credentials.

**Comment by majelbstoat** [comment]
This is still a problem.
