### ISSUE TITLE
token validation fails if key not first in jwks.json

### ISSUE THREAD

**Issue by AlexMasca** [auth0/auth0.js#1106]
### Description
Npm prebuild files are using an older version of idtoken-verifier which brakes the token validation if the jwks key is not the first in the keys list.

### Reproduction

As i do not own the auth0 server (i only did the FrontEnd implementation) I checked the files that are in node_modules after npm install and noticed that the "Could not find a public key for Key ID (kid)" error was called even when the key was in the jwks.json.

After further investigation into the minified files noticed that the for loop that checks the keys is not the same as in the idtoken-verifier version 2.0.3.

Found also a commit that fixed the issue:

https://github.com/auth0/idtoken-verifier/commit/faf94b32dedc9d108e1fdf3c38e5cadc4bf08eb4?diff=split

### Environment
- **Version of this library used: 9.13.2**
- **Other modules/plugins/libraries that might be involved: idtoken-verifier**

**Comment by stevehobbsdev** [comment]
@AlexMasca Thanks for raising this - let me raise a new release with the updated fix.
