### ISSUE TITLE
JSON.parse(token) has syntax error on IE 11 but works fine in Chrome

### ISSUE THREAD

**Issue by LiuZiHua-Andrew** [auth0/auth0.js#1110]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> We are running a react spa application by using auth0-spa-js. And previously it worked fine in IE, but after updated, it throw `Syntax error` when using IE and the caused area is JSON.Parse(...token)

### Reproduction
Click the button that will trigger `loginWithRedirect` in IE
Error: Syntax Error at `login(25, 7)`
> 
>
> Where applicable, please include:
>
> - When do authentication
`SCRIPT1002: Syntax error`
`login (25,7)`
> - After click into it
`var config = JSON.parse(
        decodeURIComponent(escape(window.atob('...tokens...'))),
      );`
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots
### Environment

> Please provide the following:

- **Version of this library used:** :  "@auth0/auth0-spa-js": "^1.6.5", 
- **Version of the platform or framework used, if applicable:** "IE 11"
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by LiuZiHua-Andrew** [comment]
Please close. 

After seeing the custom login html, found that the formatting will foamt `json.parse(fn(token))` into `json.parse( fn(token), \n )` and the extra comma will case this syntax error. There is no any issue for this repo

**Comment by adamjmcgrath** [comment]
Thanks for letting us know @LiuZiHua-Andrew - closing
