### ISSUE TITLE
Clarify or request to implement explicit returns stated in Callback of CheckSession

### ISSUE THREAD

**Issue by mdere-unbound** [auth0/auth0.js#1111]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello - based on this https://auth0.github.io/auth0.js/web-auth_index.js.html#line536 - I am using auth0.js through Lock.js and I am trying to implement a refresh system with Axios. One thing I am trying to figure out is how I should treat checkSession implementation to my refresh system. Initially looking at the documentation and deeper into the code - it doesn't seem like I can status out checkSession with respect to my intended Callback return - since the library I am using is expecting to return a resolved Promise and I am doing that in my callback. Looking at the link above I posted in the beginning of this description, it doesn't seem like it is returning the cb intended return.

### Describe the ideal solution

I am not specifically requesting a feature, but only if there is a proper workaround I can implement to really check if the checkSession did status out or not - so I can resolve an intended promise on my end. I want to hear from auth0 group on if what is the best practice on how you would ideally implement that

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by stevehobbsdev** [comment]
You're right! We just need to do another release to rebuild the docs. Let us fix that shortly - thanks for raising.
