### ISSUE TITLE
loggedIn / isAuthenticated$ returns true in crome and false in Firefox & crome anonymous.

### ISSUE THREAD

**Issue by tadeuhslima-fabricatrader** [auth0/auth0.js#1114]
### Description

I'm logging in using auth0 and did the app without problems. But when is goes to firefox or crome anonymous tab it doesn't authenticate the user and comes with an empty response on the token POST (https://fabricatrader.auth0.com/oauth/token). 

### Reproduction

authservice.ts
`import { Injectable } from '@angular/core';
import { Observable, from, throwError, BehaviorSubject, of, combineLatest } from 'rxjs';
import { shareReplay, catchError, concatMap, tap } from 'rxjs/operators';
import { Router } from '@angular/router';
import createAuth0Client from '@auth0/auth0-spa-js';
import Auth0Client from '@auth0/auth0-spa-js/dist/typings/Auth0Client';

declare let require: any;
let config = require("./../../../../auth_config.json");

@Injectable({
	providedIn: 'root'
})
export class AuthService {
	// Create an observable of Auth0 instance of client
	auth0Client$ = (
		from(
			createAuth0Client({
				domain: config.domain,
				client_id: config.clientId,
				redirect_uri: `${window.location.origin}`
			})
		) as Observable<Auth0Client>
	).pipe(
		shareReplay(1), // Every subscription receives the same shared value
		catchError(err => throwError(err))
	);

	// Define observables for SDK methods that return promises by default
	// For each Auth0 SDK method, first ensure the client instance is ready
	// concatMap: Using the client instance, call SDK method; SDK returns a promise
	// from: Convert that resulting promise into an observable
	isAuthenticated$ = this.auth0Client$.pipe(
		concatMap((client: Auth0Client) => from(client.isAuthenticated())),
		tap(res => this.loggedIn = res)
	);

	handleRedirectCallback$ = this.auth0Client$.pipe(
	  	concatMap((client: Auth0Client) => from(client.handleRedirectCallback()))
	);

	// Create subject and public observable of user profile data
	private userProfileSubject$ = new BehaviorSubject<any>(null);
	userProfile$ = this.userProfileSubject$.asObservable();

	// Create a local property for login status
	loggedIn: boolean = null;

	constructor(private router: Router) {
		// On initial load, check authentication state with authorization server
		// Set up local auth streams if user is already authenticated
		this.localAuthSetup();
		// Handle redirect from Auth0 login
		this.handleAuthCallback();
	}

	// When calling, options can be passed if desired
	// https://auth0.github.io/auth0-spa-js/classes/auth0client.html#getuser
	getUser$(options?): Observable<any> {
		return this.auth0Client$.pipe(
			concatMap((client: Auth0Client) => from(client.getUser(options))),
			tap(user => this.userProfileSubject$.next(user))
		);
	}

	private localAuthSetup() {
		// This should only be called on app initialization
		// Set up local authentication streams
		const checkAuth$ = this.isAuthenticated$.pipe(
			concatMap((loggedIn: boolean) => {
				if (loggedIn) {
					// If authenticated, get user and set in app
					// NOTE: you could pass options here if needed
					return this.getUser$();
				}

				// If not authenticated, return stream that emits 'false'
				return of(loggedIn);
			})
		);

		checkAuth$.subscribe();
	}

	login(redirectPath: string = '/') {
		// A desired redirect path can be passed to login method
		// (e.g., from a route guard)
		// Ensure Auth0 client instance exists
		this.auth0Client$.subscribe((client: Auth0Client) => {
			// Call method to log in
			client.loginWithRedirect({
				redirect_uri: `${window.location.origin}`,
				appState: { target: redirectPath }
			});
		});
	}

	private handleAuthCallback() {
		// Call when app reloads after user logs in with Auth0
		const params = window.location.search;

		if (params.includes('code=') && params.includes('state=')) {
			let targetRoute: string; // Path to redirect to after login processsed

			const authComplete$ = this.handleRedirectCallback$.pipe(
			// Have client, now call method to handle auth callback redirect
				tap(cbRes => {
					// Get and set target redirect route from callback results
					targetRoute = cbRes.appState && cbRes.appState.target ? cbRes.appState.target : '/';
				}),
				concatMap(() => {
					// Redirect callback complete; get user and login status
					return combineLatest([
						this.getUser$(),
						this.isAuthenticated$
					]);
				})
			);

			// Subscribe to authentication completion observable
			// Response will be an array of user and login status
			authComplete$.subscribe(([user, loggedIn]) => {
				// Redirect to target route after callback processing
				this.router.navigate([targetRoute]);
			});
		}
	}

	logout() {
		// Ensure Auth0 client instance exists
		this.auth0Client$.subscribe((client: Auth0Client) => {
			// Call method to log out
			client.logout({
				client_id: config.clientId,
				returnTo: `${window.location.origin}`
			});
		});
	}
}
`
authGuard.ts

`import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, UrlTree } from '@angular/router';
import { Observable } from 'rxjs';
import { AuthService } from './auth.service';
import { tap } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

    constructor(private auth: AuthService) {
    }

    canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | Promise<boolean|UrlTree> | boolean {
		return this.auth.isAuthenticated$.pipe(
			tap(loggedIn => {
				if (!loggedIn) {
					this.auth.login(state.url);
				}
			})
		);
	}
}`

If i console.log this.isAuthenticated$.subscribe(res => console.log('res' , res)); === true in crome and false in the other ways.

it also returns empty the answer for the token request by firefox and google anonymous tab. 

Hope you guys can help me out.

### Environment

"@angular/core": "~8.2.3",
"@auth0/auth0-spa-js": "^1.10.0",

**Comment by stevehobbsdev** [comment]
@tadeuhslima-fabricatrader The issue you've raised is not for this SDK - please can you re-raise this over at [auth0-spa-js](https://github.com/auth0/auth0-spa-js) if you are still running into trouble?

Thanks
