### ISSUE TITLE
Support for rotating refresh tokens

### ISSUE THREAD

**Issue by andreareginato** [auth0/auth0.js#1115]
### Describe the problem you'd like to have solved

> April 15, 2020 has been released the "rotating refresh tokens" functionality and it has not been implemented in `auth0.js`.

### Describe the ideal solution

> auth0.js enables to highly customised UI for login, signup, recovery pass and more. It even offers a higher degree of customisation than auth0-spa-js offers (and where rotating refresh tokens). I think auth0.js should be aligned in this functionality with auth0-spa-js, mostly to solve the blocking ITP issue on Safari, which does not enable the auth flow work correctly in safari 13.1.

### Alternatives and current work-arounds

> Current workarounds are to pass to enterprise plan (to use custom domain) which we can't afford at the moment and would be over-costly for a startup without revenue or to pass to `Universal Login` which we are not using due to highly customised UI interface. `auth0-spa-js` is not an option as it does not offer all the low level services auth0 offers.

### Additional context

> Thanks for taking this in consideration.

**Comment by stevehobbsdev** [comment]
Hi @andreareginato, thanks for raising. This is unfortunately an impossibility as Auth0 does not issue refresh tokens for the [implicit grant](https://tools.ietf.org/html/rfc6749#section-1.3.2), which is what this SDK uses, for security reasons. We can do this with auth0-spa-js as it uses the Auth Code + PKCE flow and therefore does not issue tokens through the URL.

As a means to workaround issues such as ITP2, please read [our guidance on local storage options with an SPA](https://auth0.com/docs/tokens/concepts/token-storage#browser-local-storage-scenarios).

**Comment by andreareginato** [comment]
Hi @stevehobbsdev, thanks for your answer.

I would love to ask for further information, taking this space to do so.

The user `auth0-spa-js` library is not a production option in [different ways](https://auth0.com/docs/libraries/auth0-spa-js/migrate-from-auth0js) (e.g. user signup). The link you showed me is very generic and I can't find a real workaround to the current issue to keep on using `auth0-js` and solving the ITP issue.

Could you please give some more detailed indications to solve the problem, if possible to solve.
It's not clear to me if a solution (out of custom domain) is possible with auth0-js.

Thanks a lot for your time.

**Comment by stevehobbsdev** [comment]
It's only somewhat mitigated when not using custom domains, unfortunately. With this SDK you are completely in charge of how you store tokens that your app uses. For your scenario you can alleviate the problem at little bit by storing your tokens in local storage. This would at least let your users refresh the page and come back and continue to have an access token (otherwise, if you're storing the token in memory, it would be lost).

You could increase the expiry time on the access token to a reasonable length as well. This can be done through the management dashboard. But I appreciate that by default the expiry time on these tokens is small.

At the end of the day, the only way to totally mitigate the problem is to use a custom domain so that your silent re-authentication works.

**Comment by andreareginato** [comment]
@stevehobbsdev thanks for your answer. Sure, custom domains are the ideal solution, but an higher cost of $1.000 per month is not possible for our current budgets. 

I ask you. Do you have any example of people using `auth0-spa-js` in combination with `auth0-js` in order to implement a fully functional custom UI in a web app? I would love to make it happen (TypeScript) and also conrtribute with an article if you think this is a viable possibility.

Thanks for your time.

**Comment by stevehobbsdev** [comment]
I can understand that the cost of implementation is prohibitive; you're right that it's not a solution for everyone.

Unfortunately I don't have a solid example that I can point you to. The two SDKs won't talk to each other per-say, but I can imagine you can initiate a login using one SDK to get an Auth0 session initiated, and then use the `checkSession` method on the other SDK to initialize it with an existing session. That's untested, but it might work.
