### ISSUE TITLE
Universal Login doesn't know the user's logged in.

### ISSUE THREAD

**Issue by Sven65** [auth0/auth0.js#1122]
I don't know if this is the right repo to report this in, but as I don't see any other repo relating to your hosted universal login, I'll use this one.

I've also asked this question on your [community forums](https://community.auth0.com/t/samlp-endpoint-doesnt-care-that-a-users-already-logged-in/46975), which has given me exactly zero responses at the time of submitting this issue.

### Describe the problem

Previously, using `https://<MY_DOMAIN>.eu.auth0.com/samlp/<CLIENT_ID>` in an iframe would redirect the user back to my application silently, provided they had logged in on the universal login page, accessed through `WebAuth.authorize()`.

Now, it requires the user to log in again.

### What was the expected behavior?

That the user won't have to log in again.

### Reproduction

1. Send the user to universal login using `WebAuth.authorize()`
2. Let the user login successfully
3. Have the user get redirected to the application
4. Open an iframe with the src set to `https://<MY_DOMAIN>.eu.auth0.com/samlp/<CLIENT_ID>`
5. See that the user will need to login again.

To reproduce, you can use [this](https://stackblitz.com/edit/react-i9drna) project on StackBlitz. Edit the `Auth.js` file to match up with your Auth0 application.

### Environment

- **Version of Auth0.js used:**

9.13.4

- **Which browsers have you tested in?**

Chrome

- **Other modules/plugins/libraries that might be involved:**

**Comment by nicosabena** [comment]
Hey @Sven65 
Auth0.js is not supposed to know if the user is logged in. If the hosted login page is displayed, it means that the Auth0 server decided that the user needs to be authenticated. This can happen for a variety of reasons:
- User wasn't previously authenticated
- The SAML request indicates `ForceAuthn="true"` (forces login)
- The application (in Auth0) is configured to force authentication on every request (`sso_disabled: true` setting via Management API v2)
- The session duration for the tenant is very short
- The request coming from the IFRAME is not sending the session cookie. Most browser would probably block cookies in this scenario, and embedding the authentication in an IFRAME is definitely not a recommended usage. 

If the above don't help, I'd suggest opening a support case with Auth0, but this is unrelated to Auth0.js.

Good luck!
