### ISSUE TITLE
Mocking Auth0 locally - Https is always prepended to auth0 domain

### ISSUE THREAD

**Issue by danmastrowcoles** [auth0/auth0.js#1134]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I've recently mocked the `@@config@@` for local development, and set the auth0Domain to a localhost (mock server), this is to avoid calling the real auth0 for local development.

The auth0Domain specified in `@@config@@` expects to not have a scheme, as https:// is always added before using it.

This means my mock server has to have https setup, which causes more complexity and other local dev issues.

### Describe the ideal solution

Customizing this currently hardcoded string -> instead of 'https' allow this to be customizable, or only add it if there is no scheme already there.
https://github.com/auth0/auth0.js/blob/b5e4f17ff6eff3faae33a1342663fac7b8152df5/src/authentication/index.js#L92

Ideally we would be able to specify the scheme, as an override, through the web auth config, however I understand that you do not want http to be used.

**Comment by frederikprijck** [comment]
Sorry for closing the issue automatically without feedback.
Let me have a chat internally with the correct people about this and get back to you.

Would you perhaps be interested in opening a PR to address this in the case that we want to make the scheme configurable?

**Comment by danmastrowcoles** [comment]
Created a PR for this issue to make the scheme an optional parameter.
