### ISSUE TITLE
Programmatic login with Cypress tests

### ISSUE THREAD

**Issue by omelnik** [auth0/auth0.js#1138]
Hello Auth0 team!

I'm trying to automate the login functionality in my Cypress tests and I'm facing one issue where I can't return data from my promise when I use `auth0.WebAuth`, but actually  I'm able to successfully login to the app with this client.  I'm using this version: `"auth0-js": "^9.14.0",

Here's my example:

*/utils/auth-helper.js
```js
import auth0 from "auth0-js";

function initializeAuth0Client(domain, redirectUri, clientID) {
  return new auth0.WebAuth({
    clientID,
    domain,
    audience,
    redirectUri,
    responseType,
    scope,
    overrides: {
      __token_issuer: `https://${domain}/`,
    },
  });
}

function handleLogin(client, user) {
  const username = user.email;
  const password = user.password;
  const realm = "Users";
  return new Promise((resolve, reject) => {
    client.login(
      {
        realm,
        username,
        password,
      },
      function (err, authResult) {
        if (err) {
          reject(authResult);
        }
        resolve(authResult);
      }
    );
  });
}

module.exports = {
  initializeAuth0Client,
  handleLogin
};
```
/integration/support/command.js

```js

Cypress.Commands.add("loginByApiWeb", (user) => {
  const auth0Client = initializeAuth0Client(domain, redirectUri, clientID);
  cy.wrap(handleLogin(auth0Client, user), {
    timeout: 10000,
  }).then((authResult) => {
    cy.log(authResult);
  });
});
```
When I tried just changing the client from ` auth0.WebAuth` to `auth0.Authentication` and I was able to return the response and received my access_token.

```js
function initializeAuth0Client(domain, redirectUri, clientID) {
  return new auth0.Authentication({
    clientID,
    domain,
    audience,
    redirectUri,
    responseType,
    scope,
    overrides: {
      __token_issuer: `https://${domain}/`,
    },
  });
}
```

<img width="564" alt="Screen Shot 2020-10-23 at 3 03 07 PM" src="https://user-images.githubusercontent.com/32174556/97057788-de80b800-1540-11eb-8215-33ffe2bbace7.png">

But I wasn't authenticated to the app and I got this error:
```
{original: {…}, code: "login_required", description: "Login required", error: "login_required", error_description: "Login required"}

```
Any help/suggestion will be appreciated. Thank you!

**Comment by yurii-sorokin** [comment]
@omelnik have similer issue, any luck fixing it?

**Comment by cody-hoffman** [comment]
@yurii-sorokin @omelnik same issue too, any luck?
