### ISSUE TITLE
How does one import this into the code

### ISSUE THREAD

**Issue by basickarl** [auth0/auth0.js#1140]
How does one import this into the code. There is no documentation on it.

import auth0 from 'auth0-js'; ?

**Comment by andreasvirkus** [comment]
Yes, your import is correct. You can then initialize a new instance of a WebAuth client:

```
import auth0 from 'auth0-js'

const webAuth = new auth0.WebAuth({
  domain: '',
  clientID: '',
  // ...
})
```

**Comment by stevehobbsdev** [comment]
Closing this as it looks to be answered. Thanks @andreasvirkus!
