### ISSUE TITLE
Getting the user profile not working

### ISSUE THREAD

**Issue by CRGavrila** [auth0/auth0.js#1143]
Hello, I followed the docs: https://auth0.com/docs/libraries/auth0js#updating-the-user-profile 
and getting user profile is not working.

Here is the snippets:
![image](https://user-images.githubusercontent.com/23153291/100066711-129c1100-2e3e-11eb-99c1-694b2c0287de.png)

webAuth.checkSession and webAuth.client.userInfo Is working

I got an error only for auth0Manage.getUser
Error:
      error: "Bad Request"
      errorCode: "Bearer"
      message: "Bad HTTP authentication header format"
      statusCode: 400

PS: I need user_metadata and app_metadata returned after webAuth.client.userInfo call

**Comment by CRGavrila** [comment]
the get request done by auth0Manage.getUser (https://domain.eu.auth0.com/api/v2/users/google-oauth2%7C11259190000079421) receive the 400 status code, even in request atuhorization  of header is the same access_token received from  checkSession

**Comment by jgalianoz** [comment]
+1
