### ISSUE TITLE
Can't properly promisify auth0 client methods

### ISSUE THREAD

**Issue by andreafspeziale** [auth0/auth0.js#1145]
### Describe the problem

It's not possible to properly `promisify` methods like `dbConnection.signup` of an `Authentication` client.

### What was the expected behavior?

A successful method invokation with `async/await`

### Reproduction

```
import { promisify } from 'util';
import { Authentication } from 'auth0-js';

const CLIENT_ID = 'your valid client id';
const DOMAIN = 'your valid domain';
const CONNECTION_OR_REALM = 'Username-Password-Authentication'; // just using the default one

const EMAIL = 'your email';
const PASSWORD = 'Ciao12345&';

const auth0AuthenticationClient = new Authentication({
  clientID: CLIENT_ID,
  domain: DOMAIN,
});

const asyncSignup = promisify(auth0AuthenticationClient.dbConnection.signup);

(async (): Promise<void> => {
  try {
    const result = await asyncSignup({
      email: EMAIL,
      password: PASSWORD,
      connection: CONNECTION_OR_REALM,
    });
    console.log('RESULT: ', result);

    process.exit(0);
  } catch (error) {
    console.log('ERROR: ', error);

    process.exit(1);
  }
})();
```

`$ npx ts-node <your ts file>`

It will produce the following error:

```
Using browser-only version of superagent in non-browser environment
(node:37115) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'baseOptions' of undefined
    at DBConnection.signup (/Users/andrea/Repository/***/***/node_modules/auth0-js/src/authentication/db-connection.js:49:22)
...
```

I've also tried by using [`bluebird`](http://bluebirdjs.com/docs/getting-started.html) as suggested [here](https://github.com/auth0/auth0.js/issues/274#issuecomment-267849610) by adding the client context and the error changed like this:

```
import { Promise } from 'bluebird';
import { Authentication } from 'auth0-js';

const CLIENT_ID = 'your valid client id';
const DOMAIN = 'your valid domain';
const CONNECTION_OR_REALM = 'Username-Password-Authentication'; // just using the default one

const EMAIL = 'your email';
const PASSWORD = 'Ciao12345&';

const auth0AuthenticationClient = new Authentication({
  clientID: CLIENT_ID,
  domain: DOMAIN,
});

const asyncSignup = Promise.promisify(auth0AuthenticationClient.dbConnection.signup, {
  context: auth0AuthenticationClient,
});

(async (): Promise<void> => {
  try {
    const result = await asyncSignup({
      email: EMAIL,
      password: PASSWORD,
      connection: CONNECTION_OR_REALM,
    });
    console.log('RESULT: ', result);

    process.exit(0);
  } catch (error) {
    console.log('ERROR: ', error);

    process.exit(1);
  }
})();
```

`$ npx ts-node <your ts file>`

Error:

```
Using browser-only version of superagent in non-browser environment
ERROR:  TypeError: Cannot read property 'XMLHttpRequest' of undefined
    at Function.getXHR (/Users/andrea/Repository/***/***/node_modules/auth0-js/node_modules/superagent/lib/client.js:66:12)
...
```

### Environment

> Please provide the following:

- **Version of NodeJS used:** v14.5.0
- **Version of TS used:** v4.1.3
- **Version of Auth0.js used:** v9.14.0
- **Which browsers have you tested in?** I'm actually using it on the server side. Does it exist an official wrapper for the BE side? I would like to avoid this => `Using browser-only version of superagent in non-browser environment`.
- **Other modules/plugins/libraries that might be involved:** eventually `bluebird` v3.7.2

**Comment by IcanDivideBy0** [comment]
Have you tried to bind the signup function?
```js
const asyncSignup = promisify(auth0AuthenticationClient.dbConnection.signup.bind(auth0AuthenticationClient.dbConnection));
```
This is pretty ugly, but should work for your first example... or at least gives you the same error as the second one :/
Since auth0 devs don't want to move away from superagent (for no particular reasons) I doubt this will be resolved anytime

**Comment by andreafspeziale** [comment]
@IcanDivideBy0 (...same for the async/await support which is supported only on their new SPA SDK) Thank you very much for your suggestion. I'll look into it.
My idea was to use this wrapper in the BE side of my project (I know it would be a stretch) but it seems to be a very bad idea.
I will search for a proper BE side SDK on the internet... any suggestion about it?

**Comment by frederikprijck** [comment]
@andreafspeziale as the readme mentions, Auth0.JS is for ClientSide usage (For SPAs, we recommend https://github.com/auth0/auth0-spa-js). For server side we have https://github.com/auth0/node-auth0.

**Comment by stevehobbsdev** [comment]
Closing this for now as it looks to be answered. If however there's something additional we can help with, please feel free to continue the conversation.
