### ISSUE TITLE
Incognito mode + localhost ERROR Error: Uncaught (in promise): Error: Login required

### ISSUE THREAD

**Issue by JacekKruzel** [auth0/auth0.js#1146]
### Describe the problem

For the bug to reprocude, following conditions must be met:

- app is served from **localhost** (dev mode)
- using chrome in incognito mode
- scenario leveraging auth0 interceptor that adds proper token to the request

Due to incognito mode auth0 does not send all the cookies, so instead of getting token silently it does the full flow. Afther that is sucessfully obtains an acess token. Saying that,  when above conditions are met, auth0 fails to add the token to the requests and tries to authorize again - this time with propmt param set to none (my gues is ib this moment the lib ties to obtain token silently).  In console _ERROR Error: Uncaught (in promise): Error: Login required_ error is visible, and requests  **are not** beeing sent.

![5](https://user-images.githubusercontent.com/77151040/104012402-08489300-51b0-11eb-9c9a-8200506c5564.png)

![2](https://user-images.githubusercontent.com/77151040/104012154-9ff9b180-51af-11eb-8a37-04db1c467f7f.png)

![3](https://user-images.githubusercontent.com/77151040/104012152-9ff9b180-51af-11eb-8bf0-fd3f99e57d16.png)

![4](https://user-images.githubusercontent.com/77151040/104012148-9ec88480-51af-11eb-8da6-fa616902a108.png)

### What was the expected behavior?

The second and following authorization endpoint calls should not happen. Requests should be sent with proper token attached.

### Reproduction

-use auth0 interceptor 
- serve app locally
- open chrome in incognito mode
- go to http://localhost:PORT
- call any endpoint that requires authentication

### Environment

- Angular 11
- @auth0/auth0-angular@1.3.1
- @auth0/auth0-spa-js@1.13.5

**Comment by frederikprijck** [comment]
Thanks for reporting.
However, this appears to be the incorrect repository.

That said, we have a PR open that is about the get merged that allows you to track this error and react accordingly as explained in the examples in that PR: https://github.com/auth0/auth0-angular/pull/104
