### ISSUE TITLE
9.14.1 published package possibly incomplete

### ISSUE THREAD

**Issue by nmastereal** [auth0/auth0.js#1148]
### Describe the problem

The 9.14.1 package (pushed 6 hours ago) looks to be missing the expected files by package.json such as auth0.min.js and auth0.min.esm.js. You can also see that https://cdn.auth0.com/js/auth0/9.14.1/auth0.min.js is unavailable. 

### What was the expected behavior?
That these files would exist so that importing the package works correctly.

### Reproduction

1. Fresh `npm install auth0-js`
2. In a JS file: `import auth0 from 'auth0-js'` 
3. Execute code consuming auth0. Should fail to import.

**Comment by ljharb** [comment]
You may want to add a "prepublish" or "prepare" script so `npm run build` can't be accidentally forgotten.

**Comment by colecloudtostreet** [comment]
Downgrading to 9.14.0 seems to fix it for me: `npm --save-exact auth0-js@9.14.0`

**Comment by nmastereal** [comment]
@colecloudtostreet I would expect that to fix it for you and others. Its of course what we did to unblock ourselves as well. However people who have the default package dependency strategy (^) will all likely start seeing some breaking errors. So best to get it fixed / prioritized in the package itself.

**Comment by colecloudtostreet** [comment]
> @colecloudtostreet I would expect that to fix it for you and others. Its of course what we did to unblock ourselves as well. However people who have the default package dependency strategy (^) will all likely start seeing some breaking errors. So best to get it fixed / prioritized in the package itself.

Yeah good point, just thought I'd share for anyone who's stuck and comes across this.

**Comment by stevehobbsdev** [comment]
Thanks for the report @nmastereal, looks like we do indeed have a failure with our publisher. I will work to resolve this as soon as I can. In the meantime, yes - please pin to 9.14.0 until this is resolved.

**Comment by nmastereal** [comment]
Have you considered u publishing 9.14.1 instead of having all the consumers pin to 9.14.0 then again unpin it when this is resolved?

**Comment by stevehobbsdev** [comment]
@nmastereal looks like we're good on the build side, I just need to cut a new release, so I'm hoping this will be fixed very shortly.

**Comment by stevehobbsdev** [comment]
This has now been merged, published to NPM and the CDN - could those affected please try 9.14.2?

Apologies for the inconvenience here!
