### ISSUE TITLE
Add methods for linking/unlinking accounts

### ISSUE THREAD

**Issue by solepano** [auth0/auth0.js#115]
It would be nice to have methods for linking and unlinking accounts using the new way of calling the API V2 endpoints with the JWTs:
Link accounts: https://auth0.com/docs/api/v2#!/Users/post_identities
Unlinkg Accounts: https://auth0.com/docs/api/v2#!/Users/delete_provider_by_user_id

**Comment by hzalaz** [comment]
Implemented in v8

**Comment by johnlim** [comment]
@hzalaz I can only see a linkUser method. What about unlinking users? Thanks.
