### ISSUE TITLE
CORS fails on fetching /.well-known/jwks.json

### ISSUE THREAD

**Issue by CyranMS** [auth0/auth0.js#1150]
Hi community,
I have an issue that suddenly I get a CORS error when requesting “/.well-known/jwks.json”.
Access to fetch at 
`https://<acc>.auth0.com/.well-known/jwks.json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I have not changed anything. Any idea why this happens suddenly?
Entries for CORS in auth0 is: `http://localhost:3000, http://localhost:3000/, http://localhost:3000/callback`

SDK: auth0-js
Version: 9.14.2

**Comment by mattsmithies** [comment]
I'm experiencing this same issue as well.

**Comment by JayWelsh** [comment]
Also experiencing this problem

**Comment by Bertrand** [comment]
[Cross posted from https://community.auth0.com/t/no-access-control-allow-origin-header-is-present-on-the-requested-resource/56311]

WARNING: This is a hack. Revert when Auth0 has fixed the issue.

To everyone who ends up here with the same issue in production, here is a workaround while Auth0 team fixes the issue:

Download the current version of your jwks.json file (generally available at https://your_app.your_region.auth0.com/.well-known/jwks.json) and store it on your domain to avoid CORS issues, or somewhere where you can easily set CORS headers (for instance S3).

Then, client-side, when instantiating WebAuth, use a private setting to tell it where to find the jwks file:

  auth0 = new WebAuth({
    domain: ...,
    clientID: ...,
    ...
    overrides: {
      __jwks_uri: "MY_OWN_JWKS_URL"
    }
   }
Where MY_OWN_JWKS_URL is the URL where you stored your jwks.json.

Hope this helps,

**Comment by stevehobbsdev** [comment]
Thanks all, this was the result of an [incident](https://status.auth0.com/incidents/rx8wtk8svly4) (outside of this SDK) that has since been resolved.
