### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by gap777** [auth0/auth0.js#1151]
### Describe the problem

We have a React SPA using auth0js. Sometimes, our users are unable to login. In those cases, the auth0 logs indicate successful authentication (e.g. auth0 log id: 90020210120135548300081259399607541298971575755827314770), but the javascript using auth0.js libraries report an invalid token.

Not sure if it’s related, but these users seem to have ipv6 addresses. We do not have any custom auth0 rules (at all).

### What was the expected behavior?

A user who can login yesterday can still log in today, given that the app code and browser have not changed. 

### Reproduction

We are unable to reproduce it, although we have had several users that are experiencing it that we can point to in our tenant. 

### Environment

> Please provide the following:

- Auth0.js v9.13.2
- Experience the issue in Safari, Firefox, and Chrome

**Comment by stevehobbsdev** [comment]
Hi @gap777, thanks for the report. Unfortunately this is also going to be difficult for me to reproduce without a solid reproduction sample that demonstrates the issue. Do you have any more context around what you're seeing that you can provide?

Not sure if you are able to do this if you're not seeing this error yourself, but if you can get a HAR file showing the failed authentication on the client side, that might help us start to look into it.

Additionally, we also now have a [React SDK](https://github.com/auth0/auth0-react) that does not depend on Auth0.js at all, but rather uses [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js). If all else fails, I'm not sure how big a job it would be to migrate your app to that SDK to see if that prevents these errors from occurring.

Aside from that, I'm afraid I don't have a lot else to go on at this point. Happy to continue discussing though.

**Comment by stevehobbsdev** [comment]
Closing this for now if there's anything additional you find that can help us debug this, please continue the thread.
