### ISSUE TITLE
Add methods for updating user_metadata

### ISSUE THREAD

**Issue by solepano** [auth0/auth0.js#116]
It would be nice to have a method for updating user_metadata, like in the [Auth0 Node.js V2 API](https://github.com/auth0/node-auth0/tree/v2)

**Comment by ddbaron** [comment]
+1

**Comment by bman654** [comment]
:+1:

**Comment by ianks** [comment]
:+1:

**Comment by cdelmas** [comment]
:+1:

**Comment by aj0strow** [comment]
The issue is without `user_metadata` it breaks signup forms with extra fields. I was hoping to save first and last name on signup.

**Comment by iamchristopher** [comment]
👍

**Comment by hzalaz** [comment]
Included in v8
