### ISSUE TITLE
Not mutate options in WebAuth

### ISSUE THREAD

**Issue by EloB** [auth0/auth0.js#1163]
### Describe the problem you'd like to have solved

> A was surprised that the options object was mutated. Is this really intended?

### Describe the ideal solution

> A simple spread on options to create a new object instance of "options"

https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L44
```js
function WebAuth(options) {
```

**Replace with:**

```js
function WebAuth({ ...options }) {
```

**Comment by stevehobbsdev** [comment]
Hi @EloB, thanks for your patience.

> Is this really intended?
I don't know, in all honesty. What issue are you facing that requires this change?

**Comment by EloB** [comment]
@stevehobbsdev No worry mate! I had a reference to that object in my application and was confused that it was changed. No biggie...

**Comment by stevehobbsdev** [comment]
Thanks @EloB - I'll leave the API as-is for the moment, but we are looking at doing some refresh work on this SDK and will keep this request in mind. Thanks for raising it!
