### ISSUE TITLE
Signup's given_name and family_name not exposed

### ISSUE THREAD

**Issue by akoss** [auth0/auth0.js#1164]
### Describe the problem

The Authentication API's Signup endpoint accepts `given_name` and `family_name` as part of the request. However, Auth0.js's webAuth.signup() accepts signup details as a `DBSignupOptions` object which doesn't declare the `given_name` and `family_name` fields. 

As such, the user's name can't be passed during registration. 

Sample code on the API docs suggests this is actually possible: https://auth0.com/docs/api/authentication?javascript#signup 

<img width="384" alt="Screenshot 2021-03-30 at 18 13 44" src="https://user-images.githubusercontent.com/6537461/113028875-b2b6cd80-9183-11eb-9b0e-d403aa74dc28.png">

### What was the expected behavior?

first_name and last_name is declared in `DBSignupOptions` and accepted during WebAuth.signup()

### Reproduction

```
webAuth.signup(
    {
        email,
        password,
        connection,
        given_name,
        family_name,
        userMetadata: {},
    },
    (error, result) => {},
)
``` 
➡️
```Argument of type '(...)' is not assignable to parameter of type 'DbSignUpOptions'.
  Object literal may only specify known properties, and 'given_name' does not exist in type 'DbSignUpOptions'.
```

Note, this approach works fine with `@ts-ignore`.

### Environment

> Please provide the following:

- **Version of Auth0.js used:** 9.14.3
- **Which browsers have you tested in?** N/A
- **Other modules/plugins/libraries that might be involved:**

**Comment by evansims** [comment]
Hey @akoss! 👋 It looks like the issue you're hitting here is actually related to the community-maintained typescript definitions (specifically, [DBSignupOptions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9dd56df993bb1218e21bf69159e01be1c620be75/types/auth0-js/index.d.ts#L905).) Those aren't maintained by us or handled in this repo, but you can open an issue/PR in https://github.com/DefinitelyTyped/DefinitelyTyped
