### ISSUE TITLE
Add signup docs to README

### ISSUE THREAD

**Issue by taion** [auth0/auth0.js#117]
The docs for signups: https://auth0.com/docs/libraries/auth0js#sign-ups are not present in README, so they don't show up in GH or NPM docs. I found them eventually, but it might be nice if they were also documented on the README.

**Comment by taion** [comment]
Eh? This still isn't documented in the README: https://auth0.com/docs/libraries/auth0js#sign-up

**Comment by hzalaz** [comment]
We are trying to trim down the README and redirect most of the use cases/examples to the docs site, we just added a link to the docs to start and we are trying to figure out what content we leave in the README

**Comment by taion** [comment]
Got it, thanks.
