### ISSUE TITLE
use the API in the browser

### ISSUE THREAD

**Issue by rolandjitsu** [auth0/auth0.js#118]
I can see that this library is node specific and if I would like to use in in the browser (web) I would need to use something like browserify. I am also aware that there is a library for web, but what I do not like about that is that you enforce the use of a UI. Can I just use the API without the UI in the browser?

**Comment by treehau5** [comment]
The readme state under usage,

"Take auth0.js or auth0.min.js from the /build directory and import it to your page."

**Comment by rolandjitsu** [comment]
I actually already tried it, but I forgot about this opened issue. But when I use the API for auth, it redirects me to the Auth0 page where you actually do the authentication. And that is not something that fits with the current architecture I have.

I've also seen something about SSO, but not sure if that is what I actually want: which is for the API to not redirect me to any pages (unless I use auth with Google or some other oAuth provider) and to just do an XHR call which will authenticate the user (or not).

**Comment by hzalaz** [comment]
Hi, I am closing this. If you need support please contact us in https://support.auth0.com unless there is a bug in this library.
