### ISSUE TITLE
can't resolve crypt module

### ISSUE THREAD

**Issue by dking3876** [auth0/auth0.js#1181]
Latest version 9.16.1 results in the following error when used in an angular build while setting version back to 9.16.0 runs a successful build.

ERROR in ./node_modules/auth0-js/dist/auth0.min.esm.js
Module not found: Error: Can't resolve 'crypto' in './node_modules/auth0-js/dist'

**Comment by stevehobbsdev** [comment]
Thanks for raising this - we're aware of the issue and are taking steps to resolve it. Will report back with action steps soon.
