### ISSUE TITLE
Verify email code for reset password

### ISSUE THREAD

**Issue by Ketcap** [auth0/auth0.js#1185]
### Verify email code for password reset

As a developer I'm able to create reset password ticket and auth0 is required to have their own form while resetting password. I would like to create my own form and ask user information about that. We don't want to user go to auth0 website rather than our website. From my form and the url i'll create or the ticket number i will create will be verified from auth0 while resetting password.

### Describe the ideal solution

Sending email with url that has my url defined before creating request.
Ex: Reset password email from auth0 will open `google.com/reset-password` instead`[domain].auth0.com/?ticket=....`
So I will have my user on my platform while doing these actions. Right now auth0 has ability to create user with management client from our form.

## Alternatives and current work-arounds

I can work-around with sending email code to user from auth0 as in like passwordless login but that's not a good way or I can generate code my own but still I want to rely on auth0 for authentication not myself.

I can create request password reset and alter that url my own and verify that but verify ticket is not possible.

### Additional context

- Verify ticket id can be added as first step to support these kind a situations
- On auth0 defining reset password base link so generated link will be user's own link.

**Comment by stevehobbsdev** [comment]
Hi @Ketcap, thanks for your patience. Please could you raise this feature request with our product team at https://auth0.com/feedback?

Thanks
