### ISSUE TITLE
Remove the vulnerability from package crypto-js 

### ISSUE THREAD

**Issue by paimon0715** [auth0/auth0.js#1193]
Hi,@stevehobbsdev a potential high severity vulnerability is introduced in your package
### Issue

   1 vulnerabilities (high severity) is introduced in **_auth0-js_**:
Vulnerability **SNYK-JS-CRYPTOJS-548472** (high severity) is detected in package **_crypto-js_**(versions:<3.2.1,>=3.3.0 <4.0.0):[https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472](https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472)
   The above vulnerable package is referenced by **_auth0-js_** via:
`auth0-js@9.16.2 ➔ idtoken-verifier@2.2.0 ➔ crypto-js@3.3.0`

### Solution
Since **_auth0-js@9.16.*_** is transitively referenced by **244** downstream projects (e.g., [auth0-lock 11.30.3](https://www.npmjs.com/package/auth0-lock) (latest version),
[@ctx-core/auth0 24.0.23](https://www.npmjs.com/package/@ctx-core/auth0) (latest version), [@ctx-core/auth0-lock 11.0.22](https://www.npmjs.com/package/@ctx-core/auth0-lock)  (latest version), [@ctx-core/auth0-ui 9.0.25](https://www.npmjs.com/package/@ctx-core/auth0-ui) (latest version), [@ctx-core/auth0-management 5.0.20](https://www.npmjs.com/package/@ctx-core/auth0-management)(latest version)), 

If **_auth0-js_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

Could you help update packages in this version?

### Fixing suggestions

(1）In **_auth0-js@9.16.*_**, you can kindly perform the following upgrades (not crossing their major versions):
`idtoken-verifier ^2.1.2 ➔ 2.1.1`;  

**Note:**
_idtoken-verifier@2.1.1 directly depends on crypto-js@4.0.0 (a vulnerability SNYK-JS-CRYPTOJS-548472 patched version)_

Thank you for your attention to this issue!

Many thanks,
Paimon

**Comment by stevehobbsdev** [comment]
Thanks for raising @paimon0715.

We recognise that `idtoken-verifier` ships with this vulnerable version, and had [already worked to perform the upgrade](https://github.com/auth0/idtoken-verifier/pull/128). However, the upgrade presents challenges for downstream projects as it now relies on native implementation of `crypto`, which dependencies like Lock do not have.

Instead, our unfortunate and temporary resolution was to pin `crypto-js` back to `3.3.0` and perform an audit of the code to identify whether or not we were actually using any of the API that us impacted by the vulnerability - which it is not.

So it's a temporary measure and one that we aim to rectify soon. In the meantime, I would look into whether your package manager allows to you resolve `crypto-js` to `>= 4.0.0` and override our settings, allowing you to use the patched version without our upgrade, and identify whether you need to include any crypto polyfills for your specific situation.

**Comment by paimon0715** [comment]
@stevehobbsdev Thanks for your feedback.
