### ISSUE TITLE
app_metadata not merged but removed

### ISSUE THREAD

**Issue by mciordache** [auth0/auth0.js#1194]
The ‘Update a User’ ( /api/v2/users/{id} - Auth0 Management API) PATCH call has a different way of dealing with the metadata fields. These properties (user_metadata and app_metadata) “are merged instead of being replaced but be careful, the merge only occurs on the first level”.

So once the app_metadata.userId is inserted it can only be changed but not removed, one may think. 

But when testing the API with { "app_metadata": {} } the value is not merged but it is deleted resulting in no app_metadata field.

**Comment by stevehobbsdev** [comment]
Thanks for reporting this. It looks to be related to the behaviour of the management API rather than the SDK - to get clarification on that, please could you raise this to our [product feedback community](https://community.auth0.com/c/feedback/95)?

Thanks
