### ISSUE TITLE
missing types for onRedirecting option in webAuth.login

### ISSUE THREAD

**Issue by zelias500** [auth0/auth0.js#1196]
Hello! I am attempting to implement an embedded login flow that makes use of the `onRedirecting` option as detailed in [this commit](https://github.com/auth0/auth0.js/commit/66751daa58ef396851f95aca0f2995e034a1a66a#diff-b7b892c42010668d375874c86eea34f8ca923f2af84bc81d0cea1c39d7ebfbe2R55)

Unfortunately, it seems that my Typescript server refuses to recognize `onRedirecting` as a legitimate option passed to the `login` function. Are the types simply missing, or am I doing something wrong?

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/11530588/129234136-5737e6bf-3b28-4abc-99da-625f4da41a44.png">

```
export const Auth0Client = new WebAuth({
  domain:       process.env.AUTH0_DOMAIN,
  clientID:     process.env.AUTH0_CLIENT_ID,
  redirectUri:  process.env.AUTH0_REDIRECT_URI,
  responseType: 'code',
  scope: 'openid profile email roles permissions',
  leeway: 60
});

// used in another file like so...
  await Auth0Client.login({
    username: data.username,
    password: data.password,
    realm: 'Username-Password-Authentication',
    nonce: window.crypto.getRandomValues(new Uint8Array(16)).join(''),
    onRedirecting: (done) => {
      done();
    }
  }, (err, authResult) => {
    if (err) throw err;
    console.log('authResult from login call', authResult);
    return authResult;
  });

```

**Comment by stevehobbsdev** [comment]
Closing for now but if you're able to provide more detail here, I'll try to help.
