### ISSUE TITLE
Can’t get google refresh token using auth0.js

### ISSUE THREAD

**Issue by duongmanhhoang** [auth0/auth0.js#1205]
### Describe the problem
I follow this link https://community.auth0.com/t/cant-get-google-refresh-token-using-auth0-js/11756

When i’m using login with google function, i can't get the refresh token.
This is my code:

```
var params = Object.assign(
  {
    overrides: {
      __tenant: config.auth0Tenant,
      __token_issuer: config.authorizationServer.issuer,
    },
    domain: config.auth0Domain,
    clientID: config.clientID,
    redirectUri: config.callbackURL,
    responseType: "code",
    scope: 'openid profile offline_access'
  },
  config.internalOptions
);

var webAuth = new auth0.WebAuth(params);

webAuth.authorize({
  connection: 'google-oauth2',
  connection_scope: 'https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/calendar.events',
  scope: 'openid profile',
  accessType: 'offline',
  approvalPrompt: 'force'
}, function(err) {
  if (err) displayError(err);
});
```
This is what i get from api /api/v2/users/{id}:
![image](https://user-images.githubusercontent.com/36806927/131479642-bbbf2b75-d568-47c9-86f7-9e0241d1ac1f.png)

I check param from authorize request and still get access_type
![image](https://user-images.githubusercontent.com/36806927/131480124-7d1a18b7-45dc-47fe-bbce-22652661bdaa.png)

And when i check goolge url redirect from auth0 i don't see the access_type param
![image](https://user-images.githubusercontent.com/36806927/131479883-983596c4-25f2-4b03-9809-2c94b6de4ce2.png)

**Comment by duongmanhhoang** [comment]
When i add state:'' to authorize method, it’s work. I wonder if it has any risks cause i’ve read that state is used to prevent attack?

```
webAuth.authorize({
  connection: 'google-oauth2',
  responseType: "code",
  state:'',
  connection_scope: 'https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/calendar.events',
  scope: 'openid profile email offline_access',
  accessType: 'offline',
  approvalPrompt: 'force'
}, function(err) {
  console.log(err);
  if (err) displayError(err);
});
```

**Comment by stevehobbsdev** [comment]
This sounds odd, I'm surprised it works if you set state to `''`. You should not do that though as you're correct - the `state` parameter there is there to help prevent XSRF attacks.

In your second example you are also passing the 'offline_access' scope when compared to the example that does not work - can you confirm if you are able to omit `state` and have it still work?

**Comment by stevehobbsdev** [comment]
I'll close this for now. If there is still an issue here, please feel free to reply and I'll do my best to help.

**Comment by swarajban** [comment]
@stevehobbsdev I'm running into this same issue and found this current thread helpful, as I was seeing the same thing (expect in auth0 lock JS). 

I have also been trying to get the refresh token and needed to use the `state: ''` to get actually obtain the refresh token from google.

I am using the 'classic' universal login page, and customized auth.params section of lock configuration.

This version works for fetching the refresh token:
```
{
    "protocol": "oauth2",
    "scope": "openid profile email offline_access",
    "response_type": "code",
    "response_mode": "query",
    "nonce": "<redacted>",
    "code_challenge": "<redacted>",
    "code_challenge_method": "S256",
    "auth0Client": "<redacted>",
    "_csrf": "<redacted>",
    "_intstate": "deprecated",
    "state": "",
    "accessType": "offline",
    "approvalPrompt": "force",
    "connection_scope": "https://www.googleapis.com/auth/calendar.events.readonly"
}
```

This one does not:
```{
    "protocol": "oauth2",
    "scope": "openid profile email offline_access",
    "response_type": "code",
    "response_mode": "query",
    "nonce": "<redacted>",
    "code_challenge": "<redacted>",
    "code_challenge_method": "S256",
    "auth0Client": "<redacted>",
    "_csrf": "<redacted>",
    "_intstate": "deprecated",
    "accessType": "offline",
    "approvalPrompt": "force",
    "connection_scope": "https://www.googleapis.com/auth/calendar.events.readonly"
}
```

This isn't a complete solution, however. When I clear the `state: ''` like this, my auth0 web app does not think the app is authenticated until refresh. 

Any ideas?
