### ISSUE TITLE
Allow Auth0.js to Work Without a DOM

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0.js#121]
Related: https://github.com/auth0/node-auth0/issues/46

This is important for universal / isomorphic rendering.

**Comment by cristiandouce** [comment]
https://github.com/auth0/auth0.js/issues/98

**Comment by cancan101** [comment]
And just using "node-auth0" doesn't really work since that library is not built to be used by client / in untrusted environments.

**Comment by cristiandouce** [comment]
Neither was this one. Do you have any desired spec of a tool/lib you'd like to have?

This lib solves problems that are tight to the browser... the other one to node.

From experience it's easier to resolve the isomorphic problem `node -> browser` by using browserify or tools like such.

But I don't really se any use of the methods exposed by this lib in the server... so that's why I'm asking you @cancan101 what would you use?

**Comment by cancan101** [comment]
`getDelegationToken` comes to mind.

**Comment by cancan101** [comment]
I think `loginWithResourceOwner` should be safe.

**Comment by cristiandouce** [comment]
@cancan101 If that's the only one I think it'd be easier and faster to just add it to https://github.com/auth0/node-auth0 project instead of working a full isomorphic refactor with all the pros and cons that come along with future maintenance. Don't you think?

**Comment by cancan101** [comment]
I would say any method that doesn't involve a popup / rendering to the DOM. Perhaps it really is just those two.

**Comment by cancan101** [comment]
(there are actually a few other methods around refresh tokens that call into `getDelegationToken`).

**Comment by cristiandouce** [comment]
https://github.com/auth0/node-auth0#apigetaccesstokencallback
https://github.com/auth0/node-auth0#auth0getuserinfo
I see the delegation related endpoints missing there... Appart from that I don't really see much more to add.

**Comment by cancan101** [comment]
@cristiandouce How would I used the linked APIs to perform a password-based login?

**Comment by joonhocho** [comment]
I created a repo, https://github.com/joonhocho/auth0-react-native, for this reason. I basically want to use auth0.js in React Native.
React Native and Node shares pretty similiar environment, so it shouldn't be too hard to support Node.js as well.
It's still work in progress, but you are welcome to make PRs or share your opinions.

**Comment by hzalaz** [comment]
Closing this for now. Will improve node-auth0 to add auth API and rework this client SDK in the next version
