### ISSUE TITLE
Cookie “com.auth0.auth.*” will be soon rejected because it has the “SameSite” attribute set to “None”

### ISSUE THREAD

**Issue by DavidCasillasRivero** [auth0/auth0.js#1220]
After doing an `WebAuth.authorize(options)` call to perform a logging via Classical Universal Login Experience the browser shows a warning:

```
Cookie “com.auth0.auth.*” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

Where the cookie seems to be named with the value of the `options.state` passed to `WebAuth.authorize(options)`. For example a `options.state: zXd34Fr` generates a cookie named `com.auth0.auth.zXd34Fr`.

All interactions are HTTPS.

According to this issue  [Cookies com.auth0.auth.* have no secure flag #1050 ](https://github.com/auth0/auth0.js/issues/1050) and this merged pull request https://github.com/auth0/auth0.js/pull/1158, the issue should be resolved in 9.15.

### What was the expected behavior?

The cookie should be set with the secury atribute.

### Environment

- **Version of Auth0.js used:** "auth0-js": "^9.18.0",
- **Which browsers have you tested in?** Firefox 94
- **Other modules/plugins/libraries that might be involved:** "react": "^17.0.2",

**Comment by stevehobbsdev** [comment]
Hi @DavidCasillasRivero, thanks for your patience here. I'm not able to reproduce this, at least in Firefox 95. The cookie appears to be created with the `secure` flag in my testing. I've attached a video. Note that you'll see the console warnings appear, but only for those cookies we use to store data for Auth0.js Playground - we don't receive a warning for the `com.auth0.auth.*` cookie.

https://user-images.githubusercontent.com/766403/146533977-b8b3350f-181e-4d4c-8a09-4384f15199e4.mov

Is there anything else you can tell me, or do you have a repro/video to share that shows the issue?

**Comment by DavidCasillasRivero** [comment]
I have share a screen capture of the process. I would share also the HARs of the request if you need them, but they have so many content, some of them URL encoded  that we will need to carefully review of all them to remove any sensitive information.

The code we use to start the login process is:

```
  auth0 = new auth0.WebAuth({
    domain: process.env.REACT_APP_AUTH0_DOMAIN || null,
    audience: process.env.REACT_APP_AUTH0_AUDIENCE || null,
    clientID: process.env.REACT_APP_AUTH0_APPLICATION_CLIENT_ID || null,
    redirectUri: process.env.REACT_APP_AUTH0_REDIRECT_URI || null,
    responseType: 'token id_token',
    scope: 'openid profile email'
  });
```
```
    const params = {};
    this.auth0.authorize(params);
```

https://user-images.githubusercontent.com/1935950/146739985-7d171e56-fae6-4545-a87b-ad198a0a9f34.mp4

**Comment by stevehobbsdev** [comment]
Thanks @DavidCasillasRivero - this actually looks like Lock on the server is still an older version that does not have the updated Auth0.js dependency with this fix. We're planning to make this upgrade after the holidays, so hopefully will just resolve itself after that.

Will keep this open until then and let you know when it has been updated.

**Comment by stevehobbsdev** [comment]
@DavidCasillasRivero We've done some work in this area in the last couple of releases, are you able to give [9.19.0](https://github.com/auth0/auth0.js/releases/tag/v9.19.0) a try and see if that resolves your issue?

Thanks

**Comment by DavidCasillasRivero** [comment]
We have done some testing today but we keep with the same warnings. We just upgraded the auth0-js component in our develop app and try a login / logout flow. There are attached some screenshots taken after cleaning all cache, storage. The only difference between new and old version of auth0-js library is a new entry in the warnings affecting a cookie that has a suffix "_" and a prefix "_compat".

[warnings.zip](https://github.com/auth0/auth0.js/files/7969509/warnings.zip)

**Comment by stevehobbsdev** [comment]
@DavidCasillasRivero Most odd. Can you confirm the version of Lock you're using in the ULP? Are you just using the standard default login template or have you customized it?

Can you also share a screenshot of the cookies in the storage tab of your browser from the same scenario in your video above (going through the ULP)?

Can you share more details about how your app is set up? You mention you're using `auth0-js` locally but you're also using the Universal Login Page; normally that page would be in control of what version you're using.

**Comment by stevehobbsdev** [comment]
Also a follow up - I wanted to check out what `js-cookie` do to remove cookies (as per the workaround in the Bugzilla report) and they set it with an outdated expiry as recommended.

I found [this issue reported](https://github.com/js-cookie/js-cookie/issues/672) to them and it's not something they can fix. We can't use the default attributes as they suggest, because we don't always want to set these cookie properties.
