### ISSUE TITLE
Check previous session with a social account before signing in.

### ISSUE THREAD

**Issue by sboland-terem** [auth0/auth0.js#1221]
### Describe the problem you'd like to have solved

My login page in the Universal Login uses both sign up and sign in functionality for social and username/password logins. I use the auth0.WebAuth() library and webAuth.authorize() for google or facebook.

On the sign up form I have a checkbox to enforce the user checks the terms & conditions. I don’t want to have this same checkbox on the signin form.  However,  the problem is that a user can simply bypass the signup option and sign in with Google and facebook.

### Describe the ideal solution

An existing or previous session with the social account is first checked if it exists.  I'm not sure if checkSession() can do this already.

## Alternatives and current work-arounds
The alternative is to move these concerns to another part of the application, e.g. after signing or signing up I check if the user has checked the terms and conditions and force them to do this.

**Comment by stevehobbsdev** [comment]
Hi @sboland-terem, please can you raise this feedback at https://auth0.com/feedback, as this request relates to completely different area of login, just want to make sure the right people see it.

Thanks
