### ISSUE TITLE
Auth0 nuxt Demo no longer works.

### ISSUE THREAD

**Issue by skwasan** [auth0/auth0.js#1222]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

**Please do not close this issue. This is headache.**
Auth0 nuxt package should be maintained by the Auth0 org. 

https://github.com/nuxt/example-auth0
This package and link no longer works.
https://auth0.nuxtjs.org/
https://auth.nuxtjs.org/providers/auth0/

> Provide a clear and concise description of the issue

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Pleas
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment
Nuxt
> Please provide the following:

- **Version of Auth0.js used:**
- **Which browsers have you tested in?**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
I'll close this issue as it looks to be a duplicate of #1223
