### ISSUE TITLE
Auth0 nuxt Demo no longer works.

### ISSUE THREAD

**Issue by skwasan** [auth0/auth0.js#1223]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

**Please do not close this issue. This is headache.**
Auth0 nuxt package should be maintained by the Auth0 org. 

This package and link no longer works.
https://github.com/nuxt/example-auth0
https://auth0.nuxtjs.org/

While nextjs auth0 tutorials are there and works seamlessely. Auth0 nuxt package should also work.

Please create and maintain nuxt package. It's very difficult to integrate it.

> Provide a clear and concise description of the issue

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Go to url - https://auth0.nuxtjs.org/

- Step 2..
- Gives error

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior

> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment
Nuxt
> Please provide the following:

- **Version of Auth0.js used:**
- **Which browsers have you tested in?**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Hi @skwasan,

We unfortunately have nothing to do with that Nuxt sample, I would suggest you raise the issue on [their GitHub repo](https://github.com/nuxt/example-auth0).

**Comment by skwasan** [comment]
But you are auth0. I understand you have not created it. But you guys
should manage it

**Comment by skwasan** [comment]
Like uou do next.js

**Comment by matreurai** [comment]
I shall Up this tread.
It would be very appreciated if you were to update your doc, provide clear procedures and add nuxt to your "technologies" for regular app setup. As Nuxt becomes bigger and bigger, its community would be very pleased if the process to integrate your service was much simpler and without issues. You guys are providing excellent doc for Next. It wouldnt be that hard to provide the same for Nuxt. As Nuxt already has an auth module, it should be very easy to implement, but its literally impossible to find decent informations about the process. You guys should look into this...
Your community is asking for it.

Thanks

**Comment by frederikprijck** [comment]
Thanks for the feedback. I am wondering what is missing from https://auth.nuxtjs.org/providers/auth0/ that makes you feel like it is impossible to find any decent information?

I mean, we don't have any Nuxt example, but it does look like the Nuxt team has documentation on how to integrate Auth0. If their documentation is out of date or not working as intended, I would reach out to them instead. 
The way to integrate Auth0 in Nuxt relies solely on Nuxt internals (auth stuff), that gets connected to our Auth0 backend. I believe there is little to document from our side here, especially given Nuxt has a dedicated section for Auth0.

If the Nuxt team would decide to remove Auth0 from their docs, we could always revisit.

**Comment by matreurai** [comment]
If you carefully take a look at the doc from Nuxt, everything is outdated, examples are from your old platform. Nothing has been updated, links to code examples and snippets are broken. I followed their few steps to implement Auth0 and I have been scratching my head through the whole process. It does'nt work. 

The only other doc they provide is links to your old Auth0 Doc website that hasnt been updated either. And even if their doc is not great (and that's on them indeed, I've contacted them also) the Auth0 team as well should be working toward trying to facilitate the integration. Nuxt is one of the biggest framework out there for Vue and yet, you have not added infos on your website to help your customers implement your platform. Far from me the idea of being rude, but This is on your part. I dare you to try to implement it in a Nuxt regular webapp project with their and your documentation currently offered... It's a nightmare. 

I don't see how you guys could'nt, first, add Nuxt to your choices of technology on your platform and try to provide a simple working example step by step to implement it in a regular webapp. Nuxt3 is coming pretty soon and it would be vary valuable and a good opportunity for your team to bring on board the whole community. The fact that you replied here is proof that you care for your product and for open-source community, on which Nuxt was built. It would be very much appreciated if you could take the first steps in reaching out to them to try to look into this. 

Being a developper, you know that outdated documentation is even worst that not finding any.
Anyway, I love the solution you are bringing to the market and I'd love to use it, but right now, I'm just unable to.
I hope you understand my (and probably others) frustration.

Looking forward to find further infos on your website soon and get news from you.

Thanks a lot for considering this

Cheers

**Comment by frederikprijck** [comment]
Hey @matreurai ,

I tried creating a new Nuxt application, then followed what's mentioned here https://auth.nuxtjs.org/providers/auth0/ and everything seems to work fine.

Here you can see what changes I made to the default created nuxtjs project: https://github.com/frederikprijck/nuxt-auth-auth0-example/commit/cedb9ad9fce945463aedb784275de4a19ffaca76.

I will raise this internally regarding documentation for nuxt, but regardless it seems like the documentation from nuxt auth works for the most part. I did have to manually install `nanoid` because of this issue: https://github.com/nuxt-community/auth-module/issues/750

Thanks.

**Comment by matreurai** [comment]
Hey @frederikprijck 

Thanks a lot for your help. I've been able to progress a bit.
I can now Sign in by creating an email and a password on my webapp, but as soon I click submit, I'm redirected to a non-existing page. Same with login -> once I login with valid credentials (I see the user added on my Auth0 list of users), I'm redirected to a non-existing page. 
I'm not sure if my Application URIs are well sets.
So far, I have set this:

Application Login URI: empty
Allowed Callback URLs: http://localhost:3000/auth/signed-in, https://localhost:3000/auth/signed-in
Allowed Logout URLs: https://localhost:3000, http://localhost:3000
Allowed Web Origins: https://localhost:3000, http://localhost:3000
Allowed Origins (CORS): https://localhost:3000, http://localhost:3000

Is there something I'm not doing well ?
Thanks a lot

**Comment by frederikprijck** [comment]
Thanks for the kind words. I believe we always try to be as helpful as possible.
Happy you got it resolved and looking forward to your experience using our platform.
