### ISSUE TITLE
auth0-js 9.18.0 build fails due to missing node_modules/auth0-js/build/auth0.min.js

### ISSUE THREAD

**Issue by dhirmadi** [auth0/auth0.js#1224]
Upgraded to auth0-js 9.18.0

Deployment failes with the following error

       - Generating browser application bundles (phase: setup)...
       An unhandled exception occurred: Script file node_modules/auth0-js/build/auth0.min.js does not exist.
       See "/tmp/ng-fT3e3P/angular-errors.log" for further details.

I could not find any build/auth0.min.js on the system.  found one in the dist directory. it seems this problem orrured already once in release 8?

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @dhirmadi. Can you let me know the context in which the SDK is being used, and this error is occurring? I can see references to Angular in the error log there, is this an Angular app?

**Comment by dhirmadi** [comment]
@stevehobbsdev 

the SDK is being used in a small project where I am building a Instagram like application based on the MEAN stack. I recently came about to upgrade all the modules to keep  the project up to date. I get the error when I use the latest version of the auth0-js module during build of the project. I have downgraded to an earlier version of auth0-js and now it compiles fine.

**Comment by stevehobbsdev** [comment]
Are you pulling in `auth0-js` as a first-class dependency into your app, or is it a transient dependency of something else? Can you do an `npm ls auth0-js` in the terminal and share the results?

The goal is to try and see what is using auth0-js from the `build/` folder, and why.

**Comment by dhirmadi** [comment]
├── auth0-js@9.14.3
    └─┬ auth0-lock@11.31.1
           └── auth0-js@9.18.0


i have to pass on the type of dependency, unclear how to answer that :)

**Comment by stevehobbsdev** [comment]
Looks like you have both - is `auth0-js` listed in your `dependencies` block in `package.json`? (first class dependency)

It's also being brought in by `auth0-lock`, which is a transient dependency.

What I'm struggling to see is what is looking for auth0-js using the `build` folder. Do you have a repro app you can share that demonstrates the issue?

**Comment by dhirmadi** [comment]
Sure, here https://github.com/dhirmadi/katyev01

**Comment by stevehobbsdev** [comment]
Thanks for your patience here. I've gotten to the bottom of this - the following path in your `angular.json` should now reference the file from the `dist` folder rather than the `build` folder:

https://github.com/dhirmadi/katyev01/blob/78c6a74942cff89a9a68048a8ab48bc0c4cf3a20/angular.json#L30

After making this change I could then build the project successfully.

My apologies that this has affected your project in a breaking way, it was unintended.
