### ISSUE TITLE
Refactor functions to classes

### ISSUE THREAD

**Issue by jimmywarting** [auth0/auth0.js#1226]
Would you be open to refactor functions into classes?
can help send in PR if you are willing

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @jimmywarting. If you had not raised a PR I would probably have said this would not be worth your time. However, as you have spent time on it I will take a look, but it's low priority. What was the motivation behind it? Is there any reason for these to be classes beyond it being a more modern implementation? There's nothing on the PR to indicate why this was done.

**Comment by jimmywarting** [comment]
VScode IDE seems to be more understanding of what a class extends and what properties it has when it's a class...
using things such as inherit is old school 

beside, it did not take so much effort, it was mostly auto converted to a class.

**Comment by stevehobbsdev** [comment]
I've left [a comment](https://github.com/auth0/auth0.js/pull/1227#issuecomment-1031593990) on the PR as to why we cannot accommodate this at this time.

Thanks again for your efforts here.
