### ISSUE TITLE
Auth0 loginWithRedirect always redirect to signup page in organization settings

### ISSUE THREAD

**Issue by amirbavand** [auth0/auth0.js#1228]
**Problem with loginWithRedirect with organization configurations**.

I am using auth0 organization functionality. I want to invite a user to a new organization. When I try to use loginWithRedirect method to redirect a user that received invitation to join an organization, this method always redirects user to the signup page. Even explicitly assigning the value of screen_hint='login' won't change the behaviour.

### What was the expected behavior?

The user should be redirected to the login page. **not the signup page**

### Reproduction

```
const { loginWithRedirect } = useAuth0();
  let loginOptions: RedirectLoginOptions = {
    prompt: 'login',
  };
   loginOptions['organization'] = organizationId;
   loginOptions['invitation'] = invitationTicketId;
   loginOptions['screen_hint'] = 'login';
   await loginWithRedirect(loginOptions);


```

Using this config, it is always redirected to signup page. But based on the docs, it should redirect the user to login page. And there is no way to change the behaviour of function

- **Version of Auth0.js used:** ~1.6.0
- **Which browsers have you tested in?** Chrome
- **Other modules/plugins/libraries that might be involved:** No library needed

**Comment by stevehobbsdev** [comment]
@amirbavand Are you sure it's this SDK and not [auth0-spa-js](https://github.com/auth0/auth0-spa-js)? If so, if this is still and issue, please raise it there.

I can also recommend upgrading before raising the issue, as [`1.6.0`](https://github.com/auth0/auth0-spa-js/releases/tag/v1.6.0) is over two years old - it's likely we may have already fixed your issue.
