### ISSUE TITLE
How to login/set session in React app using webAuth.login function

### ISSUE THREAD

**Issue by qweluke** [auth0/auth0.js#1233]
So I'm using two libs in my app:
- `@auth0/auth0-react`
- `auth0-js`

My React.js app is wrapped around the `Auth0Provider` component, like so:

```
import React from 'react';
import { useHistory } from 'react-router-dom';
import { Auth0Provider } from '@auth0/auth0-react';

const Auth0ProviderWithHistory = ({ children }) => {
  const history = useHistory();

  const onRedirectCallback = (appState) =>
    history.push(appState?.returnTo || window.location.pathname);

  return (
    <Auth0Provider
      domain={process.env.NX_AUTH0_DOMAIN}
      clientId={process.env.NX_AUTH0_CLIENT_ID}
      redirectUri={window.location.origin}
      onRedirectCallback={onRedirectCallback}
      audience={process.env.NX_AUTH0_AUDIENCE}
      scope="openid profile email"
    >
      {children}
    </Auth0Provider>
  );
};

export default Auth0ProviderWithHistory;

```

I have a custom form to handle login without navigating outside the page which is working ok.

```
import auth0 from 'auth0-js';
...
  const handleLogin = (data) => {
    const webAuth = new auth0.WebAuth({
      domain: process.env.NX_AUTH0_DOMAIN,
      clientID: process.env.NX_AUTH0_CLIENT_ID,
      audience: process.env.NX_AUTH0_AUDIENCE,
      redirectUri: window.location.origin,
      scope: 'openid profile email',
      responseType: 'code',
    });

    return webAuth.login(
      {
        username: data.email,
        password: data.password,
        popup: true,
      },
      () => history.push(successfulLoginRedirectUrl),
    );
  };
```

The issue I am struggling with is that `auth0-js` does not set a cache/session in `@auth0/auth0-react`/`Auth0ProviderWithHistory`...

So my question would is:
How to properly login a user by passing email/password with `@auth0/auth0-react` or `@auth0/auth0-spa-js` or `auth0-js`?

**Comment by stevehobbsdev** [comment]
👋🏻  Can you tell me more about your use case here and why you need both `@auth0/auth0-react` and `auth0-js`?

You mostly have a set of conflicting SDKs here; `@auth0/auth0-spa-js` (and by extension, `@auth0/auth0-react`) are specifically designed to work with the hosted [Universal Login Page](https://auth0.com/docs/authenticate/login/auth0-universal-login) and handles all of the local session state for you, whereas `auth0-js` is designed to work with the [Authentication API](https://auth0.com/docs/api/authentication) and makes no assumptions about what being logged in means for your app - all it does it give you your tokens back.

**Comment by DavidRouyer** [comment]
We all want to make custom pages for signup, login, etc. AND use the React hook `useAuth0()`.
The only way to do that is to make authentication requests using the `auth0-js` library (login, passwordlessStart, passwordLessLogin, authorize, etc.) and call the `getAccessTokenSilently()` method on `useAuth0()` to refresh the React state.

**Comment by qweluke** [comment]
@DavidRouyer that's how I've done this and it seems to be working fine expect that I'm calling `checkSession` not `getAccessTokenSilently` as it is not available in `uath0-js`

**Comment by stevehobbsdev** [comment]
@qweluke That's the recommended way currently to achieve this. I agree it's not ideal but if you have a need for using both embedded login and the ULP, then this pattern as you describe above should work.
