### ISSUE TITLE
Error handling in passwordlessStart

### ISSUE THREAD

**Issue by EeeasyBreezy** [auth0/auth0.js#1236]
### Describe the problem

Error handling in passwordless login is broken.
Consider the following code being executed with invalid value of `email` parameter (for example `food`)
```
const auth = new WebAuth(options);
auth.passwordlessStart(
    {
        connection: 'email',
        email,
        send: 'code',
    },
    (error) => {
        if (error && error.description) {
              // process error here
        } else {
            // success path actions
        }
    },
);
```

Server would respond with bad request and body:
`{"error":"bad.email","error_description":"error in email - email format validation failed: food"}`

The data, which is available in error handling callback does not match neither server response, nor `Auth0Error` type.

`'{"original":{"crossDomain":true,"method":"POST","url":"https://my-tenant.auth0.com/passwordless/start"},"code":null,"description":null,"name":"Error"}'`

### What was the expected behavior?

Being able to access server error codes and error descriptions in `passwordlessStart` callback

### Reproduction

Code above with correct options may reproduce the issue.

### Environment
- typescript@4.3.2
- react@17.0.2
- auth0-js@9.16.2
- @types/auth0-js@9.14.4
- Browser: chrome, last version

**Comment by stevehobbsdev** [comment]
Thanks for your patience here. When I test this using the build-in playground app (clone this repo, then `npm install && npm start`, then use "Login with a passwordless connection") I get an error response returned to me with the code and the description, using the input of `food` that you mention.

```js
{
    "original": {
        "original": null,
        "response": { ... }
    },
    "statusCode": "400",
    "code": "bad.email",
    "description": "error in email - email format validation failed: food"
}
```

Also ensure you're using the latest version; it could be that this used to be broken but we've inadvertently fixed it (I couldn't see anything explicit in the PR list).

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
