### ISSUE TITLE
Missing type definitions for onRedirecting property in CrossOriginLoginOptions interface

### ISSUE THREAD

**Issue by ihor-romanchuk** [auth0/auth0.js#1238]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

Type definition is missing in the latest version of "@types/auth0-js": "9.14.5".

### What was the expected behavior?

`CrossOriginLoginOptions` interface has property `onRedirecting`

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of Auth0.js used:**
- **Which browsers have you tested in?**
- **Other modules/plugins/libraries that might be involved:**

**Comment by ihor-romanchuk** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58822

**Comment by stevehobbsdev** [comment]
Thanks for raising @ihor-romanchuk - unfortunately we do not look after the types in DefinitelyTyped so I would raise the issue there for the maintainers, or raise a PR.

Taking ownership of these types or baking them into the library is something we're exploring but we're not quite there yet.
