### ISSUE TITLE
options.responseType not conforming to OpenID specs

### ISSUE THREAD

**Issue by maka-io** [auth0/auth0.js#1239]
### Describe the problem

Ref:
https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L32
The URL provided (@link https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html) specifies:

```
code id_token token
When supplied as the value for the response_type parameter, a successful response MUST include an Authorization Code, an id_token, an Access Token, and an Access Token Type. The default Response Mode for this Response Type is the fragment encoding and the query encoding MUST NOT be used. Both successful and error responses SHOULD be returned using the supplied Response Mode, or if none is supplied, using the default Response Mode.
```

When passing in `code id_token token` for `options.responseType`, there is no `Authorization Code`.  Only `id_token`, and `Access Token`

### What was the expected behavior?

"successful response MUST include an Authorization Code, an id_token, an Access Token, and an Access Token Type"

### Reproduction

```
    import { WebAuth } from 'auth0-js';

    const auth0 = new WebAuth({
      clientID: this.env.auth.clientId,
      domain: this.env.auth.domain,
      responseType: this.env.auth.responseType, // "code token id_token" 
      redirectUri: this.env.auth.redirectUri,
      scope: this.env.auth.scopes,
      audience: this.env.auth.audience,
    });

    this.auth0.authorize({
      connection: this.env.auth.connection,
      state: nonce
    });

    console.log(auth0);
```

(Omitted sensitive properties)

Request:
```
{
  "clientID": "",
  "domain": "",
  "responseType": "code token id_token",
  "redirectUri": "https://localhost:4202/auth0/callback",
  "scope": "openid",
  "audience": "",
  "plugins": {
    "plugins": []
  },
  "_sendTelemetry": true,
  "_timesToRetryFailedRequests": 0,
  "tenant": "",
  "token_issuer": "",
  "legacySameSiteCookie": true,
  "rootUrl": "",
  "universalLoginPage": true
}
```

```
{
  "accessToken": "",
  "idToken": "",
  "idTokenPayload": {},
  "appState": null,
  "refreshToken": null,
  "state": "",
  "expiresIn": 300,
  "tokenType": "Bearer",
  "scope": "openid"
}
```

### Environment

> Please provide the following:
"auth0-js": "^9.19.0",
Chrome, Safari, Edge
Angular 13

**Comment by stevehobbsdev** [comment]
Thanks for raising this @maka-io. From the spec you mention:

> The Response Type request parameter response_type informs the **Authorization Server** of the desired authorization processing flow

From what I can see in my testing, the authorization server is responding with an ID token, an Access Token and a code in the hash - can you confirm you're seeing the same?

With this response type, you already have the Access Token to hand in the callback from `parseHash` - can you elaborate on the need to also get access to  the `code` value?

**Comment by down4some1** [comment]
> ### Describe the problem
> Ref: https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L32 The URL provided (@link https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html) specifies:
> 
> ```
> code id_token token
> When supplied as the value for the response_type parameter, a successful response MUST include an Authorization Code, an id_token, an Access Token, and an Access Token Type. The default Response Mode for this Response Type is the fragment encoding and the query encoding MUST NOT be used. Both successful and error responses SHOULD be returned using the supplied Response Mode, or if none is supplied, using the default Response Mode.
> ```
> 
> When passing in `code id_token token` for `options.responseType`, there is no `Authorization Code`. Only `id_token`, and `Access Token`
> 
> ### What was the expected behavior?
> "successful response MUST include an Authorization Code, an id_token, an Access Token, and an Access Token Type"
> 
> ### Reproduction
> ```
>     import { WebAuth } from 'auth0-js';
> 
>     const auth0 = new WebAuth({
>       clientID: this.env.auth.clientId,
>       domain: this.env.auth.domain,
>       responseType: this.env.auth.responseType, // "code token id_token" 
>       redirectUri: this.env.auth.redirectUri,
>       scope: this.env.auth.scopes,
>       audience: this.env.auth.audience,
>     });
> 
>     this.auth0.authorize({
>       connection: this.env.auth.connection,
>       state: nonce
>     });
> 
>     console.log(auth0);
> ```
> 
> (Omitted sensitive properties)
> 
> Request:
> 
> ```
> {
>   "clientID": "",
>   "domain": "",
>   "responseType": "code token id_token",
>   "redirectUri": "https://localhost:4202/auth0/callback",
>   "scope": "openid",
>   "audience": "",
>   "plugins": {
>     "plugins": []
>   },
>   "_sendTelemetry": true,
>   "_timesToRetryFailedRequests": 0,
>   "tenant": "",
>   "token_issuer": "",
>   "legacySameSiteCookie": true,
>   "rootUrl": "",
>   "universalLoginPage": true
> }
> ```
> 
>  ```
> {
>   "accessToken": "",
>   "idToken": "",
>   "idTokenPayload": {},
>   "appState": null,
>   "refreshToken": null,
>   "state": "",
>   "expiresIn": 300,
>   "tokenType": "Bearer",
>   "scope": "openid"
> }
> ```
> 
> ### Environment
> > Please provide the following:
> > "auth0-js": "^9.19.0",
> > Chrome, Safari, Edge
> > Angular @13 @down4some1

**Comment by stevehobbsdev** [comment]
Closing for now but if you need any further help, please feel free to continue the conversation.
