### ISSUE TITLE
Auth0.js v9 API Docs contain broken links

### ISSUE THREAD

**Issue by mcooper-cloud** [auth0/auth0.js#1248]
### Describe the problem

The Auth0.js v9 documentation here: https://auth0.github.io/auth0.js/index.html

Contains 2 broken links:

1. v9 Migration Guide: https://auth0.com/docs/libraries/auth0js/v9/migration-guide
2. v8 Migration Guide: https://auth0.com/docs/libraries/auth0js/v8/migration-guide

Additionally, the introductory statement: "If you want to read the full API documentation of auth0.js, see [here](https://auth0.github.io/auth0.js/index.html)."  redirects the user back to the page they are on.

### What was the expected behavior?

> That these links work

### Reproduction

Click the links

### Environment

Published documentation, assumed to be production

**Comment by stevehobbsdev** [comment]
Thanks for raising @mcooper-cloud, I'll find out from our internal docs team where these have moved to, ideally we'd just put a couple of redirects in.

**Comment by stevehobbsdev** [comment]
@mcooper-cloud Are you looking to use the docs to facilitate an upgrade you're doing?
