### ISSUE TITLE
auth0 requesting for r_network in the LinkedIn gives Error

### ISSUE THREAD

**Issue by andela-idurotola** [auth0/auth0.js#125]
setting linkedIn as the connection with angular-auth0 returns an access_denied error
this error is traced to auth0js and outputs
**error_description: "Your application has not been authorized for the scope "r_network""**

**Comment by siacomuzzi** [comment]
Hi @andela-idurotola ,

Looks like LinkedIn is showing a wrong info from `Default Application Permissions` section for apps created before May 15th (see http://stackoverflow.com/questions/30241229/linkedin-new-api-cant-get-r-network-permission)

This is the explanation of your error: https://developer.linkedin.com/support/developer-program-transition#troubleshooting

Summary: If you want `r_network` or `r_fullprofile`, you need to [apply to become a LinkedIn Partner](https://developer.linkedin.com/partner-programs/apply)
