### ISSUE TITLE
Vertx module not found when building with Vite (rollup)

### ISSUE THREAD

**Issue by SirMishaa** [auth0/auth0.js#1250]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem
Hello, 

I'm doing a big migration from babel and vue-cli-service to Vite for work. I have the auth0.js dependency on the latest version.
When I'm starting the dev server or building the application, I got the following issue :

```
Failed to resolve import "vertx" from "node_modules/.vite/deps/auth0-js.js?v=f0fbb50a". Does the file exist?
1:48:56 PM [vite] Internal server error: Failed to resolve import "vertx" from "node_modules/.vite/deps/auth0-js.js?v=f0fbb50a". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/mishaa/yago/ardor/node_modules/.vite/deps/auth0-js.js?v=f0fbb50a
  1  |  import * as __require_for_vite_tEUVFk from "vertx";
     |                                              ^
  2  |  import "./chunk-ACCAMVX6.js";
  3  |  
      at formatError (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39055:46)
      at TransformContext.error (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39051:19)
      at normalizeUrl (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58329:26)
      at async TransformContext.transform (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58478:57)
      at async Object.transform (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39292:30)
      at async doTransform (/home/mishaa/yago/ardor/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50012:29)
```

I have done some search https://github.com/stefanpenner/es6-promise/issues/100 and here https://yarnpkg.com/package/vertx, I see that there is a "placeholder" library, for some security reason

I also see that auth0 are doing a requirement for this library (auth0.min.esm.js)

Does anyone know how to solve this issue? I'm a bit lost... I can't found a solution
Kind regards

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

See here: https://github.com/SirMishaa/debug-vertx

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of Auth0.js used:** Latest (9.18.0)
- **Which browsers have you tested in?** /
- **Other modules/plugins/libraries that might be involved:** Vite

**Comment by SirMishaa** [comment]
My opinion is that there is a sub-library of auth0 that requires this weird library (vertx) and makes the build process crash for some reason.

**Comment by SirMishaa** [comment]
Ok, finally, I have successfully done a reproduction, see here : 
https://github.com/SirMishaa/debug-vertx

**Comment by charlesmass2** [comment]
Thanks for sharing your resolution.
On our end, we fixed it by adding the `skipPreBuild` option.
Looks like this : 
```js
plugins: [
  viteCommonjs({ skipPreBuild: true }),
```

**Comment by charlesmass2** [comment]
Thanks for sharing your resolution.
On our end, we fixed it by adding the `skipPreBuild` option.
Looks like this : 
```js
plugins: [
  viteCommonjs({ skipPreBuild: true }),
```

Usgae of skipPreBuild : https://github.com/originjs/vite-plugins/blob/main/packages/vite-plugin-commonjs/src/index.ts
