### ISSUE TITLE
unauthorized_client

### ISSUE THREAD

**Issue by Simon5052** [auth0/auth0.js#1261]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the ideal solution

> A clear and concise description of what you want to happen.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by Simon5052** [comment]
I am trying to implement passwordless log in on a custom login. when the request is hit i get this error  error: "unauthorized_client", error_description: "Client authentication is required"}
error: "unauthorized_client"
error_description: "Client authentication is required"

Is there anyway to go about this

**Comment by stevehobbsdev** [comment]
@Simon5052 Can you check what type of application you created for this within your Auth0 dashboard? The app you're connecting to (distinguished by the "Client ID" you're using) should have it's "Application Type" set to "Single Page Application" in the settings.

![image](https://user-images.githubusercontent.com/766403/183100328-8f1e6667-10a0-4b23-ae38-82048bd46b37.png)

**Comment by Simon5052** [comment]
@stevehobbsdev the type of application i created on auth0 is the regular web application.  and I also have another question when the social log in is implemented when you log in using maybe Facebook the redirection is done on the pop up not the app itself. Is there a fix for that ?

**Comment by stevehobbsdev** [comment]
@Simon5052 When working with a SPA client, you'll need that setting set to "Single Page Application" with "Token Authentication Endpoint Method" set to "None", otherwise it'll need you to send the client secret - this is why you're getting the `unauthorized_client` error.

> the redirection is done on the pop up not the app itself

If you're opening up the login page in a popup, all the interactions with the login page including redirecting to social vendors will happen inside that popup.

**Comment by Simon5052** [comment]
I will do that. I have a question with the redirection. Does that mean I can’t do anything to make the redirect to be done on my app. Even when the redirection is not specified it does the redirection on the pop up. It leaves my client using the pop up with the real web application is stuck on the log in page  Sent from Mail for Windows From: Steve HobbsSent: Monday, 8 August 2022 11:41 amTo: auth0/auth0.jsCc: Agyare kofi Ofori; MentionSubject: Re: [auth0/auth0.js] unauthorized_client (Issue ***@***.*** When working with a SPA client, you'll need that setting set to "Single Page Application" with "Token Authentication Endpoint Method" set to "None", otherwise it'll need you to send the client secret - this is why you're getting the unauthorized_client error.the redirection is done on the pop up not the app itselfIf you're opening up the login page in a popup, all the interactions with the login page including redirecting to social vendors will happen inside that popup.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Simon5052** [comment]
@stevehobbsdev I will do that. I have a question with the redirection. Does that mean I can’t do anything to make the redirect to be done on my app. Even when the redirection is not specified it does the redirection on the pop up. It leaves my client using the pop up while the real web application is stuck on the log in page

**Comment by stevehobbsdev** [comment]
@Simon5052 You're able to pass a callback handler to `popup.authorize` that should tell you when auth is finished and the popup has closed - there you will have to do something within your app to redirect your browser at the top level.

> auth0 will be used in an asp.net mvc so wouldn't the single page application not be feasible

You're mixing two worlds of a web app here and a SPA app. You're unable to use a "Regular Web Application" type using this SDK as a client secret value is required. While you can send one, we recommend against doing this as it's difficult to store the client secret in the browser securely. As you're using an Asp.Net MVC web app, our recommendation would be to do all the auth there and redirect the browser at the top level. While it might not be a desirable user experience for your own app, it's the more secure out of the two and won't require to mix a web app and a SPA.

Closing for now as I don't believe there's anything we can do at an SDK level, but happy to continue the conversation. You might also find more guidance around your specific app needs in our [Community forums](https://community.auth0.com).
