### ISSUE TITLE
Nextjs 13 CORS issue

### ISSUE THREAD

**Issue by tw1t611** [auth0/auth0.js#1275]
### Describe the problem

I recently upgraded nextjs 12 to nextjs13, which introduces react server components.
Since than I am facing a cors error on preview and production for `/oauth/token` when calling `login()` function.
Localhost is still working.
The project is deployed on https://vercel.com.

https://preview-polyma.vercel.app/login
![image](https://user-images.githubusercontent.com/13353525/201660880-fef532b8-4796-4f29-bcf4-74bf69bbb642.png)

auth client:
```js
import auth0 from "auth0-js";

export default new auth0.WebAuth({
  domain: "dev-4svxi0bz.eu.auth0.com",
  clientID: "vHE98GMdpUVFksKkYAO32MjdfRjNZqxb",
})
```

login:
```js
  async function login(data) {
    try {
      let audience;
      if (data.email.endsWith("@polyma.io"))
        audience = "https://db.fauna.com/db/y1g9bfuqcyrcq";

      webAuth.client.login(
        {
          realm: "Username-Password-Authentication",
          username: data.email,
          password: data.password,
          audience,
          scope: "openid profile email",
        },
        function (err, authResult) {
          if (err) {
            setErrorMessage("Nutzername oder Passwort falsch.");
            return;
          }
          setToken(authResult.accessToken);
          if (!audience) {
            router.push("/request-demo");
            return;
          }
          router.push("/");
        }
      );
    } catch (err) {
      console.log(err);
    }
  }
```

app settings:
![image](https://user-images.githubusercontent.com/13353525/201664235-a0fd58a4-73e1-435a-b36b-9fa8ed1db37d.png)

grand types:
![image](https://user-images.githubusercontent.com/13353525/201664340-aa27625d-7343-470a-a93d-39d2e6fa5007.png)

full request:
![image](https://user-images.githubusercontent.com/13353525/201665477-4664eef8-fe36-4715-b099-3952645e5051.png)

### What was the expected behavior?

Request should go through, if cors origin is set in auth0 web ui.

### Reproduction

- Create default nextjs13 app
- Create oauth app
- Add origin

### Environment

- authjs 9.19.2
- latest firefox, chromium
- nextjs 13 with react server components

**Comment by stevehobbsdev** [comment]
@tw1t611 Thanks for your patience here. Looks like the config is ok to me. It's unlikely that the Next.js 13 upgrade would have caused this though. If you downgrade back to 12 (without any other changes) does it work again when deployed to Vercel?

Have you checked out our docs on Cross-Origin Authentication? https://auth0.com/docs/get-started/applications/set-up-cors - it may be that you need to set up the cross-origin authentication page.

Just generally speaking, embedded login has a certain shelf-life, as it only works in browsers that do not block third-party cookies. The recommendation is to redirect to the `/authorize` endpoint (using `webAuth.authorize`) for maximum security and compatibility with your clients, but can affect the user experience a bit as it does require a redirect. Our [Next.js Auth0 SDK](https://github.com/auth0/nextjs-auth0) is built especially for Next.js apps and provides the best developer experience.

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
