### ISSUE TITLE
Auth Redirect mismatch throws no Error

### ISSUE THREAD

**Issue by EduardJ** [auth0/auth0.js#1276]
### Describe the problem

> When The config redirectUri does not match the hosted URL no error is thrown and nothing happens (calling checkSession({})).

### What was the expected behavior?

> If there is a mismatch between redirectUri and hosted ref it should throw an Error letting the user/developer know whats wrong.

### Reproduction

- Step 1 Change Redirect URL to random localhost port  `http://localhost:randomPort/`
- Step 2 Call Checksession method

### Environment

> Please provide the following:

- **Version of Auth0.js used:**  "auth0-js": "^9.19.0",
- **Which browsers have you tested in?** : Chrome Version 107.0.5304.107
- **Other modules/plugins/libraries that might be involved:** Framework: Angular

**Comment by stevehobbsdev** [comment]
Could you please provide us with a concrete example that demonstrates the issue you're trying to solve? I generally agree that we should throw appropriate errors where possible.

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
