### ISSUE TITLE
Webpack Error - "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by lordakshaya** [auth0/auth0.js#128]
Hey,

I am trying to setup a React App using Webpack + Auth0-js. I did configuration per the example at https://github.com/auth0/lock/tree/master/examples/webpack. But, I am getting the error:

`error given was: ReferenceError: window is not defined`

Any idea, how to get past thru this? The baseline React App that I am using can be found at https://github.com/erikras/react-redux-universal-hot-example.

**Comment by cristiandouce** [comment]
https://github.com/auth0/lock/tree/master/examples/webpack is working with the latest Lock.

If you can please provide a sample repo/setup to try.
