### ISSUE TITLE
Unable to run examples on localhost

### ISSUE THREAD

**Issue by siddtheone** [auth0/auth0.js#1283]
I am unable to run examples on localhost.

- Cloned the repo on mac with VS code
- Ran `npm install` on project root.
- Ran `npm start`

![image](https://user-images.githubusercontent.com/45398971/209946355-92f91c9c-e8ab-4ab0-b891-0b4fca9931c1.png)

Tried on windows 11, in VS code. Same error in PowerShell

![image](https://user-images.githubusercontent.com/45398971/209954850-98f09193-8a77-4ce6-85ab-a2734a1375c1.png)

**Comment by ewanharris** [comment]
👋🏻  @siddtheone, thanks for the issue!

For the first error, please ensure you're using Node.js 14 or newer as the dev server uses some features only available from that [that version](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).

As for the second one, it's unfortunate that we use unix commands that aren't always available on Windows. We could 
potentially replace those calls with [rimraf](https://www.npmjs.com/package/rimraf) (although I do not have a Windows machine available to test the full dev flow), I'd be happy to review a PR for that if you were able to test on your Windows machine

**Comment by siddtheone** [comment]
I can test it.

**Comment by ewanharris** [comment]
Closing this issue out as the main issue is fixed, happy to review the Windows PR if you're still interested in that.
