### ISSUE TITLE
Superagent is severely outdated and is causing deprecation warnings

### ISSUE THREAD

**Issue by Twipped** [auth0/auth0.js#1288]
### Describe the problem

Superagent 5.3.1 was released June 27th, 2020. Current version as of opening this issue is 8.0.8.
As of version 7, Superagent began issuing deprecation warnings for anything older than 7.0.2.

```
npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
```

Additionally, the version of `formidable` that superagent 5.3.1 relies on is ALSO issuing deprecation warnings:

```
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
```

```sh
$ npm ls formidable       
[redacted project name]
└─┬ auth0-js@9.20.1
  └─┬ superagent@5.3.1
    └── formidable@1.2.6
```

### What was the expected behavior?

I expect auth0 to not be relying on deprecated libraries.

### Reproduction

Open a new terminal window:

```sh
$ mkdir temp
$ cd temp
$ npm i auth0-js
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
```

### Environment

> Please provide the following:

- **Version of Auth0.js used:** 9.20.1
- **Which browsers have you tested in?** N/A
- **Other modules/plugins/libraries that might be involved:** Superagent

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @Twipped , I've raised #1296 to address it.
