### ISSUE TITLE
Release a new version to include superagent update to 7.1.5

### ISSUE THREAD

**Issue by RomanHotsiy** [auth0/auth0.js#1298]
Could you, please, cut a new release to include [this commit ](https://github.com/auth0/auth0.js/commit/ad6901e7dec89d9c7e9643c2f222b7a9bac5a30b).

Those deprecation warnings are annoying 😅 

![image](https://user-images.githubusercontent.com/3975738/220947713-6d3ca71c-0496-4d67-9d81-6bd99497d089.png)

Thanks in advance 🙌

**Comment by stevehobbsdev** [comment]
Thanks, raised in #1299

**Comment by stevehobbsdev** [comment]
This is now released, let us know if you get any issues 👍🏻

**Comment by RomanHotsiy** [comment]
Thanks! 🙌
