### ISSUE TITLE
Override cookie domain option

### ISSUE THREAD

**Issue by telmaantunes** [auth0/auth0.js#1303]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We have multiple apps, each on their own subdomain. We want users to be able to sign in on any of these subdomains and remain signed in when visiting the other subdomains.

Currently, a cookie is created with a domain that includes the subdomain. This is too specific; the cookie will only exist on that subdomain and none of the others. In order for the cookie to span multiple subdomains it must be written as domain=.site.com.

### Describe the ideal solution

Ideally, I would be able to set a cookieDomain variable as part of the client options, on [WebAuth](https://github.com/auth0/auth0.js/blob/50de71b2af13fe28136e878032f88ec78fcc3888/src/web-auth/index.js#L46), so that later on it can be used on [CookieStorage.setItem()](https://github.com/auth0/auth0.js/blob/master/src/helper/storage/cookie.js#L24) method. There the domain can be added to the cookieAttributes when the cookie is created.

This would allow a top level domain cookie to be created with all the correct attributes, including the correct expiry date, that is accessible across multiple subdomains.

### Additional context

This issue is **heavily** based on this [one](https://github.com/auth0/auth0-spa-js/issues/884), made by @Soviut. 
Since this was approved and implemented already, I only want to match this feature.

**Comment by frederikprijck** [comment]
Thanks for the PR, as mentioned it looks great but needs changes before being able to merge it!
