### ISSUE TITLE
Custom translation for reCAPTCHA while using renderPasswordlessCaptcha method

### ISSUE THREAD

**Issue by AbhilashG97** [auth0/auth0.js#1318]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Google reCAPTCHA supports the functionality to add custom translations for languages that they don't support. The documentation link for the same can be found [here](https://developers.google.com/recaptcha/old/docs/customization#custom-translations)

I really need this functionality as I'm unable to provide localization support for certain languages to the end-users with the current implementation of `renderPasswordlessCaptcha` method

### Describe the ideal solution

It would be nice if there were an option to pass custom translations via the `custom_translations` property as mentioned in the [documentation](https://developers.google.com/recaptcha/old/docs/customization#custom-translations) for Google reCAPTCHA.

Maybe something like this would work - 

```js
new auth0.WebAuth(configuration).renderPasswordlessCaptcha(
    document.querySelector(elementClass),
    {
      lang: getUserLanguage(),
      custom_translations: {
        instructions_visual: 'Scrivi le due parole:',
        instructions_audio: 'Trascrivi ci\u00f2 che senti:',
        play_again: 'Riascolta la traccia audio',
        cant_hear_this: 'Scarica la traccia in formato MP3',
        visual_challenge: 'Modalit\u00e0 visiva',
        audio_challenge: 'Modalit\u00e0 auditiva',
        refresh_btn: 'Chiedi due nuove parole',
        help_btn: 'Aiuto',
        incorrect_try_again: 'Scorretto. Riprova.',
      },
    },
  );
```

### Alternatives and current workarounds

There are no alternatives or current workarounds for custom translations as per the auth0-js documentation.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

I contacted the team that works on the captcha side of Auth0 to get there input in this request as well.

Will circle back as soon as I got more information.

**Comment by frederikprijck** [comment]
Hey @AbhilashG97,

it looks like the links you shared are referring to an older version of the docs. In recent documentation, they mention the build in [language codes](https://developers.google.com/recaptcha/docs/language), which does include `it`, which I assume you are trying to use?

I can't seem to find any use of `customer_translations` in the latest docs.

What value are you setting `lang` to?

**Comment by AbhilashG97** [comment]
Hello @frederikprijck, 

I'm really sorry, you are right, I mistakenly referred to the old documentation which used to support this. 

I'm setting the value for `lang` as `pa` ([Punjabi](https://en.wikipedia.org/wiki/Punjabi_language)) which is unfortunately not present in the list of [supported languages](https://developers.google.com/recaptcha/docs/language)

I've searched for this issue on SO but couldn't find much there either. There was [one post](https://stackoverflow.com/questions/5101517/is-there-a-way-to-set-custom-language-strings-for-the-recaptcha-asp-net-user-con) which was closest to the issue that I'm currently facing; sadly it was not much of help.

It would be really nice if there's a way to support languages not mentioned in the documentation
