### ISSUE TITLE
Add biometrics support

### ISSUE THREAD

**Issue by PSoltes** [auth0/auth0.js#1319]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hey our organization wants to provide options of all login methods to our users this includes:

- passwordless email
- passwordless sms
- password + username
- sso enterprise connections
- biometrics
First four options are currently available when using custom home realm discovery with custom login app using this library (`authorize`,`passwordlesLogin`,`login` methods) but currently there is not method to invoke or trigger biometrics login

### Describe the ideal solution

Add method/guide/example how to trigger biometrics login using this library (or some note why it is impossible why it is so, maybe some pointers with other solutions)

Something like `startPasswordlessBiometrics` or `tryPasswordlessBiometrics` so when we discover that users prefers this we can trigger this method.

### Alternatives and current workarounds

Cant find any alternatives or workarounds except having `xor` on passwordless/password+username (cause this means we don't need custom login page and biometrics work in that case)

**Comment by frederikprijck** [comment]
Thanks for reaching out, can you elaborate what you'd say the proposed two methods would do differently as opposed to regular passwordless login?

**Comment by PSoltes** [comment]
Hey thx for quick response. As far as I understand to support both passwordless (via email or sms) and password + username login, we need to have some custom JS code (either whole app for login or custom js snippet). And this means that when we want to give user options to choose from passwordless (email,sms)/password + username/passwordless (biometrics) we cant do it, because `biometrics` are only supported when no custom login html. So this why we need a method to trigger biometrics passwordless in our custom login app

**Comment by frederikprijck** [comment]
> Also just to clarify further passwordlessStart, passwordlessLogin only support email or sms param. We can't trigger passwordless biometrics with it. Adding relevant snippet from docs.

The API endpoint to start passwordless only supports sms and email for connection, see https://auth0.com/docs/api/authentication#passwordless.

I'm still not sure I understand what exactly you are asking to be implemented in the SDK. Can you elaborate on an API level what those two new methods would do?

**Comment by PSoltes** [comment]
Hey,
I am not well versed in how actually biometrics happen in background in not customized flow, but coming from this graph provided on authentication flow
![firstauth0image](https://github.com/auth0/auth0.js/assets/22454458/74aecb53-964c-45a9-86e0-2967d1930d2f)
biometrics login is somehow triggered there. And in our flow we want that too, to encompass all available login methods and provide them for user. Simplistic diagram of our custom login app flow which uses your sdk follows
![login2](https://github.com/auth0/auth0.js/assets/22454458/01329867-c4be-437f-bd0c-f1b7e6b59aaf)
Green colored rectangles are the methods your sdk provides, white ones are we do ourselves and orange ones are the ones I'd like SDK to provide, eg have ability to trigger biometric login (auth0 somehow does it so there must be some code already written for it).
If you feel that is not responsibility of this SDK to provide this functionality I have no other option but to go searching for other solutions, but as this SDK provides options to do all other ways of login it would be great for it to at least mention this option, what are the problems with it and some pointers. In best case scenario provide out of the box methods which will check in custom login app if users device is suitable for biometrics login and then actually do id, public key creation to enroll device and authenticate user.

**Comment by frederikprijck** [comment]
Thanks for the additional information. I understand what you want to achieve, but given you proposed two exact methods, I assumed you had an idea what API's it should call under the hood so I was trying to get an understanding of what your proposed solution would look like.

Looking at the Auth0 docs, I see no explicit methods to do what you want. However, that doesnt mean you can not achieve what you want.

There may be options to use Auth0's extensibility options, as mentioned here: https://auth0.com/docs/authenticate/login/auth0-universal-login/passwordless-login/webauthn-device-biometrics

Based on your explanation, I believe you might already be aware of the above information, regardless I wanted to make sure.

To achieve what you want, looking at the documentation I shared, I believe there is no need for the SDK to provide specific endpoints. Instead, you should be able to configure Auth0 as per that link, and call regular login.

However, I would recommend you to consult your Account Manager to get a better fitter person to approach this from an architectural point of view. They can circle back to us internally if they believe our SDK limits to implement the solution needed here.

**Comment by frederikprijck** [comment]
Closing this, as I think this is answered. If not, we can always reopen.
