### ISSUE TITLE
Detect if the popup window is closed

### ISSUE THREAD

**Issue by Soliah** [auth0/auth0.js#135]
It used to be possible to detect if the popup window was closed before successfully authenticating via the err that was passed to the callback via the message `"User closed the popup window"`.

This seems to have changed with the introduction of the `LoginError`class. Now the message we get back is `"server error"`. Does this message cover other types of errors? Is there another way to detect if the popup window gets closed?

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but we're doing some clean up. 🗑 
It's been a while since you opened this issue. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
