### ISSUE TITLE
Add support for new change password flow

### ISSUE THREAD

**Issue by ritdaw** [auth0/auth0.js#138]
Is the new change password flow supported in auth0.js yet? By this I switching to "forgot password > emailed link to change password > enter new password".

**Comment by rolodato** [comment]
Yes, if you don't pass a `password` parameter the new flow will be used. If you're not using it, you should disable the old flow in your account settings: https://manage.auth0.com/#/account/advanced

**Comment by ritdaw** [comment]
Thanks for clarifying.
