### ISSUE TITLE
Dashboard - Question

### ISSUE THREAD

**Issue by kilisoria** [auth0/auth0.js#140]
Hi guys,

One question, I think that it is the place where I should make one, but, I go: 
**Is there way to connect Auth0 dashboard https://manage.auth0.com with my Api?** For example if an admin user remove an one using the dashboard, Could We to get the new about it? 
The idea could be that the Dashboard when the user is removed it hits to something as POST myapi/userauth0remove/

Thanks in advance.
Regards,
Cristian

**Comment by gnandretta** [comment]
@kilisoria hi, we have an extension to do that, please see https://auth0.com/docs/extensions/authentication-api-webhooks

**Comment by woloski** [comment]
This is not the forum to ask about this, use https://ask.auth0.com next time. To answer your question, you can use this extensions in the dashboard. 
![image](https://cloud.githubusercontent.com/assets/175880/14461510/4eac9c3c-0099-11e6-901e-aadd3c4a202b.png)
