### ISSUE TITLE
Logout on iOS does not fully log the user out on the device

### ISSUE THREAD

**Issue by ogjkoch** [auth0/auth0.js#1406]
### Checklist

- [X] The issue can be reproduced in the [auth0-js sample app](https://github.com/auth0/auth0.js/tree/master/example) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We have an Ionic Capacitor app which we build for desktop web, Android and iOS.  Unfortunately, because providing configuration at application bootstrapping time is not an option, we are using auth0-js (as opposed to auth0-angular or auth0-spa).

We are able to successfully authenticate and logout in desktop web and on Android.  However, in iOS, the credentials are never cleared from the device, despite successfully redirecting back to the application, and Auth0 logs indicating that the logout was successful.

Uninstalling and reinstalling the app or clearing user browsing data in Safari settings will cause a prompt for username as expected on the next authentication attempt, but this is not an acceptable workflow for our users.

As the auth0-js sample app is massively different than than the use case I unfortunately have, I have not attempted to try to reproduce this behavior there.

### Reproduction

On an iOS device, log in.
After successfully authenticating, call WebAuth.logout, providing domain, clientID and scope.  This seems to succeed, but the user can log back in without providing credentials.

### auth0-js version

9.22.1

### Which browsers have you tested in?

Chrome, Safari

**Comment by ogjkoch** [comment]
The cause of my problem has been determined, I suspect it's not something you're going to be interested in changing so feel free to close this issue.

In a hybrid capacitor iOS app it is necessary to build the logout url yourself and launch it with Browser.open() for cookie handling to work properly.  The way the library is coded, the logout calls route through Safari instead of the WebView the app is executing within, and subsequently cookies never get cleared in the WebView as its state is not fully shared with Safari.

**Comment by frederikprijck** [comment]
Apologies for losing track of this. Good you solved it.

> Unfortunately, because providing configuration at application bootstrapping time is not an option, we are using auth0-js (as opposed to auth0-angular or auth0-spa).

I am not sure I understand, but I still believe using Auth0-Angular (or SPA-JS) is the solution. If bootstrapping time is an issue, Auth0-SPA-JS should work instead of Auth0-Angular (which is a bit more opinionated regarding when the SDK is instantiated)

**Comment by ogjkoch** [comment]
It's not the solution for my situation because we don't have necessary client details at bootstrap time, which is required by those libraries.

**Comment by frederikprijck** [comment]
> It's not the solution for my situation because we don't have necessary client details at bootstrap time, which is required by those libraries.

The Auth0SPA-JS allows for configuring and reconfiguring at any point. Feel free to open a PR in the corresponding repository if you want, and we can try and see where the complication is.

Anyway, good you resolved it, which is the main priority 👍

**Comment by frederikprijck** [comment]
> I have not been able to locate a full example documentation of this working in an Angular Ionic Capacitor application including how to properly configure providers for a use case where you cannot use AuthModule.forRoot().

Sorry if I wasnt clear, but that's why I mean to use `Auth0-SPA-JS`, not Auth0-Angular, Auth0-Angular will have difficulties in terms of configuring post-bootstrapping yes.
