### ISSUE TITLE
"Compilation failed: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by kberesfo** [auth0/auth0.js#1409]
### Checklist

- [X] The issue can be reproduced in the [auth0-js sample app](https://github.com/auth0/auth0.js/tree/master/example) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am not 100% sure this is the right repo but im experiencing the issue with both react sdk and pure js. i have created a minimal reproduceable example provided below. I get the error in my auth0 logs and on the console of the browser. im not sure how to fix this.

### Reproduction

<!DOCTYPE html />
<html>
  <head>
    <script src="https://cdn.auth0.com/js/auth0-spa-js/2.0/auth0-spa-js.production.js"></script>
  </head>
  <body>
    <script>
      auth0.createAuth0Client({
        domain: '',
        clientId: '',
        audience: ''
      }).then(async auth0 => {
        await auth0.loginWithPopup()
        const accessToken = await auth0.getTokenSilently()
        window.document.body.innerText = `{ "Authorization": "Bearer ${accessToken}"}`;
      })
    </script>
  </body>
</html>

### Additional context

I have two stacks that both started experiencing the issue at the same time. both are different os, node versions, and sdks. One of my stacks is react the other is pure js. this has become a blocker for me. I get stuck in a loop of failed to auth and the above error

### auth0-js version

2.0&1.12

### Which browsers have you tested in?

Chrome, Firefox, Other

**Comment by frederikprijck** [comment]
This is the wrong repository.

The correct repository is https://github.com/auth0/auth0-spa-js.

However, please have a look at [the sample here](https://github.com/auth0-samples/auth0-javascript-samples/blob/master/01-Login/index.html) to showcase how to use it using CDN.
