### ISSUE TITLE
Auth0 Login with Facebook Session

### ISSUE THREAD

**Issue by dimasnur** [auth0/auth0.js#141]
Hi,
Im using login function below and Auth0.prototype.loginPhonegap will be called because im using cordova. The function works fine and i can get the token. The issue is it asks username/pass everytime the popup page is opened, even though i already logged on with my browser mobile safari. Is there any param we need to send so that it will recognize my browser session ?

authAPI.login({
      connection: 'facebook',
      popup: true,
      popupOptions: popupOptions
    }

popupOptions = {
        clearsessioncache: 'no',
        clearcache: 'no'
      };

**Comment by hzalaz** [comment]
Closing this on since in cordova you need to ask the refresh token since the session is not stored. Feel free to contact us in https://support.auth0.com
