### ISSUE TITLE
Critical vulnerability in superagent dependency.

### ISSUE THREAD

**Issue by Twipped** [auth0/auth0.js#1424]
### Checklist

- [X] The issue can be reproduced in the [auth0-js sample app](https://github.com/auth0/auth0.js/tree/master/example) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

A new critical vulnerability was announced today in formidable 2.x, which is a dependency of superagent 7 and 8. Superagent needs to be updated to version 9 to get the new version of formidable which does not have this vulnerability.

See:
- https://github.com/advisories/GHSA-8cp3-66vr-3r4c
- https://github.com/ladjs/superagent/pull/1800
- https://github.com/ladjs/superagent/issues/1799
- [v9.0.0 (release)](https://github.com/ladjs/superagent/releases/tag/v9.0.0)

### Reproduction

Run `npm audit` with auth0-js installed.

### auth0-js version

9.24.1

### Which browsers have you tested in?

Other

**Comment by laurence-myers** [comment]
The CVE has been withdrawn, so `npm audit` is no longer failing.

https://github.com/advisories/GHSA-8cp3-66vr-3r4c

**Comment by in15** [comment]
Thanks all! Yeah, I saw it got withdrawn.. improper assignment. Sheesh!

Thanks again,

Ishwar

**Comment by stevehobbsdev** [comment]
Thanks @laurence-myers, was just about to comment the same thing. Thanks for raising @in15!

**Comment by Twipped** [comment]
@stevehobbsdev might I suggest the project should still update to the latest superagent, anyway? Two major versions is a notable lag.
