### ISSUE TITLE
getSSOData never returns errors

### ISSUE THREAD

**Issue by no-man-is-an-island** [auth0/auth0.js#148]
getSSOData is always returning null as the error:

https://github.com/auth0/auth0.js/blob/3cb596fa972e0e54428e1b65c5734800b502ffb4/index.js#L1675

It feels a bit strange to ask the client to pass a callback function which takes an error as the first argument when it's always null. Furthermore, I'm trying to implement single logout at the moment, and currently I have no way of telling the difference between the cases where the user has logged out in a different application from when the request has failed (due to shoddy internet, for example)

**Comment by gnandretta** [comment]
This has been fixed on `v7.0.1`, the object is provided when there's a network error.
