### ISSUE TITLE
auth0-angular v4.1.0 is working with auth0.js v.7.0.0?

### ISSUE THREAD

**Issue by adben** [auth0/auth0.js#155]
With a clean deployment of our application, bower resolving to angular 4.1.0 and auth0 7.0.0 does not seems to work as it used to (storing the token into localstorage using a0-angular-storage 0.0.15)

```
       function googleLogin() {
            var deferred = $q.defer();
            auth.signin({
                connection: 'google-oauth2',
                popup: true,
                authParams: {
                    scope: 'openid email'
                }
            }, function (profile, token, accessToken, state, refreshToken) {
                // All good
                store.set('profile', profile);
                store.set('token', token);
                deferred.resolve();
            }, function (error) {
                // Error
                deferred.reject(error);
                analyticsService.track('Login Error', {error: error});
            });
            return deferred.promise;
        }
```

We don't see any change at the documentation and in the changelog we cannot spot any crucial change, what can be the error here?

**Comment by adben** [comment]
the workaround that work for us (we are using popup: true) is to ignoring auth0-lock and forcing auth0-js to 6.8.1

**Comment by gnandretta** [comment]
@adben auth0.js 7.0.0 was released yesterday and includes breaking changes, so using 6.8.1 is the right thing to do. I've forwarded your issue to the auth0-angular repo auth0/auth0-angular#258.
