### ISSUE TITLE
Kindly update docs to reflect the breaking change in 7.0.0

### ISSUE THREAD

**Issue by hunthunthunt** [auth0/auth0.js#159]
Release 7.0.0 introduces some breaking changes to the login methods callback function, primarily:

> The callbacks passed to login* methods now take just two arguments

However none of the online docs, nor the `example/index.html` file reflect this change.

Additionally, it would be very useful to add to the documentation all of the option properties that are accepted by the login method with a description of what each of them do.

Thanks

**Comment by gnandretta** [comment]
Hi, the example page has been updated in #160 and the online docs are being updated right now.
I will schedule some time in the near future to update our README. I've created #161 for that.

**Comment by hunthunthunt** [comment]
👍
