### ISSUE TITLE
Light version

### ISSUE THREAD

**Issue by tj** [auth0/auth0.js#163]
It would be great to have a light build, omitting the graphical stuff if you're not using that. The current build is pretty big, and takes ~130ms on my machine to evaluate. If there's anything that exists already let me know!

**Comment by tj** [comment]
wrong lib

**Comment by tj** [comment]
nvm, correct lib, hahah.. lock-*.js has this as a dep :D

**Comment by hzalaz** [comment]
@tj this the lightweight lock library if you don't want Lock UI (no graphical stuff) and is what Lock uses to perform authentication against Auth0. 
We are planning to rewrite it, so it'll probably be smaller but I don't expect a lot of improvement there. 
The  only issue you have is the build time or is there some functionality that you think it should not be here?.

**Comment by tj** [comment]
Cool yea it's quite a bit smaller without the lock, I'll take a closer look what what I actually need. I don't need old browser support so I can probably remove ~80% haha. Thanks!

**Comment by hzalaz** [comment]
Cheers, if you can share what you end up using please do 😄. Part of our rewrite will involve removing support for some really old browsers

**Comment by tj** [comment]
Ended up just using parseHash / decodeJwt / getProfile, shaves quiteeeee a bit out. Could just be the bulk from before, but sans-CDN before/after:

<img width="526" alt="screen shot 2016-05-20 at 5 49 04 pm" src="https://cloud.githubusercontent.com/assets/25254/15445449/98d3b1e6-1eb3-11e6-892f-f93820dc7452.png">

<img width="575" alt="screen shot 2016-05-20 at 5 49 55 pm" src="https://cloud.githubusercontent.com/assets/25254/15445450/9aa8ccae-1eb3-11e6-82ae-e963d03502f6.png">
