### ISSUE TITLE
aws delegation fails with 'Missing principal parameter'

### ISSUE THREAD

**Issue by whyvez** [auth0/auth0.js#164]
I noticed this while working on a new app but went back and realized that its broken on other apps we have built. This is concerning especially that there has been an issue in the user forum for 12 days now without any response back from Auth0. I also tried using the Auth0 API Explorer with the same results.

https://ask.auth0.com/t/aws-delegation-fails-missing-principal/2766

**Comment by gnandretta** [comment]
Hi, I noticed you already saw the answer on the forum but I'll answer here because it might help someone else.

The issue was due to a security fix in the API and no changes in auth0.js are required. Details can be found on https://ask.auth0.com/t/aws-delegation-fails-missing-principal/2766/5.
