### ISSUE TITLE
reqwest version used expect a window object

### ISSUE THREAD

**Issue by kandros** [auth0/auth0.js#170]
reqwest version 1.1.4 from package jason expect a window object, I'm building universal application and this is causing a compilation error #127

More recent versions of reqwest does handle the situation in wich window is not defined.

please consider update

**Comment by phuna** [comment]
@kandros : Did you get through this? I'm having the sample problem

**Comment by kandros** [comment]
@phuna i forked and updated reqwest manually, and used https://github.com/webpack/imports-loader when possible

**Comment by phuna** [comment]
@kandros Thanks for the information

**Comment by MacsDickinson** [comment]
I'm getting this too trying to add auth0 to a universal react app.

It's being = looked at here https://github.com/auth0/auth0.js/pull/181

**Comment by itsovereasy** [comment]
I'm suddenly running into this issue as well. No idea why it wasn't happening before, as I've been using this lib and running CI with mocha for a month now.

Winchan is also causing issues due to its calling of the browser global `navigator`

This is causing my builds to fail!
