### ISSUE TITLE
getProfile doesn't validate token

### ISSUE THREAD

**Issue by jniemin** [auth0/auth0.js#171]
Document states:
> The getProfile method allows you to obtain the user information after a successful login, and validates the JSON Web Token.

Token is not actually validated at all. It just decodes base64 encoding and returns content. It doesn't validate if the content matches the signature.

Is this something that should be changed in code or in docs to make them match?

**Comment by jniemin** [comment]
Or it does the validation if user_id is not defined. But at least the tokens I get from auth0 has user_id set.

**Comment by gnandretta** [comment]
Hi, the validation is done by the API. I've removed that part from the docs in 6f3791f3187f0298d6436ae5e95cc14219e66e9d to avoid any confusions.

**Comment by jniemin** [comment]
The validation code doesn't seem to get called at all

This if statement in `Auth0.prototype._getUserInfo = function (profile, id_token, callback)` is always returning true (at least in my case the profile and user_id is always there)
`if (!(profile && !profile.user_id)) {
    return callback(null, profile);
  }`

Is this intentional behaviour?

**Comment by jniemin** [comment]
This actually leaves the token vulnerable. If someone gets access to the token and is able to change it's content. `getProfile(token)` call happily returns the modified profile as the content is not verified against the signature.
