### ISSUE TITLE
str.Replace is not a function

### ISSUE THREAD

**Issue by Kaffiend** [auth0/auth0.js#176]
using via cdn with Angular 2 app and when submitting a custom login form, get a.replace is not a function.

Pulling in the unminified, it ends up being str.Replace 

Lock works fine, but im trying to use my own login forms.

Any suggestions?

**Comment by gnandretta** [comment]
Hi, could you provide a sample reproducing the issue?

**Comment by cristiandouce** [comment]
Please reopen with more information if you still have this issue.
