### ISSUE TITLE
Unauthorized error calling either login or signup methods

### ISSUE THREAD

**Issue by hunterleaman** [auth0/auth0.js#177]
Im getting this error calling the login method:

`POST https://<domain>.auth0.com/oauth/ro 401 (Unauthorized)`

```
code: "invalid_request"
error: "invalid_request"
error_description: "specified strategy does not support requested operation (instagram)"
```

**Comment by gnandretta** [comment]
Hi! could you provide a code sample reproducing the issue? Please include the creation of the `Auth0` instance and the call to the methods that cause the error.

**Comment by hunterleaman** [comment]
Auth0 initialization:

```
import * as Auth0 from 'auth0-js';

const Auth0Vars: Auth0ClientOptions = {
    clientID: 'heLoS7seNdpMFeTcwH7gSotR7JHPMYQa',
    callbackURL: window.location.href,
    callbackOnLocationHash: true,
    domain: 'trendlycommerce.auth0.com'
};

export const Auth0Instance = new Auth0(Auth0Vars);
```  
  
Method call:

```
let options = {
      popup: false,
      sso: false,
      connection: 'instagram',
      username: user.username,
      password: user.password,
      responseType: 'token'
    };

    return Auth0Instance.login(options, (err, profile, id_token, access_token, state) => {

      if(err) {
        console.log(err.details);
        return;
      }

      console.log(profile, id_token, access_token, state);
      // return this.signIn(access_token);
    });
```

**Comment by npradeeptha** [comment]
Is this only for Instagram? Have you tried any other methods to sign-in? I.E. google or facebook?

**Comment by hunterleaman** [comment]
Only for Instagram as far as I can tell. Tried GitHub and it works

**Comment by hunterleaman** [comment]
Actually, no, that was without using auth0-js, so yes only tried with Instagram.

**Comment by gnandretta** [comment]
Please, try removing the `username` and `password` from `options`. When `login` receives those parameters it assumes that it needs to perform the login using them instead of logging in with a social provider (like instagram).

**Comment by hunterleaman** [comment]
Great thank you. I removed them and it forwards me to Instagram login. Is that all I can do?

**Comment by npradeeptha** [comment]
@hunterleaman this is not related to your question but, how did you get `import * as Auth0 from 'auth0-js';` to work? 

I installed it but I couldn't find any typings for it, so I resorted to importing the .js file.

**Comment by jjn1056** [comment]
I know this thread is probably long gone but I wanted to add a note for anyone that happened upon it like me.  Basically most of the social connections don't allow you to login with a username/password anymore.  they've deprecated them for security and privacy reasons.  So this feature is mostly useful if you are using a database connection.  Its also possible some of the available social connections might still support it but none of the big ones (google, MS, Facebook) support it.  You should follow the oauth2 process instead.  So yes, having it return you a 302 redirect to the location of the login page for the social connection is 'all you can do'.

**Comment by hzalaz** [comment]
@jjn1056 it was an undocumented behaviour of auth0.js and it was never intended to work like that. If it did it was a bug in auth0.js v7 since it handled what endpoint to hit magically depending on the parameters. To login with a social IdP you must redirect to their site using /authorize and the connection name.

If you find a doc that says otherwise please let us know so we fix it
