### ISSUE TITLE
Security Vulnerability in indirect dependency "Negotiator"

### ISSUE THREAD

**Issue by chapati23** [auth0/auth0.js#178]
https://snyk.io/test/github/auth0/auth0.js

Not directly fixable here but I've seen that you forked `winchan` so might be patchable there?

**Comment by jfmercer** [comment]
I too have received this security error when I run `nsp`:

![image](https://cloud.githubusercontent.com/assets/590520/17855141/0118ab8c-6845-11e6-8a17-d54d3f70d5fd.png)
