### ISSUE TITLE
Checking callback arity to determine whether or not to redirect breaks with default args

### ISSUE THREAD

**Issue by sgtpepper43** [auth0/auth0.js#189]
In the `auth0.login` method, in order to determine whether or not auth0 should make a redirect, you check the arity of the callback function to see if the callback expects a response, [here](https://github.com/auth0/auth0.js/blob/master/index.js#L1293). Also see the comment above for more explanation. The problem is that, [according to the javascript spec](http://www.ecma-international.org/ecma-262/6.0/#sec-function-definitions-static-semantics-expectedargumentcount), default arguments do not count towards `function.length`. So if anyone sets a default for `err` or `response`, it will redirect. It would be much better to just provide a `redirect: true|false` option.

In my particular case, my callback looks like this:
`(err, { idToken } = {}) =>`. I only need the `idToken`, so I'm just destructuring it off of the response. When there's an error, though, the response object is `undefined`. In that case, I have it default to an empty object ` = {}` so that it won't throw any errors. But babel transpiles that like so:
```javascript
(function (err) {
  var _ref = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

  var idToken = _ref.idToken;
})
```
Which clearly sets the arity to 1, which it ought to. To get around this I simply do my destructuring on the next line, but that's not really a satisfactory solution, especially considering others might run into this problem and just have no idea why it's not working. I only found it because I only just migrated the code to es6; if this were a new project and I'd never used auth0 before I would've had no idea what was breaking.

**Comment by cristiandouce** [comment]
This will be fixed in the `vNext`.
