### ISSUE TITLE
Some Callbacks of getDelegationToken return non Error Object in err param

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0.js#192]
Most of the code paths pass an error object, but this path does not: https://github.com/auth0/auth0.js/blob/d0680993bebaf4efaebf229049a15203b4445dda/index.js#L1589-L1591

I think you want:

``` js
callback(new LoginError(err.status, JSON.parse(err.responseText)))
```

**Comment by hzalaz** [comment]
Will be part of our v8 rewrite
