### ISSUE TITLE
How do I pass in additional claims with getDelegationToken?

### ISSUE THREAD

**Issue by johnlim** [auth0/auth0.js#193]
I'm trying to obtain a delegation token with additional claims. How to do i pass in these additional claims? 

Using https://auth0.com/docs/api/authentication#!#post--delegation as an example, the token i received back never contains the `claims` field as needed by https://firebase.google.com/docs/auth/server/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library 

Using the method ```getDelegationToken()```, what are the options that are needed to be passed in order to have the `claims` field in the resultant token to be populated?

Thanks

**Comment by hzalaz** [comment]
Please submit your questions in support.auth0.com

**Comment by tomtobac** [comment]
@johnlim Did you find how? Support takes like 1+ week to answer a technical questions...

**Comment by johnlim** [comment]
@tomtobac Iol. I understand your pain but to be fair they did get back to me with the following answer: 
```
You can create a new rule within Auth0 for the client you are trying to use Firebase with and pass the claims you want into the "user.firebase_data" property as shown below.
This property is used by the delegation endpoint to generate the id_token which contains the token format required by Firebase API and is the consumed by Firebase API to set the firebase refreshtoken with the claims as required
Example:
function (user, context, callback) {
if (context.clientID === '<client_iud>' && context.protocol !== 'delegation') {
user.firebase_data = {
user_id: new Buffer(user.email).toString('base64'),
email: user.email,
otherclaims : {premium_account : false, nickname : user.nickname}
};
}
callback(null, user, context);
}
```
This is documented under the firebase add on page.
If you go to a client and then to the Firebase add on as shown here -> https://auth0.com/docs/quickstart/backend/firebase and look at the "Usage" tab - that has the options for it.
Hope this helps.
