### ISSUE TITLE
Support new Style Password Changes

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0.js#194]
Ie using the management api: https://auth0.com/docs/connections/database/password-change#using-the-management-api

**Comment by cancan101** [comment]
Can a user not use his own Auth token to update his password? I am getting:
```
{"statusCode":403,"error":"Forbidden","message":"You cannot update the following fields: connection, client_id, password","errorCode":"insufficient_scope"}
```

**Comment by hzalaz** [comment]
Currently you can't use a token obtain during authentication to update the password with API v2. It can be done using your own server or a web task with a API v2 token with the `update:users` scope since that token must not be used inside a public client.

**Comment by cancan101** [comment]
Okay, but the user's own token is not scoped (permissioned) to perform this new style password change?

**Comment by hzalaz** [comment]
Yes, that's what I mean with

> Currently you can't use a token obtain during authentication to update the password with API v2

Not sure what you mean with the new style of password change, if you mean the v2 of the change password flow, it uses the same [method](https://github.com/auth0/auth0.js/blob/master/index.js#L611) as before minus the password, so you only need email & connection name

**Comment by mikeesouth** [comment]
Can you provide an example on how to update the password? I'm updating the user_metadata of users with the token I get from authentication. How would I update the user password? Can you provide an example @hzalaz ?

**Comment by BrunoQuaresma** [comment]
I have the same problem.

**Comment by hzalaz** [comment]
Just call this method and your user will receive an email to change the password: http://auth0.github.io/auth0.js/docs/global.html#changePassword.
