### ISSUE TITLE
Auth0.js Doc error fo Change Password

### ISSUE THREAD

**Issue by PaulKohlerSeek** [auth0/auth0.js#195]
The docs for [Auth0.js Change Password](https://auth0.com/docs/libraries/auth0js#change-password) state `username` where it should be `email`:

```
  $('.change_password').click(function () {
    auth0.changePassword({
      connection: 'db-conn',
      username:   'foo@bar.com'
    }, ...
  });
```

Should be 

```
  $('.change_password').click(function () {
    auth0.changePassword({
      connection: 'db-conn',
      email:   'foo@bar.com'
    }, ...
  });
```

The same error is on [gitHub](https://github.com/auth0/auth0.js) docs... 

See [https://github.com/auth0/auth0.js/blob/master/index.js#L616](https://github.com/auth0/auth0.js/blob/master/index.js#L616)

**Comment by cristiandouce** [comment]
Thanks @PaulKohlerSeek
