### ISSUE TITLE
Remove the `getConnections` function

### ISSUE THREAD

**Issue by jstrutz** [auth0/auth0.js#196]
Remove the `getConnections` function, as suggested by @siacomuzzi in https://github.com/auth0/api2/issues/1177#issuecomment-241327532

Relevant code: https://github.com/auth0/auth0.js/blob/master/index.js#L1738-L1740

**Comment by gene1wood** [comment]
For those without access to the private auth0/api2 repo, can you share the rationale behind removing this function?

Also, I think the relevant code link should be https://github.com/auth0/auth0.js/blob/d0680993bebaf4efaebf229049a15203b4445dda/index.js#L1738-L1740

I ask because I use this function currently. Is there a plan for a replacement?

**Comment by glena** [comment]
@gene1wood you should use the [management api v2](https://auth0.com/docs/api/management/v2#!/Connections/get_connections_by_id) from your backend since management api v1 is deprecated.

**Comment by gene1wood** [comment]
@glena Sounds good. What would be a good replacement endpoint to call in the management api v2 that would provide something similar to `getConnections`?

**Comment by sgmeyer** [comment]
@gene1wood the Management API v2 doesn't have a public endpoint.  All endpoints would require an access token with a specific scope (in this case `read:connections`).  Today, the only way to achieve this via Management API v2 is to use the `Get all connections` endpoint, reduce the response to an array of connections where the `enabled_clients` array contains your client_id.

Here is the endpoint doc: https://auth0.com/docs/api/management/v2#!/Connections/get_connections

So you will need to create your own API endpoint that effectively does a client_credentials call to acquire and access token, perform an API call that reduces the response to an array as described above, and return the results.  From what I can see this is the only possible way (today) to achieve similar functionality.  I don't see an equivalent API v2 endpoint to do what you want other than this approach.

**Comment by gene1wood** [comment]
@sgmeyer Shawn, thanks for the detail. 

Does the current production Auth0 lock (`lock.js`) utilize the Management API v2 endpoint (not the unauthenticated v1 endpoint) to determine what connections to show the user? If so, how does `lock.js` obtain an access token with `read:connections` like you describe to be able to make this call?

If it's not obvious, we are making our own login interface (like the lock) and need to determine what connections to show to the user, based on the connections enabled on that RP (client_id) in auth0. Pretty simple and fundamental task for the auth0 login process.

**Comment by sgmeyer** [comment]
@gene1wood , Lock does not use API v2 for anything because those endpoints require a token.  Lock, instead uses a dynamically generated endpoint that returns the connection information as a javascript file.

Also, I know this is confusing, but the latest changes to auth0.js and lock where getConnections is removed is not intended to be used on the Hosted Login Page.  These versions are intended to be used when you are creating login forms where you host the login page outside of Auth0.

**Comment by wingrunr21** [comment]
@sgmeyer we are currently looking at implementing a custom interface via a Hosted Login Page as well. Stumbled across this issue while looking into how to get connections lists for a given client. As far as I can see the only ways to replace the `getConnections` functionality, even on a Hosted Login Page, would be to host our own API endpoint that performs the translation or to use the same method that the Lock widget uses. The first is a bummer as we have to maintain an endpoint and the second is using an undocumented method of getting that data.

Does Auth0 have recommendations as to how to implement a custom UI while also supporting dynamically displaying connections?

**Comment by luisrudge** [comment]
you have to create your own API and query the connections yourself. The contract between Lock and Auth0 can change at anytime and might break your code if you depend on it.

**Comment by wingrunr21** [comment]
@luisrudge I would hope that's not true as that would make it impossible to depend on a specific version of Lock other than whatever latest happens to be. That would also go directly against the [Lock documentation](https://auth0.com/docs/libraries/lock/v11).

I guess my feedback on this would be it appears to be very high friction to create your own login experience over something very simplistic, even if that experience is hosted by Auth0. Conversely, the Lock widget provides minimal levels of customization so it requires a ton of work and hoops by end users to duplicate its basic functionality if their use case doesn't match.

**Comment by luisrudge** [comment]
I see your point and I think it makes sense. I didn't express myself the best way I could. So, let me fix that statement.

We can change the format of the configuration file that Lock uses anytime we see fit, as long as this doesn't break old versions of Lock, of course.

You're right that we don't have a middle ground between Lock and writing everything from scratch. This is something we're looking into, but there are no concrete plans to fix this right now.
