### ISSUE TITLE
responseType is being ignored

### ISSUE THREAD

**Issue by lehphyro** [auth0/auth0.js#197]
I set responseType to token but I don't get the token data in a hash in callback url. I also don't get my callback javascript function called in popup mode. I ended up having to implement server-side support to get the token and put it in the page and call a javascript function in parent window. Here's what I had to do since your library doesn't do what it's supposed to:

Parent Window:
var auth0 = new Auth0({
        domain:       'domain.auth0.com',
        clientID:     'client-id',
        callbackURL:  '${fn:replace(pageContext.request.requestURL, pageContext.request.requestURI, '')}/callback',
        responseType: 'code'
    });
    $('#link').click(function (e) {
        e.preventDefault();
        auth0.login({
                    popup: true
                });
    });

    function my_callback(id_token) {
        console.log('got token: ' + id_token);
    }

Server side /callback handler:

@RequestMapping(value = "/callback", method = RequestMethod.GET)
    public String callback(HttpServletRequest request, Map<String, Object> model) {
        Auth0 auth0 = new Auth0("client-id", "domain.eu.auth0.com");
        AuthenticationAPIClient apiClient = auth0.newAuthenticationAPIClient();
        Credentials credentials = apiClient
                .token(request.getParameter("code"), "http://localhost:8080/callback")
                .setClientSecret("secret").execute();
        model.put("id_token", credentials.getIdToken());
        return "callback";
    }

Callback page:
<script type="text/javascript">
    var id_token = '${id_token}';
    window.opener.my_callback(id_token);
    window.close();
</script>

Really frustrating to spend hours trying to get something that you claim to have working actually working.

**Comment by hzalaz** [comment]
@lehphyro thanks for the snippet but can you share what you where doing that didn't work? 
A sample project will greatly help, otherwise we might need what auth0.js version you were using and how you initialise Auth0 object and how you call the login.

**Comment by lehphyro** [comment]
There you go: https://dl.dropboxusercontent.com/u/1401233/test.zip

**Comment by cristiandouce** [comment]
So, after checking your example we came out with this:

1. You need to use `auth0-js@7.2.0` or latest. We started accepting `responseType` parameter from version `7.1.0`

2. I see that you defined the `my_callback()` function, but you never provided it to the `auth0.login()` method.
  ```js
  auth0.login({options}, my_callback)
  ```

3. Whenever you specify `responseType: 'code'` or a `callbackURL` we asume you'll have a server side handler to make use of that code. If you want to be handling authentication from your client side app, you only need to provide `responseType: 'token'`.

So, here is the final piece of code that will work:

```js
    var auth0 = new Auth0({
        domain:       'redacted.eu.auth0.com',
        clientID:     'redacted',
        responseType: 'token'
    });

    function my_callback(err, authResult) {
        console.log('my_callback: ' + authResult.idToken);
    }

    $('#link').click(function (e) {
        e.preventDefault();
        auth0.login({ popup: true }, my_callback);
    });
```

**Comment by lehphyro** [comment]
It worked..
I got version 7.0.4 from your README file in the Initialize section. Could you please update it so that no one else has to go through what I just did?
