### ISSUE TITLE
how to get email id through auth0 social login

### ISSUE THREAD

**Issue by DESHU44** [auth0/auth0.js#204]
I have integrated auth0 code with my angular 2 application for social auth using the sample code provided at https://auth0.com/docs/quickstart/spa/angular2/04-user-profile. During social login, Auth0 is not providing me email id for facebook, twitter and linkedin. Can someone suggest how to configure it.?

**Comment by cristiandouce** [comment]
There are different approaches for those social logins. Please contact https://support.auth0.com so you can get the updated procedures. As an example, for twitter you need to set up a rule in the dashboard. Thanks!
