### ISSUE TITLE
UTF-8 characters from token getting corrupted in getProfile

### ISSUE THREAD

**Issue by lmserrano** [auth0/auth0.js#207]
Whenever the JWT Base64 token string corresponds to a token whose JSON has UTF-8 characters,, the `getProfile` call returns the decoded content with artifacts and erroneous characters.

I believe this is happening because in the `index.js` file, the `getProfile` call is defined as (as of the master version of the repository at the time of this issue's creation):

``` javascript
Auth0.prototype.getProfile = function (id_token, callback) {
  if ('function' !== typeof callback) {
    throw new Error('A callback function is required');
  }
  if (!id_token || typeof id_token !== 'string') {
    return callback(new Error('Invalid token'));
  }

  this._getUserInfo(this.decodeJwt(id_token), id_token, callback);
};
```

and the `decodeJwt` method being used is defined as:

``` javascript
Auth0.prototype.decodeJwt = function (jwt) {
  var encoded = jwt && jwt.split('.')[1];
  return json_parse(Base64Url.decode(encoded));
};
```

which is using `var Base64Url         = require('./lib/base64_url');`, and `base64_url` and which I believe is not supporting the special characters out of the box.

**Comment by mescher** [comment]
I fixed that issue by using `jwtHelper.decodeToken(myToken)` from the `angular-jwt.js` library.

Not sure if there is a non-angular version of their library, but it did the trick for me.

**Comment by hzalaz** [comment]
Will be part of our v8 rewrite. Also we recommend using `getUserInfo`
