### ISSUE TITLE
Issue with salesforce authentication

### ISSUE THREAD

**Issue by mohitn2015** [auth0/auth0.js#212]
I am using latest version of auth-0.js installed via node.I am using salesforce as openid provider but i do see an issue that the domain name configured does not match with the name in the token.
browser: chrome on mac
ex:
```
 var startSalesForceOpenIdConnectApp = function() {
        auth0 = new Auth0({
            domain: 'login.salesforce.com' + '/services/oauth2', 
            clientID: consumer_key,
            callbackURL: callbackurl,
            responseType: salesforceConfig.response_type
        });
        var provider = salesforceConfig.auth_provider;
        var nonce_gen = randomNonce(10);

        auth0.login({
            domain:  'login.salesforce.com' + '/services/oauth2', 
            connection: provider + '-auth0',
            clientID: consumer_key,
            scope: salesforceConfig.scope,
            redirect_uri: callbackurl,
            redirect: true,
            response_type: salesforceConfig.response_type,
            sso: true,
            nonce: 123,
            popup: false,
            popupOptions: {
                width: 450,
                height: 800
            }
        });
    };
 if (auth0.parseHash(window.location.hash)) {
        var result = auth0.parseHash(window.location.hash);
        console.log(result.IdToken)l
}
```
would appreciate your response?

**Comment by mohitn2015** [comment]
<img width="1081" alt="screen shot 2016-10-11 at 6 04 24 pm" src="https://cloud.githubusercontent.com/assets/13837477/19293928/3f5538f6-8fdd-11e6-96f1-76623ff07efb.png">

**Comment by mohitn2015** [comment]
The issue seems to be with the following line:

// iss should be the Auth0 domain (i.e.: https://contoso.auth0.com/)
    if (prof.iss && prof.iss !== 'https://' + this._domain + '/') {
      return invalidJwt(
        'The domain configured (https://' + this._domain + '/) does not match with the domain set in the token (' + prof.iss + ').');
    }

why do we append("/") to the domain name?because of that the error is being thrown?
This seems to be a quick fix.

**Comment by hzalaz** [comment]
@mohitn2015 auth0.js is meant to be used with Auth0 IdP not with an external one.
