### ISSUE TITLE
responseType option is ignored on passwordless logins

### ISSUE THREAD

**Issue by lnhrdt** [auth0/auth0.js#215]
The responseType constructor parameter has no effect when using passwordless login.

For example, this comes back to the callbackURL with a code, not a token:

```es6
const auth0 = new Auth0({
    domain: 'some-domain',
    clientID: 'some-client-id',
    responseType: 'token',
    callbackURL: 'http://example.com/authentication/callback',
});
requestMagicLink({email: 'someone@example.com'});
```

This behavior seems to be due to this line which calculates the responseType instead of using the constructor parameter:
https://github.com/auth0/auth0.js/blob/v7.2.1/build/auth0.js#L1814

As a result, I cannot create a "magic link" authentication flow which sends a token to a callbackURL. I am only able to send a code to the callbackURL. I can get the token by calling `verifyEmailCode` but this seems like an unnecessary step. Is this by design? If not, any tips to get this working?

using auth0-js 7.2.1

**Comment by lnhrdt** [comment]
> I can get the token by calling `verifyEmailCode`

Actually, this is turning out to be not so straightforward either. The client seems to make a call to `https://example.auth0.com/passwordless/verify` but quite strangely the server responds with the JWT in a cookie and a 400 status code. The client then returns only an error object to the callback function which is:

```es6
{error: "server_error"}
```

So I'm not able to use magic links via a token (comes back as a code) or with a code (client can't parse the server's response after calling `verifyEmailCode`). Any tips?

**Comment by woloski** [comment]
Can you open a support ticket support.auth0.com with all the details of the issue? Thanks!

**Comment by lnhrdt** [comment]
I feel like I'm really getting the runaround here. I filed a ticket like you asked but I'm having to justify getting it escalated there to get a developer to look at it.

I'm trying to get feedback on if this is a bug in auth0-js or if I'm misunderstanding it's API. Isn't that appropriate to address here in GitHub?

**Comment by hzalaz** [comment]
`startPasswordless` is not using https://github.com/auth0/auth0.js/blob/v7.2.1/build/auth0.js#L203 to determine the appropriate `response_type` value
