### ISSUE TITLE
Any plan to create a typescript version of the Auth0 class

### ISSUE THREAD

**Issue by FabienDehopre** [auth0/auth0.js#219]
I don't know if it's the good place to ask this question but any way, I'll throw it here.

Is there any plan to create a typescript version of the Auth0 class? It would make the code more readable and maintainable as well as providing a declaration file automatically (always up-to-date) to be used in any typescript-based project (like angular2).
And since the typescript is transpiled to javascript, it will remain fully compatible with previous versions.

**Comment by hzalaz** [comment]
@FabienDehopre currently we don't have plans to do it. If we decide to do it, it will be probably in https://github.com/auth0/angular-auth0 or similar library for Angular 2.

**Comment by hzalaz** [comment]
Currently this is not planned for auth0 v7, will re-evaluate once v8 is finished

**Comment by mikeesouth** [comment]
Any news here @hzalaz? I'm having trouble importing and using auth0.js v8 into my project (that uses typescript).
For auth0.js 7.6.x I used `import Auth0 from 'auth0-js'` and typescript 2.1. And I created my auth0 object using:
```
var auth0 = Auth0({
  domain: 'foo',
  clientID: 'bar'
});
```

After upgrading to v8 I'm trying to use the same syntax but with webAuth, like this:
`import Auth0 from 'auth0-js'` and
```
var webAuth = Auth0.WebAuth({
  domain: 'foo',
  clientID: 'bar'
});
```
I get no error but the returned webAuth object is undefined. Without types and these kind of breaking changes it's a real pain to upgrade to the latest versions.

I would strongly urge you to reconsider this and add type definitions to auth0.

**Comment by hzalaz** [comment]
@mikeesouth I think your are missing a `new` when creating the webAuth object ( see https://github.com/auth0/auth0.js#initialize). We *never* provided typings, they were a contribution from the community to [DefinitelyTyped](http://definitelytyped.org) repo since we don't use it internally and making sure it works is an increased cost we are not considering on taking right now. Before providing the types we are aiming on improving our docs and samples, and providing a migration guide from v7 to v8 to ease the migration process (I hope by next week we'll have it)

**Comment by mikeesouth** [comment]
@hzalaz ah - it was that simple, thanks! :)
So now I have the custom username flow almost working but I do not understand how to get user info in v8. Can you help? I have this code:
```
auth0 = new Auth0.WebAuth({
  clientID: 'CLIENT_ID',
  domain: 'DOMAIN'
});

auth0.client.login({
  realm: 'Username-Password-Authentication',
  username: email,
  password: password,
  scope: 'openid given_name family_name email user_metadata'
}, (err, result) => {

  // Auth is successful, I get idToken, accessToken and tokenType: 'Bearer'

  auth0.client.userInfo(result.accessToken, (err, user) => {
   
    // Also successful, user.sub is the userID (auth0|....)
   
    var auth0Manage = new Auth0.Management({
      domain: this.config.get(C.CONFIG_AUTH0_DOMAIN),
      token: result.idToken
    });
    auth0Manage.getUser(user.sub, (err, info) => {
      console.log('info: ', info);
    });

  });
});
```
The final auth0Manage.getUser() call gives me this error:
`XMLHttpRequest cannot load https://<masked>.eu.auth0.com/api/v2/users/auth0%7C5<masked>631. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.`
Should I pass idToken or accessToken to the getUser() call?

**Comment by luisrudge** [comment]
@mikeesouth did you add localhost to your allowed CORS endpoints in the dashboard?

![image](https://cloud.githubusercontent.com/assets/941075/21958630/630bf4e8-da91-11e6-8af8-51ff70a8d5c1.png)

**Comment by mikeesouth** [comment]
@luisrudge yes I have, that isn't the problem. Thanks for the suggestion though.

**Comment by brackio** [comment]
@mikeesouth were you able to get this resolved? I am stuck with the same problem.

**Comment by mikeesouth** [comment]
@brackio nope, I gave up quickly and used my Management API client on my server side that I use for other administrative tasks for auth0.
