### ISSUE TITLE
Exchange authorization_code for access_token and id_token not working

### ISSUE THREAD

**Issue by rug1** [auth0/auth0.js#234]
Hello,

I am using sms passwordless login and I can login correctly and I am redirected correctly to my specified callback url: `http://localhost:8000/authenticated?code=AUTHORIZATION_CODE`. I have been following [this](https://auth0.com/docs/protocols/oauth2/oauth-web-protocol) tutorial but when I get to step 4 and 5 to exchange the authorization_code for the access_token and id_token I am getting this error message back: `{"error":"access_denied","error_description":"Unauthorized"}`.

This is how I am sending the code to the Auth0 server through a POST:
```javascript
var code = request.query.code;
var url = `https://${process.env.AUTH0_CLIENT_DOMAIN}/oauth/token?client_id=${process.env.AUTH0_CLIENT_ID}&redirect_uri=http://localhost:8000/authenticated&client_secret=${process.env.AUTH0_CLIENT_SECRET}&code=${code}&grant_type=authorization_code`;

Wreck.post(url, (err, res, payload) => {
    console.log(payload.toString());
});
```
Is there something that I am missing from my querystring? Or something I need to do before sending this post request?

**Comment by glena** [comment]
Hi @rug1 

First, this issue is not related to auth0.js, so I would recommend to use the support center (https://support.auth0.com) for things not related.

Second, you need to post the payload, not send it as params in the query string. In this case it should be something like this:

```js
var code = request.query.code;
var url = `https://${process.env.AUTH0_CLIENT_DOMAIN}/oauth/token`;
var body = { 
  client_id:process.env.AUTH0_CLIENT_ID,
  redirect_uri:'http://localhost:8000/authenticated',
  client_secret:process.env.AUTH0_CLIENT_SECRET,
  code:code,
  grant_type:'authorization_code'
};

Wreck.post(url, {payload:body}, (err, res, payload) => {
    console.log(payload.toString());
});
```

Finally, check the nodejs quickstart, we suggest to use passportjs to make it easier: https://auth0.com/docs/quickstart/webapp/nodejs/00-intro

**Comment by rug1** [comment]
@glena Thanks for your help!

**Comment by himalayaahuja** [comment]
@glena Trying to implement the same for google-oauth2 social native authorization code flow, it always says error status : 403
invalid grant type and invalid authorization code.. I've done the exact steps mentioned in the documentation.. could you please help us out..??
