### ISSUE TITLE
Check for callback by counting args is wrong

### ISSUE THREAD

**Issue by mgonto** [auth0/auth0.js#26]
Right now, Auth0.js code to check if I sent a callback to do `/ro` for Username & password does the following:

````js
if (callback && callback.length > 1) {
````

This means my callback HAS to have 2 parameters to be considered a "callback".

Therefore, the following code we have on `auth0-angular` doesn't work:

````js
var applied = function(fn) {
        return function () {
          var argsCall = arguments;
          safeApply(function() {
            fn.apply(null, argsCall);
          });
        
        };
      };

signIn(options, applied(onSignInCallback));
````

As you can see I always forward all arguemnts. To make this work, I had to add 2 arguments that I don't use.

I just wanted to know WHY it checks for the amount of args of the function and if it can be changed.

Thanks!

/cc @jfromaniello

**Comment by arcseldon** [comment]
Update on progress please?

**Comment by gnandretta** [comment]
@arcseldon we will try a different approach in the next release of lock, which exposes the same behavior. If we are happy with it we can use the same thing here.

**Comment by arcseldon** [comment]
@gnandretta - thank you for reply - sounds good. A support ticket prompted my enquiry.

**Comment by cristiandouce** [comment]
This will be fixed with `vNext`
