### ISSUE TITLE
Replace callback with promises

### ISSUE THREAD

**Issue by bertolo1988** [auth0/auth0.js#274]
```
  public retrieveProfile() {
    return new Promise((resolve, reject) => {
      let idToken = localStorage.getItem('id_token');
      this.auth0.getProfile(idToken, (err, prof) => {
        if (err) {
          reject(err);
        } else {
          localStorage.setItem('profile', JSON.stringify(prof));
          resolve(prof);
        }
      });
    });
  }
```

Is there a better way of doing this?

**Comment by twistedstream** [comment]
@bertolo1988: If you use a Promise library like Bluebirdjs, you can use [promisify](http://bluebirdjs.com/docs/api/promise.promisify.html) which creates a function that wraps that callback method and returns a promise, all in one line of code:

```js
function retrieveProfile() {
  const idToken = localStorage.getItem('id_token');
  const getProfile = Promise.promisify(this.auth0.getProfile, { context: this.auth0 });
  return getProfile(idToken)
    .then(prof => {
      localStorage.setItem('profile', JSON.stringify(prof));
      return prof;
    });
}
```

**Comment by bertolo1988** [comment]
@twistedstream  thanks alot for your answer! For now, i prefer to avoid +1 more dependency.
Are you guys thinking about updating your APIs in the future?

**Comment by hzalaz** [comment]
@bertolo1988 we have no plans to add promises since not all browsers support it.

**Comment by adamdama** [comment]
@hzalaz Are you still maintaining this standpoint? At some point all modern browsers will support Promises as part of ES6 or even ES7.

Are there no plans to support new features of JS even when they are supported widely?

**Comment by luisrudge** [comment]
We will revisit this option in the next major version. We're planning v9 for some time next month. After that we'll start planning for v10 with full support for async/await (meaning, promises).

**Comment by Boid-John** [comment]
How do you not have promise support implemented yet?

**Comment by luisrudge** [comment]
@Boid-John we have other priorities right now.
