### ISSUE TITLE
Add custom fields to user profile

### ISSUE THREAD

**Issue by tgoldenberg** [auth0/auth0.js#279]
I can't find anything on this repo about adding custom fields to a user on signup and adding them to the user profile (i.e., address, full name, mobile, birthday, etc.). Can we add this to the documentation? I feel like it's an important piece. Also having difficulty instructions on this in the website itself (auth0.com), but that is a separate issue as well. Thanks!

**Comment by hzalaz** [comment]
@tgoldenberg thanks, we'll try to add this to the website docs since we want to avoid cluttering the README with all the use cases of auth0.js.

**Comment by ankitashende** [comment]
hiii, any updates on this subject? i am trying to add custom field to the login result, but could not find any documentation on the same.
