### ISSUE TITLE
[v8] README / Docs - Migration and passwordless

### ISSUE THREAD

**Issue by jonashaefele** [auth0/auth0.js#287]
I just tried to migrate from auth0.js v7.x to v 8.0.1 but got stuck even after reading through the code examples and some of the source code.

The docs are very patchy and inconsistent.

https://auth0.com/docs/libraries/auth0js uses v7.4 without explicitly mentioning it.

NPM/Github Readmes refer to v8, but omit any hints on how to migrate from v 7.x to v8.x
Readme.md for v8 lacks any reference to passwordless logins which were supported in v7.x

Helpful additions to the v8 Readme.md would be:

- basic migration guide
- documentation on how passwordless works in v8

**Comment by hzalaz** [comment]
Thanks we just released that yesterday so we are still updating the docs. Feel free to submit an issue from our docs site or contact us using https://support.auth0.com if you need assistance
