### ISSUE TITLE
Documentation vs Code samples out of date?

### ISSUE THREAD

**Issue by northern** [auth0/auth0.js#294]
Hi,

I'm just working my way through this library. I came to this repository through the documentation page on the Auth0 website: https://auth0.com/docs/libraries/auth0js

However, I find myself doing some head scratching. Eg, for username/password login, on the Auth0 documentation page I'm seeing the following code example:

    auth0.login({
      connection: 'db-conn',
      username:   $('.username').val(),
      password:   $('.password').val(),
    });

However, the documentation on this repository page seems to use this code:

    auth0.client.login({
      realm: 'Username-Password-Authentication', //connection name or HRD domain
      username: 'info@auth0.com',
      password: 'areallystrongpassword',
      audience: 'https://mystore.com/api/v2',
      scope: 'read:order write:order',
      }, function(err, authResult) {
        // Auth tokens in the result or an error
    });

Notice `realm` vs `connection` and how the values of both are distinctly different. Also notice `auth0.login` vs `auth0.client.login`. Furthermore, when cloning this repository I see example code like this:

      webAuth.redirect.loginWithCredentials({
        connection: 'tests',
        username: $('.login-username').val(),
        password: $('.login-password').val(),
        scope: 'openid'
      }, htmlConsole.dumpCallback.bind(htmlConsole));

The `connection` seems to be set to `tests` (not sure what that means).

The documentation on this repository lists a number of parameters, e.g, `domain`, `client_id`, etc. However, it seems that some more detailed information regarding these parameters is missing. E.g. what is the `audience` parameter? I'm sure the description makes sense if you know what it's purpose is. Also the `scope` parameter, what are the allowed values? The documentation shows values such as `scope: 'read:order write:order'` while the code shows scope values as `scope: 'openid profile'`.

Any insights would be much appreciated.

Thanks,
Luke

**Comment by SteveByerly** [comment]
It would also be nice to get a migration guide from v7. I was trying to compare diffs against v7, but it looks like they're on different commit histories (why?).

**Comment by hzalaz** [comment]
@northern @SteveByerly we released the library a few days ago and we are working on the docs and a migration guide, until then just feel free to browse the code or contact us via https://support.auth0.com if you have questions.

Right now there is no reason, beyond being on the bleeding edge or try new things 😄 , to upgrade to v8. The code is simple enough to understand just reding it and the public api has more comments than in v7.

@SteveByerly about the history, since it's a complete rewrite from scratch we just started from an orphan branch.

**Comment by northern** [comment]
@hzalaz Thanks for that.

Apologies. I'm just starting with Auth0 so I have no context of versions and new releases etc. Just to be clear, to some sort of documentation or guide, what exactly do you recommend?

**Comment by hzalaz** [comment]
@northern we have a lot of quick starts for SPA https://auth0.com/docs/quickstart/spa, either using Lock our your own UI with auth0.js.

**Comment by fredguth** [comment]
@hzalaz, I have 2 suggestions.  
1) Tag your API Reference so that we know that we are looking different code versions.  
2)Also, as the example directory works as an updated documentation, please add an example of passwordless login (without lock).
