### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by juanslingerURUIT** [auth0/auth0.js#301]
Hi guys,

Running on latest version of auth0 (v8.0.4) I´m seeing warning _'loginWithResourceOwner' will be soon deprecated, user 'login' instead._

Reading at API documentation under Login -> Database/AD/LDAP (Active) it advices to use
`{method: 'POST', url: 'https://YOUR_AUTH0_DOMAIN/oauth/token'}` with 'grant_type' = 'password'.

Searching the code, it replaces attribute 'grantType' for value 'http://auth0.com/oauth/grant-type/password-realm'. 

Using either one or the other, I´m having the same error that is 'unsupported_grant_type'.

Please help.
Thanks

**Comment by hzalaz** [comment]
@juanslingerURUIT you need to enable our [authorization api feature](https://auth0.com/docs/api-auth/tutorials/configuring-tenant-for-api-auth) for your tenant. 

We encourage the use of that endpoints to better use our [api authorization feature](https://auth0.com/docs/api-auth), if you don't want that just ignore the warning or there is a flag in the constructor to disable these warnings.

**Comment by juanslingerURUIT** [comment]
@hzalaz great!

Enabling the authorization API feature solve my issue!

I want to change because the warning message says that _LoginWithResourceOwner_ will be deprecated.

Thanks!
