### ISSUE TITLE
Provide up to date typescript definition type

### ISSUE THREAD

**Issue by nolazybits** [auth0/auth0.js#302]
Auth0Js V7 has the types in npm @types/auth0-js
but the V8 version doesn't have a definition yet (or I couldn't find it).

Would it be possible to include such definition either in the project itself (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) or ask the developer in charge of @types/auth0-js to leave it to you so you can sync both library and types?

The best option would be obvisouly to have it in the library itself :)
Cheers.

**Comment by hzalaz** [comment]
@nolazybits we are not planning adding the typescript definition to the project for the time being and the type definition of the older version in @types was not submitted by us. I'd suggest you contact the one who submitted it on the first place or submit your own in a PR to the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by nolazybits** [comment]
Thanks for answering that fast.
I will contact them

**Comment by Aaronius** [comment]
I know @hzalaz has stated that Auth0 isn't planning on adding TypeScript definitions, but that was more than 5 years ago. Considering TypeScript is more popular than ever, are there any plans to change this? Auth0 could definitely help out its developer community by providing types. [Here's a running list of the types missing from @types/auth0.](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52877#issuecomment-877387523)
