### ISSUE TITLE
parseHash doesn't find JWT from hosted page.

### ISSUE THREAD

**Issue by thedavidmeister** [auth0/auth0.js#305]
Using https://cdn.auth0.com/js/auth0/8.0.4/auth0.js and Chrome on Mac OS X

Please excuse the clojure.

Here's the config for authorize call.

```clojure
(def authorize-config
 (clj->js {:redirectUri (-> js/window .-location .-origin)
           ; Need a scope AND "id_token" responseType to get a JWT.
           :responseType "id_token"
           :scope "openid"}))
```

Here's creating a new WebAuth.

```clojure
(defn web-auth
 []
 (auth0.WebAuth.
  (clj->js {:domain auth.auth0.config/domain
            :clientID auth.auth0.config/client-id})))
```

A DOM element that when clicked will login by sending to the hosted login page.

```clojure
(h/defelem login
 [_ children]
 (let [web-auth (auth.auth0.api/web-auth)]
  (h/div
   :click #(.authorize web-auth el.auth0.hosted-login.config/authorize-config)
   children)))
```

Trying to scrape the JWT from the URL when returning from the hosted page.

```clojure
(let [web-auth (auth.auth0.api/web-auth)]
 (.parseHash web-auth
  (-> js/window .-location .-hash)
  (fn [e r]
   (.log js/console r)
   (when r
    (taoensso.timbre/debug "Auth0 access hash found in URL. Logging in.")
    (let [t (.-accessToken r)]
     (.log js/console t)
     (.userInfo (.-client web-auth)
      t
      (fn [e p]
       (.log js/console t)
       (.log js/console p)
       (login! p t))))))))
```

The `id_token=` appears in the URL with a valid JWT in it, but `.parseHash` logs `undefined` for `r`.

**Comment by thedavidmeister** [comment]
did some digging with `validateToken`

<img width="596" alt="screen shot 2017-01-12 at 9 26 13 pm" src="https://cloud.githubusercontent.com/assets/629710/21885938/deb39da6-d90d-11e6-96c7-c1c788cbb085.png">

the hosted page is using the wrong JWT algorithm?

**Comment by glena** [comment]
No. Your client is configured to use HS256.

The new auth0.js version enforces id_token verification on client side (signature, nonce, issuer and audience) to add an extra security layer against csrf, which is not posible with HS256 tokens (to do that you might need to expose your client secret which is a no go).

Instead, by using RS256 (it does an asymmetric cryptographic signature of the token), the sdk is able to fetch the public keys from your tenant and do the verification (while the private key keeps secure will be never exposed).

If is not posible to you to switch to RS256 in the short term, I would suggest to downgrade to v7 or implement the parseHash function on your own (here is an example of what Lock.js is doing in this scenario to provide BC https://github.com/auth0/lock/blob/master/src/core/web_api/legacy_api.js#L89-L151)

**Comment by thedavidmeister** [comment]
@glena none of this is documented at all (except one or two sentences in a docblock comment in this repo). The whole thing failed silently and didn't even provide an error to `parseHash`.

**Comment by glena** [comment]
Yes, we are working on the docs.
About failing silently, it is returning the error in the callback, isnt it?

**Comment by thedavidmeister** [comment]
from memory i only saw an error when i manually reproduced with `validateToken`

**Comment by thedavidmeister** [comment]
@glena also, I've read articles from auth0 saying that CSRF is not possible against JWT in general, so why the "extra protection"?

**Comment by thedavidmeister** [comment]
@glena https://auth0.com/blog/cookies-vs-tokens-definitive-guide/

> Cross Site Request Forgery attacks are not an issue if you are using JWT with local storage.
