### ISSUE TITLE
SAMLP Identity Provider - something went wrong: not supported connection

### ISSUE THREAD

**Issue by jonigl** [auth0/auth0.js#309]
Hi,

I'm trying to get a custom login work with SAMLP Identify Provider connection, but I received the following error message: "Not supported connection" perhaps there is something that I'm omitted or I have to change my auth0.js version.

Here is my info:
- Code snippet or sample project that reproduces the bug

```
public login(username, password) {
    this.auth0.login({
      connection: 'My-Connection-Federation-Services-Name',
      responseType: 'token',
      email: username,
    }, function(err) {
      if (err) alert("something went wrong: " + err.message);
    });
  };
```

-  Auth0.js version

> auth0-7.6.1.min.js

- Browser & OS

> Chrome Version 55.0.2883.95 (64-bit)
> macOS Sierra 10.12.2 (16C67)

Thanks!

**Comment by hzalaz** [comment]
@jonigl `Not supported connection` seems to be a server error that might be caused but some configuration in your tenant. Please contact css via https://support.auth0.com and provide us with your tenant information.

One thing I'd try is avoid passing the `email` attribute just in case.

**Comment by jonigl** [comment]
@hzalaz Avoid passing the email attribute did the trick. Thank you! 😃 
It would be nice to have this documented.
