### ISSUE TITLE
resetPassword callback converts response text to an object

### ISSUE THREAD

**Issue by Markus-ipse** [auth0/auth0.js#310]
I have the following code:
```typescript
  public resetPassword() {
    const resetOptions = {
      email: this.user.email,
      connection: this.user.identities[0].connection
    };
    this.webAuth.changePassword(resetOptions, (err, response) => {
      console.log(response); // see screenshot below
    });
  }
```
It works fine and the reset email is sent out, but the response looks as follows:
![image](https://cloud.githubusercontent.com/assets/830794/21932963/7ea32a08-d9a3-11e6-96ae-be4110186f3f.png)

**Comment by Markus-ipse** [comment]
Seems like the server sends the header `Content-Type:application/json; charset=utf-8` while the actual response body is just a string.

**Comment by glena** [comment]
Yes already reproduced and seeing internally how to properly fix it
thx for reporting

**Comment by Markus-ipse** [comment]
A patch for the service endpoint or for Auth0.js?

Just asking as it seems like it's the service that needs to be fixed so that it's Content-type actually matches the response.

**Comment by glena** [comment]
I am committing to release a patch for Auth0.js by monday
