### ISSUE TITLE
Passwordless type should be `code` or `link`. 

### ISSUE THREAD

**Issue by darkyen** [auth0/auth0.js#314]
Passwordless authentication `type` should be `code` or `link` instead of `email` or `sms`. This in turn breaks the code flow. This is reproducible at https://jsfiddle.net/p0jb23yv/8/

**Comment by ayushinigam** [comment]
For password less authentication if I use type as 'code' or 'link'
Response:  ```statusCode: 400,
  code: 'bad.request',
  description: 'the following properties are not allowed: type' } ```

And in case I remove type option
Response: ```statusCode: 400,
  code: 'server_error',
  description: 'server_error''```

**Comment by fredguth** [comment]
@ayushinigam try:
```
webAuth.passwordlessVerify({
      connection: 'sms',
      phoneNumber,
      verificationCode: code
    }, (error) => { ... });
```
