### ISSUE TITLE
popup.signupAndLogin prompts hosted Lock in Ionic

### ISSUE THREAD

**Issue by chenkie** [auth0/auth0.js#334]
When calling `WebAuth.popup.signupAndLogin` from an Ionic 1.x app, the user gets created but hosted Lock is opened in the popup and prompts for a login.

```js
function signup(username, password) {
  angularAuth0.popup.signupAndLogin({
    connection: 'Username-Password-Authentication',
    email: username,
    password: password
  }, onAuthenticated);
}

function onAuthenticated(err, authResult) {
  if (authResult && authResult.accessToken && authResult.idToken) {
    // save tokens
  }
  // ...
}
```

![popup signupandlogin](https://cloud.githubusercontent.com/assets/1847678/22308393/bbb5a0ea-e314-11e6-92ad-fafe394203ce.gif)

**Comment by glena** [comment]
Can't repro, are you using the latest version (`8.1.3`)?

![signupandlogin](https://cloud.githubusercontent.com/assets/5647310/22382010/a3b60fc2-e4a2-11e6-9d11-244ccfec5271.gif)
