### ISSUE TITLE
`delegation` will be soon deprecated, what should I use?

### ISSUE THREAD

**Issue by wong2** [auth0/auth0.js#344]
As https://github.com/auth0/auth0.js/blob/bbc6e509dd133b97e42b17f86e40f3a126b77e3c/src/authentication/index.js#L349 says: `delegation` will be soon deprecated, then what api should I use to refresh the token with refresh_token?

**Comment by hzalaz** [comment]
@wong2 for the time being it's safe to use `/delegation` we should not have published that log warning yet since the replacement is not ready yet.

Will remove this in the next version
