### ISSUE TITLE
responseType isn't optional

### ISSUE THREAD

**Issue by cesarvarela** [auth0/auth0.js#348]
The docs are outdated 

using version `"auth0-js": "^8.2.0"`
 
![image](https://cloud.githubusercontent.com/assets/1172479/22663170/5ff35f66-ec8a-11e6-9c7f-b1fb6f302f14.png)

**Comment by hzalaz** [comment]
@cesarvarela it's optional in the constructor not for `authorize` method options. Will update the docs to reflect that.
