### ISSUE TITLE
/oauth/token does not require client_secret?

### ISSUE THREAD

**Issue by victorias** [auth0/auth0.js#350]
Hi there! Quick question: Does /oauth/token no longer require client_secret? It's listed as a required parameter [in the API docs](https://auth0.com/docs/api/authentication#authorization-code) but it is not required by the SDK.

**Comment by hzalaz** [comment]
@victorias depending on the type of client you create in the dashboard you can call this endpoint without a secret, e.g. Native Mobile apps or SPAs will call this endpoint but won't be able to hold a secret in the app itself.

The type of application is specified when you create a Client in your Auth0 Dashboard
