### ISSUE TITLE
Getting user profile with id token

### ISSUE THREAD

**Issue by RobinJayaswal** [auth0/auth0.js#351]
I want to achieve the same that this code is doing, just fetching user profile, but with the id token instead of access token:

```javascript
webAuth.parseHash(function(err, data) {
  // would like to use idToken on the next line
   _self.webAuth.client.userInfo(data.accessToken, function(err, profile) {
     alert('hello ' + profile.name);
   })
})
```

Is there a method for this that I am not seeing in the source code, and if not why not?

**Comment by hzalaz** [comment]
auth0.js v8 is mean to be used with our [API Auth](https://auth0.com/docs/api-auth) feature and uses standard OAuth endpoints.

If you need to request the profile you could:

- Call `userInfo` with the `access_token`
- Decode the `id_token` with a jwt decoding library and validate it's signature (In the client with RS256 or in the backend with HS256)
- Call manually https://auth0.com/docs/api/authentication#get-token-info with the `id_token`
- Keep using auth0.js v7 that still has the method to call `/tokeninfo`
