### ISSUE TITLE
scope in the response is not expected.

### ISSUE THREAD

**Issue by idl-shaohua** [auth0/auth0.js#355]
I'm using the angular2 to implement the user login, and request can be sent and got the response. But the scope is not my expected.

Below is the request payload. I marked some information.
```
client_id: "************"
grant_type:  "http://auth0.com/oauth/grant-type/password-realm"
password: "testtest"
realm: "Username-Password-Authentication"
scope: "openid roles email name nickname user_id"
username: "test@example.com"
```

Below is the response that I got.
```
{"access_token":"****","expires_in":36000,"scope":"openid email","id_token":"****","token_type":"Bearer"}
```

Auth0-js version 8.2.0

**Comment by hzalaz** [comment]
@idl-shaohua what matters is that you got the scopes you requested in the `id_token`. Will report the issue with the server team to fix that attribute but `openid email name nickname` is the same as `openid email`
