### ISSUE TITLE
Is there a way to get a new accessToken with the refreshToken

### ISSUE THREAD

**Issue by mikegleasonjr** [auth0/auth0.js#357]
I am now using the offline access scope and I get an accessToken along a refreshToken. Great.

How can I simply call an API endpoint to get a new accessToken using a refresh token without using the whole `renewAuth` thingy?

Thanks

EDIT: in the docs it says to contact the `delegation` endpoint, but it gives you back an `id_token`, not an `accessToken`. 

EDIT2: It's funny I want to do exactly what is depicted there: https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

![](https://cdn.auth0.com/blog/refresh-token/diag2.png)

**Comment by RahavLussato** [comment]
@mikegleasonjr how did you solve this ?

**Comment by mikegleasonjr** [comment]
Add the offline_access scope to get a refresh token.
