### ISSUE TITLE
redirectUri does not work if it has the hash symbol

### ISSUE THREAD

**Issue by fredguth** [auth0/auth0.js#360]
How to replicate:

```
new auth0.WebAuth({
      domain: '{whatever}.auth0.com',
      clientID: '{Client Id}',
      redirectUri: `http://{something}/#/callback`,
      prompt: 'none',
      scope: 'openid profile',
      audience: 'https://{whatever}.auth0.com/userinfo',
      responseType: 'token'
    })
```
then, try passwordless authentication
```
webAuth.passwordlessVerify({
      connection: 'sms',
      phoneNumber,
      verificationCode: code
    }, (error) => {});

```

The Problem:
Auth0 is redirecting to `http://{something}#accesstoken...`, when we expected it would redirect to h`ttp://{something}/#/callback#accesstoken...`

It seems that the `#` inserted in the `redirectUri` confuses auth0.js.  

I looked for this handling in auth0 and couldn't find.

**Comment by hzalaz** [comment]
@fredguth I believe there is little auth0.js can do since when the user is redirected the server sets the whole fragment of the redirect uri so when it gets back to auth0.js is already stripped and that's why auth0.js expects the fragment to be just the oauth2 response attributes

**Comment by fredguth** [comment]
@hzalaz the problem is that auth0.js expects the fragment to be oauth2 response, while some JS frameworks use the fragment for routing.
 
I just wanted to add that I understand the importance of being OIDC compliant for Auth0, but the changes in v8 brought too much complexity for using it with SPAs.  We managed to make our app work with Auth0, but it took a lot of effort and if we knew it would be so in advance we would certainly look for another alternative.  

The only reason I am pointing this is because I like Auth0 and I hope it thrives.

**Comment by hzalaz** [comment]
@fredguth what I meant before is that we AFAIK don't do anything with it in auth0.js and that behavior predates v8. I understand that some JS fwk do some non friendly things but that is how OAuth2 should work https://tools.ietf.org/html/rfc6749#section-3.1.2

> The endpoint URI MUST NOT include a fragment component.

We are working on adding different `response_mode` for JS fwk that are not friendly with this format but now the only two solutions are using a different Url for the callback or stop using hash routing and use path/location instead.

The other pain point we know is the keeping the user logged in (previously refresh token) and we are working on improving that too (the solution will be somewhat related to adding a new `response_mode`).

**Comment by Sojer23** [comment]
@fredguth So late but...you can solve it inserting this piece of code in the app manager file (if you use AngularJS fwk).

`$locationProvider.html5Mode({
        enabled: true,
        requireBase: false
      });`

I am developing an application with AngularJS but without HTML5...so I require the field: 'requireBase:false', because I don't use <base> target.
