### ISSUE TITLE
how to fetch user metadata on login?

### ISSUE THREAD

**Issue by tgoldenberg** [auth0/auth0.js#364]
Before the latest version, I could request the user's profile with the metadata included. Now, it isn't included. I'm not sure what Auth0 is recommending to retrieve this information. My current user profile from `this.auth0.client.userInfo` looks like this:

<img width="746" alt="screen shot 2017-02-20 at 5 22 26 pm" src="https://cloud.githubusercontent.com/assets/10930134/23143783/3e189200-f791-11e6-8411-14f3fe653c7e.png">

Do I have to do a server-side call to fetch this data now? I saw the documentation on the `auth0.Management` module, but it was not at all clear to me what my "PRIMARY_IDENTITY_TOKEN"  is.... Appreciate any help!

**Comment by tgoldenberg** [comment]
When I try to call the `auth0.Management` method, I get an error, saying I have some wrong headers. I am using the JS framework [Next.js](https://github.com/zeit/next.js):

<img width="527" alt="screen shot 2017-02-20 at 5 36 02 pm" src="https://cloud.githubusercontent.com/assets/10930134/23144076/2648d71e-f793-11e6-94ad-23eac5750922.png">
<img width="382" alt="screen shot 2017-02-20 at 5 35 44 pm" src="https://cloud.githubusercontent.com/assets/10930134/23144078/28752d8a-f793-11e6-8f9c-5820f0bc5c0e.png">

**Comment by tgoldenberg** [comment]
@hzalaz I am still not clear on what the solution is. Could you please explain how I can retrieve the user_metadata with the user profile on `auth.client.userInfo`?

I would recommend not closing this, as the issue is still unresolved, and is significantly different from the issue referenced.

**Comment by chchmatt** [comment]
I agree with @tgoldenberg that is this is significantly different from issue #328 and this is unresolved.  I have discovered a workaround however (I'm using typescript):

            // Setup Auth0.
            this.auth0 = new auth0.WebAuth({
                audience: 'https://my-domain.com/userinfo`,
                clientID: 'my-client-id',
                domain:  'https://my-domain.com/',
                redirectUri: 'https://my-domain.com/callback',
                responseType: 'token',
                scope: 'openid email profile'
            });

The following does NOT work: 

    this.auth0.client.login({
        realm: 'my-connection',
        username: 'email@example.com',
        password: 'my-password',
        scope: 'openid email profile'
    },
    (error, authResult) => {
         // authResult only contains details for openid and email scope, but not profile scope.
    });

However auth0.redirect.signupAndLogin does work and includes the profile details, so my workaround it to call auth0.redirect.loginWithCredentials instead:

    this.auth0.redirect.loginWithCredentials({
        connection: 'my-connection',
        username: 'email@example.com',
        password: 'my-password',
        scope: 'openid email profile'
    },
    error => {
        // Only reaches here when there's an error.
        // A successful login will redirect using the callback url.
    });

Phew! Wasted a lot of time on this!

**Comment by SteveByerly** [comment]
I also spent a lot of time fighting this problem. I'm still using the `loginWithCredentials` until there's a better alternative. I wish this was documented better in the project.

**Comment by chchmatt** [comment]
@hzalaz is it possible to get this reopened and investigated please.

**Comment by hzalaz** [comment]
@chchmatt can you open a new one with your details ?

**Comment by tgoldenberg** [comment]
@hzalaz Why is this closed? My question was not addressed at all, and the issue that was referenced is about updating user metadata, not retrieving it on login. 

Closing issues that are unresolved does not make the repository seem more secure. I think it sends a red flag, IMHO.

**Comment by hzalaz** [comment]
@tgoldenberg the issue in https://github.com/auth0/auth0.js/issues/364#issuecomment-281198171 was fixed in our backend (allowing that header in CORS) and is the correct way to get the whole profile using OpenID connect flows. Calling `/userinfo` will only return the values defined in the OpenID connect spec.

**Comment by hzalaz** [comment]
Also we don't usually use github to answer questions since it will overwhelm the developers and we try to move people towards https://support.auth0.com so our support team can handle all auth0 related questions

**Comment by tgoldenberg** [comment]
FYI, what I am doing now is invoking `auth0.client.login`, which returns an idToken.

From here, I am making a request to `yourdomain.auth0.com/tokeninfo`. This gives me the whole profile.

If the original problem has been fixed, I like forward to simplifying this approach and retrieving the user data from one request. Would be great if others confirmed that this works too.

**Comment by tgoldenberg** [comment]
@hzalaz I think that is a mistake in Auth0's approach. Github issues allow other users to weigh in and provide helpful answers. My experience with Auth0 has been pretty horrible. I waited more than 1 month to get an answer back from them. 

The Github issues are actually helpful to the entire community, in resolving issues like this. I did reach out to customer support and the experience was not helpful. I suggest that you keep issues open until they are resolved and allow other developers to weigh in. This will only increase the benefit of using the product and will help build up a strong community of users. My two cents.

**Comment by tgoldenberg** [comment]
Also, if I reach out to customer support, my problem and the solution are not viewable to others. Having these issues documented for future users will make adoption much easier. From this issue, it's clear that others had the same problem and many probably benefitted from the discussion.

I understand that you have a community forum, so that is helpful, too. But I don't think the issue I raised was inappropriate for a Github issue.

**Comment by hzalaz** [comment]
Its our approach for now and we don't want too keep long discussions on how to implement things here and use the forum instead https://community.auth0.com which will me more broad than auth0.js users. Sorry to hear about support delays and its something we are working all the time to improve.

The initial question was appropriate its just we don't want to have discussions of how to use auth0 here. @tgoldenberg if you want can you post the question in the community forum and we can discuss there? (if you have one already the better)

And thanks for the notice about the CORS issue
