### ISSUE TITLE
.redirect.loginWithCredentials (deprecated) vs. .client.login

### ISSUE THREAD

**Issue by dennis82m** [auth0/auth0.js#371]
I can't find any information on the difference of both. I noticed that .redirect.loginWithCredentials is deprecated now and that auth0.login (? not existing) .client.login should be used instead. While the "Authorization" Extensionen worked well with .redirect.loginWithCredentials, the app_metadata is not updated any more when the user signs in using .client.login??!

Am I missing something?

**Comment by hzalaz** [comment]
@dennis82m you can still use that method the warning is more a suggestion than a proper deprecation warning since it does not state is already deprecated and might be better suited for your use case

**Comment by hzalaz** [comment]
Also we are going to reword those warnings since its misleading
