### ISSUE TITLE
Signup without redirect (and retrieve auth0 user_id)

### ISSUE THREAD

**Issue by tgoldenberg** [auth0/auth0.js#372]
I would like to create the auth0 user in the backend, without using the client. This seems to be totally doable, just by fooling around in the Node console. However, I get stuck about here:
```
var auth0 = require('auth0-js');

var webAuth = new auth0.WebAuth({
  clientID: 'CLIENT_ID',
  domain: 'DOMAIN',
  redirectUri: 'REDIRECT',
  responseType: 'token id_token',
});

var params = {
  connection: 'Username-Password-Authentication',
  responseType: 'token',
  email: 'SAMPLE_EMAIL@example.com',
  password: 'password'
};

webAuth.signupAndAuthorize(params, function(err) { console.log('ERR', err); });
```

Here, I get the 400 response and error description if the user is already created. But on success, I get nothing. All I need is the `user_id` for my process as a response. Is it possible for this method to return the created user? Thanks!

**Comment by hzalaz** [comment]
@tgoldenberg this library is intended to use in the browser and not in backend.
