### ISSUE TITLE
Custom Login Form

### ISSUE THREAD

**Issue by techpool** [auth0/auth0.js#374]
Currently there are a few ways to implement custom login for a user through auth0. What I need is have a completely custom look and feel instead of the styling of auth0. I really don't like the idea of overriding the CSS implemented by auth0 and hence I want to have my own form.

I tried using the method:

```
webAuth.redirect.loginWithCredentials({
  connection: 'Username-Password-Authentication',
  username: 'testuser',
  password: 'testpass',
  scope: 'openid'
});
```

but this gives deprecation warning and tells me to use `webAuth.authorize({})`. But the problem with the later is it opens up the hosted page where again I need to use the auth0 lock which is predesigned by the auth0.

The other idea of token does not suits well for me as I need to `code` response type to a standard backend callback url in order to implement the session data.

It would be really great if the feature persists in the future releases as well or there is a way to implement the same with `webAuth.authorize` method.

Currently using:
auth.js   --> 8.2.0
browser --> Google Chrome Version 56.0.2924.87 (64-bit)

**Comment by hzalaz** [comment]
You can customize the login page you see calling `webAuth.authorize({})` in [your dashboard](https://manage.auth0.com/#/login_page). 

Also the warning is just a warning to encourage usage of other endpoints but its still acceptable to use it, once its officially deprecated we'll provide a timeline for it.

**Comment by SteveByerly** [comment]
This isn't really a good answer. Auth0 directs users to use the custom login pages all over the documentation, but doesn't address the fact that several things break when you try to implement using the recommended login functions.

I'm still hoping that the auth0-js docs will address the different auth flows and how/why they differ in more detail.

**Comment by hzalaz** [comment]
@SteveByerly we are changing our recommendations and will update the docs soon to reflect the hosted login page (which can also be customized and there is no need to use Auth0 style at all). What is your specific issue?

**Comment by bragma** [comment]
As a side question, I am just starting to look into customized hosted login page because I really need the renewAuth feature. Does renewAuth require lock to work or it works independently of how the hosted login page is done? Ex: suppose I totally rewrite the login page to use a custom form + jquery or auth0.js, will this break the renewAuth or will it still work?
Thanks!

**Comment by hzalaz** [comment]
@bragma it relies on OAuth flows so its independent if the login page uses Lock, auth0.js or you call the endpoints yourself.

**Comment by bragma** [comment]
@hzalaz thanks for the quick answer. But just to be sure, it still requires to use the hosted page (however it's done) since it relies on cookies stored on auth0's server, right?

**Comment by hzalaz** [comment]
@bragma in a simplified way yes. As long you use the OAuth flow to authenticate (by calling /authorize)  renewAuth will work
