### ISSUE TITLE
Angular 2 Auth0.WebAuth is not a constructor

### ISSUE THREAD

**Issue by eluizbr** [auth0/auth0.js#375]
Auth0.js Version: http://cdn.auth0.com/js/auth0/8.3.0/auth0.min.js

HI,
I'm  try use de Auth0 with Angular 2, and i got some issues.

I try this:

`
    declare var Auth0: any;

@Injectable()
export class AuthService {
    auth0 = new Auth0.WebAuth({
        domain: 'mydomain.auth0.com',
        clientID: 'MYID',
        responseType: 'token',
        redirectUri: 'http://localhost:4200/'
    })

    googleLogin() {
        this.auth0.authorize({
            connection: 'google-oauth2'
        })

    }
}

`

With this setup above, i received this error:

EXCEPTION: Uncaught (in promise): TypeError: Auth0.WebAuth is not a constructor
TypeError: Auth0.WebAuth is not a constructor

What is wrong in my setup ?

I follow this guide : https://auth0.com/docs/libraries/auth0js

Thanks

**Comment by hzalaz** [comment]
@eluizbr any more info like snippet of code, version, etc? It's probably related on how you require it specially since you are using typescript

**Comment by eluizbr** [comment]
@hzalaz  Thanks...
Auth0.js Version: http://cdn.auth0.com/js/auth0/8.3.0/auth0.min.js
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

**Comment by hzalaz** [comment]
and your code where you import lock? Have you checked our quickstarts?

**Comment by eluizbr** [comment]
This is my auth service....
In my loginComponet, i call  googleLogin()
`
import { Injectable } from '@angular/core';
import { tokenNotExpired } from 'angular2-jwt';

declare var Auth0Lock: any;
declare var Auth0: any;

@Injectable()
export class AuthService {

    auth0 = new Auth0.WebAuth({
        domain: ,
        clientID: ',
        responseType: 'token id_token',
        redirectUri: 'http://localhost:4200/'
    })

    constructor() {}

    login() { }

    googleLogin() {
        this.auth0.popup.authorize({
            connection: 'google-oauth2'
        }, function() {
            console.log('log...')
        })


    }

    authenticated() {
        /**
         * Checa se o token não esta expirado;
         * Este função utiliza o token armazenado no localStorage "id_token"
         */
        return tokenNotExpired();
    }

    logout() {
        // Remove todos os dados do localStorage, forçando assim o logout da aplicação
        localStorage.clear();
    }
}

`

**Comment by luisrudge** [comment]
Try `auth0` instead of `Auth0`

**Comment by eluizbr** [comment]
@luisrudge Thanks... Solved my problem...

Thanks

**Comment by luisrudge** [comment]
No problem! Glad you got it working!

**Comment by harinathebc** [comment]
I got same problem as above.

Im using auth0 only not Auth0.

Please let me how this problem is solved. Right now im using 8.7 version.

**Comment by luisrudge** [comment]
@harinathebc are you importing via npm or cdn? can you share a code snippet?

**Comment by harinathebc** [comment]
Imported using CDN.

<label>Email</label><input type="text" id="email"><br>
<label>Password</label><input type="password" id="password"><br>
<button class="signin-db">Sign in with Email/Password</button>

<script src="https://cdn.auth0.com/js/auth0/8.7/auth0.min.js"></script>
<script src="http://code.jquery.com/jquery.js"></script>
<script type="application/javascript">
  var webAuth = new auth0.webAuth({
    domain:         'tavvaforu.auth0.com',
    clientID:       'QizVo__bAaFOjjT9HlCXL4UXAXL0Fq5G',
    redirectUri:    'http://localhost/vmanage-module/auth/callback'
  });
  // sign-in with social provider with plain redirect
  $('.signin-google').on('click', function() {
    webAuth.authorize({
      connection: 'google-oauth2' // use connection identifier
    });
  });
  // sign-in with social provider using a popup (window.open)
  $('.signin-google-popup').on('click', function() {
    webAuth.popup.authorize({
      connection: 'google-oauth2'
    });
  });

  $('.signin-db').on('click', function() {
	  alert('asdfasdf');
    webAuth.redirect.loginWithCredentials({
      connection: 'Username-Password-Authentication',
      username: 'testuser',
      password: 'testpass',
      scope: 'openid'
    });
  });
  // Parse the authentication result
  webAuth.parseHash((err, authResult) => {
    if (authResult) {
      // Save the tokens from the authResult in local storage or a cookie
      localStorage.setItem('access_token', authResult.accessToken);
      localStorage.setItem('id_token', authResult.idToken);
    } else if (err) {
      // Handle errors
      console.log(err);
    }
  });
</script>

**Comment by luisrudge** [comment]
You're using `auth0.webAuth`. It's `auth0.WebAuth`.

**Comment by harinathebc** [comment]
Thank you!!! have a great help i strugged for almost 2 hrs. Saved my time and life!!!

**Comment by harinathebc** [comment]
I just copied from auth0 site only.again this error.

Error: responseType option is required

Im new to auth0 Can you please share any snippet if you have so that it will be helpful.

**Comment by luisrudge** [comment]
Please follow our quickstarts. They're complete and working: https://auth0.com/docs/quickstarts
If you have any questions, reach out to our amazing support team at https://support.auth0.com/

**Comment by harinathebc** [comment]
Sure. Hope i also followed same. there itself its showing like above.

Let me try this in my local uysing repo https://github.com/auth0-samples/auth0-php-web-app/tree/master/00-Starter-Seed/basic-webapp

![auth0_issue](https://user-images.githubusercontent.com/25786958/27167914-eb7cfe84-51c0-11e7-8b83-425622e82ec6.png)

**Comment by harinathebc** [comment]
Can you please provide repo url which is having custom signin and sigout!!! 

I tried this its working as expected. But i want custom sign which doesn't need registration.

Also we need user to be registered using auth0 Register API when calling my php code.

**Comment by luisrudge** [comment]
Please contact our amazing support team at https://support.auth0.com/

**Comment by nicholasruunu** [comment]
Had the same problem following the Quickstart example for Symfony (PHP).
Really frustrating... thanks @luisrudge.

**Comment by luisrudge** [comment]
Can you point me to the quickstart?

**Comment by nicholasruunu** [comment]
@luisrudge Click on a client in the client list, quick start tab, scroll to bottom and click custom ui tab. Can't link to the site properly since it's a SPA.

**Comment by luisrudge** [comment]
Thanks! I just notified our docs team and they'll submit a fix shortly. Sorry for the confusion 🎉
