### ISSUE TITLE
Get user Info and token

### ISSUE THREAD

**Issue by eluizbr** [auth0/auth0.js#376]
I try get user info and token from authorize method.

I try this:

```
        this.auth0.authorize({
            connection: 'google-oauth2'
        }, (err, result) => {
            console.log(err, result)
        });
```

I not received any results.
What de correct way to can get user info and token?

I use:
Angular 2.4.9
node: 6.9.4
os: darwin x64
Auh0.js 8.3.0

Thanks

**Comment by eluizbr** [comment]
Solved!

**Comment by gregor-srdic** [comment]
How?

**Comment by eluizbr** [comment]
I used this: 
https://auth0.com/docs/libraries/auth0js/v8#extract-the-authresult-and-get-user-info
