### ISSUE TITLE
Only user_metadata can be updated using auth0.js

### ISSUE THREAD

**Issue by hosuaby** [auth0/auth0.js#389]
Method Management#patchUserMetadata allows only update of user_metadata field in user profile, but not attributes in root level of user profile or app_metadata. There is any particular reason why method that can patch all of them was not implemented?

**Comment by luisrudge** [comment]
app_metadata is meant to updated by an authenticated client, not by the user. All the backend SDK's have the ability to update the app_metadata property.

**Comment by pal** [comment]
What backend SDK would that be @luisrudge? If I need to update app_metadata from my JS client, do I need to construct this call myself, or is there another SDK available? 

Found only these: https://auth0.com/docs/libraries#auth0-sdks

**Comment by luisrudge** [comment]
.net, nodejs, etc. we have sdks for a bunch of languages.
