### ISSUE TITLE
Why delegate token was removed from v8 ?

### ISSUE THREAD

**Issue by hosuaby** [auth0/auth0.js#390]
I am interested to make a Single Page Application using Angular that can save files into AWS S3. I found a great example: https://github.com/auth0-samples/auth0-s3-sample.
But I discovered that last commit was made in 2015 and method auth0#getDelegationToken was removed from auth0.js v8. Delegate endpoint still available on Auth0 API. There's any security reasons or other to remove ability to get delegate token?

**Comment by jkucharski** [comment]
Also looking for delegation token to be returned. Moving to angular2 with newer auth0/lock, but still need to call secured aws apigateway services. Is there a replacement flow?

**Comment by gnanda17** [comment]
hey i had the same frustration looking at the existing examples. This is what worked for may not sure if it might help you.  There is a delegate method which I used to obtain aws credentials for my app. 
You can see this method on  line 401  of https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js
``` js
var auth0 = new Auth0.Authentication({
      domain: 'yourdomain.com',
      clientID: 'yourclientid'
    });
 const options = {
      clientID: 'yourclientid',
      id_token, // you get this from the lock on successful authentication
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer'
    };
auth0.delegation(options, (err, res) => {
      if (!err) {
        this.awsCredentials = res.Credentials;
      }
      console.log('error', err);
```
I had to set the aws configuration via an auth0 rule and then was able to get aws credentials when calling the delegation method. I am sure the rule might need further tweaking but this is at least a base case that works.
```js
function (user, context, callback) {
    // set AWS settings
    if (context.clientID === 'yourclientid') {
    context.addonConfiguration = context.addonConfiguration || {};
    context.addonConfiguration.aws = context.addonConfiguration.aws || {};
    context.addonConfiguration.aws.principal = 'yourawsprincipal';
    context.addonConfiguration.aws.role = 'yourrolearn';
    callback(null, user, context);
    } else callback('unauthorized');
}
```

**Comment by hzalaz** [comment]
@gnanda17 I'd recommend you contact us via https://support.auth0.com to get help on using Auth0 Delegation, but the principal and role can be sent from the options in the `delegation` method call.

On the topic of this issue, delegation can be called as stated in @gnanda17 comment (pointing the method in v8) also the migration guide has a section https://auth0.com/docs/libraries/auth0js/v8/migration-guide#delegation. 

We are working on improving the delegation feature in Auth0 (which will include improving the docs) but everything still works (if there are bugs please report them so we can fix them or submit a PR and it will be merged).

**Comment by jkucharski** [comment]
The auth0 rule certainly works, but as an alternative, I ended up
abandoning the delegation step altogether in favor of a "custom authorizer"
on the aws API Gateway side. This does not help if you're trying to access
a different AWS service, but if you are simply trying to call AWS API
Gateway service endpoints, this is a much cleaner approach:

1) Authenticate through auth0 and include some type of role attribute in
your scope so it is encoded within your id_token.
2) Make calls to your API Gateway service passing the id_token in your
Authorization header. (Authorization: bearer [id_token])
3) Configure a custom authorizer in AWS API Gateway ( simple lambda
function ) to verify the token passed in the authorization header.
Configure your api gateway methods to use your custom authorizer (in lieu
of AWS_IAM).
4) Use the decoded role attribute to determine the IAM Policy that the
authorizer returns. Use the policy to define access to your web service
endpoints.

I prefer this approach as it puts role-based access control within a single
lambda function (your custom authorizer). To simplify returning a policy
from your authorizer, have your lambda function retrieve an existing custom
policy using the iam javascript sdk. If you want to use other attributes
from your id_token within your lambda functions, in your body mapping
template include something like:

{
    "principal": {
        #foreach($authorizerKey in $context.authorizer.keySet())
        "$authorizerKey" :
"$util.escapeJavaScript($context.authorizer.get($authorizerKey))"
        #if($foreach.hasNext),#end
        #end
    }
}

These are made available in the $context.authorizer by including them along
with the policy. See
http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html

**Comment by canada11** [comment]
@gnanda17 Is that project available to see publicly? I tried to use what you posted (after fixing a missing curly brace and parenthesis) but I don't know what to import/where to import to get that to work. I'm new to Angular but I have a decent grasp on it. I'd like to use this delegation but I guess I'm having trouble importing the auth0-js sdk into my Angular app. I can't find anything that can explain it clearly to me. Could you link to that project?

@hzalaz How much longer till the docs get updated?

**Comment by lumberj** [comment]
Why was this issue closed? There's only incomplete documentation in the migration guide.

**Comment by jleppert** [comment]
For a company whose only product is providing developer APIs, Auth0 certainly does a terrible job. When is it ever acceptable to deprecate features and break end user applications on a whim because someone decided something is not "best practices" (whatever that means)?

This will be the last time I use or implement Auth0 and I will not be recommending it any longer. Ya'll have ruined my week. What should have been a simple affair and implementation has been fraught with problems. Your own API clients, documentation, web site, console, etc. are all out of sync with one another leaving me to try random things to get stuff to work. This poor developer experience does not inspire much future confidence in your product.

Implementing authentication shouldn't involve reading 12 different KB articles and random forum posts strewn throughout the Internet and mysterious toggles hidden under advanced panels in your dashboard. What we have here, public/private key crypto, at its core, is not complicated. You've made it complicated, confusing, contradictory, and a poor UX.

I hope this message reaches someone at Auth0 who has the sense to fix these things. Every time I have to Google how to use your product I get closer to just ripping it all out.

**Comment by luisrudge** [comment]
@lumberj what steps are missing in the migration guide?

**Comment by luisrudge** [comment]
@jleppert thanks for the honest feedback. Having first class support material for developers is our main goal. Our customers are developers, so we take documentation, quick starts and SDKs very seriously. With that being said, there are **definitely** gaps that we absolutely need to fill. If you're cool with it, I'd like to understand what are you trying to achieve and where did the docs failed you.

Is the only problem you're having with delegation? Are you having any other issues finding docs to get something else done?

**Comment by luisrudge** [comment]
About the delegation discussion: I'm gathering information on how to move forward with this. I'm not saying we'll add the method back (we probably won't), but I'm pushing to have a clear path for anyone migrating from v7 and also new users.

What I do know right now: If you absolutely need to use this feature, keep using v7 or call the `/delegation` endpoint directly. There's more details here: https://community.auth0.com/answers/6310/view. I understand this is not the answer you all are looking for, but it is what we have today.

I'll update this issue whenever I have more information about this.

Thank you all for the patience.

**Comment by luisrudge** [comment]
Hi folks. After some internal testing, this is the latest recommendation:

For customers already using delegation with auth0.js@v7, you can just upgrade to the latest version following the [migration guide](https://auth0.com/docs/libraries/auth0js/v8/migration-guide#delegation). It will work just fine.

For new customers, you have to ping our amazing support team at https://support.auth0.com - they will help you figure it out your scenario and, if needed, can enable the legacy delegation flows.

We do have something in the works for Q1 2018 (estimate), you can read more here: https://auth0.com/docs/migrations#introducing-api-authorization-with-third-party-vendor-apis

Thank you all for your patience ❤️

**Comment by gdjennings** [comment]
For those seeking a solution, I have added a small serverless project that creates an API GW endpoint for securely performing sts:AssumeRole along the lines of @jkucharski mentioned.
https://github.com/gdjennings/auth0-aws

It's still pretty crude and basic but is working for new Auth0 clients without working delegation endpoints. It suits my need since I currently only have 1 role to assume. A little work to be done to make more flexible.

**Comment by klintan** [comment]
@gdjennings thanks ! After all I've read it seems that is the "new" (and only)  way to do it ?  creating a lambda helper function for getting AWS credentials. 
I was hoping to not create a Lambda function but keeping it all client-side (which seemed to be the old/legacy way to do it, as described here https://github.com/auth0-samples/auth0-s3-sample, and also the new delegation method in more recent versions of Auth0 js libs). 
Could someone clarify this is the way it will be done going forward (aka we need to always create a lambda to get AWS SAML credentials etc) ?
