### ISSUE TITLE
Scope does not have an effect on client.login

### ISSUE THREAD

**Issue by anho** [auth0/auth0.js#391]
Hi,

when specifying a specific scope in ``client.login`` (lets assume its ``openid foo``) the library/backend always reports back a scope of ``openid profile email address phone`` and does NOT contain anything I am requesting for. Its probably not the intended way, isn't it?

I'm currently working with version 8.4.

**Comment by luisrudge** [comment]
Can you provide the options you're using to create the auth0 object and to call the login method?

**Comment by kristinn93** [comment]
I'm having the same problem, I have tried many variations of the following.
```javascript
const authClient = new auth0.WebAuth({
  clientID: 'xxxxxxxxx',
  domain: 'xxxxx.auth0.com',
  responseType: 'token',
  scope: 'openid app_metadata user_id',
});

authClient.client.login(
  {
    realm: 'Username-Password-Authentication',
    username: USERNAME,
    password: PASSWORD,
  }, (err, authResult) => {
    console.log(authResult);
} );
```
No matter what I put in scope I always get an response that contains :
```
scope: 'openid profile email address phone'
```

How do I get the user_id ?
Any help appreciate

**Comment by luisrudge** [comment]
Can you try adding the scope to the login call to see if that works?

**Comment by kristinn93** [comment]
```javascript
const authClient = new auth0.WebAuth({
  clientID: 'xxxxxxxxx',
  domain: 'xxxxx.auth0.com',
  responseType: 'token',
  scope: 'openid app_metadata user_id',
});

authClient.client.login(
  {
    realm: 'Username-Password-Authentication',
    username: USERNAME,
    password: PASSWORD,
    scope: 'openid app_metadata user_id',
  }, (err, authResult) => {
    console.log(authResult);
} );
```

This had no effect @luisrudge

**Comment by luisrudge** [comment]
Alright. I'll check this out

**Comment by hzalaz** [comment]
@kristinn93 you should get the user id in the id_token `sub` claim, so if you decode it you can get it, but you won't get the metadata sadly. The reason for that is that call follows OIDC spec and neither app_metadata nor user_id are valid scopes for that and thats why the response contains only those scopes listed (`openid profile email address phone`).

You have two alternatives, use this method instead http://auth0.github.io/auth0.js/docs/auth0-js/8.4.0/global.html#loginWithResourceOwner that will return the id_token as you wanted or write a custom rule to modify the id_token and inject custom claims with the info you need.

If you need help writing the rule please contact us via https://support.auth0.com

**Comment by kristinn93** [comment]
Thanks for the helpful response @hzalaz

**Comment by kristinn93** [comment]
Follow up: loginWithResourceOwner returns user_id, which is what I was looking for

**Comment by webberig** [comment]
@hzalaz Your link is throwing a 404 error...
In fact, I can't seem to find any reference to the "loginWithResourceOwner" method in the documentation. I did find the info I needed in the source code. 

Do you intend to deprecate this function ? Because I'll be using this to migrate from v7 to v8 SDK...

**Comment by Anees-Raja** [comment]
I can't get the profile information either. And I couldn't find or open a newer issue similar to what i'm experiencing. 

`auth0 = new auth0.WebAuth({
  domain: xxxx.auth0.com,
  clientID: xxxxxxxxxx,
  redirectUri: 'http://localhost:3000/dashboard',
  audience: xxxxxxxxxx,
  responseType: 'token id_token',
  scope: 'openid profile'
})`

**Comment by luisrudge** [comment]
@Anees-Raja what method are you calling? `client.login`? If that's the case, please use just `login`:

```
var webAuth = new auth0.WebAuth({
  domain: xxxx.auth0.com,
  clientID: xxxxxxxxxx,
  redirectUri: "http://localhost:3000/dashboard",
  audience: xxxxxxxxxx,
  responseType: "token id_token",
  scope: "openid profile"
});
webAuth.login({ username: "example@example.com", password: "p4$$w0rd" });

```

**Comment by Anees-Raja** [comment]
@luisrudge will the login function do 0auth with google and stuff? I was trying to use the universal login method which uses authorize()

`
  constructor() {
    this.login = this.login.bind(this);
    this.logout = this.logout.bind(this);
    this.handleAuthentication = this.handleAuthentication.bind(this);
    this.isAuthenticated = this.isAuthenticated.bind(this);
  }
  
  login() {
    this.auth0.authorize();
  }

  handleAuthentication() {
    this.auth0.parseHash((err, authResult) => {
      if(authResult && authResult.accessToken && authResult.idToken) {
        let expiresAt = JSON.stringify((authResult.expiresIn) * 1000 + new Date().getTime())
        this.setSession(authResult, expiresAt)
        location.hash = ''
      } else if (err) {
        location.pathname = '/login/'
        console.log(err)
      }
    })
  }

  setSession(authResult, expiresAt) {
    localStorage.setItem('access_token', authResult.accessToken)
    localStorage.setItem('id_token', authResult.idToken)
    localStorage.setItem('expires_at', expiresAt)
    location.pathname = '/dashboard/'
  }

  isAuthenticated() {
    let expiresAt = JSON.parse(localStorage.getItem('expires_at'))
    return new Date().getTime() < expiresAt;
  }

  logout() {
    localStorage.removeItem('access_token')
    localStorage.removeItem('id_token')
    localStorage.removeItem('expires_at')
    location.pathname = '/login/'
  }

  getUserInfo() {
    if(localStorage.getItem('id_token')) {
      return jwtDecode(localStorage.getItem('id_token')) // returns nothing about user profile
    } else {
      return {}
    }
  }
`

**Comment by luisrudge** [comment]
No, for that you should use `authorize`
