### ISSUE TITLE
renewAuth example not working

### ISSUE THREAD

**Issue by saggiyogesh** [auth0/auth0.js#392]
auth0 version: 8.4.0

Getting 403 forbidden error while checking `renewAuth` example. 
However, related tests are passing. 

![image](https://cloud.githubusercontent.com/assets/551509/24031567/4a561c8c-0b09-11e7-9514-caddfaa24bb2.png)

**Comment by luisrudge** [comment]
@saggiyogesh did you try adding your client's domain and ID?

**Comment by saggiyogesh** [comment]
Hi, 
Changed the domain & id. Now getting this error

![image](https://cloud.githubusercontent.com/assets/551509/24056514/0f7a4adc-0b6a-11e7-8a2a-32a6ff34281b.png)

**Comment by hzalaz** [comment]
Yes and that's a valid case since depending on your settings or how much time has passed after the original auth or what scopes you are requesting might need to re-login or provide consent and auth0 will return that error. When that happens your app should just show the login page.
