### ISSUE TITLE
`renewAuth` does not respect 'SSO Cookie Timeout'

### ISSUE THREAD

**Issue by aaaa0441** [auth0/auth0.js#394]
Hello,

I'm working on an Angular SPA & using `renewAuth` methods (as documented on https://github.com/auth0/auth0.js#api) for the purpose of (A) silently renewing access token & (B) checking SSO status.

I set up the 'SSO Cookie Timeout' to '1 minute' for easier testing (as shown below).
![sso-cookie-timeout-1-minute](https://cloud.githubusercontent.com/assets/747071/24090097/56a68136-0d91-11e7-98e5-34a8eeb1be22.png)

(A) is working as expected, returning new token with refreshed token expiry time in  `authResult.idTokenPayload.exp`;
However, for the purpose of (B) checking SSO status, the response is always positive with a new authResult object returned (even when the request is sent more than '1 minute' after the previous call).

Is this expected behaviour? Or did I call the method incorrectly?

The code snippet is here:
```
    function getRenewAuthPromise() {
      var deferredRenewAuthResult = $q.defer(),
          renewAuthOptions = {
            scope: 'openid',
            redirectUri: silentAuthRedirectUri,
            usePostMessage: true
          };

      function renewAuthHandler(err, authResult) {
        if (err) {
          deferredRenewAuthResult.reject(err);
          return;
        }
        if (authResult) {
          deferredRenewAuthResult.resolve(authResult);
          return;
        }
        throw new Error('Not handled');
      }

      angularAuth0.renewAuth(renewAuthOptions, renewAuthHandler);

      return deferredRenewAuthResult.promise;
    }
```

Libraries (& their versions) used in the SPA:
* "angularjs" "1.6.1"
* "angular-auth0" "2.0.0-beta.1"
* "angular-jwt" "0.1.9"
* "angular-lock" "2.0.0-beta.1"
* "angular-ui-router" "1.0.0-rc.1"
* "auth0.js" "8.4.0"
* "auth0-lock" "10.13.0"

Thanks

Yours Sincerely
Martin

**Comment by aaaa0441** [comment]
Thanks to João's help on https://auth0.com/forum/t/renewauth-does-not-respect-sso-cookie-timeout/5673/10, I consider this issue to be invalid and the `renewAuth` method to be working as expected.

Do take note that changes to the 'SSO Cookie Timeout' setting is only effective for new SSO sessions created after the change. Regarding existing sessions, while I did not confirm, they probably contain timeout of the previous setting when they were created. So while testing, do use Incognito mode as suggested by João! 👍

**Comment by luisrudge** [comment]
Thanks for the feedback @aaaa0441! 🎉
