### ISSUE TITLE
Why does parseHash require a clientID & domain?

### ISSUE THREAD

**Issue by aaaa0441** [auth0/auth0.js#396]
As part of the silent-authentication iframed page code, i have the following:

```
var location = window.location,
    webAuth = new auth0.WebAuth({
      // At least with Auth0's current setup, these two keys does not need to contain actual value but instead
      // just need to be assigned for below `parseHash` call to work here
      clientID: '',
      domain: ''
    });

webAuth.parseHash(window.location.hash, function(err, result) {
  parent.postMessage(err || result, [location.protocol, location.host].join('//'));
});
```

`parseHash` method is apparently not using the values from `clientID` or `domain`. However, if not provided, there would be errors.

The same issue was brought up before, in https://github.com/auth0/lock/issues/446 as a 'lock' issue.

**Comment by hzalaz** [comment]
`parseHash` needs the clientId/domain to validate the id_token, but it obtains the values from when you create WebAuth which are mandatory parameters.

**Comment by aaaa0441** [comment]
@hzalaz it apparently only needs clientID, domain to be empty string, or any other value to 'validate the id_token'; which means the actual value of clientID & domain are not actually used.

What I am saying is, since this specific method `parseHash` does not actually use these values for anything, why not make this method a 'static' method instead of an instance method?
