### ISSUE TITLE
Nonce does not match for renewAuth

### ISSUE THREAD

**Issue by thoean** [auth0/auth0.js#400]
I'm trying to renew the id_token in the background.

When debugging, the callback correctly returns the id_token, but it fails to validate it due to a mismatch in the nonce. I believe the reason is that the [`iframe-handler` does not set the `nonce` in the options](https://github.com/auth0/auth0.js/blob/b6f1c57098021a54e5a68ecc01c1fbaf88d4fa75/src/helper/iframe-handler.js#L56), and therefore is null.

This is the code in my application:

```javascript
      let webAuth = new auth0.WebAuth({
        domain: domain,
        clientID: clientId,
        responseType: 'id_token token',
        scope: 'openid profile'
      });
      let renewOptions = {
        redirectUri: `${window.location.origin}/silent-callback.html`,
        usePostMessage: false, // --> I have to use false here since setting it to true returns the main window object in the authResult; I didn't debug this further and hoped to get it working with setting this to false
        nonce: 'Aco4IjEXm4hRPLc.MvOlApylOxJOQeHa'
      };
      webAuth.renewAuth(renewOptions, function(err, authResult) {
        console.log(err); // --> this is set to: {error: "invalid_token", errorDescription: "Nonce does not match."}
        console.log(authResult); // --> this is null
      });
```

**Comment by lina128** [comment]
I have the same issue. Have you found a solution?

**Comment by thoean** [comment]
@lina128 , I had to change to popup mode so I didn't investigate too much. The callback URL is too restrictive for my needs. I see there's an open pull request, so it looks promising to have a solution soon.
