### ISSUE TITLE
responseType code not return code

### ISSUE THREAD

**Issue by uhe1896** [auth0/auth0.js#404]
<script type="text/javascript" src="https://cdn.auth0.com/js/auth0/8.4/auth0.min.js"></script><br/>
<script><br/>
auth = new auth0.WebAuth({<br/>
domain: 'mydomain.auth0.com',<br/>
clientID: 'myclientID',<br/>
redirectUri: window.location.href,<br/>
responseType: 'code'<br/>
});<br/>
<br/>
auth.client.login({<br/>
realm: 'myDB',<br/>
username: 'user',<br/>
password: 'passwd',<br/>
}, (err, res) => {<br/>
console.log(err);<br/>
console.log(res);<br/>
});<br/>
</script><br/>
<br/>
the code pasted always returns object like:<br/>
{<br/>
accessToken: 'token string'<br/>
expiresIn: 86400<br/>
idToken: "id token string"<br/>
scope: "openid profile email address phone"<br/>
tokenType: "Bearer"<br/>
}<br/>
<br/>
why no code returned here? any thing am I doing wrong?<br/>

**Comment by luisrudge** [comment]
Ops, never mind my previous comment. 

The `client.login` method will call the `/oauth/token` endpoint, which only returns tokens 🎉 

If you want to get a code, you have to call `redirect.loginWithCredentials`, like this:

```html
<!DOCTYPE html>
<html>

<head>
  <script type="text/javascript" src="https://cdn.auth0.com/js/auth0/8.4/auth0.min.js"></script>
</head>

<body>
  <script>
    auth = new auth0.WebAuth({
      domain: 'mydomain.auth0.com',
      clientID: 'myclientID',
      redirectUri: window.location.href,
      responseType: 'code'
    });
    var code = window.location.search.replace('?code=', '');
    if (!code) {
      auth.redirect.loginWithCredentials({
        connection: 'myDB',
        username: 'user',
        password: 'passwd'
      });
    } else {
      console.log('code: ' + code);
    }
  </script>
</body>

</html>
```

Keep in mind that this code can only be used to get user information via the `client.userInfo(code)` method. If you want to ask for an audience or get a consent prompt, you have to use the Hosted Login Page, via the  `auth.authorize()` method.

**Comment by uhe1896** [comment]
thanks @luisrudge
