### ISSUE TITLE
auth0-js does not work with browserify

### ISSUE THREAD

**Issue by bjabes** [auth0/auth0.js#405]
I'm able to pull in Auth0Lock in Typescript/Angular2 using a simple:
 `import Auth0Lock from 'auth0-lock';`

However the same approach simply does not seem to work for:
`import auth0 from 'auth0-js';`

I'd really rather not use a separate approach (e.g. CDN) to bundle the auth0.min.js file. Any help?

**Comment by luisrudge** [comment]
What error do you get? It should work just fine.

**Comment by bjabes** [comment]
after the import, when loading the page, it dies on
`var webAuth = new auth0.WebAuth({ ...` 
saying auth0 is undefined.

**Comment by bjabes** [comment]
I was able to get this working by changing the import to
`import { WebAuth } from 'auth0-js';
...
var webAuth = new WebAuth({ ...`

**Comment by luisrudge** [comment]
Yep.. there's no docs for browserify/webpack yet. :(

`import * as auth0 from 'auth0-js';` works as well.
