### ISSUE TITLE
WebAuth transaction-manager.js: appState or appStatus?

### ISSUE THREAD

**Issue by bragma** [auth0/auth0.js#412]
I am not totally sure, but I think there is some misnaming of the "appState/appStatus" parameter between parts of the code expecting a transaction to contain an "appStatus" property (ex: https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L134), but when a transaction is generated the same parameter is called "appState", as an example here: https://github.com/auth0/auth0.js/blob/master/src/web-auth/transaction-manager.js#L40, where it is set in the object, but also here https://github.com/auth0/auth0.js/blob/master/src/web-auth/transaction-manager.js#L23 where the transaction options are processed.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/auth0.js/pull/539/commits/75c32a33a2b83299e79419e947ef7f9ae5daa15c
