### ISSUE TITLE
embedded style with button that just redirects

### ISSUE THREAD

**Issue by chrisschaub** [auth0/auth0.js#414]
I am trying to find a way with auth0.js to implement a button or login link link that just redirects for a SAML enterprise connection -- all info is entered at idp. I can do this with "lock" by using the embedded style form. But with auth0.js, there doesn't seem to be a way to create a button that just redirects the the idp without the interim popup step. Is there a way to have a button that once clicked just redirects for a saml connection?

**Comment by chrisschaub** [comment]
bump

**Comment by luisrudge** [comment]
auth0.js will not have html elements. You can create the button the way you want and call whatever method you want inside auth0.js. If your question is how to redirect to a saml connection, please get in touch at https://support.auth0.com.
Thanks!

**Comment by chrisschaub** [comment]
It's not about how to redirect to saml, it's about avoiding the popup before redirecting. I don't see an option to do this in auth0.js, lock can do this with embed.

**Comment by luisrudge** [comment]
Can you share a working Lock configuration for this? I can help you find out how lock does this

**Comment by hzalaz** [comment]
@chrisschaub just call authorize method and add the parameter `connection` with the name of the SAML connection you wish to use

**Comment by chrisschaub** [comment]
Will that prevent a modal popup and just redirect to SAML idp?

**Comment by hzalaz** [comment]
Its what it does https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L344
