### ISSUE TITLE
V8.6 uncaught type error

### ISSUE THREAD

**Issue by johnlim** [auth0/auth0.js#417]
Upgrading from V8.5 to V8.6 produces the following error which wasn't present previously:
```
Uncaught TypeError: Cannot read property 'replace' of null
    at n.parseHash (auth0.js:3)
    at n.callback (auth0.js:3)
    at n.callbackHandler (auth0.js:3)
    at n.messageEventListener (auth0.js:3)
    at usePostMessage.transientMessageEventListener (auth0.js:3)
```

**Comment by luisrudge** [comment]
when that happens?

**Comment by johnlim** [comment]
@luisrudge Sorry for the tardy reply. It happens inside the call to `renewAuth`. Also, it happens when one uses the `angular-auth` library. Hope that clarifies.

**Comment by foray1010** [comment]
it happens to me too when I try to call `renewAuth` directly from `auth0.js`
this error come from https://github.com/auth0/auth0.js/blob/0eb4ca3edd2a240f4dfa36ebd6a57d25ad70ca0a/src/web-auth/index.js#L110
and it doesn't exist in `8.5.0`
