### ISSUE TITLE
Access_token in SPA auth0

### ISSUE THREAD

**Issue by anitchanana** [auth0/auth0.js#418]
hi 
i have created a SPI that logs in using auth0 and auth0 returns id and access token.
There is also an API configured as client of auth0.
There are couple of things
1. Access_token is very small in length and API does not validates this.
2. I need to access an API using this token.

So my question is why access token is so small and how will the API verify this token.

My client side is

  var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
      auth: {
          response_type: 'id_token token',
        params: { scope: 'openid email' } 
    }
  });

and API side is

 var options = new JwtBearerOptions
            {
                Audience = Configuration["Auth0:ApiIdentifier"],
                Authority = url 
             
            };
            app.UseJwtBearerAuthentication(options);

What i am doing wrong here ?

**Comment by SteveByerly** [comment]
Also seeing this same issue. I get an access token back, but it's only 10-ish characters long. Would like to try to use this token to call a backend API.

**Comment by hzalaz** [comment]
```
var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
auth: {
response_type: 'id_token token',
params: { scope: 'openid email' }
}
})l
```

performs only authentication and only returns a token usable for auth0 api. If you need to ask for a token for one of your APIs added to the dashboard you need to pass an audience.

**Comment by anitchanana** [comment]
Thanks @hzalaz 
I added audience and now token is validated by API
