### ISSUE TITLE
google-oauth2 missing idToken

### ISSUE THREAD

**Issue by gregor-srdic** [auth0/auth0.js#427]
Thank you for using Auth0.js! Please read the following before creating a new issue.
I am using auth0.js v8.6 and testing in Google Chrome. If I login with username and password ('Username-Password-Authentication') I get all the required tokens in response. But when I try to login with Google, I only get the access token in redirect URL, what am I doing wrong :S Docs are really vague about this.
This is how I invoke the popup:
```
        webAuth.popup.authorize(
          {
            connection: 'google-oauth2',
            scope: 'openid offline_access name email roles identities',
            audience: ' ... my api URL ... ',
            responseType: 'token',
            redirectUri: 'http://localhost:8100/token.html'
          },
          function (err, data) {
            ...
          }
        );
```
And this is the redirect page, that sends the received token from the popup back to the main page:
````
  var auth0 = new auth0.WebAuth({
        domain: '...',
        redirectUri: '...',
        clientID: '...',
        responseType: 'token'
      });
      var result = auth0.parseHash(window.location.hash, function(err, data) {        
        opener.postMessage(err || JSON.stringify(data), "*");
        window.close();
      });
```

Any help really appriciated.

**Comment by hzalaz** [comment]
Your main issue is that the responseType is `token` so that will only yield an access_token, if you need and id_token you should request it by adding it to the response type.

However If you supply an `audience` you should not use popup, so your choices are to drop either popup or audience since the popup flow is not compatible yet with OAuth 2 flow.
