### ISSUE TITLE
Nonce does not match

### ISSUE THREAD

**Issue by rochdev** [auth0/auth0.js#429]
I am getting an `invalid_token: Nonce does not match.` error from auth0.js when using the official example from [here](https://auth0.com/docs/libraries/auth0js/v8)

The script:

```js
webAuth.renewAuth({
  scope: 'openid',
  redirectUri: 'http://localhost:3000/silent-callback.html'
}
```

The silent callback:

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.auth0.com/js/auth0/8.6.1/auth0.min.js"></script>
    <script type="text/javascript">
      var webAuth = new auth0.WebAuth({
        domain: '****',
        clientID: '****'
      });
      var result = webAuth.parseHash(window.location.hash, function(err, data) {
        parent.postMessage(err || data, "http://localhost:3000");
      });
    </script>
  </head>
  <body></body>
</html>

```

It works if I use the `usePostMessage` option, which I cannot use because of #428

I am using Auth0.js 8.6.1 on latest Chrome.

**Comment by luisrudge** [comment]
Can you try this instead:

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript">
      parent.postMessage(window.location.hash, "http://localhost:3000/");
    </script>
  </head>
  <body></body>
</html>
```

**Comment by rochdev** [comment]
That seems to work. However, the documentation is completely wrong then.

Also, I'm not sure to understand why this works while `usePostMessage` is set to false.

**Comment by luisrudge** [comment]
To be clear: it's a bug. It should work with both snippets.

**Comment by luisrudge** [comment]
@rochdev can you build a sample repro? I just tried with [this](https://github.com/auth0/auth0.js/tree/master/example) example (I replaced the callback.html file with the snippet you sent) and it works.

**Comment by rochdev** [comment]
It still works if I completely removing the `postMessage` call in `silent-callback.html`. Not sure to understand how.

**Comment by dorilla** [comment]
Adding "nonce" with a random generated string value to the options passed into "renewAuth" worked for me

**Comment by oliverlloyd** [comment]
As per dorilla's comment above, we need to pass a random string to 'solve' the same problem of nonce errors. Not super happy with this workaround to be honest, mainly because I can't explain it. Can anyone shed some light on why we need to do this?

auth.js
```
export default class Auth extends EventEmitter {
  auth0 = new auth0.WebAuth({
    domain: 'QQQ.eu.auth0.com',
    clientID: 'QQQ',
    redirectUri: `${window.location.origin}/auth/callback`,
    audience: 'https://QQQ.eu.auth0.com/userinfo',
    responseType: 'token id_token',
    scope: 'openid profile'
  });

  // etc...

  isAuthenticated() {
    // Check whether the current time is past the
    // access token's expiry time
    const expiresAt = JSON.parse(localStorage.getItem('expires_at'));
    if ( new Date().getTime() < expiresAt ) return true
    // Their token has expired, if they had one...
    const aTokenExists = JSON.parse(localStorage.getItem('access_token'))
    if ( aTokenExists ) return this.renew()
    // otherwise they've either logged out or never logged in
    return false
  }

  renew() {
    this.auth0.renewAuth({
      redirectUri: `${window.location.origin}/auth/renew`,
      usePostMessage: true,
      nonce: 'a random string to workaround auth0 bug', // https://github.com/auth0/auth0.js/issues/429
    }, (err, result) => {
      if (err) {
        this.login();
      } else {
        this.setSession(result);
      }
    });
  }
}
```

routes.js
```
export const makeMainRoutes = () => {
  return (
    <ApolloProvider client={client}>
      <BrowserRouter history={history}>
        <div>
          <Switch>
            <Route path="/auth/callback" render={(props) => {
              handleAuthentication(props);
              return <Callback {...props} />
            }}/>
            <Route path="/auth/renew" component={SilentCallback} />
            // etc...
          </Switch>
        </div>
      </BrowserRouter>
    </ApolloProvider>
  );
}
```

SilentCallback.js
```
export default function SilentCallback() {
  var data = {
    type: 'auth0:silent-authentication',
    hash: window.location.hash
  };
  window.parent.postMessage(data, "*");
  return null
}
```

**Comment by dorilla** [comment]
Using a nonce is a way to mitigate replay attacks. Documentation here: https://auth0.com/docs/api-auth/tutorials/nonce

As to why it's required, perhaps it's due to OIDC Conformance: https://auth0.com/docs/api-auth/intro (skip to the part about `Implicit Grant`)

```The nonce request parameter must be a cryptographically secure random string. After validating the ID token, the client must validate the nonce to mitigate replay attacks. Requests made without a nonce parameter will be rejected.```

This is just me speculating. I don't work for Auth0.

**Comment by oliverlloyd** [comment]
@dorilla Thanks, this makes more sense now. Not really sure why this isn't document but as far as I can see this is how this function should be called:

``` 
import decodeJwt from 'jwt-decode'
// ...
export default class Auth extends EventEmitter {
  renew() {
    // A user's token has expired (after 2 hours) so we try to renew it.
    // The user should not be aware of this happening unless for some reason
    // we cannot renew their session - perhaps they've been inactive for a
    // while or their account is invalid suddenly - so we ask them to
    // authenticate once more.
    //
    // Note the use of a nonce token
    // See: https://auth0.com/docs/api-auth/tutorials/nonce
    //
    function randomString(length) {
      var bytes = new Uint8Array(length);
      var random = window.crypto.getRandomValues(bytes);
      var result = [];
      var charset = '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._~'
      random.forEach(function (c) {
          result.push(charset[c % charset.length]);
      });
      return result.join('');
    }

    const nonce = randomString(16)
    this.auth0.renewAuth({
      redirectUri: `${window.location.origin}/auth/renew`,
      usePostMessage: true,
      nonce: nonce,
    }, (err, renewResult) => {
      if (err) {
        console.error(err)
        // The access_token is probably bad, remove it so we don't keep trying
        // to renew it.
        localStorage.removeItem('access_token');
      } else if ( decodeJwt(renewResult.idToken).nonce !== nonce ){
        // Something fishy is going on.
        console.error('The nonce string returned did not match the one sent.')
        // Ensure user is asked to login again
        localStorage.removeItem('access_token');
      } else {
        // Save the returned session data to LS
        this.setSession(renewResult);
      }
    });
  }
}
```

**Comment by hzalaz** [comment]
@oliverlloyd auth0.js will try to generate a nonce for you if web crypto is available (http://caniuse.com/#feat=getrandomvalues). So all that is not needed if you are using IE>11 and in case you need to support them you will need a polyfill

**Comment by oliverlloyd** [comment]
Ahh, I see. Does it also verify that the response contains the same value that was sent or is this only possible if I send my own?

**Comment by hzalaz** [comment]
should do all that OOB, if it does not please submit an issue 😄

**Comment by oliverlloyd** [comment]
Got it. Thanks.

One thing for the thread. I've noticed that if I send multiple asynchronous renew() calls (using different nonce values) then only the last one to return works. The others get the 'invalid_token: Nonce does not match' error. I presume because the auth0 server is holding the nonce value at the client scope (not at request scope) so it gets replaced each time and only matches correctly on the last call.

**Comment by SteveByerly** [comment]
@hzalaz "if you are using IE>11 and in case you need to support them you will need a polyfill" is there any documentation on what browser support there is for auth0.js and how it handles lack of support for certain features?

**Comment by hzalaz** [comment]
@oliverlloyd I am not sure and I'll have to tests it since its not how renewAuth is expected to be used by sending a lot of concurrent requests (you might get rate limited). 

@SteveByerly we have this documented [here](https://auth0.com/docs/support/matrix), the web crypto is the only thing that we have partial support so far (we will add the missing not in the docs and README).

**Comment by fredrikj** [comment]
@hzalaz It seems to me that the natural way to use renewAuth is to call it at a certain time before your tokens expire. The leads to a synchronisation of requests coming from different tabs in the same browser (since they of course share the tokens). Hence -  concurrent calls does not seem like a very unlikely situation. Is this a necessary error in the case of concurrent calls?

**Comment by luisrudge** [comment]
@fredrikj if you need to call it multiple times (or from multiple tabs), you can use a different `postMessageDataType` for each call. It should work for multiple concurrent calls.

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
