### ISSUE TITLE
Throw a specific error to the user if the Authentication mode asked is not available in the current platform/app

### ISSUE THREAD

**Issue by mgonto** [auth0/auth0.js#44]
We have right now 3 Authentication modes:
- Popup
- Redirect
- Post to `/ro`

Not all the calls can be made in all devices.

For example, `redirect` cannot be used in `Cordova` and `Phonegap`.

We should add a mechanism in `auth0.js` to detect in what platform / app we're currently and if we're asked to perform an Authentication mode that we cannot do, we should throw a specific error for that.

Firebase is doing [something similar](https://www.firebase.com/docs/web/guide/user-auth.html#section-popups).

**Comment by hzalaz** [comment]
Closing this one. In v8 we will be explicit on what mode you are using.
