### ISSUE TITLE
Signup User Enumeration Risk

### ISSUE THREAD

**Issue by jculverwell** [auth0/auth0.js#447]
When using the signup method of auth0.js if you try and signup with an existing username it returns:

{"name":"BadRequestError","code":"user_exists","description":"The user already exists.","statusCode":400}

Isn't this exposing the site to user enumeration risk https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)

Assuming it does are there are workarounds to avoid this?

**Comment by luisrudge** [comment]
Hi @jculverwell. Since this is not an issue with the library, I think you're better of asking this question in our support channel here: https://support.auth0.com/
