### ISSUE TITLE
RenewAuth flow broken due to timeoutCallback firing after successful renew

### ISSUE THREAD

**Issue by parliament718** [auth0/auth0.js#448]
- [ 8.7.0 ] Auth0.js version
- [ Chrome & OSX ] Browser & OS

I'm having issues with the renewAuth token flow. The token is successfully renewed but then one minute later user is logged out.

The cause seems to be the fact that `loadEventListener()` method does not call `destroy()`, which ultimately calls `clearTimeout(this.timeoutHandle)`.

```
IframeHandler.prototype.messageEventListener = function (e) {
  this.destroy();
  this.callbackHandler(e.data);
};
IframeHandler.prototype.loadEventListener = function () {
  var _this = this;
  //HERE should have this.destroy()  just like messageEventListener
  _this.callback(this.iframe.contentWindow.location.hash);
};
```

Conceptually, when the iframe gets a load event and the code reads the hash successfully, there should be no reason timeoutCallback should be firing a minute later due to the `setTimeout(this.timeoutHandle)` which is never reset:

![pic1](https://cloud.githubusercontent.com/assets/3580270/26682569/e72aa60a-46ae-11e7-9b2c-601bcdced222.png)

**Comment by bragma** [comment]
Strange, I am using renewAuth but didn't notice it. Are you redirecting to a separate callback page or your main app page?

**Comment by luisrudge** [comment]
Are you sure you're using 8.7.0? The code you referenced doesn't exist anymore.
Here's the new event listener in the IframeHandler: https://github.com/auth0/auth0.js/blob/master/src/helper/iframe-handler.js#L59

**Comment by luisrudge** [comment]
Also, I just tested with our examples page and the timeout didn't fire after the renewAuth result was returned by the server.

**Comment by luisrudge** [comment]
If you can reproduce the issue, please reopen the issue with a repro project or some repro steps.

**Comment by kmaida** [comment]
I'm also encountering this issue. It typically happens after `renewAuth()` has successfully retrieved new tokens several times before it then fails on a subsequent renewal.

Version 8.7.0
