### ISSUE TITLE
Client login: return profile data for database connection

### ISSUE THREAD

**Issue by sharok** [auth0/auth0.js#450]
I have custom login page in my Angular 2 application and I have implemented login/signup. I use database connection:
```
this.auth0.client.login({
      realm: 'Username-Password-Authentication',
      responseType: 'token',
      username: credentials.username,
      password: credentials.password,
      scope: 'openid profile'
    })
```

I get the following response:
```
accessToken: "7ffAFpxqRGueR1LZ"
expiresIn:86400
idToken: some_token
tokenType:"Bearer"
```

But, the response doesn't contain info about user: email, picture, nickname and other fields. I have `profile` in scope as you can see, I tried to put `email` there, but response always the same.

Is it bug or I miss something? I read your documentaion about 2 hours and didn't found solution.

I use the 8.7.0 version.

**Comment by luisrudge** [comment]
did you decode the idtoken?

**Comment by sharok** [comment]
No.... why I have to? Why can't I get it in response, I believe in the 7 version I got all data without decoding?
Why is there scope property them?

**Comment by luisrudge** [comment]
login/signup callbacks receive an `authResult` object, which is the same thing returned by the `parseHash` function, which you can check in our readme how it works: https://github.com/auth0/auth0.js#api

Once you have the `accessToken`/`idToken` you can either decode the `idToken` or use the `accessToken` to fetch the user's information.

The scope docs is [here](https://auth0.com/docs/scopes/current).
