### ISSUE TITLE
Trouble with isomorphic react app bundling with rollup and babel

### ISSUE THREAD

**Issue by kurtmilam** [auth0/auth0.js#452]
I'm trying to pull auth0-js into my isomorphic react application that depends on rollup and babel for bundling / transpiling, but I've had a ton of trouble trying to get it to work.

I've managed to clear up a few server-side errors by adjusting my rollup config, but I'm currently stuck.

The auth0 branch on [this repository](https://github.com/kurtmilam/karet-express-boilerplate/tree/auth0) can be used to reproduce the erratic behavior.

Files of interest:
1. /rollup.config.js
2. /src/public/client.js (where I import auth0-js and create `webAuth` component).

This is a follow up to a mildly off-topic discussion that took place in #446 .

**Comment by luisrudge** [comment]
Thanks for opening the issue? Can you create a simple repro project so I can test and help you out?

**Comment by kurtmilam** [comment]
Thanks for getting back to me. I've just pruned the project at [this repository](https://github.com/kurtmilam/karet-express-boilerplate/tree/auth0) back to what I believe are the essential elements. Please let me know if you need it in some other form.

**Comment by kurtmilam** [comment]
I cross-posted this [here](https://github.com/rollup/rollup/issues/1439) in hopes that someone from the rollup project would be willing to take a look.

**Comment by luisrudge** [comment]
This doesn't work for me.
![image](https://user-images.githubusercontent.com/941075/26932753-de8d7cca-4c3a-11e7-8bfb-ed00b4fceed6.png)
It doesn't load the JS file at all

**Comment by kurtmilam** [comment]
Since apologies. I left a couple of stragglers in package.json that caused the bundling to fail.

I've remedied the problem and tested by cloning the project to a new directory.

Installation Instructions:
```
git clone https://github.com/kurtmilam/karet-express-boilerplate.git
cd karet-express-boilerplate
git checkout auth0
npm install
nmp run watch
```

**Comment by kurtmilam** [comment]
Please hold off on this while I test out a tip from the rollup issue.

**Comment by kurtmilam** [comment]
Can someone from the auth0 team confirm whether it should be possible to run auth0.js v8 on the server? I assumed it could, based on this comment by @hzalaz in an [auth0/lock issue](https://github.com/auth0/lock/issues/592#issuecomment-276452084).

> Some changes were made in lock.js and auth0.js to avoid relying on window object and breaking server side rendering but lock is not there yet (auth0.js v8 can be used without issues)

I've gotten some help from the rollup team, but we/they haven't been able to get it working yet. I've tried with auth0 v8.7.0 and v8.8.0 with no luck.

**Comment by luisrudge** [comment]
what errors are you having right now?

**Comment by kurtmilam** [comment]
The server error I'm seeing right now is 'crypto is not defined'.

**Comment by luisrudge** [comment]
yeah, basically, we still rely on some window/document objects, so SSR won't work if you need to authorize a user. In any case, you shouldn't be authorizing users using your server. As it stands, auth0.js is SSR friendly because it doesn't blow up when you require it like it did previously. You still can't use this on the server though.

**Comment by kurtmilam** [comment]
Thanks so much for helping me out here. The solution ended up being a combination of things:

1. Pass `{ browser: true }` to the node-resolve rollup plugin.
2. Place `isBrowser` ( `typeof window !== 'undefined'` ) guards before all invocations of auth0 to make sure it's never invoked on the server.

I appreciate your patience and dedication in helping me determine the solution!
