### ISSUE TITLE
auth0.client.login

### ISSUE THREAD

**Issue by varyandeveloper** [auth0/auth0.js#456]
Hi, I am trying to use auth0.client.login. I have configured default audience and default connection and my app type is SPA

This is the code

`const auth0 = new Auth0.WebAuth({
    clientID: AUTH_CONFIG.clientID,
    domain: AUTH_CONFIG.domain,
    responseType: 'token'
});
`

`auth0.client.login({
            password: uPass,
            realm: 'Test-db',
            username: uName
        }, (err: any, user: any) => {
            alert(err)
        });`

And this is response

`{error: "unauthorized_client",…}
error
:
"unauthorized_client"
error_description
:
"Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client."`

Can you help to figure it out, please?

**Comment by sandrinodimattia** [comment]
You have to enable the grant type: https://auth0.com/docs/clients/client-grant-types

**Comment by varyandeveloper** [comment]
Thank you for your quick response @sandrinodimattia. is there a way to add grant_type with auth0 management interface or it is possible programmatically only?

**Comment by luisrudge** [comment]
Only via api https://auth0.com/docs/api-auth/tutorials/password-grant#realm-support
