### ISSUE TITLE
Win7 IE 10 Support?

### ISSUE THREAD

**Issue by dansomething** [auth0/auth0.js#461]
I'm seeing the following error when attempting the login from any of the [Angular examples](https://github.com/auth0-samples/auth0-angular-samples) which use version 8.7.0 of this library. I'm using IE 10 on Win 7.

```
SCRIPT5022: Caught exception occurred : nonce option is required 
vendor.bundle.js, line 984 character 5
```

The error occurs when clicking the "Log In" link in the samples which calls `this.auth0.authorize();` in auth.service.ts.

It looks like there's a failure to create the nonce due to IE10 not supporting web crypto.

*Steps to reproduce*
* Git clone the [Angular samples](https://github.com/auth0-samples/auth0-angular-samples)
* Uncomment the IE 10 import lines in polyfills.ts
* Follow the [readme](https://github.com/auth0-samples/auth0-angular-samples/blob/master/01-Login/README.md) instructions
* Point IE 10 to https://localhost:4200
* Click the 'Log In' link.

I'm working around this for now by creating and storing my own nonce in IE10, but I'd prefer to let the library manage that if possible.

**Comment by luisrudge** [comment]
For IE10 and other browsers that don't support the `web cryptography api`, you should provide your own `nonce`. I'll ping the docs/samples about this issue in our samples. Thanks 🎉

**Comment by arvinsim** [comment]
Can you give me the link to the docs/samples? I am having the same problem as the OP.

**Comment by luisrudge** [comment]
Sorry, I'm not sure the docs team added a section about this. In any case, you can follow my previous advice. I will personally mention this in the docs.

**Comment by luisrudge** [comment]
@arvinsim just to clarify: Did you have this problem with the angular sample as well?

**Comment by arvinsim** [comment]
@luisrudge I have integrated Auth0 v7 into my React app. Our testers have identified IE10,Win7 as a problematic platform.

So I don't think this is an Angular specific problem :)

**Comment by luisrudge** [comment]
v7? or v8?

**Comment by arvinsim** [comment]
We are using `v7.6.0`. Let me know if upgrading to `v8` is relevant to the issue.

**Comment by luisrudge** [comment]
I'm not sure it is. v7 will only receive security fixes though. v7 has the same issue as v8 though: https://github.com/auth0/auth0.js/blob/v7/lib/nonce-generator.js#L3 We use the Web Crypto API to generate random strings. IE10 doesn't have that, so you'll have to provide your own nonce.
