### ISSUE TITLE
BUG: a rule doesn't add claims to id_token

### ISSUE THREAD

**Issue by zatziky** [auth0/auth0.js#463]
`"auth0-js": "^8.8.0"`

I suspect there is a bug in auth0. When adding the following rule to the flow

```
function (user, context, callback) {
   var namespace = 'https://my-app.io/';   
   var organization = user.user_metadata.organization;
   context.idToken[namespace + 'organizationId'] = user.user_metadata.organization.id;
   callback(null, user, context);
 }
```

JWT token of `id_token` doesn't contain any `organizationId` whereas accessing `user-info` I get the field `organizationId`.

Is it a bug or am I doing something wrong?

**Comment by luisrudge** [comment]
Hi, since this is not auth0.js related, please open a ticket with our amazing support team at https://support.auth0.com/

**Comment by zatziky** [comment]
@luisrudge Thx Luis, I did so.
