### ISSUE TITLE
Authentication API authorize

### ISSUE THREAD

**Issue by james-prado** [auth0/auth0.js#465]
I can't seem to get authorization working with any providers (google, twitter, fb, etc...). The only error I get is this ![screenshot](https://user-images.githubusercontent.com/13836920/27741339-cb6cc796-5d82-11e7-9396-1598e62ef612.png)

App.js
``` 
import React, { Component } from 'react'
import Auth from './Auth.js'

class App extends Component {
	onClick = e => {
		e.preventDefault
		Auth.popup.authorize({
			connection: 'google-oauth2'
		})
	}

	render() {
		return <button onClick={this.onClick}>Sign In</button>
	}
}

export default App
```

Auth.js 
```
import auth0 from 'auth0-js'

const Auth = new auth0.WebAuth({
	domain: 'domain.auth0.com',
	clientID: 'myID...',
	responseType: 'token id_token'
})

export default Auth
```

auth0-js version: 8.8.0
browser: chrome 58
OS: macOS Sierra 10.12.5

**Comment by luisrudge** [comment]
Hi, since this is not a bug report, please open a ticket with our amazing support team at https://support.auth0.com/
