### ISSUE TITLE
IE11 - Nonce does not match

### ISSUE THREAD

**Issue by critchie** [auth0/auth0.js#471]
- Code Snippet: 05-Token-Renewal from [Samples](https://github.com/auth0-samples/auth0-angular-samples)
- Auth0.js version: 8.8.0
- Browser: IE11 v. 11.0.9600.18015IS
- OS: Windows 7 Professional SP1

Description/Issue
Followed the instruction in the README.md pointing the app to my API.  The app works flawlessly using Chrome.  IE11 however fails when the authService.handleAuthentication is called after being redirected back to the app after a successful login.  From what I can determine it fails with "Nonce does not match".

**Comment by luisrudge** [comment]
Did you change the sample code? If so, can you isolate the issue with a simple example so we can reproduce?

**Comment by ashishdasnurkar** [comment]
I'm seeing the same issue with auth0.js v8.9.3 on Safari Private window. After authentication, I see `{"error":"invalid_token","errorDescription":"Nonce does not match."}`. I could reproduce it with current angularjs quickstart as-is https://auth0.com/docs/quickstart/spa/angularjs

**Comment by ashishdasnurkar** [comment]
it seems the failover to CookieStorage isn't working. I added console.log for getItem and setItem. In Safari private window, auth0.js falls back on using CookieStorage correctly and uses it to set the Nonce in the cookieStorage. However after authentication when auth0.js does getItem the nonce is null. See the screenshot below

![screen shot 2017-09-05 at 6 29 02 pm](https://user-images.githubusercontent.com/5362188/30057744-91afc892-926a-11e7-8f05-fa25a38b749b.png)

**Comment by ashishdasnurkar** [comment]
store.js seems to have solved similar issue for reference https://github.com/marcuswestin/store.js/issues/168#issuecomment-283123205

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
