### ISSUE TITLE
Cannot read property 'getStoredTransaction' of undefined

### ISSUE THREAD

**Issue by NathHorrigan** [auth0/auth0.js#472]
I'm using binding the parseHash function to RxJS and Redux-Observable and I'm getting the following error (I'm pretty sure its Auth0.js related but I could be wrong):
> Cannot read property 'getStoredTransaction' of undefine

Here is my function call:

```
export const parseLogin = (action$, store) =>
  action$.ofType(actionTypes.parseLogin)
    .mergeMap(action => {
      const webAuth = store.getState().app.webAuth
      if (typeof webAuth !== 'undefined') {

        const parse = Observable.bindCallback(webAuth.parseHash)
        return parse(window.location.hash)
          .map((err, authResult) => {

            console.log(authResult.accessToken)

          })
          .catch(e => {
            console.log(e)
          })

      }
    })
```

**Comment by luisrudge** [comment]
can you try calling parseHash without all of that and see if it works? parseHash is very important for auth0.js and Lock. I'm pretty sure we'd have been flooded with issues if it wasn't working 😅

**Comment by FabienDehopre** [comment]
I also tried to use the rxjs bindCallback method but it did not work neither.
It's because when the parseHash method is called, it's not bound and do not have access to `this` (which is undefined).

**Comment by NathHorrigan** [comment]
@luisrudge parseHash was working perfectly before hand. @FabienDehopre did you come up with a workaround for this?

**Comment by luisrudge** [comment]
Ok. Since this is not auth0.js related, I'll close the issue. Thanks for the update @NathHorrigan 🎉

**Comment by FabienDehopre** [comment]
@NathHorrigan You wrap the call to parseHash inside an observer:
```ts
const webAuth = new auth0.WebAuth({
  clientID: 'XXXX',
  domain: 'domain.auth0.com',
  responseType: 'token id_token',
  audience: 'https://your_api/',
  redirectUri: `${location.protocol}//${location.host}/callback`,
  scope: 'openid profile email'
});
///////////////////////////////////////////
Observable.create(observer => {
  webAuth.parseHash((err, authResult) => {
    if (err) {
      observer.error(err);
    }
    else if (authResult && authResult.idToken && authResult.accessToken) {
      observer.next(authResult);
    }

    observer.complete();
  });
});
```
