### ISSUE TITLE
Audience Invalid

### ISSUE THREAD

**Issue by lcborn4** [auth0/auth0.js#473]
I am currently getting this error: 
```
        "name": "JsonWebTokenError",
        "message": "jwt audience invalid. expected: http://localhost:1337"
```
The backend needs an audience of  http://localhost:1337. However the token that im creating is putting my clientID at the aud. 

In my front end which is built in angular2,

```
  auth0 = new auth0.WebAuth({
    domain: AUTH_CONFIG.domain,
    clientID: AUTH_CONFIG.clientID,
    redirectUri: AUTH_CONFIG.callbackURL,
    audience: 'http://localhost:1337', <-- i set the audience to this
    //aud: 'http://localhost:1337',
    responseType: 'token id_token',
    scope: 'openid profile'
  });
```

then i call this: 

```
    this.auth0.client.login({
      realm: 'Username-Password-Authentication',
      username: username,
      password: password,
      audience: this.auth0.audience
```

To get my token.

The authresult token I am getting does not have localhost:1337 as my aud. Instead it is my auth0 clientId.

**Comment by luisrudge** [comment]
I assume you're talking about `id_token`. Is that right? If that's the case, then the `aud` is correct, since the `audience` is always going to be from the client that made the authorization request, in this case it's `AUTH_CONFIG.clientID`.

**Comment by lcborn4** [comment]
is it possible to change it from clientID?

**Comment by luisrudge** [comment]
No. It's just how the open id spec works.

**Comment by luisrudge** [comment]
> audience {OPTIONAL, string}: The default audience, used if requesting access to an API.

The readme states that `audience` is used when you request access to an API. You're just loging in, so you'll get the audience for your client, which is your clientId.

**Comment by lcborn4** [comment]
ok I got it to work. Thanks for the help
