### ISSUE TITLE
Feature Request: usePostMessage in logout

### ISSUE THREAD

**Issue by dimitrovs** [auth0/auth0.js#474]
Currently the logout endpoint redirects the browser to the auth0 logout URL. It will be very useful to add 'usePostMessage' in its options and make it behave like renewAuth (injecting an iframe and doing the redirect there).

**Comment by luisrudge** [comment]
What's the use case?

**Comment by dimitrovs** [comment]
My use case is using auth0 with admin-on-rest, which calls logout every time it gets 401 from the backend, and when logout is complete it redirects to login. If I actually call auth0.logout during this process then I can't redirect to login. I can put the app login URL as the Auth0 logout URL but I don't know what other cleanup the framework would have done if I had resolved its promise instead.

I think there can be various UX designs that can benefit from not blindly sending the user off to another page, and you guys already have the code for this anyway as part of the renewAuth flow.

**Comment by luisrudge** [comment]
Can you call auth0's logout after the framework finishes cleaning up the internal stuff?

**Comment by dimitrovs** [comment]
No, the logout hook is the first thing they call during the logout process. But I looked at the source and there isn't any cleanup actually going on so my integration is working fine for now with the login page as Auth0 logout URL.

**Comment by luisrudge** [comment]
Alright. Thanks for letting us know. I'm glad you got it working 🎉
