### ISSUE TITLE
iOS Safari 10.3.3 SecurityError for localStorage

### ISSUE THREAD

**Issue by hwestbrook** [auth0/auth0.js#477]
- [x] Code snippet or sample project that reproduces the bug
- [x] Screenshots when appropriate
- [x] Auth0.js version = 8.7.0
- [x] Browser & OS = iOS Safari 10.3.3

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

-----------------------

I'm using Auth0-lock & React for a web app I've created. It works great, except when I have a user the has cookies turned off in iOS. When I have that situation, I'm getting the following error:

![image](https://user-images.githubusercontent.com/335309/28850085-5400384e-76cf-11e7-825c-49342d73a685.png)

I've traced this error back to auth-js, specifically, [this line](https://github.com/auth0/auth0.js/blob/master/src/helper/storage/handler.js#L8): 
```
this.storage = windowHandler.getWindow().localStorage || new CookieStorage();
```

This seems to be a relatively [common issue](https://www.google.com/search?q=SecurityError+%28DOM+Exception+18%29%3A+The+operation+is+insecure.+localstorage&oq=SecurityError+%28DOM+Exception+18%29%3A+The+operation+is+insecure.+localstorage&gs_l=psy-ab.3...1548.5074.0.5178.17.14.2.0.0.0.167.1420.9j5.14.0....0...1.1.64.psy-ab..1.1.104...0.fVbOw3L6YRM).

I've fixed it within node_modules for my project by changing the above to:
```
try {
   this.storage = windowHandler.getWindow().localStorage || new CookieStorage();
} catch(e) {
   this.storage = new CookieStorage();
}
```

**Comment by luisrudge** [comment]
Can you send a PR with this? That'd be amazing. 🎉

**Comment by hwestbrook** [comment]
OK, I've done that

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/auth0.js/pull/698
