### ISSUE TITLE
How to get the authentication response in querystring instead of hash

### ISSUE THREAD

**Issue by JohnCoding94** [auth0/auth0.js#479]
The need is simple, ``hash`` aren't transmitted to the server, so universal apps cannot decode the token on the callback unless the params are in ``querystrings`` when invoking the ``redirectUri``.

I looked at the ``parseHash`` method's source code and it looks like it has been planned to work with both configurations, but i don't see where i can tune this option.

**Comment by luisrudge** [comment]
try the different `responseMode` configurations available in the readme: https://github.com/auth0/auth0.js#auth0webauth

**Comment by JohnCoding94** [comment]
@luisrudge thanks for the link! I didn't see this page.

I just tried, but i am redirected to ``https://login.eu.auth0.com/login/callback?state=***#`` instead of my own redirect uri after the user sign in on the Auth0 hosted page, which is an error page (Oops!, something went wrong).

The only thing i changed is adding the `responseMode: query`, so it looks like this:

````js
const client = new auth0.WebAuth({
  domain: conf.auth0.domain,
  clientID: conf.auth0.clientId,
  redirectUri: conf.auth0.redirectUri,
  audience: 'https://***.eu.auth0.com/userinfo',
  responseType: 'token id_token',
  responseMode: 'query', // the redirect works fine if i don't override this param
  scope: 'openid email'
});

client.authorize();
````

The error i get on this page is ``unsupported_response_mode: Unsupported response mode: query``.

Any idea about why it is not supported?

**Comment by Eomm** [comment]
I have the same issue. I would like to have the response via queryString. Any help will be appreciated

**Comment by luisrudge** [comment]
Why do you need the response via query string?

**Comment by davidthor** [comment]
+1 on this. I have the same issue trying to build an isomorphic application using [Nuxt](https://nuxtjs.org/), and ran into the same issue described by @JohnCoding94. `responseMode` of `query` seemed like the natural answer documented above, but seems to be causing problems.

**Comment by luisrudge** [comment]
I just confirmed with the backend team and that's indeed the case. responseMode=query is only supported for the code grant flow (responseType=code). I'm updating docs and readme to reflect that:
https://github.com/auth0/auth0.js/pull/527
https://github.com/auth0/docs/pull/5187

If you want to read more about the different flows, you can read this article which is very helpful: https://auth0.com/docs/api-auth/which-oauth-flow-to-use

**Comment by Errorname** [comment]
Hey!
I would also like to know if there is a reason for not allowing a query responseMode. Do you have any info @luisrudge ?

**Comment by luisrudge** [comment]
yeah. According [to the spec](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes), you shouldn't return a token or id_token in the query string to prevent leaks during transport and risks to the privacy of the user.

**Comment by Errorname** [comment]
Thank you for the explanation
