### ISSUE TITLE
user_metadata keys get converted to snake case

### ISSUE THREAD

**Issue by gmahomarf** [auth0/auth0.js#480]
Using Auth0.js version 8.8.0

```.js
auth0.webAuth.signup({
  email,
  password,
  user_metadata: {
     someKey: 'someValue'
  }
})
```

Before sending the request, `user_metadata`'s keys get converted to snake case, so in the database it ends up as `{ some_key: "someValue" }`

I haven't seen anything regarding this in the documentation. Is this the expected behavior?

**Comment by luisrudge** [comment]
It's a bug. There's a pr to fix it here https://github.com/auth0/auth0.js/pull/475. This will be released next week. Sorry :tada:

**Comment by gmahomarf** [comment]
Thanks for the quick response. I'll go ahead and close this and keep an eye on the PR.
