### ISSUE TITLE
Cannot read property 'WebAuth' of undefined: With Requirejs

### ISSUE THREAD

**Issue by phronesis** [auth0/auth0.js#491]
I am creating an Auth0 extension for Magento 2. Magento uses requirejs to load javascript modules.
When I load auth0.js, it returns an undefined object.
This is the exact error I get:
`Cannot read property 'WebAuth' of undefined`
This is the code snippet:
```
<script >
    'use strict';
    var auth0Config =<?php echo json_encode($block->getConfigData()); ?>;


    require(['jquery','DavidUmoh_Auth0/js/lib/auth0'],function($,auth0){

        $(function(){

         var config = auth0Config;

         var webAuth = new auth0.WebAuth({
             domain: config.domain,
             clientID: config.client_id,
             redirectUri: config.callbackUrl,
             audience: 'https://' + config.domain + '/userinfo',
             responseType: 'code',
             scope: 'openid profile'
         });

         $('li.authorization-link > a').click(function(e) {

             e.preventDefault();
             webAuth.authorize();
         });
     });
 })
</script>
```

I am using the current version of auth0.js, gotten from here:
https://raw.githubusercontent.com/auth0/auth0.js/v8.9.2/build/auth0.js

Browser: Chrome, OS: Mac OSX

**Comment by luisrudge** [comment]
It must be a problem with your requirejs configuration. if the auth0 object is undefined, it means that you're not loading it correctly.
