### ISSUE TITLE
Logout function

### ISSUE THREAD

**Issue by jorgeucano** [auth0/auth0.js#494]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ x ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ x ] Code snippet or sample project that reproduces the bug
- [ x ] Screenshots when appropriate
- [ x ] Auth0.js version
- [ x ] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

Auth0.js version => http://cdn.auth0.com/js/auth0/8.6/auth0.min.js
Browser & OS => Mac Sierra, Windows 10

I can login, work with client, update data, all work fine, when I try to logout show this error with this code:

```js
this.auth0.logout({
      'returnTo': environment.auth0Config.logoutURL,
      'client_id': environment.auth0Config.clientID
});
```

Error
<img width="1131" alt="captura de pantalla 2017-08-22 a la s 10 02 47" src="https://user-images.githubusercontent.com/5982204/29566710-1fc9c07e-8721-11e7-8522-db5a83c17325.png">

Web
<img width="1149" alt="captura de pantalla 2017-08-22 a la s 09 46 03" src="https://user-images.githubusercontent.com/5982204/29566369-fe388342-871f-11e7-9c70-d56226f4ee6c.png">

I check the config for the project, check the redirects URLS, and work, for localhost and production, but the logout not working.

My project is in Angular v4, I use the instructions => https://auth0.com/docs/libraries/auth0js/v8

Thanks in advance

**Comment by luisrudge** [comment]
What error are you getting? (Click in the "see details for this error)

**Comment by jorgeucano** [comment]
Oh sorry is this

<img width="556" alt="captura de pantalla 2017-08-22 a la s 10 08 04" src="https://user-images.githubusercontent.com/5982204/29566902-e2e51284-8721-11e7-8950-1654d8c1aee0.png">

**Comment by luisrudge** [comment]
I'm talking about this:
![image](https://user-images.githubusercontent.com/941075/29566934-f799c24c-8721-11e7-84d5-474d11292de9.png)

**Comment by jorgeucano** [comment]
show this => 

<img width="582" alt="captura de pantalla 2017-08-22 a la s 10 09 56" src="https://user-images.githubusercontent.com/5982204/29566980-2d23188c-8722-11e7-81e5-63dce0919b7d.png">

when I go to the url and check

<img width="376" alt="captura de pantalla 2017-08-22 a la s 10 10 26" src="https://user-images.githubusercontent.com/5982204/29566995-35b6bf3a-8722-11e7-984c-cdd57fa575d6.png">

**Comment by luisrudge** [comment]
Just follow the instructions in that message. You need to add the logout url to your allowed logout urls. 🎉

**Comment by jorgeucano** [comment]
okey its different inputs =) sorry and thanks !
