### ISSUE TITLE
Unale to Import ES6

### ISSUE THREAD

**Issue by rmemon** [auth0/auth0.js#495]
Sorry to put this in issue, 
I am using Es6 syntax in my angular app, to develop web pack based angular1.x app,

I am unable to import auth0.lock, from node_modules

```
import uibootstrap from 'angular-ui-bootstrap';

**import auth0 from  'auth0-js';**

angular.module('loginApp', [
    // Third Party Modules
    uibootstrap,      

    // Internal Modules
    'app.services',
    'app.controllers',
])
```

Thanks in Advance

**Comment by luisrudge** [comment]
We do that on Lock, so I guess your project is misconfigured:
https://github.com/auth0/lock/blob/c1f700fcb9b4a423ee8139d61fcea3c81e424ca3/src/core/web_api/p2_api.js#L1

did you try `import * as auth0 from 'auth0-js'`?
