### ISSUE TITLE
renewAuth() + error 500 => no error returned

### ISSUE THREAD

**Issue by xurei** [auth0/auth0.js#498]
```
auth0.renewAuth(renewAuthOptions,
function (err, result) {
	if (err) {
		/* in case of 500 error, this is not called */
		console.error('Error occured while renewAuth :', err);
	}
	else {
		console.debug('renewAuth result', result);
	}
});
```

If the link `https://keemotion.eu.auth0.com/authorize?...` returns a 500 error, the error event is not triggered. 

More context : We got this error after removing a user in the manager.

Tested with versions 8.8.0 to 8.9.3, on firefox and chrome.

**Comment by luisrudge** [comment]
do yo see any errors in the console?

**Comment by xurei** [comment]
Just the 500 error from the browser.

After 30s, I get the timeout error. It should be triggered directly after the 500 error.

**Comment by blakek** [comment]
We're getting this when trying to register a new user using a custom DB

**Comment by luisrudge** [comment]
Hi, I just checked and it's impossible for us to know when an iframe errors out because of the way iframes work. In the next release, you'll be able to add a `timeout` option to your `renewAuth` call (something like `renewAuth({timeout: 4000})`.
