### ISSUE TITLE
Distinguish no internet connection error

### ISSUE THREAD

**Issue by balinterdi** [auth0/auth0.js#50]
In our client application, we want to be able to set apart the case where the user does not have an internet connection and display a message accordingly on the login screen.

It seems to me though that the error status code for the "no connection" error is transformed into a 401 because of [this line](https://github.com/auth0/auth0.js/blob/master/lib/index.js#L891) that fixes an IE 10 error, judging from the code comment.

Is there a way to distinguish the "no connection" error from other errors and have everything also work under IE10?

**Comment by pose** [comment]
Reproduction steps:

1. go to the auth0.js login
2. disconnect from the network
3. try to login


Notify @patrickyoung when this is fixed.
