### ISSUE TITLE
Are there plans on exposing various callback-based function(s) as Promises/Observables?

### ISSUE THREAD

**Issue by another-guy** [auth0/auth0.js#502]
Many methods in this library like `this._auth0.parseHash((caughtError, authResult) => { ... }`, or `this._auth0.client.userInfo(accessToken, (caughtError, userProfile) => { ... }` are actively using callbacks to deal with asynchronicity. While it works, it's a bit of an old-school with pretty nasty consequences (callback hell, complex code for flow control, etc).

Promises and Observables are pretty common better replacements to callbacks. Do the auth0-js contributors want to migrate the code to use any of these?

**Comment by luisrudge** [comment]
Not in this version, maybe in the next major.

**Comment by another-guy** [comment]
@luisrudge
 Does closing this issue mean I should not even be thinking about creating a pull request for this change?

**Comment by luisrudge** [comment]
Yes, at least not right now. Promisifying the library is super easy and everyone can do that with a few lines of code. Hopefully we'll have fully async/await compatible code in the next major 🙏

**Comment by another-guy** [comment]
@luisrudge  since the timeline for the release of the next version is a big unknown, I tried to write a sketch of a wrapper. Could anyone from the Auth0 team take a very quick look whether I'm going the right way? https://github.com/another-guy/promisify-auth0-js/pull/1

**Comment by luisrudge** [comment]
@another-guy that's pretty cool. Personally, I'd just use something like https://github.com/pensierinmusica/js-promisify so you just have to call that method. You can also copy/paste the important thing and create a helper method: https://github.com/pensierinmusica/js-promisify/blob/master/index.js

**Comment by another-guy** [comment]
@luisrudge  I really appreciate your guidance and the time dedicated to reviewing the code. I wish I worked in a team where peers do know as much as you and do care about details they see in the code. :1st_place_medal: 

I did use a library to promisify the API (`typed-promisify` instead of `js-promisify` since the former one is TypeScript friendly). If you have a moment to glance at the updated PR, I'd be able to close it, and release the package by end of week.

https://github.com/another-guy/promisify-auth0-js/pull/1/files -- **PR**
https://github.com/another-guy/promisify-auth0-js/pull/1/commits/27836a7b9f4df42be7ee46f31f9e2417a51a2311 -- **Commit with `typed-promisify`**

**Comment by luisrudge** [comment]
Hey! Great to read that. We're always hiring: https://auth0.com/jobs
I think the PR is alright now. Thanks for creating the package. 🎉

**Comment by another-guy** [comment]
Okay, I released it. https://www.npmjs.com/package/promisify-auth0
Of course, the wrapper could be build friendlier (now the original js comment docs are not passed-through, and the wrappers have to be constructed manually). But it's at least ready to go. For as long as `auth0.js` is not changing it's public API.

Thanks for helping out!

**Comment by luisrudge** [comment]
We change the public API from time to time. I suggest you keep an eye on our repo and keep up with your repo!

As for the impostor syndrome, we all have. If you don't apply, you'll never know.
