### ISSUE TITLE
Build error with @angular/cli 1.4.2

### ISSUE THREAD

**Issue by smlee** [auth0/auth0.js#504]
In my .angular-cli.json I include auth0.min.js instead of the cdn.
`"scripts": [
        "../node_modules/amplify/lib/amplify.store.min.js",
        "../node_modules/auth0-js/build/auth0.min.js"
      ],`

After the build is successful I get this error:
![image](https://user-images.githubusercontent.com/1771936/30567925-a1d9e7e4-9ca0-11e7-806b-b994f0d17f98.png)

So I added:
`"../node_modules/auth0-js/build/auth0.min.js.map",`
to "scripts" and try to build production I get this error in my terminal:
![image](https://user-images.githubusercontent.com/1771936/30568013-035bf232-9ca1-11e7-8d90-f18992246634.png)

**Comment by luisrudge** [comment]
Sorry, but I don't know what is going on with your build 😞 It's definitely not related to auth0.js though. I don't know how angular works but I'll ping someone that does to see if they can help you. In any case, I think you should ask this in an angular-related forum. Thanks!

**Comment by luisrudge** [comment]
cc @chenkie

**Comment by chenkie** [comment]
@smlee how are you importing auth0.js in your project? is it something like:

```ts
import auth0 from 'auth0-js';
```

**Comment by smlee** [comment]
@chenkie It's not imported using the import syntax. I'm using it the way it is shown at auth0 website.

`  private auth0;

  constructor(
    private router: Router,
    private http: Http
  ) {
    this.auth0 = new auth0.WebAuth({
      domain: environment.domain,
      clientID: environment.client_id,
      redirectUri: `${environment.frontend_url}/authentication`,
      scope: 'email id_token read:current_user profile',
      responseType: 'token id_token'
    });`
