### ISSUE TITLE
renewAuth does not work with 3rd party cookies disabled

### ISSUE THREAD

**Issue by methyl** [auth0/auth0.js#506]
When I disable 3rd party cookies in Chrome, I'm no longer able to use renewAuth silently. It fails as iframe has different domain and no cookies are getting transferred.

Is there any way to mitigate this besides reverse-proxying auth0 to make domains match?

**Comment by luisrudge** [comment]
I'm afraid no. we're working on custom domains for auth0, but, until then, there's no way to fix this.
