### ISSUE TITLE
missing Forgot Password feature

### ISSUE THREAD

**Issue by PatrickJS** [auth0/auth0.js#51]
[![Tipe CMS](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by gdi2290** [comment]
lol 4 years later I ended up landing on my own issue about the same problem

**Comment by luisrudge** [comment]
@gdi2290 I'm glad we have the solution in the same issue
