### ISSUE TITLE
Review Auth0.js snake casing of additional parameters

### ISSUE THREAD

**Issue by aaguiarz** [auth0/auth0.js#513]
The Auth0.js v8 currently performs automatic snake casing of parameters which means that if parameters `param1` and `paramTest` are sent to `/authorize` endpoint they will reach rules context `query` object as `param_1` and `param_test` purely because of the side-effect imposed by Auth0.js and the fact that Auth0.js ends up being used internally within the hosted login page.

This behavior should be reviewed in the next major version as although additional non specification parameters are frowned upon the behavior itself is unexpected and confusing.

The issue itself was originally reported by a user in the community forum and was also previously discussed at: https://auth0.slack.com/archives/C0LQPGPM3/p1504100368000063

**Comment by luisrudge** [comment]
related: https://github.com/auth0/auth0.js/issues/480

**Comment by luisrudge** [comment]
This will come in the next major.
