### ISSUE TITLE
Auth0 API it not instantly synced to Auth0 data

### ISSUE THREAD

**Issue by mmazzarolo** [auth0/auth0.js#515]
Hello there!  
First of all, thank you for all the work you're doing on Auth0.  

I'm writing this issue regarding a [weird problem](https://github.com/mmazzarolo/numvalidate/issues/1) I'm having in [an app](https://github.com/mmazzarolo/numvalidate) where I make heavy use of the Auth0 API/Management API.  
In the app above, after an user signup successfully it is redirected [here](https://github.com/mmazzarolo/numvalidate/blob/master/client/pages/Dashboard.js), and after the page is rendered I make a call to [the Auth0 API](https://github.com/mmazzarolo/numvalidate/blob/master/server/services/auth0.js#L35) which **sometimes** returns a 404.  
The real issue though, is that making the same API call after some seconds returns a 200, meaning that the issue is timing related.  

It basically boils down to a simple question: If an user sign-ups successfully through Auth0, should I be able to access to its informations instantly (by calling `${AUTH0_API_URL}/users?q=user_id="${userId}"`)?  
Is the data we fetch with the Auth0 API synced with the real data on Auth0 server?  

From my testing (and from the user who posted in the linked issue) the answer is **no**: sometimes the user informations do not get propagated instantly to the Auth API (and unfortunately as you may already imagine, this is not that easy to reproduce).  

Let me know if I can help you in any other way. 

Keep up with the good work!

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by luisrudge** [comment]
The search API might take a couple of seconds to update the indexes, but you should use the api to get an user by id directly: https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id

**Comment by mmazzarolo** [comment]
@luisrudge thank you for taking the time for pointing me to the `get_users_by_id` link, I missed it!
