### ISSUE TITLE
renewAuth() example html page review

### ISSUE THREAD

**Issue by iamdanthedev** [auth0/auth0.js#517]
Regarding the callback html page example on https://github.com/auth0/auth0.js#api, when ```usePostMessage == true``` the html may be significantly simplified and no extra libs needed:

```html
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
    parent.postMessage(document.location.hash, document.location.origin);
  </script>
</head>
<body></body>
</html>
```

**Comment by luisrudge** [comment]
Can you send a PR with that change? That would be amazing! Thanks!
