### ISSUE TITLE
renewAuth (checkSession in last version) acquire a new token from Auth0 when using auth0.client.login method

### ISSUE THREAD

**Issue by netshall777** [auth0/auth0.js#520]
Request for new feature.
As soon as "The checkSession method allows you to acquire a new token from Auth0 for a user who is already authenticated against the hosted login page for your domain." would be nice to have possibility to acquire a new token from Auth0 v.8 also for users, that are using auth0.client.login without hosted login page. As it was in v.7 with auth0.refreshToken method.

- [ ] Code snippet or sample project that reproduces the bug

auth0.refreshToken(refresh_token, function (err, delegationResult) {
  // Get here the new delegationResult.id_token
});

- [ ] Auth0.js version
8.10.1

- [ ] Browser & OS
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Ubuntu 16.04 (64-bit)

**Comment by luisrudge** [comment]
It does exactly that.

**Comment by netshall777** [comment]
Can you give example for method auth0.refreshToken for auth0 version 8?

**Comment by netshall777** [comment]
Can you give example for method auth0.refreshToken for auth0 version 8?

**Comment by luisrudge** [comment]
use `checkSession`: https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens

**Comment by netshall777** [comment]
But as described: "The checkSession method allows you to acquire a new token from Auth0 for a user who is already AUTHENTICATED AGAINST THE HOSTED LOGIN PAGE for your domain."
But I'm doing authentication with auth0 method on OUR CUSTOM LOGIN PAGE

**Comment by netshall777** [comment]
But here is written: "The checkSession method allows you to acquire a new token from Auth0 for a user who is already AUTHENTICATED AGAINST HOSTED LOGIN PAGE for your domain."
In our case we are using our CUSTOM LOGIN PAGE and auth0 method
auth0.client.login({
      realm: 'REALM-NAME',
      username: "some-username",
      password: "some-password",
    }, () => {some CB function}).
The question: Is it possible to use checkSession if user sign in with CUSTOM LOGIN PAGE and auth0 method auth0.client.login()?

**Comment by luisrudge** [comment]
`client.login` is the only method that won't work, because `oauth/token` doesn't save a session on auth0's server. You should use just `auth0.login`, then `checkSession` will work.
Keep in mind that you have to enable Cross Origin Authentication for this method to work. https://auth0.com/docs/cross-origin-authentication

**Comment by netshall777** [comment]
Can not find auth0.login method in documentation. What params should it receive?

**Comment by netshall777** [comment]
Can not find auth0.login method in documentation. What params should it receive?
It is executing redirect to redirectUrl with tokens as params in hash. So I should use parseHash method to grab tokens. AND for this case JsonWebToken Signature Algorithm should be RS256. With HS256 doesn't work. Right?

**Comment by luisrudge** [comment]
http://auth0.github.io/auth0.js/global.html#login
look at the second `login` method. We're still adding docs about this in auth0.com/docs

**Comment by netshall777** [comment]
changed app to work with auth0.login(). setup server on http://localhost:3000

**Comment by netshall777** [comment]
changed app to work with auth0.login(). login() works as expected. 
but still can not refresh tokens in silent authentication with this.auth0.checkSession({
      audience: 'my_audience',
      redirectUri: 'http://localhost:3000/silent',
      usePostMessage: true
    }, CB);
setup server on http://localhost:3000
angular 4 app works on https://https://localhost:4000
get error 400 in console. 
auth0 log says: "The specified redirect_uri 'http://localhost:3000/silent' does not have a registered origin."
http://localhost:3000/silent is in Allowed Callback URLs & in Allowed Web Origins within auth0 Client.
When I just open static page "silent" in browser I get: "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://localhost:4000') does not match the recipient window's origin ('http://localhost:3000')."
Browsers: Chrome 62.0.3202.62 (64-bit) or FF 56.0 (64-bit)
OS: Ubuntu 16.04 (64-bit)

**Comment by luisrudge** [comment]
you should put http://localhost:3000 in the Allowed Web Origins field

**Comment by netshall777** [comment]
Thank you for fast reply.
Now I get in auth0 logs: "Type: Failed Silent Auth; Description: Consent required"
And in Angular 4 app console: "Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘http://localhost:3000’) does not match the recipient window’s origin (‘https://localhost:4000’)."
No network errors.

**Comment by luisrudge** [comment]
That's probably because the user is not logged in yet, so you can't renew the tokens. You have to call authorize first. 

There's a nice angular quick start here: https://auth0.com/docs/quickstart/spa/angular2/01-login
We'll be adding the `checkSession` to the quick starts, in the mean time, you can forget the part about token renewal. Just use `checkSession` instead of renewToken and you'll be fine.

**Comment by netshall777** [comment]
exactly, I'm using checkSession. Here's angular 4 function:
renewToken() {
    this.auth0.checkSession({
      audience: 'my_audience',
      redirectUri: 'http://localhost:3000/silent',
      usePostMessage: true
    }, (err, result) => {
      if (err) {
        console.log(err);
        alert(`Could not get a new token using silent authentication (${err.error}).`);
      } else {
        console.log(result);
        alert(`Successfully renewed auth!`);
        this.setSession(result);
      }
    });
  }
User is already logged in and inside the app when I call this function, because I'm calling it (for testing purposes only) with button inside the app.

**Comment by luisrudge** [comment]
I don't know what's goin on. Please provide a repro project with clear instructions on how to reproduce the problem so I can look at.

**Comment by netshall777** [comment]
ok. I'll prepare

**Comment by alobban** [comment]
Any update on this?
I am receiving 400 error

**Comment by luisrudge** [comment]
what's the error?

**Comment by alobban** [comment]
This is what the error translates to when I open it in the browser:

**Comment by luisrudge** [comment]
please click in the "show error" link on the bottom left.

**Comment by alobban** [comment]
invalid_request: The specified redirect_uri 'http://localhost:3002/auth/silent-callback' does not have a registered origin.

**Comment by luisrudge** [comment]
Please follow the docs on how to use `checkSession`: https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens

You have to setup the Allowed Web Origins in the dashboard with your website's origin, in this case `http://localhost:3002`.

**Comment by alobban** [comment]
Is there something specific I am missing? I followed those instructions and everything is already setup

**Comment by luisrudge** [comment]
It should work. Can you post a code snippet so I can test it locally?

**Comment by alobban** [comment]
You're correct! It works!, I place in the Allowed Web Origins **http://localhost:3002/auth/silent-callback** instead of **http://localhost:3002**

**Comment by luisrudge** [comment]
coooool 🎉

**Comment by alobban** [comment]
Wait, why can't I access my public methods in the callback of the checkSession method? Says cannot read property 'clearOldNonces' of undefined

**Comment by luisrudge** [comment]
http://ryanmorr.com/understanding-scope-and-context-in-javascript/

**Comment by alobban** [comment]
public checkSessionStatus(): void {
      this.auth0.checkSession({
        audience: 'https://afn.auth0.com/api/v2/',
        scope: 'read:order write:order',
        redirectUri: `${this.host}auth/silent-callback`,
        usePostMessage: true
      }, function (err, authResult) {
        if (authResult && authResult.accessToken && authResult.idToken) {
          // window.location.hash = '';
          this.clearOldNonces();
          this.setSession(authResult);
        } else if (err) {
          console.log(err);
        }
      });
    }

**Comment by alobban** [comment]
@luisrudge I had to update the Auth0 code to use the arrow function in order to preserve scope. Anyway, I have another issue.
