### ISSUE TITLE
responseMode 'query' not working

### ISSUE THREAD

**Issue by davidthor** [auth0/auth0.js#526]
I've run into the same issue described in https://github.com/auth0/auth0.js/issues/479#issuecomment-319903112, and wasn't sure why the issue was closed as the problem is still active as of today. I'm trying to use [Nuxt](https://nuxtjs.org/) to build an isomorphic application and cannot leverage the parseHash() method server side for pre-rendering since the hash info is intentionally ignored by the server. 

The documentation for the library clearly indicates the availability of a "query" option for the `responseMode` option, and the field also seems to be part of the OpenID spec directly. Using this option however consistently yields an issue with the Auth0 service and the error page linked below is shown. It's also worth noting that this error page is a result of the callback flow reaching a URL hosted at login.auth0.com instead of my own callback URL. Full URL structure is below:

```
https://login.auth0.com/login/callback?state=......
```

[Screenshot of auth0 error page](https://imgur.com/a/GchGy)

```js
const auth = new auth0.WebAuth({
  domain: process.env.AUTH0_DOMAIN,
  clientID: process.env.AUTH0_CLIENT_ID,
  redirectUri: `http://${process.env.HOST}:${process.env.PORT}${process.env.AUTH0_REDIRECT_URI}`,
  audience: `https://${process.env.AUTH0_DOMAIN}/userinfo`,
  responseType: 'token id_token',
  responseMode: 'query',
  scope: 'openid profile email'
});

auth.authorize();
```

**Comment by luisrudge** [comment]
I can't see your screenshot. Can you upload it again?

**Comment by davidthor** [comment]
@luisrudge just updated the comment formatting to expect the proper link. Sorry about that.

**Comment by luisrudge** [comment]
can you click the "see details" and paste the content, please?

**Comment by davidthor** [comment]
A yellow box appears with the text, "unsupported_response_mode: Unsupported response mode: query". Not sure why I didn't see that link before, so thank you.

**Comment by luisrudge** [comment]
Yup. I just confirmed with the backend team and that's indeed the case. responseMode=query is only supported for the code grant flow (responseType=code). I'm updating docs and readme to reflect that:
https://github.com/auth0/auth0.js/pull/527
https://github.com/auth0/docs/pull/5187

If you want to read more about the different flows, you can read this article which is very helpful: https://auth0.com/docs/api-auth/which-oauth-flow-to-use
