### ISSUE TITLE
Request: expose auth0.WebAuth as a separate module

### ISSUE THREAD

**Issue by blakew** [auth0/auth0.js#534]
I would like to use the Authentication library without having node or the browser client. However this doesn't work since I get the following error:

```
TypeError: Cannot read property 'indexOf' of undefined
      
      at isInternetExplorer (node_modules/winchan/winchan.js:32:6)
      at node_modules/winchan/winchan.js:85:10
      at Object.<anonymous> (node_modules/winchan/winchan.js:309:2)
      at Object.<anonymous> (node_modules/auth0-js/src/web-auth/popup.js:2:13)
```

If I comment out WebAuth from index.js, I get what I want.

Not sure how often this has been requested but for me, it would be great if the WebAuth or Authentication module were a separate library.

**Comment by luisrudge** [comment]
auth0.js is a browser sdk. as such, it requires a browser. everything inside auth0-js is meant to be used from a browser.

**Comment by luisrudge** [comment]
if you're not using from node or a browser, where are you running it?

**Comment by blakew** [comment]
Mobile with react-native. Testing with jest

**Comment by luisrudge** [comment]
Cool, you should take a look at https://github.com/auth0/react-native-auth0

**Comment by blakew** [comment]
I see, thanks man ... 

It seems like there isn't a way to create a platform-agnostic REST client that can use the auth0 libraries that make calls to the auth0 endpoints. And aside from WebAuth modules, there's no functional difference between the 2 libraries. Do I have that right?

I'm developing and testing my API such that both the client and server code can be reused outside of react-native and my current DB choice. Of course I'd rather use auth0-supported client libraries than roll my own HTTP requests.

**Comment by luisrudge** [comment]
The two platforms (browser/native) are completely different. There is no way you can share the same code between the two platforms when using authentication in a secure way.
