### ISSUE TITLE
When logging in with Username and Password and not using `/ro` and there's an error, redirect should be used

### ISSUE THREAD

**Issue by mgonto** [auth0/auth0.js#54]
When you send a callback to `auth0.js` with less or equal than 1 parameter (just the error), redirect mode is used to log the user in.

However, when there's an error logging the user in, instead of actually doing a redirect as well and returning the error there, it's returning the error after the requests finishes which is not consistent.

This brings some consistency errors like https://github.com/auth0/auth0-angular/issues/118

**Comment by cristiandouce** [comment]
Related to auth0/auth0.js/issues/26

**Comment by arcseldon** [comment]
Update on progress please?

**Comment by gnandretta** [comment]
@arcseldon the team has plans to do a whole review of the library once we release the next version of lock.

**Comment by arcseldon** [comment]
@gnandretta - thanks for update.
