### ISSUE TITLE
Passing nested objects does not work as expected when calling authorize endpoint/hosted pages  

### ISSUE THREAD

**Issue by johnlim** [auth0/auth0.js#541]
Hi,

- Auth0.js version - v8.10.1
- Browser & OS - Chrome/Mac OS

I'm calling the `authorize` endpoint as follows:
```
this.auth0.authorize({
  scope: 'openid',
  redirectUri: window.location.origin,
  responseType: 'token',
  params: {
   accessType: 'offline',
   approval_prompt: 'force',
 }
})
```
In the network requests, I can see
```
https://myAuth0Tenant/authorize?client_id=xxxx&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=token&params%5Baccess_type%5D=offline&params%5Bapproval_prompt%5D=force&state=FhEXIZ12DMTkigjcrZZ.K0vfs~CF53rB&auth0Client=xxxxxxIjoiOC45LjMifQ%3D%3D
```
which shows that the `params` object is encoded correctly in the params list as ```params[accessType]=offline and params[approvalPrompt]=force``` . 

However, in hosted pages (which is triggered by the call to the authorize endpoint), the config returned by @@config@@, is as follows 
``` 
....
extraParams: {
  auth0Client: "xxxxx"
  params:""
  protocol:"oauth2"
  response_type:"token"
  scope: "openid"
  state:"xxxxxx"
}
``` 
which shows `params` as an empty string. 

Somehow, the @@config@@ object in hosted pages drops the nested object, `params {accessType: offline, approvalPrompt: force}`.
Is this a bug with the authorize endpoint or an issue within hosted pages?
I need the params object so that I can pass it into Auth0 Lock which is used in my hosted pages, which requires the `accessType` and `approvalPrompt` to be nested inside a params object.
I could simply flatten my the parameter list when calling the authorize endpoint and then re-construct it inside hosted pages but I'd prefer if the interface (i.e options object) is consistent with Lock and the authorize endpoint. 

Is this something that you guys would consider fixing? Thanks.

Regards,
John

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK itself, since we're sending the parameters correctly. It's more the hosted login page not behaving the way you need. Please reach out to our amazing support team at https://support.auth0.com so they can get in touch with the appropriate team. If this is not currently supported, then they can create a feature request. If it's a bug, they will ping the correct team to fix it.
