### ISSUE TITLE
Social Connections not returning all json

### ISSUE THREAD

**Issue by matthewcocker** [auth0/auth0.js#542]
What do I need to add to 'scope' to get all of the json from a twitter connection?

**Comment by luisrudge** [comment]
It actually depends. You can try with `openid profile email`. This should bring pretty much everything. To read more about claims and scopes, read: https://auth0.com/docs/scopes/current

**Comment by matthewcocker** [comment]
Using scope 'openid profile email' returns this

```
array(5) {
  ["sub"]=>
  string(17) "twitter|#######"
  ["nickname"]=>
  string(2) "MC"
  ["name"]=>
  string(2) "MC"
  ["picture"]=>
  string(75) "https://pbs.twimg.com/profile_images/####.jpg"
  ["updated_at"]=>
  string(24) "2017-11-02T19:20:06.920Z"
}
```

Not 

  {
    "name": "##",
    "picture": "##",
    "description": "##.",
    "lang": "en",
    "location": "England, United Kingdom",
    "screen_name": "##",
    "time_zone": "##",
    "url": "##",
    "updated_at": "2017-11-02T19:03:50.069Z",
    "user_id": "twitter|####",
    "nickname": "MC",
    "identities": [
        {
            "provider": "twitter",
            "user_id": "####",
            "connection": "twitter",
            "isSocial": true
        }
    ],
    "created_at": "2017-11-02T15:36:31.381Z",
    "last_ip": "###",
    "last_login": "2017-11-02T19:03:50.068Z",
    "logins_count": 30,
    "blocked_for": [],
    "guardian_enrollments": []
}

Have I missed a step somewhere?

**Comment by luisrudge** [comment]
where are you getting the second json from?

**Comment by matthewcocker** [comment]
I'm trying to migrate from Auth0.js v7 to V8, thats the data I used to received and is also shown in User Details panel in the Auth0 dashboard

**Comment by luisrudge** [comment]
what are you calling with v7 and v8? can you share both methods?

**Comment by matthewcocker** [comment]
V7

```
<script src="https://cdn.auth0.com/w2/auth0-7.1.min.js"></script>
<script>
  var auth0 = new Auth0({
    domain:         '#####.eu.auth0.com',
    clientID:       '#####',
    callbackURL:   'https://####.herokuapp.com/callback',
  });
  $('.signin-twitter').on('click', function() {
    auth0.signin({connection: 'twitter'});
  });
</script>
```

V8
```
<script src="https://cdn.auth0.com/js/auth0/8.10.1/auth0.min.js"></script>
<script>
  var webAuth = new auth0.WebAuth({
    domain:         '#####.eu.auth0.com',
    clientID:       '#####',
    redirectUri:    'https://####.herokuapp.com/callback',
    scope:          'openid profile email',
    responseType:   'code'
  });
  $('.signin-twitter').on('click', function() {
    webAuth.authorize({connection: 'twitter'});
  });
</script>
```

**Comment by luisrudge** [comment]
can you check the differences between the requests? both should hit the `/authorize` endpoint, but they clearly have some different parameters.
