### ISSUE TITLE
There was an error processing the login

### ISSUE THREAD

**Issue by iDVB** [auth0/auth0.js#546]
Chrome 61.0.3163.100
lock-9.0.min.js

Newb to Auth0. I've got this example app setup on AWS https://github.com/serverless/examples/tree/master/aws-node-auth0-custom-authorizers-api

However, I seem to only have things half setup/working. The Lock button when clicked does display the embedded lock popup. You can then login with google.... or signup for a new account. However, when things attempt to redirect... I get the error `There was an error processing the login.`
![Error processing](https://content.screencast.com/users/dvanbrunt/folders/Snagit/media/57adb8e8-8202-4c14-b718-d39f0ecd4651/2017-11-03_17-34-59.png)

However, I don't see any errors in the auth0 logs...
![Users](https://content.screencast.com/users/dvanbrunt/folders/Snagit/media/bedfa922-8fd2-4016-9590-582d990d31ca/2017-11-03_17-40-40.png)

and I DO see a valid user created in auth0...
![Users](https://content.screencast.com/users/dvanbrunt/folders/Snagit/media/e0ad5f9c-ae1c-42d7-a99d-2c16bee65fc4/2017-11-03_17-37-45.png)

**Comment by luisrudge** [comment]
Hi, sorry you found an outdated example of Auth0 in the wild. I'm not sure who maintains those examples, so I'm afraid I can't help you with this particular example. We have a dedicated org that we maintain examples, please check out: https://github.com/auth0-samples/

**Comment by AmalAbdullaev** [comment]
HI,how did you solve this problem??

**Comment by kriefsacha** [comment]
Also want to know if someone resolved it .. @AmalAbdullaev  @iDVB
