### ISSUE TITLE
 How do I change the logo using auth0.js? 

### ISSUE THREAD

**Issue by gofreddo** [auth0/auth0.js#550]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ x] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

How do I change the logo using auth0.js?  The only samples I can find are for auth0-lock.  https://auth0.com/docs/libraries/lock/v10/ui-customization

**Comment by luisrudge** [comment]
auth0.js itself has no logos, so I'm not sure what you're talking about. If you're talking about the hosted login page, then go [here](https://auth0.com/docs/hosted-pages/login). If you're talking about Lock, then go [here](https://auth0.com/docs/libraries/lock/v10/ui-customization)
