### ISSUE TITLE
Where is the Changelog for 8.11.1 ?

### ISSUE THREAD

**Issue by GautierT** [auth0/auth0.js#559]
Hi,
Where can i find the changelog for 8.11.1 ? The file changelog.md doesn't talk about this version.

I'm looking for it because since the update i have an error : `'state' does not match.`

Thanks

**Comment by luisrudge** [comment]
The changelog is in the v8 branch. 8.11.1 was just a patch fix. You can check the 8.11.0 changelog here: https://github.com/auth0/auth0.js/blob/v8/CHANGELOG.md#change-log-1

Can you provide more info about the error you're getting? Provide a code snippet so I can try to reproduce it etc.

**Comment by GautierT** [comment]
Okay. Thanks @luisrudge. 
I don't really have the time these days... Sorry.
I will stick on 8.10.1 for now. Must be related to this pull : https://github.com/auth0/auth0.js/pull/548

**Comment by GautierT** [comment]
i dispatch a function like this : 

`    this.props.dispatch(fetchLogin('database', this.state_params, this.state.email, this.state.password, this.state.signup))` 

`this.state_params` contains things like name or promo code


fetchLogin : 
```
export function fetchLogin (type = 'database', state, username, password, signup = false) {
  return dispatch => {
    dispatch(login())
    state = JSON.stringify(state)

    if (type === 'database') {
      if (signup) {
        authService.signup(username, password, state)
          .then(() => {
            return dispatch(loginSuccess())
          })
          .catch((err) => {
            return dispatch(loginFailure(err))
          })
      }
      else {
        authService.login(username, password, state)
          .then(() => {
            return dispatch(loginSuccess())
          })
          .catch((err) => {
            return dispatch(loginFailure(err))
          })
      }
    }
    else if (type === 'facebook') {
      authService.loginWithFacebook(state)
    }
    else if (type === 'github') {
      authService.loginWithGithub(state)
    }

  }

}
```

And authService is a class.
the login function is like this : 
```
	login (username, password, state) {
		return new Promise((resolve, reject) => {
			this.auth0.redirect.loginWithCredentials({
				connection: 'Username-Password-Authentication',
				username,
				password,
				state,
				scope: 'app_metadata'
			}, err => {
				if (err) {
					debug('login error : ', err)
					reject(err)
				}
				resolve()
			})
		})
	}
```

Hope it helps

**Comment by GautierT** [comment]
in my AuthService i instantiate auth0 in the constructor like this : 
```
		this.auth0 = new auth0.WebAuth({
			clientID: clientId,
			domain: domain,
			responseType: 'token id_token',
			redirectUri: redirectUrl
		})
```

I'm on React 16.1 btw

**Comment by luisrudge** [comment]
Thanks. I'll release a patch fix shortly. The fix is here: https://github.com/auth0/auth0.js/pull/560

**Comment by luisrudge** [comment]
I'll let you know when the new version is released

**Comment by GautierT** [comment]
Awesome. Thanks for this quick fix.

**Comment by luisrudge** [comment]
`8.11.2` was just released. Can you test it and see if it fixes your issue? Thanks!

**Comment by GautierT** [comment]
Yes. It fixes the issue. 
Thanks a lot.

**Comment by luisrudge** [comment]
Awesome. Thanks for the feedback!
