### ISSUE TITLE
parseHash is not taking into account the options.state anymore

### ISSUE THREAD

**Issue by damien-gl** [auth0/auth0.js#562]
Since latest `auth0-js` release (8.11.x) there is a breaking change preventing us to login into our application because apparently `parseHash` is not taking into account the `options.state` anymore (we are not using the transaction manager of `auth0-js`).

Proposed PR to fix this: https://github.com/auth0/auth0.js/pull/561

**Comment by luisrudge** [comment]
Let's discuss in the PR
