### ISSUE TITLE
Breaking change with `web_message` in v8.11.3

### ISSUE THREAD

**Issue by csvn** [auth0/auth0.js#565]
Hello,

After upgrading from `v8.11.2` to `v8.11.3` of `auth0-js`, our login flow breaks. When looking into it, I tried out starting our app and only switching back and forth between the versions. I noticed that the `/authorize` calls were slightly different:

```
# Some random values trimmed to 'xxx' for both requests below

# v8.11.3 - Reponse 400, with the "Ooops, something went wrong.". No additional info.
https://apptus-dev.eu.auth0.com/authorize?client_id=xxx&response_type=id_token%20token&response_mode=web_message&audience=https%3A%2F%2Fesales.apptus.com%2F&scope=openid%20organizations%20o1000&state=xxx&nonce=xxx&prompt=none&auth0Client=xxx

# v8.11.2 - Reponse 200
https://apptus-dev.eu.auth0.com/authorize?client_id=xxx&response_type=id_token%20token&response_mode=fragment&audience=https%3A%2F%2Fesales.apptus.com%2F&scope=openid%20organizations%20o1000&redirect_uri=http%3A%2F%2Flocalhost%3A35361%2Frenew.html&state=xxx&nonce=xxx&prompt=none&auth0Client=xxxx
```

Without changes in our code, `v8.11.3` seems to send `response_mode=web_message` instead of `response_mode=fragment`, and removes the `redirect_uri` param. The relevant code that triggers the `/authorize` endpoints above looks like this:

```ts
class Auth0Service {
  constructor(private env: EnvConfig) {
    this.web = new a0.WebAuth({
      domain: env.auth0Domain, // string
      clientID: env.auth0ClientId, // string
      leeway: 10,
      audience: 'https://esales.apptus.com/',
      responseType: 'id_token token',
      responseMode: 'fragment'
    });
  }

  renewAuth(scope: string) {
    this.web.renewAuth({
      scope, redirectUri // string
    }, cb);
  }
}

// ...

auth0.renewAuth('...');
```

I looked up [the changes between the versions](https://github.com/auth0/auth0.js/compare/v8.11.2...v8.11.3) and could not figure out how this was the result.

I tried if we could use `WebAuth.checkSession()` method instead, but it has the same `400` error. Is the `response_type=web_message` not available for `eu` tenants yet?

For now, I guess I will have to pin the version to `v8.11.2` to avoid breaking changes.

Let me know if you need any additional info

--------------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [x] Auth0.js version
`v8.11.3`
- [x] Browser & OS
Chrome / Windows

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by luisrudge** [comment]
Hi, web_message is disabled by default because you have to setup that in your dashboard. But `renewAuth` doesn't use web_message at all. In version 8.x, only `checkSession` uses web_message. Can you check where in your code are you calling checkSession?

**Comment by csvn** [comment]
That's the thing, we have no calls at all that use `checkSession`, only `renewAuth` is used. But doing the small patch version bump, with no other changes, it breaks the login flow of our app.

I'll provide the full file if it might help. This is the only file that imports `auth0-js`. The class is registered to Angular as a provider. The `web` property is private, and is not accessed from any other place.

```ts
import * as a0 from 'auth0-js';
import { Injectable } from '@angular/core';
import { nodeback } from '@apptus/util'; // utility for node-style-callback => promise
import { EnvConfig } from '../config/index';


/** Wrapper around `auth0-js`, with configuration and promise-based API */
@Injectable()
export class Auth0Service {
  private web: a0.WebAuth;

  constructor(private env: EnvConfig) {
    this.web = new a0.WebAuth({
      domain: env.auth0Domain,
      clientID: env.auth0ClientId,
      leeway: 10,
      audience: 'https://esales.apptus.com/',
      responseType: 'id_token token',
      responseMode: 'fragment'
    });
  }

  private get location() {
    return window.location;
  }

  private get origin() {
    return this.location.origin;
  }

  /**
   * Reject if there's no auth info to parse, resolve with
   * auth result if success, otherwise `null`
   */
  parseHash() {
    return nodeback<a0.Auth0DecodedHash>(cb => this.web.parseHash({}, cb))
      .then(res => {
        if (res) {
          return res;
        }
        throw new Error('No Auth0 credentials in hash!');
      }, err => {
        throw err;
      });
  }

  userProfile(userId: string, idToken: string) {
    return nodeback<a0.Auth0UserProfile>(cb => this.management(idToken).getUser(userId, cb));
  }

  patchUserMetadata(userId: string, metadata: object, idToken: string) {
    return nodeback<a0.Auth0UserProfile>(cb => {
      this.management(idToken).patchUserMetadata(userId, metadata, cb);
    });
  }

  /** Performs "Silent authentication", which is the standard redirect flow inside iframe */
  renewAuth(orgScope?: string) {
    const options = {
      scope: getScope(orgScope),
      redirectUri: `${this.origin}/renew.html`
    };

    return nodeback<auth0.Auth0DecodedHash>(cb => this.web.renewAuth(options, cb));
  }

  /** Redirects to Auth0 /authorize endpoint for Authentication & Authorization */
  authorize() {
    this.web.authorize({
      scope: getScope(),
      redirectUri: this.origin
    } as any);
  }

  /** Redirects to Auth0 SSO /logout endpoint */
  logout() {
    this.web.logout({
      returnTo: this.origin
    });
  }

  private management(idToken: string) {
    return new a0.Management({ domain: this.env.auth0Domain, token: idToken });
  }
}


function getScope(organizationScope = 'defaultOrganization') {
  return `openid organizations ${organizationScope}`.trim();
}
```

*(We are aware that `id_token` should be avoided, but we need to implement backend support for `app_metadata`(read)/`user_metadata`(read/write) operations. The `/userinfo` endpoint does not support any of these fields.)*

**Comment by luisrudge** [comment]
Can you post the snippet of your renew.html page?

**Comment by csvn** [comment]
Sure.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="icon" type="image/x-icon" href="https://cdn.esales.apptus.com/assets/images/favicon.ico">
  <title>Apptus eSales</title>
</head>
<body></body>
</html>
```

We had issues when using `postMessage` where `auth0-js` accidentally got webpack-dev-server messages when using Angular in dev mode. But the hash-parse method has worked in previous versions without issues due to same origin with the iframe.

**Comment by csvn** [comment]
Just a small gif showing what happens when we upgrade from 8.11.2 => 8.11.3. I tried removing some of the (even more) tedious ports such as install/bundling. Due to the script failing get hold of tokens, user is redirected to login again, cue endless login loop.

![auth0-js-login-issue](https://user-images.githubusercontent.com/8770194/32916687-2d5aa362-cb1d-11e7-9a28-ee63ce66e24c.gif)

**Comment by luisrudge** [comment]
Did you customize your hosted login page?

**Comment by csvn** [comment]
Yes, we have added logo, primary color, set `allowSignUp` to false, and added a tiny bit of styling to the background.

**Comment by luisrudge** [comment]
What lock version are you using in the hosted login page?

**Comment by csvn** [comment]
`https://cdn.auth0.com/js/lock/10.11/lock.min.js` seems to be.

**Comment by csvn** [comment]
I tried switching to `default template` to compare. Seems `responseType` has changed slightly:

```js
// Our current settings
auth: {
  responseType: config.callbackOnLocationHash ? 'token' : 'code',
  
  // ...
}

// Default
auth: {
  responseType: (config.internalOptions || {}).response_type ||
          config.callbackOnLocationHash ? 'token' : 'code'
  // ...
}
```

Could this be the culprit? I did not consider it since I thought `promt: false` used server redirects, so that the `400` response could not come from the hosted login page.

**Comment by luisrudge** [comment]
Alright, this is pretty weird.  [This](https://github.com/auth0/auth0.js/commit/2d7243d2675dbc5070305fe9236af5daebf8fbfd) is the change that went in the 8.11.3 release. I can't see why this would make your requests use web_message instead. Also, in our [example page](https://github.com/auth0/auth0.js/blob/master/example/index.html), this doesn't happen at all.

Can you create a repro project without angular and everything and see if you get the same problem? You can use [this page](https://github.com/auth0/auth0.js/blob/master/example/index.html) as a starting point if you want. I tested with this page and the renewAuth method works as expected, which makes me think it's a combination of factors with your app and the hosted login page.

**Comment by luisrudge** [comment]
This new config doesn't change much, unless it's changing the responseMode, which I don't think it is.

**Comment by csvn** [comment]
I agree. I don't understand either. It encountered it randomly when I reinstalled `node_modules`. I'll try to see if I can reproduce it a little later. Thanks a lot for looking into it!

**Comment by csvn** [comment]
@luisrudge Hi again, sorry it took a bit of time for me to get back to this.

First off, this issue does not affect all browsers. As far as I have seen, this issue does not occur on Firefox in Windows 10/Linux, but it does occur in Chrome for W10/Linux.

I looked a bit more at the error we received, and it seems that the `renewAuth()` can return `null null` in Chrome. This breaks the login for our apps since it's expected to receive an `err` or `data`. A reproduction with steps is here: https://github.com/csvn/auth0-error

I believe that the `iframe.src` change may cause a timing issue that affects Chrome.

Since some other stuff has changed, I can't really reproduce the other stuff I mentioned. I think this is the root cause of our issues though. Let me know if if you need anything else or still can't reproduce the issue.

**Comment by luisrudge** [comment]
Hi @csvn. Apparently there’s a browser inconsistency about when to add the `src` attribute to an iframe. In an attempt to fix an issue that chrome wasn't handling the `iframe.src` correctly, we merged https://github.com/auth0/auth0.js/pull/563 to fix it. I'm truly sorry that I didn't check the same method specifically with `usePostMessage: false`. All our docs and examples have this set to `true` and it didn't cross my mind to test it. Again, I'm sorry and this is my fault.

Moving forward, our docs are starting to point customers to use `checkSession` because it's simpler to setup and also less error prone for both the developer and with browsers.

The fix to this problem would be to assign the `iframe.src` twice (so it satisfies both chrome and other browsers), but this is a terrible hack and something we are not keen on implementing and maintaining.

I think the best way forward is for you to start using `postMessage` like our docs suggested, or migrate to `checkSession` so this won't be an issue anymore. I can help you with whatever you decide.

**Comment by luisrudge** [comment]
I'm closing the issue because it's not a problem with `web_message` itself, but I'll help you use `postMessage` or `checkSession`.

**Comment by csvn** [comment]
We plan on starting to use `checkSession` and `web_message` soon, as it seems simpler to use. All it takes is setting `Allowed Web Origins` in the client, and then switching to `checkSession`, right? Until then we can stick to `v8.11.2`. I reported this issue mostly due to it being a breaking change for us.

When I implemented this, I started out trying the `postMessage` flow, but this did not work well with Angular (since ng-cli use `webpack-dev-server`). `auth0-js` incorrectly used the `postMessage` that came from the webpack dev server, which made the `renewAuth` fail every time. When we tried `usePostMessage: false`, it just worked, so I did not open a issue for this.

**Comment by luisrudge** [comment]
Yeah, using web_message is super simple. If you want to use `usePostMessage:true`, all you need to do is follow the changes in this PR: https://github.com/auth0-samples/auth0-react-samples/pull/44/files
You can now filter the postMessage data type using the `postMessageDataType` option. 
Thanks for understanding the situation. If you need help migrating to checkSession, let us know! 🎉

**Comment by csvn** [comment]
@luisrudge Nice, thanks for your help!
