### ISSUE TITLE
Check Session can only be used on one api at a time

### ISSUE THREAD

**Issue by NiallArkEnergy** [auth0/auth0.js#567]
I am using auth0-js 9.0.0-beta.5. In Chrome, Firefox and IE11. My application needs to access 3 apis. So after logging in with the hosted page I need to make a request to the authorize endpoint. I do this using checkSession. The problem seems to be that each call to checkSession listens to the same postMessage. So the first iframe wins and the other two get {"error":"invalid_token","errorDescription":"`state` does not match."}

**Comment by luisrudge** [comment]
Sorry, I missed your comment in the PR. Let's discuss there.
