### ISSUE TITLE
Callback error Safari and Chrome "invalid_token" CORS error 

### ISSUE THREAD

**Issue by amoldavsky** [auth0/auth0.js#568]
<img width="1109" alt="screen shot 2017-11-18 at 15 26 08" src="https://user-images.githubusercontent.com/12831000/32984455-fb33e656-cc74-11e7-8c0c-10bc6cc15eb6.png">

I have started the discussion in the following issue, so there is some preliminary info there:
https://github.com/auth0/auth0.js/issues/540#event-1345275619

Steps:
1. goto http://cc.donr.io/
2. when redirected to auth0 login enter demo@donr.io / testing123
3. when back on the callback page you will get an error
```
{error: "invalid_token", errorDescription: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc." }
```

Result

This results in either at least another trip back to the login page but sometimes gets into continuous redirect loop back to login page.

Happens intermittently in Chrome and Safari.
OS
- macOS Sierra 10.12.6

Browsers
- Chrome Version 62.0.3202.89 (Official Build) (64-bit)
- Safari Version 11.0.1 (12604.3.5.1.1)

Auth0.js versions
- 9.0.0-beta.5
- 8.11.3

Debugging info and HAR files below

**Comment by amoldavsky** [comment]
Chrome HAR files:
[chrome-auth0-har.zip](https://github.com/auth0/auth0.js/files/1484998/chrome-auth0-har.zip)

**Comment by amoldavsky** [comment]
I am not quire sure where and why the CORS issue is happening.... I am using `WebAuth`, perhaps some misconfiguration on my end?

**Comment by luisrudge** [comment]
@amoldavsky are you still using the jwks hack? Can you paste a snippet of code on how you're using WebAuth?

**Comment by amoldavsky** [comment]
no hacks, all the hacks were just for local testing, since I modify the code directly `node_modules` once i `npm install` it is all gone. Perhaps a bit of a hacky way to test things but works well at times.

In the URL I provided in the `steps` you should be able to see the flow. Here are some snippets...

app.component.ts:
```

**Comment by amoldavsky** [comment]
Not doing anything unusual here really, let me know if you need more snippets.

**Comment by luisrudge** [comment]
Yeah. Seems pretty standard. I can't say what's happening either. Does it happen with one of our quickstarts if you use it your client? If yes, can you point me to it?

**Comment by amoldavsky** [comment]
mmm good idea, let me take one of the quickstart reops and put in my settings, will keep you posted

**Comment by amoldavsky** [comment]
ok, so that little test off of the main repo led me to the issue which led me to the solution....
I forked your repo here https://github.com/amoldavsky/auth0.js and i deployed it to Heroku to serve te `/example` dir. Than I pointed it to my instance and gave it my configs. Well, it worked!

So than when i went again through the source i realized what was wrong, I was not waiting for the fetch of the jwks. In my original code, the initial snippet which i got form some web example, didn't wait for the respone of `handleAuthentication`.

Changing the service method to:
```
public handleAuthentication(): any {
    return new Promise( (resolve, reject) => {
      this.auth0.parseHash((err, authResult) => {
        if (authResult && authResult.accessToken && authResult.idToken) {
          window.location.hash = '';
          this.setSession( authResult );
          return resolve();
        } else if (err) {
          alert(`Error: ${err.error}. Check the console for further details.`);
          return reject();
        }
        return reject();
      });
    })
  }
```

and the consumer to this:
```
ngOnInit(): void {
    this.analytics.trackPageViews();
    this.authSsrvice.handleAuthentication()
      .catch( () => {
        if ( !this.authSsrvice.isAuthenticated() ) {
          this.authSsrvice.login();
        }
      })
  }
```

everything works, no errors so far.

**Comment by amoldavsky** [comment]
@luisrudge my friend, I am sorry for burning your time! and more sorry for burn ing mine on a silly issue.

Well at least I went through your source three times, know it pretty well now  👍

**Comment by luisrudge** [comment]
No problem. I'm glad you found the solution. Thanks for sharing it here as well 🎉

**Comment by s-pace** [comment]
We had a similar issue on chrome. It comes from an extension `Privacy Badger`.

You can try it in incognito mode to check if it comes from your extensions.
