### ISSUE TITLE
unsafe access to window.localStorage

### ISSUE THREAD

**Issue by AVVS** [auth0/auth0.js#570]
https://github.com/auth0/auth0.js/blob/v8/src/helper/storage/handler.js#L8

Based on the browser settings simply accessing localStorage property would throw a SecurityError and hence kill the whole app. Please do not access it like that at all.

I'd suggest using https://github.com/localForage/localForage to work with storage, to determine availability of drivers and ultimately provide some meaningful errors to end users if they have their 3rd party storage & cookies disabled, for instance. Furthermore sessionStorage is much more convenient for storing nonce & state as it would be erased once the tab is closed, fixing some other open issues.

**Comment by luisrudge** [comment]
We have a PR ready to fix this (we're not ready to jump ships and use an external dependency quite yet). Can you help and write the test case for it? That would be amazing 🎉 
https://github.com/auth0/auth0.js/pull/478

closing as duplicate of https://github.com/auth0/auth0.js/pull/478
