### ISSUE TITLE
Angular2 cannot find module

### ISSUE THREAD

**Issue by Dyanngg** [auth0/auth0.js#589]
I'm writing this app in angular2 and wanted to incorporate Auth0. As I followed the tutorial, I first did 
`npm install --save auth0-js` and put the `<script type="text/javascript" src="../node_modules/auth0-js/build/auth0.js"></script>` line in my index.html. 

Now when I copied the code snippet for auth.service.ts, I get the error 
`ERROR in /Users/ding/Documents/webProjects/collab-system/oj-client/src/app/services/auth.service.ts (4,24): Cannot find module 'auth0-js'.`
which I have no idea why is present. 

Auth0.js version is 8.12.0, using angular 2.3.1 on mac OSX.

---- Screenshots -----
![screen shot 2017-12-10 at 9 40 19 pm](https://user-images.githubusercontent.com/11527024/33817323-d1738660-ddf3-11e7-987d-2d72a26fb8e4.JPG)
![screen shot 2017-12-10 at 9 48 59 pm](https://user-images.githubusercontent.com/11527024/33817352-061ffad8-ddf4-11e7-802e-118f42244490.JPG)
![screen shot 2017-12-10 at 9 49 13 pm](https://user-images.githubusercontent.com/11527024/33817354-08f35af2-ddf4-11e7-928e-45b70d870f5b.JPG)
![screen shot 2017-12-10 at 9 51 18 pm](https://user-images.githubusercontent.com/11527024/33817399-480cb8c8-ddf4-11e7-9a35-9c609a2190dc.JPG)
Auth0 is indeed installed in node_modules
![screen shot 2017-12-10 at 9 54 01 pm](https://user-images.githubusercontent.com/11527024/33817499-bd6fa1a2-ddf4-11e7-80e4-de8d0970f667.JPG)

**Comment by luisrudge** [comment]
Please follow our angular2 quick start: https://auth0.com/docs/quickstart/spa/angular2/01-login

**Comment by Cjesse** [comment]
Hi, @Dyanngg I encountered the same error, did you solve the problem and how? thanks!

**Comment by Jinshuo1994** [comment]
I don't think the official response above actually gives a solution. What I do is just remove `import * as auth0 from 'auth0-js';` add `declare var auth0: any;` and include the CDN in index.html
