### ISSUE TITLE
renewAuth not documented

### ISSUE THREAD

**Issue by murphyke** [auth0/auth0.js#592]
The `renewAuth` method is not documented in the [web docs](https://auth0.com/docs/libraries/auth0js/v8) or in the [README for auth0.js v8](https://github.com/auth0/auth0.js/blob/v8/README.md).

The example code (e.g. [auth0-react-examples](https://github.com/auth0-samples/auth0-react-samples/blob/master/05-Token-Renewal/src/Auth/Auth.js#L100-L117) uses this method, so presumably the documentation for this is on the way?

**Comment by luisrudge** [comment]
We're removing docs on renewAuth because the recommended way of doing that is now using checkSession: https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens
