### ISSUE TITLE
checkSession stuck in spa needing a body

### ISSUE THREAD

**Issue by tahoemph** [auth0/auth0.js#595]
I am using auth0.js 8.12.0.  I am using chrome on a linux box for test.

I have a SPA that would like to launch check to see if there is a SSO login early.  But IframeHandler about line 52 wants the page to have a body.  I am still building the page at this point.  I can delay until a later point but would like to kick off this process earlier.  What is the reason that this iframe isn't attached to the top level of the document?  I think it is is only used for posting messages between domains.

code in question: https://github.com/auth0/auth0.js/blob/master/src/helper/iframe-handler.js#L51

**Comment by luisrudge** [comment]
It's attached to the body to make sure all scripts have been loaded.

**Comment by tahoemph** [comment]
@luisrudge That is contrary to web performance in single page apps these days.  We don't want to be blocking on a bunch of script loads when they are unrelated to the task at hand.  It should be the client that determine when it is ready to try to authenticate.  Given the latency of this call I want to start it as soon as possible.

**Comment by luisrudge** [comment]
Can you create a PR so I can test with some internal apps?
