### ISSUE TITLE
Docs are missing callback and `relay_url`

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#596]
- Looks like `auth.popup.authorize()` assumes that the second arg is a callback, but the docs don't mention it:

https://auth0.com/docs/libraries/auth0js/v8#webauth-popup-authorize-

- Docs also don't mention a `relay_url`:

```js
  auth.popup.authorize(
    {
      connection: 'github',
      responseType: 'token'
    },
    (err, authResult) => {
      console.log({ err, authResult })
    }
  )
```

`{original: "missing required 'relay_url' parameter", code: null, description: null}`

This doesn't fix it:

```js
  auth.popup.authorize(
    {
      connection: 'github',
      responseType: 'token',
      relay_url: 'http://localhost:3000/'
```

`v8.12.1`

**Comment by luisrudge** [comment]
Thanks! I added the callback in the docs. The relay_url is used only in very specific cases, so it shouldn't be an issue.
https://github.com/auth0/docs/pull/5465

**Comment by lorensr** [comment]
@luisrudge thanks—what is relay_url and how do I provide it? Adding it as an attribute in the first argument had no effect on the error message

**Comment by lorensr** [comment]
Yeah, when I try the above code, I get this `err`:

original: "missing required 'relay_url' parameter", code: null, description: null

**Comment by luisrudge** [comment]
Can you build a repro with this?
I just ran the example file in this repo and it works as expected: https://github.com/auth0/auth0.js/blob/master/example/index.html#L328

**Comment by lorensr** [comment]
I'm using popup. When I run the example an click Github button under `Login with /authorize (popup)`, I get this:

![image](https://user-images.githubusercontent.com/251288/34231116-b60e5c08-e5a8-11e7-9835-8191f6cdf6a9.png)

When I use my own data:

https://github.com/lorensr/auth0.js/commit/1d7305f66dbf078b590977842a3672f9ccae888b

I get this:

![image](https://user-images.githubusercontent.com/251288/34231186-fa596e16-e5a8-11e7-9434-805600450cd8.png)

**Comment by luisrudge** [comment]
hmm.. maybe it's github specific? can you try with twitter?

**Comment by lorensr** [comment]
Same result w/ Twitter. Probably has to do with the configuration of my
graphql.auth0.com, but it gives me no indication of what.

**Comment by luisrudge** [comment]
Right.. can you try passing `owp: true` to the `authorize` call and see if that works?

**Comment by lorensr** [comment]
That works, thank you very much! After adding localhost to allowed origins. Don't see `owp` in the docs:

https://auth0.com/docs/libraries/auth0js/v8#webauth-popup-authorize-

And now in the callback, `authResult` is of  the form: `{accessToken: "foo", expiresIn: 7200, tokenType: "Bearer", state: "bar"}` 

`expiresIn` is different from my JWT expiration setting:

![image](https://user-images.githubusercontent.com/251288/34237569-623c108e-e5cb-11e7-8660-b6d7dea38b69.png)

Is there somewhere I can configure access token expiration?

**Comment by luisrudge** [comment]
I'm not sure your value is valid tbh.. I think you're better off asking in our support channels: https://support.auth0.com

I'll ping the docs team to add the owp param.

**Comment by BennettStaley** [comment]
@luisrudge, thanks for the info on the OWP param. Is that a valid long term solution to this issue? I'm are migrating from v6 to v9 as we speak. The redirect error when using a popup was entirely unhelpful as a popup _shouldn't_ "redirect" so to speak.

Furthermore the OWP param is still not included anywhere in the docs, nor do the docs mention that the second param for popup.authorize is a callback.

**Comment by luisrudge** [comment]
Sorry, the docs were merged to v8 but not to v9. I opened another PR here: https://github.com/auth0/docs/pull/5932

About the `owp` option, I asked to the backend team if this will be supported in the future, I'll let you know when they answer me. Although, ideally, you should always use the redirectUri + a popup callback page for that:

```js
webAuth.popup.authorize({
  redirectUri: 'https://myapp.com/callback_popup.html'
}, function(err, authResult) {
 //do something
});
```

And then your callback page would look like this: https://github.com/auth0/auth0.js/blob/master/example/callback_popup.html

**Comment by Christopher2K** [comment]
Hi ! FYI these informations (about the owp param) still missing today at https://auth0.com/docs/libraries/auth0js/v9 !

**Comment by bhatakshatha** [comment]
documentation on owp is still missing today at https://auth0.com/docs/libraries/auth0js/v9
