### ISSUE TITLE
User + password login to /ro: make a callback, using .bind()

### ISSUE THREAD

**Issue by IvanRave** [auth0/auth0.js#60]
.bind() doesn't work for login requests to /ro

http://jsfiddle.net/IvanRave/rmbxvsk2/

and it's really strange behavior in a callback: 
* if null or one param - redirect
* it two or more params - post to /ro

please add some other method for redirection
or some special option for this
or good docs for this behavior

**Comment by pose** [comment]
@IvanRave The behavior is a known issue: https://github.com/auth0/auth0.js/issues/26

**Comment by cristiandouce** [comment]
Dup of auth0/auth0/issues/26
