### ISSUE TITLE
renewAuth does not work anymore due to location.hash being empty in SilentAuthenticationHandler

### ISSUE THREAD

**Issue by damien-gl** [auth0/auth0.js#601]
Hi!
The renewAuth does not work anymore for us on v8.12.1 on Chrome (Windows & MacOS).

It seems that the `location.hash` in `SilentAuthenticationHandler. getCallbackHandler` is empty here:
https://github.com/auth0/auth0.js/blob/v8/src/web-auth/silent-authentication-handler.js#L68

Here is the value of `eventData.sourceObject.contentWindow.location` that we get:
```
{
    "href": "about:blank",
    "ancestorOrigins": {
        "0": "http://localhost:5000"
    },
    "origin": "null",
    "protocol": "about:",
    "host": "",
    "hostname": "",
    "port": "",
    "pathname": "blank",
    "search": "",
    "hash": ""
}
```

We suspect that this bug got introduced with this commit:
https://github.com/auth0/auth0.js/commit/2d7243d2675dbc5070305fe9236af5daebf8fbfd
Because the iframe source URL is set after `addEventListener` and the event is then called for the `about:blank` Chrome page being loaded instead of the actual renewal URL page being loaded.

Can you please have a look.
Thanks!

**Comment by luisrudge** [comment]
What version were you using before?

**Comment by damien-gl** [comment]
Version 8.10.x

**Comment by luisrudge** [comment]
how do you use the renewAuth method? there's more context about this issue here: https://github.com/auth0/auth0.js/issues/565#issuecomment-349086162

**Comment by damien-gl** [comment]
Thanks for the info regarding the issue.
We are simply using renewAuth like this:

```
renewAuth({
      scope: 'openid email user_metadata app_metadata',
      responseType: 'token',
      responseMode: 'fragment',
      redirectUri: ...
    }, (err, result) => {...})
```

To fix this issue can you maybe do the following check here: 
https://github.com/auth0/auth0.js/blob/v8/src/web-auth/silent-authentication-handler.js#L56

```
case 'load': 
          if (eventData.sourceObject.contentWindow.location.protocol === 'about:') {
            return false;
          }
// Fall through to default
default:
          return true;
```

**Comment by luisrudge** [comment]
Can you send a PR with that change and a test?

**Comment by damien-gl** [comment]
Hi @luisrudge 

Here are the 2 PRs.
V9: https://github.com/auth0/auth0.js/pull/619
V8: https://github.com/auth0/auth0.js/pull/620

Please have a look.
Thanks

**Comment by damien-gl** [comment]
Hi @luisrudge 
Any update on this? We are looking forward to have this fix merged for our production release.
Thx.

**Comment by damien-gl** [comment]
Any update on this? (@luisrudge @aaguiarz)

**Comment by luisrudge** [comment]
@damien-gl thanks for both PRs! Sorry to keep you waiting, I was on vacation 🌴

**Comment by damien-gl** [comment]
thanks @luisrudge
