### ISSUE TITLE
Remove popup_options warning

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#606]
It would be good to not have this warning:

![image](https://user-images.githubusercontent.com/251288/34376750-8347ceae-eabb-11e7-815a-5f6f196f3737.png)

while still using `popupOptions` to change the height of the popup:

![image](https://user-images.githubusercontent.com/251288/34376757-8bdb7994-eabb-11e7-8924-5a61c2a7c250.png)

**Comment by luisrudge** [comment]
😲 misssed this one 😊
