### ISSUE TITLE
Document difference between renewAuth and checkSession

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#608]
Looks like they do the same thing? When would I use one vs the other?

http://auth0.github.io/auth0.js/global.html#renewAuth
http://auth0.github.io/auth0.js/global.html#checkSession

**Comment by luisrudge** [comment]
They do the same thing but checkSession is easier (no callback page). We're only recommending checkSession from now on.

**Comment by johnlim** [comment]
@luisrudge Does that mean that with checkSession, we no longer need to manually implement/call silent callback in an iframe?

**Comment by luisrudge** [comment]
@johnlim yes! That's the beautiy of it. You can remove the silent-callback.html file 🎉

**Comment by johnlim** [comment]
@luisrudge I'm not sure if its a bug but when I call `checkSession()` without passing in `responseType`, I get a `responseType is required` error. However, iirc, instantiating webAuth defaults it to `token` if no redirectUri is provided. Therefore, I should not get a `responseType is required` error when the responseType parameter is not passed in the call to checkSession(). Did something change in V9?

**Comment by luisrudge** [comment]
There's no default for response_type, I just removed that info from the readme: https://github.com/auth0/auth0.js/pull/697

> If you don't provide a global `responseType`, you will have to provide a `responseType` for each method that you use

**Comment by chrisschaub** [comment]
I ended up using just localstorage bare and then checking for keyval pairs with more distinct names. I am using chrome on ubuntu 16.04. Definitely not in private mode. Anyway, I found a solution that works. I will try to write a better bug report  by the weekend.
