### ISSUE TITLE
Package naming causes common Grunt tasks to fail

### ISSUE THREAD

**Issue by jjongsma** [auth0/auth0.js#61]
When running "usemin" and "rev:dist" tasks with a common options (i.e. includes = **/*.js), Grunt builds fail due to this module being named "auth0.js" (it tries to open it as a JS file). Not *strictly* your fault, but the nonstandard naming convention makes it impossible for me to use bower to manage the auth0 dependency at this point since I need to rename it and rewire my local dependencies manually. I haven't run into any other packages that do this.

I would recommend publishing as "auth0-js" or just "auth0" and switching to that as the default package for your other dependencies (auth0-angular, etc).

**Comment by pose** [comment]
Hi @jjongsma,

Do you have an example of that so we can see possible workarounds?

Thanks in advance,

**Comment by cristiandouce** [comment]
https://github.com/auth0/auth0.js/blob/master/package.json#L2

```JSON
{
  "name": "auth0-js",
  "version": "6.6.0",
  "description": "Auth0 headless browser sdk",
```
