### ISSUE TITLE
CheckSession should set redirect_uri to the main window origin

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#610]
When Lock issues a silent authentication request with `response_mode=web_message`, it's using the original `redirectUrl` as the value for the `redirect_uri` parameter. 
For requests with `response_mode=web_message`, the `redirect_uri` should be the origin of the main window, to allow for a proper web message communication. 
In particular, if the origin of the callback URL used differs from the main window's origin, the silent authentication request will fail. 

E.g. a page served from `https://mydomain.com/login' has:

```
var lock = new Auth0Lock( 
  clientId, 
  domain, 
  { 
    auth: { 
      // (Notice the different web origin in this callback URL from the page location)
      redirectUrl: 'https://www.mydomain.com/callback', 
      [...]
[...]
```

The above config will cause a silent auth request doing

`https://.../authorize?response_mode=web_message&redirect_uri=https://www.mydomain.com/callback`

The server will respond with code to communicate with the `https://www.mydomain.com` origin, and the communication will fail (because the origin of the main window was `https://mydomain.com`).

**Comment by luisrudge** [comment]
moved from https://github.com/auth0/lock/issues/1208

**Comment by jaredhanson** [comment]
If pages are being served from `mydomain.com` (without `www`), then the callback URL needs to be registered under that domain, and used as so:

```
https://.../authorize?response_mode=web_message&redirect_uri=https://mydomain.com/callback
```

Communication to any unregistered origin is expected to fail, so if both `mydomain.com` and `www.mydomain.com` are in use, both need to be registered.
