### ISSUE TITLE
Did you want to spell the word  "receive" (vs recieve) ?

### ISSUE THREAD

**Issue by jeis2497052** [auth0/auth0.js#614]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ X] Code snippet or sample project that reproduces the bug

diff --git a/docs/global.html b/docs/global.html
index d56852b..113997e 100644
--- a/docs/global.html
+++ b/docs/global.html
@@ -2443,7 +2443,7 @@ After that, you'll have to use the <a href="global.html#parseHash"><code>parseHa
 
 
             <td class="description last">
-                <p>address where the user will recieve the change password email. It should match the user's email in Auth0</p>
+                <p>address where the user will receive the change password email. It should match the user's email in Auth0</p>
 
             </td>
         </tr>

git grep recieve

docs/authentication_db-connection.js.html: * @param {String} options.email address where the user will recieve the change password email. It should match the user's email in Auth0
docs/global.html:                <p>address where the user will recieve the change password email. It should match the user's email in Auth0</p>
docs/web-auth_index.js.html: * @param {String} options.email address where the user will recieve the change password email. It should match the user's email in Auth0
src/authentication/db-connection.js: * @param {String} options.email address where the user will recieve the change password email. It should match the user's email in Auth0
src/web-auth/index.js: * @param {String} options.email address where the user will recieve the change password email. It should match the user's email in Auth0

- [ ] Screenshots when appropriate
- [ ] Auth0.js version
- [ ] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by luisrudge** [comment]
Do you want to send a PR to fix those? 😊
