### ISSUE TITLE
V9 Documentation Confusion

### ISSUE THREAD

**Issue by NoCopy** [auth0/auth0.js#617]
NPM Install now seems to default to v9.02, which is fine. However, At https://github.com/auth0/auth0.js/tree/v9.0.2 this is the first statement on the page:

> Auth0.js v9 uses our latest embedded login API. **This version is not supported in centralized login scenarios** (i.e. Hosted Login Pages). If you are using a Hosted Login Page, keep using Auth0.js v8.

Yet, in the migration guide for V9 is states the following:

> If you are using auth0.js to implement login embedded in your applications, **we recommend moving to a centralized login approach**

And under the heading Should I migrate to v9? the first bullet point states:

> In your application, **to trigger centralized login, using the .authorize() method**, where the user is redirected from your website to an Auth0's Hosted Login Page.

So if I am understanding correctly, v9 can be used in centralized login scenarios _but not_ on the hosted login page itself? that could be stated a lot more clearly if that is the case.

**Comment by aaguiarz** [comment]
You understanding is correct, we'll adjust the docs. 

Thanks a lot for the feedback
