### ISSUE TITLE
WebAuth authorize custom API scopes unexpected behavior

### ISSUE THREAD

**Issue by c-neves** [auth0/auth0.js#622]
I have an Auth0 SPA client and one Auth0 API with the following custom scopes: `read:users` and `create:posts`.

Following the docs, custom API scopes should be passed here:
```javascript
auth0 = new auth0.WebAuth({
    // ...
    responseType: 'token id_token',
    scope: 'openid profile email read:users create:posts'
  })
```

I use the hosted login page, so after loging in with Github I get the following:
![issue](https://user-images.githubusercontent.com/9116538/34645576-c0794ebc-f338-11e7-92ad-827dd62ed1c7.png)

I don't know, maybe I'm wrong here, but should these custom scopes show up to the end user?

From what I understand these scopes are supposed to be used by my API to authorize requests.

auth0-js@9.0.2

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. The consent widget is rendered by the server itself.  Please reach out to our amazing support team at https://support.auth0.com so they can help you with your questions 🎉
