### ISSUE TITLE
Authorize issue from Safari 10.1.2 in private window

### ISSUE THREAD

**Issue by edmgt** [auth0/auth0.js#623]
Hi,

I am calling [auth0.authorize](https://github.com/auth0/auth0.js#api) and running Safari 10.1.2 in private window but it does not seem to work. For Facebook and Google signins it loads a pop-up with usual sign in form but on redirect instead of a normal workflow I get I get the following: ```code: "invalid_token", description: "`state` does not match."```

- [ ] Auth0.js version: 8.12.1 and 9.0.2
- [ ] Browser & OS: macOS 10.12.6, Safari 10.1.2 (12603.3.8)

This **does not happen** on Safari 10.12.6 running in normal window or Safari 11.0.2 (12604.4.7.1.6) running in normal/private windows.

Is this a known issue or something I can/should patch on my end rather than auth0.js?

Cheers.

**Comment by luisrudge** [comment]
looks like safari in private mode has some quirks.. I'll investigate that when I have some free time.

Another issue: https://github.com/auth0/lock/issues/1242#issue-293115151

**Comment by luisrudge** [comment]
I just tested with safari 11.0.3 and it works, so I think it's specific to 10.1? Can you test with safari@11?

**Comment by edmgt** [comment]
As described above this only seems to happen in Safari 10.1.2 (12603.3.8) and below. It is also reproducible on an older iOS devices seemingly due to the same Safari issue. Thanks.

**Comment by luisrudge** [comment]
I just tested and it works! It will use cookies instead:
![image](https://user-images.githubusercontent.com/941075/38596351-6390de70-3d27-11e8-9d58-06fff480170a.png)
