### ISSUE TITLE
Obtain an actual email_verified value without re-login?

### ISSUE THREAD

**Issue by IvanRave** [auth0/auth0.js#63]
After registration (and login after that) I have {email_verified: false}

After verification of email this method returns the same value (email_verified: false)
- getProfile() or /tokeninfo

even after renewIdToken or refreshToken

only re-login helps to obtain actual value: (email_verified: true)

Is there any possibility to obtain it without re-login?

**Comment by cristiandouce** [comment]
If still an issue mind reopen please. Thanks!

**Comment by grashopper** [comment]
Please reopen.  I'm confused as to what the purpose of the Verification Email if the signup api dbconnections/signup logs you in before the 'Confirm my account' link is clicked.

**Comment by rolodato** [comment]
@grashopper You can pass `loginAfterSignup: false` to avoid logging in automatically. Also, it's perfectly feasible for applications to allow logging in users without verified emails, you can provide limited functionality or just show a message telling the user to click on the verification link.

**Comment by grashopper** [comment]
@rolodato I included loginAfterSignup: false with not effect.  

{
                connection: AUTH0_DB_CONNECTION_NAME,
                username:   $scope.registerInfo.emailAddress,
                password:   $scope.registerInfo.password,
                loginAfterSignup: false
            }

**Comment by grashopper** [comment]
the full function is

auth0.signup({
                connection: AUTH0_DB_CONNECTION_NAME,
                username:   $scope.registerInfo.emailAddress,
                password:   $scope.registerInfo.password,
                loginAfterSignup: false
            }, function (err) {
                if (err){
                    console.log("Error :" + JSON.stringify(err));
                    if(err.code){
                        $scope.error_400_user_exists = true;
                        console.log("error_400_user_exists");
                    }

                    var settingsObj = {id: store.get('user_id') }
                    userUpdateService.update(settingsObj);

                    $scope.state_info = true;
                    $scope.state_legalAcceptance = false;
                    $scope.state_confirmation = false;

                }else{
                    $scope.updateUser();
                    $scope.state_info = false;
                    $scope.state_legalAcceptance = false;
                    $scope.state_confirmation = true;
                    console.log('Registration Successful');
                    //console.log('auth: ' + auth);
                };
                $scope.$apply();
            });

**Comment by rolodato** [comment]
@grashopper Sorry about that, `loginAfterSignup` is the option name for Lock and not auth0.js. Could you try passing `auto_login: false` instead?

**Comment by grashopper** [comment]
thank you, that worked.  now i need to prevent the user from logging in
before the email has been verified. so i created rule 'Force email
verification'.  however, i don't seem to be getting back
the UnauthorizedError.

function (user, context, callback) {
  if (!user.email_verified) {
    return callback(new UnauthorizedError('Please verify your email before
logging in.'));
  } else {
    return callback(null, user, context);
  }
}

here is my code.

auth.config.auth0js.signin({
    connection: "Username-Password-Authentication",
    scope: 'openid',
    callbackOnLocationHash: true,
    username: $scope.login.emailAddress,
    password: $scope.login.password
}, function(err) {

    if(err){
        console.log("There was an error logging in", err);  <=====
THIS LINE DOES NOT FIRE
        if(err.status == 401){
            $scope.error_401_invalid_user_password = true;
            console.log("error_401_invalid_user_password");
        };
        if(err.status == 429){
            $scope.error_429_too_many_requests = true;
            console.log("error_429_too_many_requests");
        };
    }else{
        $scope.resetLoginForm();

        //console.log("auth.user_id: " + JSON.stringify(auth.user_id));
        console.log("Successfully logged in");
    }
    $scope.$apply();
});



Thank you,

Perry

**Comment by rolodato** [comment]
This is expected because rules are executed after login, not signup. In any case I would suggest you ask any questions on ask.auth0.com, this isn't the place to discuss them. Thanks!

**Comment by grashopper** [comment]
I will ask the question ask.auth0.com, but please notice that the call
is signin
not signup.


Thank you,

Perry
