### ISSUE TITLE
npm package of 8.12.2 does not contain the 'build' folder and .js files

### ISSUE THREAD

**Issue by rhino5oh** [auth0/auth0.js#632]
After upgrading to 8.12.2 via npm I get the following error:

```
An error occured during the build:
Error: ENOENT: no such file or directory, open 'C:\path\to\node_modules\auth0-js\build\auth0.js'
    at Error (native)
```

After navigating to the node_modules/auth0-js folder and doing an 'ls', I see that there is in fact no build folder or auth0.js file anywhere.

However, if I revert back to 8.12.1, I do see the build folder, as well as all .js files, and I no longer receive any error

**Comment by luisrudge** [comment]
That's pretty weird.. The build folder is in the tag but wasn't published: https://github.com/auth0/auth0.js/compare/v8.12.1...v8.12.2
I'm not sure what happened. Maybe an issue with our build server, but I'm not sure.. I'll monitor in the next release. I can't re-release the 8.12.2 version because it's been more than 24h since the last publication, so I can't fix this one. Please rollback to 8.12.1 until 8.12.3 is released.

**Comment by luisrudge** [comment]
What's even weirder is that the next release (v9.x) has the build folder as expected: https://unpkg.com/auth0-js@9.1.0/build/ 🤔

**Comment by rhino5oh** [comment]
hmm definitely weird.  I can live with 8.12.1 for now though.  Thanks for looking into it!

**Comment by benmccallum** [comment]
8.12.3 still doesn't seem to have it...

**Comment by luisrudge** [comment]
8.x is not supported anymore. Can you upgrade to 9.x?

Luís

________________________________
De: Ben McCallum <notifications@github.com>
Enviado: segunda-feira, dezembro 31, 2018 2:11 PM
Para: auth0/auth0.js
Cc: Luís Rudge; Comment
Assunto: Re: [auth0/auth0.js] npm package of 8.12.2 does not contain the 'build' folder and .js files (#632)


8.12.3 still doesn't seem to have it...

**Comment by benmccallum** [comment]
I suppose I can if the upgrade doesn't involve much. Will check the upgrade guide. 

Bit of a shame the last patch of last major version was left broken though.

**Comment by luisrudge** [comment]
Indeed. I'll release a new patch version for compatibility, but it's low priority and the 8 -> 9 upgrade is a security upgrade, so you really should upgrade 😬

**Comment by benmccallum** [comment]
I've gone through the upgrade guide and applied the changes. Was straightfwd and just a version bump for us although I haven't tested yet. Cheers

**Comment by luisrudge** [comment]
🎉
