### ISSUE TITLE
Social login returns correct tokens. Username / Password login does not.

### ISSUE THREAD

**Issue by tnolet** [auth0/auth0.js#634]
Hi,

I'm banging my head against the wall here. The auth0.js docs are really unclear and vague about all the different ways to login someone, but I managed the social one. It works now. For username / password (database) users, I keep getting incorrect tokens back. 

Main difference between the tokens is that the tokens are MUCH shorter when using the username password option, i.e.

My app is a SPA (vue.js) talking to a Hapi API. The code on the Vue app is as follows:
The first two functions are called from a callback page and work great: they results it an access token I use to do API requests. 100% A-OK. 
The other function (usernamePwdLogin) also gives back an id and access token, but these are invalid. 

```javascript

// works awesome. Redirect to callback page.
function socialLogin (provider) {
  webAuth.authorize({
    responseType: 'token id_token',
    redirectUri: REDIRECT_URL,
    audience: process.env.AUTH0_AUDIENCE,
    scope: SCOPE,
    connection: provider
  })
}

// works awesome. Is called on callback page and give's me the right tokens. All is good.
export function setTokens () {
  return new Promise((resolve, reject) => {
    webAuth.parseHash((err, res) => {
      if (err) return reject(err)
      localStorage.setItem(ID_TOKEN_KEY, res.idToken)
      localStorage.setItem(ACCESS_TOKEN_KEY, res.accessToken)
      return resolve()
    })
  })
}

// Log's in the user, but returns faulty tokens....
function usernamePwdLogin (username, password) {
  return new Promise((resolve, reject) => {
    webAuth.client.login({
      scope: SCOPE,
      realm: AUTH0_USERPWD_AUTH,
      username,
      password
    }, (err, res) => {
      if (err) return reject(err)
      localStorage.setItem(ID_TOKEN_KEY, res.idToken)
      localStorage.setItem(ACCESS_TOKEN_KEY, res.accessToken)
      return resolve()
    })
  })
}
```

I've lost track of what I tried and what I've read. I have no idea what the difference between `webAuth.login()` and `webAuth.client.login()` is and if I should use it or not.

backend code is almost a copy & paste of the Hapi.js example in the offical guides:

```javascript
  server.register([require('hapi-auth-bearer-token'), require('hapi-auth-jwt2'), require('hapi-authorization')], (err) => {
    Hoek.assert(!err, err)

    server.auth.strategy('token', 'jwt', {
      complete: true,
      key: jwksRsa.hapiJwt2Key({
        cache: true,
        rateLimit: true,
        jwksRequestsPerMinute: 5,
        jwksUri: `https://checkly.eu.auth0.com/.well-known/jwks.json`
      }),
      validateFunc: validate,
      verifyOptions: {
        audience: config.auth0.audience,
        issuer: 'https://checkly.eu.auth0.com/',
        algorithms: [ 'RS256' ]
      }
    })

```

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario. Also, did you read our blog post about [vuejs auth tutorial](https://auth0.com/blog/vuejs2-authentication-tutorial/)? We also have a [quickstart with vue](https://auth0.com/docs/quickstart/spa/vuejs/01-login).
