### ISSUE TITLE
How to set query params in `authorize` without hitting a warning because of the params whitelist

### ISSUE THREAD

**Issue by donaldpipowitch** [auth0/auth0.js#637]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [x] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ ] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [x] Auth0.js version 8.8.0
- [x] any Browser & any OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

---

Hi everyone!

We use a hosted login page and it is possible to access additional query params via `config.extraParams` as mentioned in [this support post](https://community.auth0.com/questions/9079/configuring). However as far as I can tell it is not possible to add additional params in the `authorize()` function of this lib without getting a warning, because of this [whitelist](https://github.com/auth0/auth0.js/blob/52db303093914b4edd67a6ce445c3edcee4905ce/src/helper/parameters-whitelist.js#L23). Is there a way to explicitly add certain params as a opt-in to the whitelist so we don't see a warning?

Use case: We want clients to be able to set a locale via query parameter so that the login page is shown in the language which they think is the best language for the current user (e.g. when they have stored something like a preferred locale in a cookie somewhere on their site - some place which can't be accessed from the hosted login page).

Thank you!

**Comment by luisrudge** [comment]
the endpoint only accepts OAuth 2.0 params, that's why you're seeing the warnings. For your specific case, you can use [this](https://github.com/auth0/auth0.js/blob/52db303093914b4edd67a6ce445c3edcee4905ce/src/helper/parameters-whitelist.js#L49) param or disable the warnings altogether using the option `_disableDeprecationWarnings: true`.
