### ISSUE TITLE
9.1.2: Error with redirectUri origin

### ISSUE THREAD

**Issue by bkniffler** [auth0/auth0.js#640]
Since the latest version 9.1.2 I get an error:
"The redirectUri's origin (http://localhost) should match the window's origin (http://localhost:3010)."

I'm pretty sure its because of this commit: https://github.com/auth0/auth0.js/commit/ceed49706f9af24eaf49ad21b778cad0d0ca3b49

Since the port is omitted, it won't use the correct port.

When I go back to previous version 9.1.0, it works great.

**Comment by luisrudge** [comment]
released under  v9.1.3
