### ISSUE TITLE
IE11 does not support anchor.origin

### ISSUE THREAD

**Issue by proglottis** [auth0/auth0.js#642]
While testing auth0.js v9.1.0 we discovered that popup auth using `popup.loginWithCredentials` no longer works in IE 11.

It gives the error message:
```
error: "origin_mismatch",
error_description: "The redirectUri's origin (undefined) should match the window's origin (https://...)."
```

After some debugging I believe this is caused by the use of anchor.origin here https://github.com/auth0/auth0.js/blob/ce402c8628c8f34a69145415fecbb5233a9500d3/src/helper/object.js#L128 This function is not supported by IE and always returns undefined.

In chrome:
```
getOriginFromUrl('http://example.com/foo/bar')
"http://example.com"
```

In IE11:
```
getOriginFromUrl('http://example.com/foo/bar')
undefined
```

And the actual popup snippet:
```js
        angularAuth0.popup.loginWithCredentials({
          connection: CONFIG.AUTH0.CONNECTION,
          username: params.email,
          password: params.password,
          redirectUri: CONFIG.AUTH0.REDIRECT,
        }, function(err, authResult) {
          if (err) {
            reject(err);
            return;
          }
```

**Comment by luisrudge** [comment]
it was fixed on 9.1.2 (I still need a patch to fix the specified port, it should be out in a few minutes) https://github.com/auth0/auth0.js/blob/master/CHANGELOG.md#v912-2018-01-26
