### ISSUE TITLE
IE11 checkSession always return login_required

### ISSUE THREAD

**Issue by critchie** [auth0/auth0.js#648]
- Code snippet or sample project that reproduces the bug
I'm using your sample app from this [article](https://auth0.com/docs/quickstart/spa/angular2/05-token-renewal)
- Auth0.js version 9.1.3
- Browser & OS: IE11 & Windows 7 Professional Service Pack 1

Application works as designed when using Chrome.  However IE11 does not.  With IE11, I can get logged in fine.  But if I click the Renew button the checkSession() call always return login_required.

The only thing changed in the code is changes to settings to point to my Auth0 client and I had to turn on all the polyfills in polyfills.ts so IE11 would load the app.

**Comment by luisrudge** [comment]
did you try outside of the example itself?

**Comment by critchie** [comment]
I'm not sure I'm following...  The issue appeared in the app I'm developing for my client.  To make sure it wasn't something I was doing I pulled the Auth0 example app down and got it working with Chrome and then tried it with IE11 and the same thing happened with it as the application I'm developing.  So I'm at a loss as to what is going wrong.

**Comment by luisrudge** [comment]
Yeah, I'm trying to rule out any issues with the sample itself. Can you please clone this repo and run:

```
npm install
npm start
```

Then go to https://localhost:3000/example, click the login button and then click the check session button. With that, we can pinpoint where the error is happening. THanks!

**Comment by critchie** [comment]
We IE11, I used "Login with /authorize:" using johnfoo@gmail.com/1234 which was successful.  Then I clicked Renew button and get:
```
{"error":"login_required","errorDescription":"Logi{
    "error": "login_required",
    "errorDescription": "Login required",
    "state": "YoIkUa2G8IxOGgMQxbuRNBgOYaSiIY~F"
}
```

I performed the same steps with Chrome and all was successful.

**Comment by luisrudge** [comment]
Ok thanks. I'll investigate.

**Comment by critchie** [comment]
Any updates on this investigation?

**Comment by luisrudge** [comment]
Hi, sorry! Not yet. I'll fix an IE issue this week, so I'll dig into this issue as well.

**Comment by critchie** [comment]
Sorry to keep hounding you on this... any updates?

**Comment by luisrudge** [comment]
Hi @critchie. So, what's not working for you is that you're logging in with the Universal Login Page (former Hosted Login Page) and checkSession is not working. Is this the case?
Does it work if you use the `Login with username and password:` button?

**Comment by critchie** [comment]
I followed your instructions from a few weeks ago and ran the Auth0.js playground example.

My results were:

> With IE11, I used "Login with /authorize:" using johnfoo@gmail.com/1234 which was successful. Then I clicked Renew button and get:

```
{"error":"login_required","errorDescription":"Logi{
    "error": "login_required",
    "errorDescription": "Login required",
    "state": "YoIkUa2G8IxOGgMQxbuRNBgOYaSiIY~F"
}
```
>I performed the same steps with Chrome and all was successful.

**Comment by luisrudge** [comment]
Yeah, but you said you tried the `login with /authorize`, which calls the Universal Login Page. I want to know if this still happens when you try the "login with username and password" button.

**Comment by critchie** [comment]
The version I have doesn't have an option worded exactly like "login with username and password".

I do have a "Login with database connection:" and that gives me:
```
{"error":"access_denied","errorDescription":"Unkno{
    "error": "access_denied",
    "errorDescription": "Unknown or invalid login ticket.",
    "state": "rt6LoQFOxfg0LrSwRIQzXYiN8JHvzDQ6"
}
```

**Comment by critchie** [comment]
In IE11...
"Login with database connection (client login):" works and when using it the Renew button works.

**Comment by luisrudge** [comment]
ok so it's a combo: IE11 + Universal Login Page Login + `checkSession` fails. Correct?
Are you clicking the renew button? or the check session one?
![image](https://user-images.githubusercontent.com/941075/36449780-9915eb64-166a-11e8-9a26-0f80bb8d8f9a.png)

**Comment by critchie** [comment]
I'm checking the Renew button.

**Comment by luisrudge** [comment]
try the check session button

**Comment by critchie** [comment]
I logged in with "Login with /authorize:" and then click CheckSession button.

```
{"accessToken":"lW2NoRkc7nLo34sRfzjs8BTDNPCRUTzh",{
    "accessToken": "lW2NoRkc7nLo34sRfzjs8BTDNPCRUTzh",
    "idToken": null,
    "idTokenPayload": null,
    "appState": "SaLO0ydiQ04asCzTtHMJ6~TDhs0Ug85h",
    "refreshToken": null,
    "state": "SaLO0ydiQ04asCzTtHMJ6~TDhs0Ug85h",
    "expiresIn": "7200",
    "tokenType": "Bearer",
    "scope": null
}
```

So this appears to work.

**Comment by luisrudge** [comment]
cool! This is the checkSession method. The renewAuth method is a bit different and requires a callback page etc. Go with checkSession which is the best way moving forward.

**Comment by critchie** [comment]
Hmmm...   that is what I'm doing in my code.  And in my code I always get login required which is why I opened this issue.  I will take a look at your code and see if I'm missing something in my code.  But my code is already using checkSession.

**Comment by luisrudge** [comment]
See if you can spot anything that stands out from the example code I showed you. If you can't, paste your code here so I can take a look

**Comment by critchie** [comment]
This will be like comparing apples to walnuts.  You code is straight up simple javascript and I'm in an angular 4 app using Typescript.

Here is my webauth setup:
```
            this._auth0 = new Auth0.WebAuth({
                clientID: clientId,
                domain: domain,
                responseType: 'token id_token',
                redirectUri: redirectUri,
                audience: audience,
                scope: `openid profile loginApplicationId-${loginApplicationId}`
            });
```
Then I do this:
```
                    this._auth0.checkSession({}, (err, result) => {
                        if (err) {
                            // redirect to our in-house SSO system that does lots of account stuff for the app and logs the user in to Auth0
                        } else {
                            let expiresAt = JSON.stringify((result.expiresIn * 1000) + Date.now());

                            localStorage.setItem('access_token', result.accessToken);
                            localStorage.setItem('token', result.idToken);
                            localStorage.setItem('expires_at', expiresAt);
                        }
```
When the app starts it immediately calls this code that calls checkSession.  If it fails (which it should on the first time through) the app redirects to our in-house SSO application that does a lot of accounts work for the app (authorization and roles type things...  can this user use the app type things) and of course logs the user into Auth0.  After successful login it redirects back to the calling the app.  The checkSession is immediately hit again but this time it should pass.  It does in Chrome and FireFox but not in IE11.

It is hard for me to take our real world app and explain all its working parts and compare it to a simple demo app.  Do you see anything out of the ordinary?

**Comment by luisrudge** [comment]
how is your sso app doing the auth? auth0.js?

**Comment by critchie** [comment]
Our developer for that app says they are using "lock control 10.19.0" found [here](https://cdn.auth0.com/js/lock/10.19.0/lock.js)

He said "its not the hosted page in auth0 but a local page with the lock control."

Does that help?

**Comment by luisrudge** [comment]
do you have the config used for lock? Also, we're in lock@11.2.3, so you might want to update that before testing this

**Comment by bmingles** [comment]
I'm having the same issue. checkSession works fine in Chrome but always seems to return a 'login_required' error in IE11

**Comment by bmingles** [comment]
Update: My issue was specifically showing up when testing on `localhost`. It seems that it was being caused by how IE classifies localhost in the intranet zone by default. This post clued me in: https://community.auth0.com/t/ie-11-doesnt-redirect-on-successful-login-when-using-cross-origin-authentication/8705

I was able to fix my issue by unchecking a box in the local intranet zone settings.

![image](https://user-images.githubusercontent.com/1900643/50049340-6ed25400-00b1-11e9-9f70-09801483607e.png)

I suspect there may be similar issues not restricted to localhost usage if IE is classifying something in a non-internet zone trying to access auth0.
