### ISSUE TITLE
Auth0.js with Ionic and Angular 5

### ISSUE THREAD

**Issue by jmb1304** [auth0/auth0.js#650]
I am writing an app with Ionic 3.9.2, which uses Angular 5. The [instructions](https://auth0.com/docs/quickstart/native/ionic2) on your website say to use auth0.js and @auth0/cordova. When I try to install these using npm, it gives me an error saying "Unmet Peer Dependency @angular/core@5.0.3" and "Unmet Peer Dependency @angular/http@5.0.3".
![image](https://user-images.githubusercontent.com/11755752/35781244-31685c82-09ad-11e8-8fed-fd6acfc30f70.png)
There are also several other errors saying "angular2-jwt@0.2.3 requires a peer of @angular/core@^2.0.0||^4.0.0 but none was installed." Please update this library and your documentation to reflect how to implement auth0 into an ionic application with angular 5.

**Comment by luisrudge** [comment]
I'll talk with the docs team about ionic 3. AFAIK, there's no content for ionic 3 yet.
