### ISSUE TITLE
getOriginFromUrl: IE11 always includes a port

### ISSUE THREAD

**Issue by proglottis** [auth0/auth0.js#651]
https://github.com/auth0/auth0.js/blob/2bc36781d3f25182e3dfababb79d7335064df73b/src/helper/object.js#L129

In IE11 this seems to always return the port even when it isn't required resulting in this error:
> The redirectUri's origin (https://test.domain.com:443) should match the window's origin (https://test.domain.com).

**Comment by maxpaj** [comment]
Experiencing the same issue.

**Comment by luisrudge** [comment]
I'll try to fix this in the next week. If any of you want to try it out something and submit a PR, I can review it ASAP. Thanks for the patience 🎉
