### ISSUE TITLE
Vue.js beforeReach router guard + global is undefined

### ISSUE THREAD

**Issue by rpersaud** [auth0/auth0.js#652]
I'm following this tutorial - https://www.storyblok.com/tp/how-to-auth0-vuejs-authentication - with vue cli - 3.0.0-alpha.7 and router/pwa preconfigured, and I constantly run into global is undefined error. I traced it down to the auth0 helper, windows.js - where replacing global.window .... with just window worked for me. I tried applying the eslintrc -
    "env": {
        "browser": true,
        "node": true
     }
but it didn't make a difference. I don't believe it's a `this` context issue when the router checks the guard, nonetheless, I don't really know what the best approach is - to create a pr to fix global if its not available in the helper, or trace down the problem further with either vue or auth0.

**Comment by luisrudge** [comment]
I don't know either. Maybe it's best to contact the author.

**Comment by rpersaud** [comment]
updated vue-cli via yarn global add @vue/cli today, and it got bumped a patch version which now seems to fix the problem. Vue 3.0.0-alpha.7 was the problem, 3.0.0-alpha.8 works.
