### ISSUE TITLE
Invalid token - `state` does not match

### ISSUE THREAD

**Issue by jeiman** [auth0/auth0.js#655]
So for some reason I can't seem to authenticate users on certain computers/laptops that has the same browser versions.

`auth.js`

```
export var webAuth = new auth0.WebAuth({
    domain: 'xxx.auth0.com',
    clientID: 'xxx',
    responseType: 'token id_token',
    audience: 'https://xxx.auth0.com/userinfo',
    redirectUri: 'http://localhost:3000'
  })
```

`Login.vue`

```
if (window.location.hash) {
        webAuth.parseHash({ hash: window.location.hash }, (err, authResult) => {
          if (err) {
            return console.log('parseHash error', err)
          }
          if (authResult) {
            webAuth.client.userInfo(authResult.accessToken, function(err, user) {
              if (err) {
                console.log('err accessToken', err)
              }
              localStorage.setItem('profile', JSON.stringify(user))
              localStorage.setItem('id_token', authResult.idToken)
              window.location = '/state'
            })
          }
        })
      }
```

**Picture:**

![error](https://user-images.githubusercontent.com/3265758/35907594-52b3612e-0c29-11e8-92cd-cd8a8f0e9198.jpeg)

**Other details:**

Auth0 version:
NPM - `8.12.2`
ScriptJS - `8.12.2`

Browser: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
O.S: Windows 10

The issue is not happening on my laptop (which is running on the the Browser version mentioned above), but it is happening on other laptops (same browser version).

Not too sure what else to try here. Been looking at the forums, nothing is working out.

Would love some insights on this.
Thank you.

**Comment by luisrudge** [comment]
Can you reproduce this in any way? Your code looks fine, but we need to find a way to reproduce the issue.

**Comment by VinSpee** [comment]
I'm having the same issue, happens of everly login, but on refresh, i can get profiles without issue.

Here's my auth component:

```jsx
import Auth0Lock from 'auth0-lock';
import { withRouter } from 'react-router-dom';
import { Component } from 'react';
import PropTypes from 'prop-types';

class AuthProvider extends Component {
  static propTypes = {
    history: PropTypes.object.isRequired, // eslint-disable-line
    children: PropTypes.func.isRequired,
  };

  constructor(props) {
    super(props);
    this.state = {
      profile: null,
    };

    this.history = props.history;
    this.lock = new Auth0Lock(AUTH_CONFIG.clientId, AUTH_CONFIG.domain, {
      autoclose: true,
      auth: {
        redirectUrl: AUTH_CONFIG.callbackURL,
        responseType: 'token id_token',
        audience: `https://${AUTH_CONFIG.domain}/userinfo`,
        params: {
          scope: 'openid profile',
        },
      },
    });
    this.handleAuthentication();
    // binds functions to keep this context
    this.getProfile = this.getProfile.bind(this);
  }

  componentWillMount() {
    const { userProfile, getProfile } = this;
    if (!userProfile) {
      getProfile((err, profile) => {
        this.setState(state => ({
          ...state,
          profile,
        }));
      });
    } else {
      this.setState(state => ({
        ...state,
        profile: userProfile,
      }));
    }
  }

  getProfile(cb) {
    const accessToken = this.getAccessToken();
    if (accessToken) {
      this.lock.getUserInfo(accessToken, (err, profile) => {
        if (profile) {
          this.userProfile = profile;
        }
        cb(err, profile);
      });
    }
  }

  getAccessToken = () => {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      console.error('No access token found');
    }
    return accessToken;
  }

  setSession(authResult) {
    if (authResult && authResult.accessToken && authResult.idToken) {
      // Set the time that the access token will expire at
      const expiresAt = JSON.stringify((authResult.expiresIn * 1000) + new Date().getTime());
      localStorage.setItem('accessToken', authResult.accessToken);
      localStorage.setItem('idToken', authResult.idToken);
      localStorage.setItem('expiresAt', expiresAt);
      // navigate to the home route
      this.history.replace('/');
    }
  }

  handleAuthentication() {
    // Add a callback for Lock's `authenticated` event
    this.lock.on('authenticated', this.setSession.bind(this));
    // Add a callback for Lock's `authorization_error` event
    this.lock.on('authorization_error', (err) => {
      console.log(err); // eslint-disable-line no-console
      this.props.history.replace('/');
    });
  }

  isAuthenticated = () => {
    // Check whether the current time is past the
    // access token's expiry time
    const expiresAt = JSON.parse(localStorage.getItem('expiresAt'));
    return new Date().getTime() < expiresAt;
  }

  login = () => {
    // Call the show method to display the widget.
    this.lock.show();
  }

  logout = () => {
    // Clear access token and ID token from local storage
    localStorage.removeItem('accessToken');
    localStorage.removeItem('idToken');
    localStorage.removeItem('expiresAt');
    // navigate to the home route
    this.props.history.replace('/');
    this.setState(() => ({
      profile: null,
    }));
  }

  render() {
    const { children } = this.props;
    return children({
      profile: this.state.profile,
      authInstance: this.lock,
      login: this.login,
      logout: this.logout,
      authenticated: this.isAuthenticated(),
    });
  }
}

export default withRouter(AuthProvider);
```

and login:

```jsx
import React from 'react';
import Button from 'components/button';
import Auth from 'components/auth';
import { withRouter } from 'react-router-dom';

const LoginPage = () => (
  <div>
    <Auth>
      {({
        login,
      }) => (
        <button
          onClick={login}
          className="
            Bd(n)
            Bg(n)
          "
        >
          <Button>
            Log In
          </Button>
        </button>
      )}
    </Auth>
  </div>
);

export default withRouter(LoginPage);
```

**Comment by luisrudge** [comment]
thanks @VinSpee can you build a simple repro so we can isolate the issue?

**Comment by nicosabena** [comment]
I've seen this happening sometimes if the authorize request is made from a different origin than the callback URL. E.g. you navigate to "http://myapp.com", and instead of redirecting first to "https://myapp.com", it goes directly to "https://yourtenant.auth0.com/authorize?...&redirect_uri=https://myapp.com" (notice the difference between "http://" and "https://").
Since Auth0.js stores the `state` in local storage before redirecting to Auth0 for later verification, you need to ensure that the origin where the authorize request originates is the same as the callback URL.

@luisrudge for easier troubleshooting, I might be a good idea to log in the console a little more data, like the state that came in the callback, and what was there in localStorage (no match?). Even a list of states present in LocalStorage might help.

**Comment by luisrudge** [comment]
@nicosabena that's a nice idea, but always logging that would not be good. Maybe we should have a debug mode (manually set localStorage or ?debug in the url or something).

**Comment by VinSpee** [comment]
Here's a minimal repro: 

code: https://github.com/VinSpee/auth0-debug
live: https://github.com/VinSpee/auth0-debug

**Comment by luisrudge** [comment]
@VinSpee are you having this issue with google apps only?

**Comment by luisrudge** [comment]
I tested your app a few times and I always get the profile back. Do I have to do something different to see the error?
![gh-state](https://user-images.githubusercontent.com/941075/36279397-293f5248-127e-11e8-97d5-9e03fb45ce9c.gif)

**Comment by VinSpee** [comment]
@luisrudge to be more clear: I am able to get the profile, but always get the console error:

> Object { error: "invalid_token", errorDescription: "`state` does not match." }

**Comment by luisrudge** [comment]
@VinSpee ah, right. Sorry I missed that! Does this happen only with google?

**Comment by VinSpee** [comment]
i've only tried in w/ google auth, I'll try with another provider

**Comment by VinSpee** [comment]
I just tried it w/ GitHub as the provider and got the same error:

>Object { error: "invalid_token", errorDescription: "state does not match." }

**Comment by luisrudge** [comment]
@VinSpee your code is running twice:

![image](https://user-images.githubusercontent.com/941075/36281294-50742b94-1284-11e8-9ce3-15117fafc098.png)

Every time you use the `<Auth>` component, you're creating a new instance of Lock, and this is messing up the state handler.

So, it runs twice because you use the component both in the index route and in child routes:
https://github.com/VinSpee/auth0-debug/blob/master/src/index.js#L20
https://github.com/VinSpee/auth0-debug/blob/master/src/Login.js#L6

We have a react sample [here](https://github.com/auth0-samples/auth0-react-samples/tree/embedded-login/01-Embedded-Login) if you want to take a look.

You're also shipping two versions of react, because auth0-lock is using react@15, so you need to add this to your package.json file:
```js
  "resolutions": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
```

**Comment by staab** [comment]
I've been having the same problem, and I've found a workaround which I'll describe below just because I saw a lot of google results for this error, which seemed to be caused by all kinds of different things. However, I *did* find the proper solution, which is to use `WebAuth.logout` rather than `buildAuthorizeUrl`:

```
export function logout() {
  webAuth.logout({
    clientID: process.env.REACT_APP_AUTH0_CLIENT_ID,
    responseType: 'token',
    redirectUri: window.location.origin,
  })
}
```

My problem was that I generated a logout url using `buildAuthorizeUrl` with auth0-js v9.4.2. When I do this though, I redirect to the url manually, so the `state` doesn't get set by auth0:

```
export function logout() {
  const state = randomId()

  // Save state to localstorage for Auth0
  // https://auth0.com/docs/protocols/oauth2/oauth-state
  localStorage.setItem('auth0-authorize', state)

  const domain = process.env.REACT_APP_AUTH0_DOMAIN
  const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID
  const returnTo = webAuth.client.buildAuthorizeUrl({
    clientID: clientId,
    responseType: 'token',
    redirectUri: window.location.origin,
    state,
  })

  const params = stringify({returnTo, client_id: clientId})

  window.location.assign(`https://${domain}/v2/logout?${params}`)
}
```

When someone hits the site and isn't authenticated, I redirect them to auth0 with `authorize`. This sets the state in a different place in localstorage (seems to be a randomly generated string). To handle both my custom logout state and the built-in logout state, I'm providing an options parameter to `parseHash` with the state set _only_ if my custom key is set (being sure to clear my custom one when I use it to avoid always rejecting one set by auth0). Here's my code:

```
function checkAuthResult(err, authResult) {
  if (err) {
    // If we tried to log them in automatically, redirect to auth0
    webAuth.authorize()
  } else if (!authResult) {
    // Try logging them automatically first
    // https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens
    webAuth.checkSession({}, checkAuthResult)
  } else if (authResult.accessToken) {
    resolve(authResult)
  }
}

// If we log out, auth0 doesn't set the state properly, so we have to do it manually.
// We can't do it every time though, because when they're trying to log from a url
// not generated by buildAuthorizeUrl, we need to let the default behavior work.
const state = localStorage.getItem('auth0-authorize')
const params = state ? {state} : {}

// Make sure to clear our custom state key
localStorage.setItem('auth0-authorize', '')

webAuth.parseHash(params, checkAuthResult)
```

So that's my worka

**Comment by luisrudge** [comment]
@staab not sure I understand: why are you setting a state when doing a log out?

**Comment by staab** [comment]
@luisrudge because I'm redirecting to the login page for auth0, which doubles as our landing page for folks who aren't signed in (I'm not using auth0-lock, and our software is login-only). As I understand it, there's no way to go to that page and have it successfully log someone in if `state` isn't set. Also, as far as I can tell, this is exactly what the `logout()` method was created for.

**Comment by luisrudge** [comment]
@staab 

to log in with the universal login page, you do:

```js
var options = {}; //anything you want, state is not required but you can use your own state here if you want
webAuth.authorize(options);
```

to log out from auth0, you do:
```js
var options = {}; //again, no state required
webAuth.logout(options);
```

I mean, you're free to call the /v2/logout endpoint by yourself (although I don't see the point in doing it manually), but there's no need to send a state to the logout endpoint.

**Comment by staab** [comment]
@luisrudge that's what I'm doing now (see the top of my original comment). I was mostly including my manual logout solution for posterity, since I hadn't seen the mistake I had made anywhere else after some googling.

After some more digging, it turns out that it's not logout that's passing `state`, I'm redirecting back to my app after logging out, then calling authorize, which passes state. I had missed that step. So you're right, `logout` doesn't use `state`.

**Comment by staab** [comment]
Ok, so I tried passing a `redirectUri` built using `buildAuthorizeUrl` with a custom managed state to get the app > logout > hosted login page redirect flow I want, but `logout` always returns a 302 with `Location: myappdomain` rather than the redirect_uri that gets passed via query parameters. I think this is what threw me off originally; is there a way to get `logout` to set the `Location` header to `mydomain.auth0.com/login?...` with a valid state/audience/etc?

**Comment by staab** [comment]
Ok, so I tried passing a `redirectUri` built using `buildAuthorizeUrl` with a custom managed state to get the app > logout > hosted login page redirect flow I want, but `logout` always returns a 302 with `Location: myappdomain` rather than the redirect_uri that gets passed via query parameters. I think this is what threw me off originally; is there a way to get `logout` to set the `Location` header to `mydomain.auth0.com/login?...` with a valid state/audience/etc?

**Comment by luisrudge** [comment]
`logout` expects a `returnTo` param, not `redirectUri`.


```js
logout({
  returnTo: 'https://myapp.com/login'
})
```

**Comment by luisrudge** [comment]
For reference: 
https://auth0.com/docs/libraries/auth0js/v9#logout
https://auth0.com/docs/api/authentication#logout

**Comment by staab** [comment]
Ah ok thanks, that did the trick.

Now that my credibility has been destroyed by not being able to read the documentation properly, is redirecting to the login page straight from the logout endpoint a common use case or am I an outlier? If it's common, it would be really nice for logout/buildAuthorizeUrl to handle setting `state` the same way `authorize` does.

**Comment by luisrudge** [comment]
from logout directly to the universal hosted login page is the first time I saw it 😝 
The best way to do what you want is:

your app > click logout > `webauth.logout({returnTo: 'https://myapp.com/login'})` > https://myapp.com/login > `webAuth.authorize()` > universal login page.

So, you create a step in between the logout and redirecting to the universal login page and, in this new step, you call authorize(). Then auth0.js will handle all the state and everything should work!

**Comment by luisrudge** [comment]
@bramski what was the error? we want to support objects so you can restore an app state if you need to

**Comment by bramski** [comment]
@luisrudge Here's the problem:
![screen shot 2018-04-11 at 5 20 50 pm](https://user-images.githubusercontent.com/421781/38649951-1dfac7ea-3dae-11e8-9e16-f09ecc8aff54.png)

**Comment by maneshom** [comment]
same error as @VinSpee .But it works fine with google chrome .In mozilla,Error showing only in the first time of login and after the cookie added it works.

**Comment by DarryllRobinson** [comment]
What was the final resolution for the error? I also get the 'state does not match' error the first time and it goes straight through the second.

**Comment by benschaaf** [comment]
@nicosabena mention of HTTP vs HTTPS made the difference for me.

I am now forcing all traffic to HTTPS and now all requests work.

Previously, a user would enter on HTTP and try to authenticate. The callback was set to send them back to the domain but on HTTPS, hence the mixed/non-matching state. As the callback was set to return to HTTPS, the second and all subsequently requests worked as expected. It was no longer mixed or not matching. It was HTTPS from there on out.

**Comment by sgentile** [comment]
> same error as @VinSpee .But it works fine with google chrome .In mozilla,Error showing only in the first time of login and after the cookie added it works.

Same here - except for me it's with certain Internet Explorer users (not all).   After several attempts it lets them in.    There is definitely a bug here, but the documentation fails to mention what causes this error and any attempts to solve it.

**Comment by sgentile** [comment]
Also, I think there might be a timing issue here.  It's as if it can't read the cookie (auth0 uses a cookie ?) the first time on the request/response.

> What was the final resolution for the error? I also get the 'state does not match' error the first time and it goes straight through the second.

Lastly, I am https to https - I get it both with http to https and https to https.

**Comment by DarryllRobinson** [comment]
When I changed the AUTH_CONFIG to the one below, it worked for me. I think there was an issue with the way the callback URL was being created but I'm not sure.

`export const AUTH_CONFIG = {
  domain: 'fcmcms.eu.auth0.com',
  clientId: 'f$%*$$%*$%$*%$*$$%$*y',
  callbackUrl: process.env.NODE_ENV === 'development' ? 'http://localhost:3000/callback' : 'https://domain.com/callback',
}`

**Comment by luisrudge** [comment]
@DarryllRobinson how it was before?

**Comment by nicosabena** [comment]
I want to summarize the two common causes I see in customer support related to this `state does not match` error (apologies for repeating the content of my previous post, but I'm adding a second cause here):

* Callback URL set to a different domain. E.g. your app started at the `http://myapp.com` and the callback is set to `https://myapp.com` (note the different `http` vs `https` scheme). Auth0.js/Lock store the `state` in local storage, which is not shared across different domains. In the `http`/`https` case, the correct approach is to redirect to the `https` scheme first and then initiate the login.
* A flow in the app is causing `parseHash` to be called twice. The first time it's run, the slot in local storage used for the specified state is cleared, so the second time you will always get this error. Make sure that your app only calls this once. Note that, by default, [Lock calls it automatically upon initialization if it finds a result in the location of the hosting window](https://auth0.com/docs/libraries/lock/v11/configuration#autoparsehash-boolean-).

**Comment by luisrudge** [comment]
Another **super** common case is when your users bookmark the /login endpoint instead of your app's url. This will cause the `parseHash` method to fail as well.

**Comment by DarryllRobinson** [comment]
> @DarryllRobinson how it was before?

Sorry, I meant to say I had updated it to: `callbackUrl: window.location.origin + '/callback'`

**Comment by therockstorm** [comment]
I get this error in Firefox with all extensions and Content Blocking disabled using the provided [sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/01-Login). To reproduce, login and then refresh the page, `"auth0-js": "9.8.2"`.

**Comment by enashnash** [comment]
> I want to summarize the two common causes I see in customer support related to this `state does not match` error (apologies for repeating the content of my previous post, but I'm adding a second cause here):
> 
> * Callback URL set to a different domain. E.g. your app started at the `http://myapp.com` and the callback is set to `https://myapp.com` (note the different `http` vs `https` scheme). Auth0.js/Lock store the `state` in local storage, which is not shared across different domains. In the `http`/`https` case, the correct approach is to redirect to the `https` scheme first and then initiate the login.
> * A flow in the app is causing `parseHash` to be called twice. The first time it's run, the slot in local storage used for the specified state is cleared, so the second time you will always get this error. Make sure that your app only calls this once. Note that, by default, [Lock calls it automatically upon initialization if it finds a result in the location of the hosting window](https://auth0.com/docs/libraries/lock/v11/configuration#autoparsehash-boolean-).

I noticed that my `/callback` page was being called a second time by `browser-sync`. The error went away when I added the following to my `browser-sync` configuration (https://browsersync.io/docs/options#option-snippetOptions):
```
  snippetOptions: {
    ignorePaths: "callback"
  }
```

**Comment by strongSoda** [comment]
Hello,

I have made this todo app with auth0 [todo app](https://hasuratodowithapollo.herokuapp.com/). Everything works fine on chrome & edge. On Mozilla, I am able to login/signup, and after that even add new todos, but I can't update existing todos, the only thing that shows up in the console is `state` does not match. This is also the case when https to https.

**Comment by therockstorm** [comment]
@luisrudge Can we get this re-opened? It's still an issue in Firefox.

**Comment by therockstorm** [comment]
The repro project is the official Auth0 React Sample Login project, https://github.com/auth0-samples/auth0-react-samples/tree/master/01-Login. Clone it, set the `domain` and `clientId` in `auth0-variables.js`, run `npm start`, login, and refresh the page in Firefox. You'll get "`state` does not match.".

**Comment by fourthmeal70** [comment]
I am also seeing this problem in Firefox and am able to reproduce it using the official Auth0 Vue sample Login Project: https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login 

I notice when I refresh the page it goes back to the callback url. Something with how Firefox treats a page refresh?

**Comment by luisrudge** [comment]
Can you record a HAR file of this? I just came back from vacations and I'll take a look at this during this week.

**Comment by fourthmeal70** [comment]
Attached is a har file: 
[Archive 19-01-07 09-14-54.zip](https://github.com/auth0/auth0.js/files/2733081/Archive.19-01-07.09-14-54.zip)

**Comment by strongSoda** [comment]
@luisrudge  here's the HAR file for the todo app I created https://drive.google.com/drive/folders/1LHAy05zQTvuc1MQJjx7OWYSEYESRwJe-?usp=sharing

**Comment by sgentile** [comment]
One of the main issues with this bug is Auth0 is missing something in their
explanation.  Everyone says 'make sure not sending twice', 'http to https'
etc... but it's more than that.

I've tried all the above, sent HAR files, and still haven't had an
explanation of the issue.

Works fine in all browsers but IE.   In IE, I've had to do a retry work
around to get past this issue.

**Comment by fourthmeal70** [comment]
Since this is definitely still an issue and @luisrudge is investigating, should this issue get re-opened? Or should a new issue be submitted?

**Comment by luisrudge** [comment]
I'll start with this in a few hours. If there's an issue with the SDK, I'll reopen it.

**Comment by luisrudge** [comment]
About Firefox: this is a firefox/sample issue and has nothing to do with the SDK itself. It's exactly what @fourthmeal70 said.. When you click refresh page in firefox, it seems to use the previous URL for some reason, causing the page to try to parseHash again, which will break. I'll redirect the issue to our samples team.

**Comment by luisrudge** [comment]
@sgentile what version of IE is this happening?

**Comment by sgentile** [comment]
IE 11

Difficult to reproduce, only happened to users inside a domain.   Same
users with Firefox and Chrome worked fine

**Comment by luisrudge** [comment]
@sgentile what doesn”inside a domain” means?

**Comment by KevinKons** [comment]
> I want to summarize the two common causes I see in customer support related to this `state does not match` error (apologies for repeating the content of my previous post, but I'm adding a second cause here):
> 
> * Callback URL set to a different domain. E.g. your app started at the `http://myapp.com` and the callback is set to `https://myapp.com` (note the different `http` vs `https` scheme). Auth0.js/Lock store the `state` in local storage, which is not shared across different domains. In the `http`/`https` case, the correct approach is to redirect to the `https` scheme first and then initiate the login.
> * A flow in the app is causing `parseHash` to be called twice. The first time it's run, the slot in local storage used for the specified state is cleared, so the second time you will always get this error. Make sure that your app only calls this once. Note that, by default, [Lock calls it automatically upon initialization if it finds a result in the location of the hosting window](https://auth0.com/docs/libraries/lock/v11/configuration#autoparsehash-boolean-).

Can you talk more about the correct approach of the first situation? I didnt really understand what i have to do

**Comment by luisrudge** [comment]
@KevinKons make sure both your app and redirect url are in the same domain.

**Comment by KevinKons** [comment]
> @KevinKons make sure both your app and redirect url are in the same domain.

They are in the same domain. My website is in http://integralse.com.br and my callback url are http://integralse.com.br/callback
My website is in http, is it wrong? Should it be in https to work properly with auth 0?

**Comment by KevinKons** [comment]
When I test my application in localhost it work just fine but when i try to run it in the web-server it does not work. I am running it with docker

**Comment by luisrudge** [comment]
Do you have a repro I can test?

**Comment by KevinKons** [comment]
do you mean the source code?

**Comment by luisrudge** [comment]
I mean try to isolate the authentication code and make it fail so I can take a look or give me instructions on how to login in your application

**Comment by KevinKons** [comment]
I can give you instructions on how to login, I'll send you an email in luis@luisrudge.net with credentials. Ok?

**Comment by luisrudge** [comment]
before doing that, please send a HAR file with all the authentication requests to luis.rudge@auth0.com

**Comment by KevinKons** [comment]
ok

**Comment by longfellowone** [comment]
Also having this issue, Firefox 67 on linux. Using the ReactJS demo app, untouched

**Comment by therockstorm** [comment]
> About Firefox: this is a firefox/sample issue and has nothing to do with the SDK itself. It's exactly what @fourthmeal70 said.. When you click refresh page in firefox, it seems to use the previous URL for some reason, causing the page to try to parseHash again, which will break. I'll redirect the issue to our samples team.

This is still happening in the sample app, @luisrudge. You mentioned redirecting it o that team, could you provide a link so I can follow that issue?

**Comment by trusktr** [comment]
> Callback URL set to a different domain. E.g. your app started at the http://myapp.com and the callback is set to https://myapp.com

Can a trailing slash make a difference? f.e. `http://localhost:9080` vs `http://localhost:9080/`?

**Comment by luisrudge** [comment]
Yes

Luís
________________________________
De: Joe Pea <notifications@github.com>
Enviado: Tuesday, April 30, 2019 12:09:26 AM
Para: auth0/auth0.js
Cc: Luís Rudge; Mention
Assunto: Re: [auth0/auth0.js] Invalid token - `state` does not match (#655)


Callback URL set to a different domain. E.g. your app started at the http://myapp.com<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmyapp.com&data=02%7C01%7C%7Cbeb1d13bab5848c7521a08d6cd1941cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636921905686693712&sdata=5EgXex4ha4p%2FsXxqWlRahmVzT6nzhmbjnvCw%2B42RaGM%3D&reserved=0> and the callback is set to https://myapp.com<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmyapp.com&data=02%7C01%7C%7Cbeb1d13bab5848c7521a08d6cd1941cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636921905686703717&sdata=25bVtG3sK8XyfhwrhfKC5rEsPz17XaIR3Z1Llq2f7QQ%3D&reserved=0>

Can a trailing slash make a difference? f.e. http://localhost:9080 vs http://localhost:9080/?

**Comment by trusktr** [comment]
@luisrudge Not sure I understand correctly. So for example, if we're on `http://localhost:1234/foo/` then `redirectUrl` or `returnTo` (or both?) need to also be exactly `http://localhost:1234/foo/`?

**Comment by trusktr** [comment]
In all sincerity, this ``` `state` does not match. ``` message is not at all helpful. The above comments mention some "possible causes", but it's still not clear. It'd be nice if there was a clear reason stated (in the error output) what the specific problem is.

**Comment by trusktr** [comment]
I *think* I'm using auth0-lock like normal. I've constructed it, and given it some options. Then when I try to log in, I get the above error.

After stepping through auth0 code, I see that `StorageHandler.setItem` is being called twice with the same value. Eventually, `WebAuth.parseHash` is called internally, and this seems related to the above problem of 

> app is causing parseHash to be called twice

But, I'm not calling `parseHash`, I'm just using `Auth0Lock`. What can be causing the Lock to indirectly cause that `parseHash`-called-twice problem?

**Comment by trusktr** [comment]
Yep, I can confirm by stepping through `auth0-js` code (used by `auth0-lock`) that `parseHash` is called twice, which ultimately calls `WebAuth.validateAuthenticationResponse` twice, and that second call outputs that **_cryptic_** error message.

**Comment by trusktr** [comment]
CRAAAAAP.

So I'm using `lock.resumeAuth`, but I did not set auth0-lock Lock option `autoParseHash` to false, so this caused `parseHash` to be called twice. So I solved that issue by setting `autoParseHash` to false.

Note, in the [`autoParseHash`](https://auth0.com/docs/libraries/lock/v11/configuration#autoparsehash-boolean-) or [`resumeAuth`](https://auth0.com/docs/libraries/lock/v11/api#resumeauth-) documentation, _there is not a single mention of this cryptic error_!!!!

However, now that I've solved that problem, and I can verify that `parseHash` is not being called twice, now something else is causing _the same error_.

It'd be very nice if for the Auth0 team to take this problem seriously and make it more clear, both in the documentation, and by providing contextual error messages rather than ``` `state` does not match. ```.

Now I'll continue to step through auth0 code in Chrome devtools until I find the second source of the error, which as end user wish I didn't have to do.

**Comment by luisrudge** [comment]
> @luisrudge Not sure I understand correctly. So for example, if we're on http://localhost:1234/foo/ then either redirectUrl or returnTo (or both?) need to also be exactly http://localhost:1234/foo/?

If you want to redirect to `http://localhost:1234/foo/`, then it needs to match that url exactly (`http://localhost:1234/foo` is not the same as `http://localhost:1234/foo/` in this case).

> In all sincerity, this `state` does not match. message is not at all helpful. The above comments mention some "possible causes", but it's still not clear. It'd be nice if there was a clear reason (in the error output) stating what the specific problem is.

I agree, but auth0-js doesn't have enough information on why the state didn't match. We can add the possible causes that we mentioned in this thread, but we can't pin point exactly what happened because there's simply not enough info. From Auth0-js's perspective, all we know is that we were expecting a string to be present in a cookie, but the string is not there.


> CRAAAAAP.

> So I'm using lock.resumeAuth, but I did not set auth0-lock Lock option autoParseHash to false, so this caused parseHash to be called twice. I solved that issue by setting autoParseHash to false.

> Note, in the autoParseHash or resumeAuth documentation, there is not a single mention of this cryptic error!!!!

I opened a PR to make it clearer that you can only use `resumeAuth` when you use `autoParseHash:false`: https://github.com/auth0/docs/pull/7569

> It'd be very nice for the Auth0 team to take this problem seriously and make it more clear, both in the documentation, and by providing contextual error messages rather than `state` does not match..

See me previous message about not having enough context to pinpoint the issue

> Now I'll continue to step through auth0 code in Chrome devtools until I find the second source of the error, which as paying customer wish I didn't have to do.

Feel free to ping our amazing support team at http://support.auth0.com to get some help figuring out your issue.

> If anything, a prorated refund of the wasted time would be very welcome, and would make all frustrations go away, because I need to be working on the business product where I work, instead of wasting resources.

I can't do that, but feel free to ping someone at http://support.auth0.com with your frustrations to see what they can do.

**Comment by trusktr** [comment]
Thanks, I left a comment in the PR, I do thinking mentioning the exact ``` `state` does not match ``` message would be helpful.

Alright, I've found that inside of `WebAuth.prototype.validateAuthenticationResponse`, `options.state` is `undefined`, which causes the error.

Any idea why `options.state` inside `WebAuth.prototype.validateAuthenticationResponse` can be undefined?

**Comment by trusktr** [comment]
Docs say:

> Auth0.js, when used in single-page applications, handles the state generation and validation automatically if not specified.

I'm not supplying a `state` value, so shouldn't it be automatically generated?

**Comment by luisrudge** [comment]
@trusktr it is, unless you're using IE10 (no support to crypto)

**Comment by trusktr** [comment]
I'm in Electron with Chrome 66.0.3359.181.

**Comment by trusktr** [comment]
Looks like the `Auth0Lock` constructor is calling the `Auth0APIClient` constructor, and the `options` that it passes into that has `state` as `undefined`. Eventually, `WebAuth.prototype.validateAuthenticationResponse` reads the undefined value from `Auth0APIClient.authOpt.state`, which is undefined.

**Comment by luisrudge** [comment]
FYI, Auth0.js and Lock do not support Electron. More context [here](https://community.auth0.com/t/failed-by-cors-on-signup/13374/9). We have some guidance on how to build electron apps with Auth0 here: https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/

**Comment by trusktr** [comment]
Still, any idea why `state` is `undefined`?

**Comment by trusktr** [comment]
Here's another question: if we manually supply a value, then it won't be undefined. What sort of value should we supply there?

**Comment by trusktr** [comment]
Okay, even if I supply a hard-coded value for `auth.params.state` in `Auth0Lock` options, I still get the same error, in `WebAuth.prototype.validateAuthenticationResponse` I still see `options.state` is `undefined`.

**Comment by trusktr** [comment]
I see `TransactionManager.prototype.process` is not called before the error happens, and the default state handling is in that method.

Am I calling `lock.resumeAuth` too early? Do I need to wait for something before calling it in my entry point?

**Comment by trusktr** [comment]
If `autoParseHash` is set to `false`, is there anything we need to do besides call `lock.resumeAuth` with the hash?

**Comment by luisrudge** [comment]
@trusktr do you want to publish a repro somewhere that I can take a look? I feel like you're trying to dig into the internals too much and this feature is working as expected, so it should be an integration issue
