### ISSUE TITLE
Logout 'returnTo' not working with federated option 

### ISSUE THREAD

**Issue by SteveALee** [auth0/auth0.js#660]
```auth0.logout({ federated: true, returnTo: 'localhost:3000/login' })```

I'm using google

when federated is enabled I do not ever get back to my login page. Rather I get taken to the Google choose account form and after login in that then goes to the google account home page. 

Here's the network F12 log
```
302 GET logout?client_id=<XXX>&federated=true&returnTo=http://localhost:3000/login&auth0Client=<XXX> alwaysinmind.eu.auth0.com
302 GET logout accounts.google.com
200 GET Logout2?ilo=1&ils=s.youtube,s.GB&ilc=0&continue=https://accounts.google.com/ServiceLogin&zx=1975721742 accounts.youtube.com
200 GET Logout2?ilo=1&ils=s.GB&ilc=1&continue=https://accounts.google.com/ServiceLogin&zx=1603405200 www.google.co.uk
```

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can assist you and ping the correct team that handles this scenario. Thanks 🎉

**Comment by SteveALee** [comment]
I also found if the ```federated``` member is there at all it is treated as true. if set to `false` or `'false'` you are still logged out of the IdP

**Comment by SteveALee** [comment]
@luisrudge If I follow that link it only offer community or sales - not support ?

**Comment by luisrudge** [comment]
@SteveALee We only provide support for paid customers. Customers with the free plan can use our community forum, which also has support engineers answering questions everyday, but have a low priority. Please create a post in the forum and paste it here. I'll ping someone internally about this.

**Comment by SteveALee** [comment]
AH - I can't sign in it's giving errors.  Iwas signed in then it says singn in and create and now I can't sign in or out :(

It should not be this hard!!!

**Comment by SteveALee** [comment]
Tried in another browser

```
Problem processing your login request
We're sorry, but there was a problem processing your login request from the Identity Provider. Common causes for this error include:
A user with the same username or email already exists on this site.
There was an issue decoding the information sent from the Identity Provider.
Please contact your system administrators for more help in resolving this issue.


```

**Comment by SteveALee** [comment]
@luisrudge I give up. It's impossible for me to create a support ticket. :(

**Comment by luisrudge** [comment]
I'm so sorry! So I'm pinging two teams internally. The support center team and also the server team. They're isolated issues, but I'm reporting them both. I'll get back to you when they get back to me.

**Comment by SteveALee** [comment]
Thank you :)

I stuck in an error loop on the community site. Even if I logout google.

**Comment by SteveALee** [comment]
More info - the [logout docs](https://auth0.com/docs/logout) say federated is just a name with out a value but the SDK code is passing true / false. That obviously need addressing as well

`https://alwaysinmind.eu.auth0.com/v2/logout?federated`

**Comment by luisrudge** [comment]
@SteveALee I'm fixing this as we speak. 

About the support center, are you trying to log in with the same account that you use in the dashboard?

**Comment by luisrudge** [comment]
@SteveALee I just got confirmation from the server team: we redirect to `accounts.google.com/logout` as you saw. Google, however, doesn't use the redirect_uri in the logout like other federated connections do, so you can't go back to your app when using google. There's more information (and workarounds) here: https://stackoverflow.com/a/4202318

**Comment by SteveALee** [comment]
I think so - I always use the same email

**Comment by SteveALee** [comment]
@luisrudge Great stuff - or rather not such great stuff ;( But at least I have some things to try, all be it a tad messy.

thanks

**Comment by jerdog** [comment]
Hey @SteveALee - I can help fix your issue logging into the community which is caused by someone else having the same "email username" as you. Our existing platform has some challenges with that and we're moving away from that to something a lot more user-friendly and powerful. I will need your email address you're trying to login with - feel free to DM that to me on Twitter @IamJerdog

**Comment by SteveALee** [comment]
@ jerdog  Thanks!

steve@opendirective.com is me 

I also logged in via GitHub which uses the same email so perhaps that caused the problem - I use it everywhere, including for my auth0 account :)

**Comment by SteveALee** [comment]
@jerdog ^^^

**Comment by jerdog** [comment]
and yeah - that's the problem. I've created you an account and you should be good to go now. Might require a cache wipe

**Comment by SteveALee** [comment]
I'm in tah!
