### ISSUE TITLE
Are we allowed to use appState?

### ISSUE THREAD

**Issue by jeffijoe** [auth0/auth0.js#662]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [x] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [x] Auth0.js version 9.2.2

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

----

I'm trying to pass some info to the hosted login page and get it back as well.

I noticed by `console.log`ing the WebAuth result from ´parseHash` that there is an `appState` parameter which does not seem to be documented.

By setting it to an object, sure enough I got it back again, which is great. Although I was not able to access it on the hosted login page. :(

Is this a valid way to preserve state between redirects? Cause I couldn't find any documentation on it.

When using it though, I got a warning from `auth0-js` that the `app_state` (notice the underscore rather than camelCase) is not an allowed parameter.

```js
new auth0.WebAuth({ ... }).authorize({ appState: { a: 1, b: 2 } })
```

**Comment by luisrudge** [comment]
You can use it just fine. But this won't be shared between your app and the hosted login page (or vice versa). The appState is a **local** state.

**Comment by jeffijoe** [comment]
Got it, where is `appState` documented?

**Comment by luisrudge** [comment]
It isn't 😁

**Comment by jeffijoe** [comment]
Ah, fair enough 😄

**Comment by jrmc223** [comment]
Mind if I document it?

**Comment by jrmc223** [comment]
@luisrudge Thanks for this, otherwise I would have to reimplement a lot of auth0.
I am willing to add documentation for it if possible.

**Comment by luisrudge** [comment]
@jrmc223 You can send a PR to the README if you want. THanks!
