### ISSUE TITLE
JSDocs: Wrong method signature for renewAuth

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/auth0.js#675]
The jsdocs for the method `renewAuth` is auto-generated as `renewAuth(options)` while it should be `renewAuth(options, cb)`. The method is async and needs to be passed a callback.

js-docs: https://auth0.github.io/auth0.js/global.html#renewAuth

code method: https://github.com/auth0/auth0.js/blob/95d811f752b908049027e4d4036fe8753aaaab1e/src/web-auth/index.js#L308

**Comment by luisrudge** [comment]
fixed https://github.com/auth0/auth0.js/pull/674
