### ISSUE TITLE
Call signup from api without enabling public signup?

### ISSUE THREAD

**Issue by jmargaglione** [auth0/auth0.js#679]
I am using the auth0-js package in a React application, and I am trying to use the signup method.  I turned off Public Signups on my database connection, as I want people to go through my signup process instead of just using the Signup tab on the lock widget. According to the options description:  "Check this if you want to prevent sign ups to your application. You will still be able to create users with your api credentials or from the dashboard."

Here is my code:

```js
auth0 = new auth0.WebAuth({
		domain: AUTH_CONFIG.domain,
		clientID: AUTH_CONFIG.clientId,
		redirectUri: AUTH_CONFIG.callbackUrl,
		audience: `https://${AUTH_CONFIG.domain}/userinfo`,
		responseType: 'token id_token',
		scope: 'openid profile app_metadata user_metadata'
	});

auth0.signup({
		connection: 'Username-Password-Authentication',
		email: user.email,
		password: user.password
	},
	(err, result) => {
		if(err) return logger.warn('Something went wrong', err);
		else {
			logger.info('result from auth0 signup/login', result);
		}
	});
```

The result from this call is '400 public signup is disabled'.

Since I am using the API with my credentials, I assumed this would work.  Is there a different API I need to be using, or other options I need to pass?

Thanks.

**Comment by luisrudge** [comment]
You need to use a backend created by you to handle user creation using our Management API.

> You will still be able to create users with your api credentials or from the dashboard.

This is the management API you need to use: https://auth0.com/docs/api/management/v2#!/Users/post_users

Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
