### ISSUE TITLE
Firefox signing issue 58.0.2 (64-bit)

### ISSUE THREAD

**Issue by altras** [auth0/auth0.js#680]
Hello!

We're using auth0js version `9.2.3`. On Firefox 58.0.2 (64-bit), macOS 10.13.3 (17D47) the following error is happening on regular and private browsing: 

[TypeError: keyInfo is undefined](https://trello-attachments.s3.amazonaws.com/5a7b0e1a21b3052415861273/5a90298ab01f492e163b6416/29f1eb118210572c2a492f262bc9cd60/Feb-23-2018_16-06-55.mp4) 

I've narrowed down the exception to https://github.com/auth0/idtoken-verifier/blob/4e982bc4db9a5110edf4f80501b63202360ed884/src/index.js#L197 but I'm not very sure if it's an issue within idtoken-verified? or maybe from its dependency on superagent? or maybe from our auth0 dashboard settings? 

Inspecting the error we receive from [https://github.com/auth0/auth0.js#api](parseHash):

```
error: "invalid_token"
errorDescription: "Request has been terminated\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."
```

Have you stumbled upon such issue before?

On Chrome 64.0.3282.186 (Official Build) (64-bit) the signing process works as expected :)

**Comment by luisrudge** [comment]
I just tested [this](https://github.com/auth0/lock/blob/master/support/index.html) page with this additional configuration:

```js
auth: {
        responseType: 'token id_token'
      }
```
This works just fine in the same setup you mentioned:

![image](https://user-images.githubusercontent.com/941075/36793723-e7566494-1c7c-11e8-9627-ed83daf56475.png)

This doesn't look like a bug in the SDK, more like a configuration issue. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by rkoberg** [comment]
I just tried too and it did not work in FF, but did in Chrome, Safari, & Opera. Will get in touch with support. Thanks.

**Comment by bas080** [comment]
I have had the same issue and the same error.

```
errorDescription: "Request has been terminated\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."
```
