### ISSUE TITLE
Fixing the bug "inconsistent bug handling" with #667 broke semver

### ISSUE THREAD

**Issue by Pyrolistical** [auth0/auth0.js#686]
I was on v9.2.3, but when I updated to v9.3.1 I ran into this change: https://github.com/auth0/auth0.js/pull/667

This caused `error.error` to become `error.code` and and `error.error_description` to be `error.description`. This is a breaking change! This kind of change should have been reserved for v10.

The backwards compatible way to would have been to _add_ `error.code` and `error.description`, but leave the old ones there until v10.

**Comment by luisrudge** [comment]
Hi, fix is here: https://github.com/auth0/auth0.js/pull/685
 🎉 
We'll release it shortly
