### ISSUE TITLE
login() with email causes /authorize error

### ISSUE THREAD

**Issue by SteveALee** [auth0/auth0.js#691]
Auth0.js 9.3.2
Firefox  Dev edition on latest Windows
Code snippet using [auth0.js.login() here](https://github.com/AlwaysInMind/aim-web-app/blob/master/client/src/drivers/auth.js#L58-L69) 

Browser console warning  - 'Following parameters are not allowed on the `/authorize` endpoint: [email]'

But login appears to work fine

**Comment by luisrudge** [comment]
are you calling this inside the hosted login page?

**Comment by luisrudge** [comment]
I guess you aren't, since this is part of your app. I'm not sure what's going on: [This](https://github.com/auth0/auth0.js/blob/master/example/index.html#L250) code doesn't throw the warning.

**Comment by luisrudge** [comment]
ahh, sorry. you're using `email` and we're not filtering that out 😁

**Comment by luisrudge** [comment]
The fix will be out in the next release

**Comment by SteveALee** [comment]
Problem seems to have gone. Was this the CDN hosted script changing?

**Comment by luisrudge** [comment]
what cdn link are you using? we didn't release anything

**Comment by SteveALee** [comment]
Please ignore - it *is* still happening

I was looking at 9.3.2 diffs trying to figure out what had changed and appeared to show a cdn lookup. My bad
