### ISSUE TITLE
Silent authentication via iframe fails in electron

### ISSUE THREAD

**Issue by coded-aesthetics** [auth0/auth0.js#699]
We are using electron 2.0.0-beta.2 (Chrome 61) and auth0 9.3.2.
The electron version is not significant since the behavior is the same with older versions.

When trying to do silent authentication with auth0.renewAuth we get the error net::ERR_BLOCK_BY_CLIENT and a login_required error is issued to the redirect_uri.
The auth0 cookie is present for our auth0 domain but it seems like it can't be read, because of security restrictions in electron.

I started to tinker with a webview based solution, but my knowledge of the implementation specifics is too limited to advance any further. If you think there is a solution I would be glad to help.

**Comment by luisrudge** [comment]
I'm not sure what the restrictions are, but you can call `webAuth.authorize({...yourParams, prompt: 'none'})`. This doesn't run in an iframe, so you'll probably see a window for a small amount of time. Does that work?

**Comment by coded-aesthetics** [comment]
Hey Luis, thanks for the reply!

I looked deeper into the problem...
Using checkSession returns a login_required, too.
What's more, if I log in on app startup and then navigate to the login again using authorize with the same configuration but **without** the prompt: 'none', so that I can see what is going on, it seems like the auth0 login page cannot remember me. The login screen shows a blank login dialog.

I then ran the example at https://github.com/auth0-samples/auth0-angular-samples/tree/master/05-Token-Renewal with our config and slightly modified it, so I was able to navigate to the login screen even if I had logged in before. Here I was getting a previously logged in as "my_email@here.com" and upon clicking it, my authentication was renewed, without me having to enter the password again.

I think that maybe the inability of the auth0 page at the login screen to remember me as a previously logged in user might somehow be connected to the silent auth renewal failing.

I could make out two differences between our electron app and the sample app. In the electron app the auth0 login screen the localStorage stayed empty, but in the example it was populated with entries like key -> com.auth0.auth.sIHrL_GFt6ZF5dObVOtpwuWeq91mr6EK, value -> {nonce: "...somenonce...}.
The second difference is, that in the example app after registering as a new user i was additionally prompted to grant permissions (Hi test@test.com, Idana Desktop No-Consent is requesting access to our idana tenant) This dialog does not appear in the electron app.

**Comment by luisrudge** [comment]
This doesn't look like a bug in the SDK, more like a configuration or environment issue. Since there's so many moving parts, I'd advise you to react to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by enzoaeneas** [comment]
I have the same problem when running our app in Chrome. The application (Angular 4+) is configured as a SPA and normal login flow works perfectly.
But if I hit F5, 'checkSession' fails with 'login_required' and I have to run 'authorize' again.
This shows me the user that I logged in under (Azure AD), but this is not "silent".
I do not see this behavior when using Edge or Firefox.

**Comment by enzoaeneas** [comment]
I figured it out - it is the issue with requiring third party cookies to be set. My browser was blocking third party cookies from being set and this prevented silent authentication flow from working in Chrome. Not exactly the most secure option when using the *.auth0.com domain, but fixable using custom domains I assume.
