### ISSUE TITLE
Update to newer url-join

### ISSUE THREAD

**Issue by edmorley** [auth0/auth0.js#701]
Hi!

auth0-js currently depends on [url-join](https://github.com/jfromaniello/url-join) 1.1.0, which was released 2016-04-05. The latest version of url-join is now v4.0.0:
https://github.com/jfromaniello/url-join/blob/master/CHANGELOG.md

Please can this dep be updated? (To pick up bug fixes and also ensure projects that use both auth0-js and url-join don't have to include two versions on the package in their bundle.)

Many thanks :-)

**Comment by luisrudge** [comment]
can you send a PR with that?

**Comment by luisrudge** [comment]
We'd also need the same pr for https://github.com/auth0/lock
