### ISSUE TITLE
Consider using a tool to automate dependency updates

### ISSUE THREAD

**Issue by edmorley** [auth0/auth0.js#702]
Hi!

auth0-js's dependencies are mostly up to date at the moment (with the exception of #701), however it would be great to (a) ensure this remains the case in the future, (b) reduce the amount of effort for the package maintainers.

At Mozilla many of our projects now make use of the [Renovate](https://renovateapp.com/) service (like Greenkeeper but with non-hacky yarn.lock support and IMO preferable UX) - so I was wondering if you'd be open to checking it out? 

Features of note:
* in addition to the standard GitHub app, there is a forking variant that opens PRs from a fork of the repo, thereby needing fewer permissions
* sensible defaults/UX to reduce noise (eg closing a breaking major version PR means Renovate won't pester you about that major version again, but will still open minor/point releases for the version you're on)
* highly customisable rules/schedules/grouping of related deps

Best wishes,

Ed

**Comment by luisrudge** [comment]
We're deciding how to this in a company wide rollout, so I'll close this specific issue knowing that, eventually, we'll decide and add to all repos.
