### ISSUE TITLE
Redirect to redirectUri after successful signup using webAuth

### ISSUE THREAD

**Issue by prabhakarreddy1234** [auth0/auth0.js#704]
I want to redirect user to a redirectUri after succesful signup. I don't see any option to do that right now with  auth0.js v9.  Can somebody point me in the right direction.

var webAuth = new auth0.WebAuth({
domain: ‘@Model.Domain’,
clientID: ‘@Model.ClientId’,
redirectUri: ‘@Model.CallbackUrl’,
responseType:‘code’
});

webAuth.signup({
connection: ‘Username-Password-Authentication’,
email: registerEmail.val(),
password: registerPassword.val(),
state: a0state
}, function (err) {
if (err)
displayRegisterError(err.code);
});

**Comment by luisrudge** [comment]
https://auth0.github.io/auth0.js/global.html#signupAndLogin

**Comment by prabhakarreddy1234** [comment]
Thanks @luisrudge 
When i use `webAuth.signupAndLogin` i get  `signupAndLogin` is not a found in `webAuth`.  I am just referring  auth0.js CDN . Do i need to load any other auth0 related js files to get it work ?

**Comment by prabhakarreddy1234** [comment]
Thanks @luisrudge 

I am using invitation flow. When user gets invitation he will be shown a signup page and he gets created, authorized and redirected to home page. Works fine. But i need to pass some `state` in this redirection.  I added additional `option` like `state:a0state`. But this is not being passed to  `redirectUri`.  Any help in this is highly appreciated.

 In short, i want to pass some state back to redirectUri in `signupAndLogin` function.
