### ISSUE TITLE
checkSession timeout instead of error 500 authorize Unable to construct sso user

### ISSUE THREAD

**Issue by jamesacres** [auth0/auth0.js#710]
This can be reproduced by deleting the user, then call checkSession.

Using auth0-js 9.3.3 I am seeing Error in console after calling checkSession with a user which did have an sso session but has since been deleted.

`iframe-handler.js:53 GET https://[domain].eu.auth0.com/authorize.. 500 ()`

Response from authorize has
`<strong>server_error</strong>: Unable to construct sso user.`

But the callback is not called until it times out, giving the following instead of the actual error
`{error: "timeout", error_description: "Timeout during executing web_message communication"}`

**Comment by luisrudge** [comment]
That's expected. The iframe's parent (auth0.js) doesn't have any information about the error being thrown inside the iframe, so we wait for a few seconds and then we throw a timeout. I can't help you with the `Unable to construct sso user` error, though. You'll have to reach out to our support team at https://support.auth0.com
