### ISSUE TITLE
checkSession() requires callback to be a function via assertion

### ISSUE THREAD

**Issue by bvalerius** [auth0/auth0.js#712]
I'm wondering if the assertion check for whether or not the "cb" parameter passed into `checkSession()` can be removed. Is it necessary? 

I'm currently migrating away from `renewAuth()` to `checkSession()` and I was able to `Bluebird.promisify()` renewAuth, but I can't with checkSession due to the assertion.

**Comment by luisrudge** [comment]
we have the same check in both methods:
https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L367
https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L433

Maybe it's something in your configuration?

**Comment by bvalerius** [comment]
Apparently I overlooked how I was calling the function. An empty or config object is required in the call. No issue here!
