### ISSUE TITLE
Redirect and Popup modes are inconsistent

### ISSUE THREAD

**Issue by mgonto** [auth0/auth0.js#72]
There're inconsistencies when using `redirect` and `popup` mode after the login has succeeded or failed. 

Let's see how they work now: 

### Code
```js
auth0.login({}, function(err, token, profile) {
  // first check for errors when authenticating or when getting the profile
  if (err) {
     // do something
  } 

  // save profile and token
  window.token = token;
  window.profile = profile
})
```

### Advantages

* Error for both Authentication and getting a profile is in a single point
* We don't have nested callbacks
* We can save the token and profile together

### Disadvantages

* The profile is fetched for us and we don't know/understand how.

## Redirect mode

```js
// login.js
auth.signin({});

// boot.js
var authHash = auth.parseHash(window.location.hash);
if (authHash && authHash.id_token) {
  window.token = authHash.id_token;
  auth.getProfile(authHash.id_token, function(err, profile) {
    // Check profile fetch errors
    if (err) {
      // do sth
    } 
    window.profile = profile;
  });
}
if (authHash && authHash.error) {
  // Handle authentication errors here
}
```

### Advantages

* We know everything that's going on. We know how the profile is fetched and when.

### Disadvantages
* We have nested callbacks
* We do error handling twice in 2 different places
* It requires much more code which doesn't add value to us

## Proposal

My proposal is to make `popup` and `redirect` mode consistent by making the redirect mode also return a callback with the profile and default to check  `window.location.hash`.

### Code for redirect

```js
auth.processAuthenticationHash(function(err, token, profile) {
  // first check for errors when authenticating or when getting the profile
  if (err) {
     // do something
  } 

  // save profile and token
  window.token = token;
  window.profile = profile
});
```

### Important parts

* Internally the `processAuthenticationHash` function will check if there's a hash or search. If there's not, it  just won't call the callback
* It'll do error handling for both authentication part as well as profile fetching

Thoughts?

@woloski @jfromaniello @cristiandouce

**Comment by jfromaniello** [comment]
@mgonto an api like the proposed one could be useful, but I won't call it `parseHash`, in my mind parseHash is similar to JSON.parse or qs.parse and nothing more.

Something like `parseHashAndGetProfile` or `getProfileFromHash` will be a better name

**Comment by tjanczuk** [comment]
Would `auth.parseHash` require the hash to be present (and call callback with error when absent), or would it be a no-op in case there is no hash (and don't call the callback)?

**Comment by mgonto** [comment]
Agreed on the new name.

Maybe `processAuthenticationHash` or something like that?

@tjanczuk that's a good question. I think a `noop` would be extremely confusing. I think we should add another method called `hasAuthenticationHash()`. The dev would call it before calling `processAuthenticationHash`. If he doesn't call it, then yes, he'd get an error. Thoughts?

**Comment by cristiandouce** [comment]
1) we should check `window.location.hash` as well as `window.location.search`.

The ask for `hasAuthenticationHash()` would still require 2 error handlings, am I rigth? So we end up doing the same with different naming... I think.

**Comment by mgonto** [comment]
`hasAuthenticationHash` would return true or false.

`processAuthenticationHash` would just have one error handler. Why do you think they'd be true? One which is both for authenticaiton and profile fetching like in `popup` mode.

@cristiandouce

**Comment by mgonto** [comment]
Updated proposal :)

**Comment by cristiandouce** [comment]
````js

// boot.js
var authHash = auth.parseHash(window.location.hash);
if (authHash && authHash.id_token) {
  window.token = authHash.id_token;
  auth.getProfile(authHash.id_token, function(err, profile) {
    // Check profile fetch errors
    if (err) {
      // do sth
    } 
    window.profile = profile;
  });
}
if (authHash && authHash.error) {
  // Handle authentication errors here
}
```

VS

````js

// boot.js
var hasHash= auth.hasAuthenticationHash();
if (authHash) {
  auth.parseHash(function(err, token, profile) {
    // first check for errors when authenticating or when getting the profile
    if (err) {
       // do something
    } 

    // save profile and token
    window.token = token;
    window.profile = profile
  });
}
```

Where do you handle the auth error that comes with the hash? I might be misunderstanding, but would the intention be to merge it with the first parameter of the callback?

**Comment by mgonto** [comment]
So the idea is to keep both the old and the new APIs I think. 

If you use `parseHash`, you'd not use `hasAuthenticationHash` and otherwise. Does that make sense @cristiandouce ?

**Comment by cristiandouce** [comment]
BTW, is it really needed to do the if check outside?

Can't it be processed inside the processAuthenticationHash method?

**Comment by mgonto** [comment]
@cristiandouce yes it can, but then in the callback function, you'd have to check the `error` to see which kind of error it was, and if it was a missing hash one, just ignore it. I think that's more work than an if before, thoughts?

**Comment by tjanczuk** [comment]
Does it make sense to surface the token at all if the error occurred during profile fetching?
