### ISSUE TITLE
Social login through going back in history fails

### ISSUE THREAD

**Issue by c10b10** [auth0/auth0.js#723]
Not sure if this fits here, but here it goes.

I've implemented authentication in a React app. 
When I click on login:

* the `WebAuth` object calls its `authorize` method
* the user gets redirected to a page where they login with they Google account, and then, 
* he gets redirected back to the app with the `id_token` query param in the url. Here I verify the token, and eventually I redirect the user back to the route they started from by replacing this history route. (I don't want them to be able to return to the url that contains the `id_token` query param).

Now when he goes back in the browser, he's taken to the Google login page. 

Here's the problem. If there (on the Google login page, after getting there by clicking on back), they click on their user to login, they get to `login.auth.com` error page that looks like this: http://hoarding.s3-eu-west-1.amazonaws.com/Screen-Shot-2018-03-29-17-41-57.png.

Can anybody explain:

1. Why? (I'm guessing some sort of nonce verification fails)
1. Can anything be done to fix this?

**Comment by luisrudge** [comment]
For this specific error, you'll have to get in touch with our support team at https://support.auth0.com, but it feels like this is some sort of state/nonce validation indeed. Even if the server supported this, the `parseHash` method would fail with `state doesn't match` error.
