### ISSUE TITLE
validateAuthenticationResponse null transaction state, undefined response state

### ISSUE THREAD

**Issue by Neaox** [auth0/auth0.js#730]
This appears to be a bug to me, but it might just be the way I am using it. Given the following code:

```
const auth0 = new WebAuth({
  domain: config.domain,
  clientID: config.clientId,
  audience: `https://${config.domain}/userinfo`,
  responseType: 'token id_token',
  redirectUri,
  scope: 'openid profile email'
})

auth0.login({
  email,
  password,
  realm: config.connection,
  popup: true,
  nonce: nonce(15)
}, cb)
```

The code fails in `validateAuthenticationResponse` because `transactionState` is `null`, but `parsedHash.state` is `undefined`

The following error occurs.

```
code: "invalid_token",
description: "`state` does not match."
```

~~ I recommend changing https://github.com/auth0/auth0.js/blob/09d08a796bcc5ff6f4c8e224d8ea4397e927c952/src/web-auth/index.js#L219 so that it resolves to `undefined` instead of `null`. I have attached a pull request (https://github.com/auth0/auth0.js/pull/729) that does this.~~

~~I'm unsure if there are cases where a null state would be returned with the response. Perhaps we need to check for `null` OR `undefined`?~~

The pull requests fails tests, is there something wrong with my setup?

Could the following line be changed? https://github.com/auth0/auth0.js/blob/09d08a796bcc5ff6f4c8e224d8ea4397e927c952/src/web-auth/index.js#L222

To:
```
var shouldBypassStateChecking = state == null && transactionState == null;
```

Essentially do not check the state if both are `null` or `undefined`?

**Comment by luisrudge** [comment]
how are you calling parseHash?

**Comment by Neaox** [comment]
I'm not calling it myself. `auth0.login` takes care of that.

https://auth0.com/docs/libraries/auth0js/v9#webauth-login-

`auth0.login` does the following:
* Calls `co/authenticate` with the `client_id`, `credential_type`, `password`, `realm` and `username`.  A `co_id`, `co_verifier` and `login_ticket` is returned.
* Calls `authorize` with the `client_id`, `response_type`, `redirect_url`, `scope`, `realm`, `nonce`, `login_ticket`, `response_mode` (`web_message`), `prompt` and `auth0Client`. - This call is done in a hidden iframe and sent back to the main page via message.
* The response including the state is verified (this is where it fails).

There is no hash to parse, the data is sent via message from the iframe.

**Comment by Neaox** [comment]
Upon further investigation it seems this issue happens since `v9.3.0` when the security fix was introduced. I don't think the changes made in `v9.3.0` account for this use case. This issue does not happen in `v9.2.3`.

**Comment by luisrudge** [comment]
someone just reported the same issue and I got 1 and 1 together and found the fix: https://github.com/auth0/auth0.js/pull/731

**Comment by Neaox** [comment]
Great! Thanks!!

**Comment by Neaox** [comment]
Any idea when this might be released?

**Comment by luisrudge** [comment]
I'll try to get it reviewed and released this week.

**Comment by Neaox** [comment]
Thanks!

**Comment by luisrudge** [comment]
Let's leave this issue open until the PR is merged 😁

**Comment by Neaox** [comment]
Sorry, my bad.
