### ISSUE TITLE
Fetch client settings - namely the passwordPolicy

### ISSUE THREAD

**Issue by jthegedus** [auth0/auth0.js#734]
Since this SDK allows signup with email and password and these are subject to the same password policy as defined in Auth0, it would make sense to 
1. support fetching a client's settings and password policy
2. expose a utility in the SDK to test a password against a policy

I created a request on the forum - https://community.auth0.com/t/request-password-policy-through-js-sdk/10646/1 - but didn't quite explain myself well.

It seems the Auth0 lock already performs the password policy request logic with these: 

```javascript
export function fetchClientSettings(clientID, clientBaseUrl, cb) {
  load({
    method: "setClient",
    url: urljoin(clientBaseUrl, 'client', `${clientID}.js?t${+new Date()}`),
    check: o => o && o.id === clientID,
    cb: cb
  });
}
```
* https://github.com/auth0/lock/blob/2ce38322d7ffc9485fc6c36dd2be5bdfd4482095/src/core/client/settings.js
* https://github.com/auth0/lock/blob/2ce38322d7ffc9485fc6c36dd2be5bdfd4482095/src/utils/cdn_utils.js

so maybe it wouldn't too much work to get that happening within this SDK?

As for having a password utility to validate a password against a policy client-side, I've no idea where to start...

I'm happy to contrib to any work on this feature request :+1:

**Comment by jthegedus** [comment]
I performed some more research and it seems odd that you can use the management API to create a connection with a passwordPolicy, but you cannot query a passwordPolicy through the management API.

**createConnection** allows these params:
```json
"passwordPolicy": "",
"password_history": "object",
"password_no_personal_info": "object",
"password_dictionary": "object",
```

**getConnection**:
fields: `options`

```json
"password_dictionary": {
  "enable": false
},
"password_no_personal_info": {
  "enable": false
},
"password_history": {
  "enable": false,
  "size": 5
}
```

It's odd that I can get all information around password settings except the `passwordPolicy`.

**Comment by luisrudge** [comment]
Hi. We liked your idea and we're adding it to our product ideas' backlog. Keep in mind that, if we decide to move forward with this feature, it will have to be available in all our SDKs as well, so it might take some time to get it all done.

I'm closing this issue so we can keep the issue list with actual bugs, but we can continue discussing it here if you want to share your thoughts.

**Comment by luisrudge** [comment]
getConnection only returns `passwordPolicy` when it's set to anything but 'none':

![image](https://user-images.githubusercontent.com/941075/38419383-a92bf898-3976-11e8-9b31-7b09f5af98cf.png)

**Comment by jthegedus** [comment]
Ah okay, thanks for reporting back!
