### ISSUE TITLE
Refactor how we process transactions

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#740]
```js
var params = objectHelper
    .merge(this.baseOptions, [
      'clientID',
      'responseType',
      'redirectUri',
      'scope',
      'audience',
      '_csrf',
      'state',
      '_intstate',
      'nonce'
    ])
    .with(options);
  params = this.transactionManager.process(params);
```

snippets like this are all over the place. Ideally, we should abstract this so we don't have to copy/paste everywhere

**Comment by luisrudge** [comment]
test

**Comment by lbalmaceda** [comment]
Worth noting that as of today, if you need to add or remove a value from that array you'll need to change it everywhere.

**Comment by luisrudge** [comment]
With #787, it was pretty clear this is a deeper issue with how we pick and choose which param goes in and out. Needs more thought and it will probably break users, so we'll leave this to the next major as a feature request.
