### ISSUE TITLE
Not properly handeling "Connection Timeout" and "Connection Refused" exceptions

### ISSUE THREAD

**Issue by patrickyoung** [auth0/auth0.js#75]
auth0.6.1.0.js is not handling "Connection Timeout" and "Connection Refused" exceptions.  

There was a recent fix to handle "Internet Disconnected" [commit 68aea5dee564c60ede71e0668468f7433f723f3b], but the fix does not cover the situation when the browser can't connect to Auth0 (for example: Auth0 service is down or some network issues).  The error reported is "invalid_password" which may be confusing to users.

**Comment by pose** [comment]
Hi @patrickyoung,

Can you try now? I've added a new error code named `connection_refused_timeout` for that scenario. You can find those changes in the new minor version `6.2.0`. Let me know if you find any issues.

Thanks in advance,

**Comment by patrickyoung** [comment]
@pose My testing shows both situations are properly handling TIMEOUT and CONNECTION_REFUSED exceptions.

**Comment by pose** [comment]
@patrickyoung Glad to hear that. Let me know if you find any other issues. Thanks!
