### ISSUE TITLE
IE10 does not have window.msCrypto available.

### ISSUE THREAD

**Issue by nicosabena** [auth0/auth0.js#750]
IE10 does not have `window.msCrypto`, which makes it impossible to generate a cryptographically secure random number. 

https://github.com/auth0/auth0.js/blob/b6f1c57098021a54e5a68ecc01c1fbaf88d4fa75/src/helper/random.js#L9

When this happens and you try to issue an `/authorize` request, you get:

```
A nonce is required.
```

We should provide a more informative message to point users in the right direction (like "this browser does not support generating a cryptographically secure nonce"), and possibly a troubleshooting paragraph somewhere about this. Also, if there's no good way to solve this, we need to clarify that IE 10 won't be supported for implicit flows.

**Comment by luisrudge** [comment]
There's no good way to do this in a secure way, so we shouldn't advise a client side solution. This is a docs issue, can you ping the docs team? Thanks!
