### ISSUE TITLE
Circular Dependencies Warning when Bundling with Rollup

### ISSUE THREAD

**Issue by bennypowers** [auth0/auth0.js#752]
When bundling with rollup and rollup-plugin-commonjs with options `{main: true}`, rollup complains of circular dependencies:

The circular reference in question occurs here:
## src/authentication/index.js:382
```js
Authentication.prototype.getSSOData = function(withActiveDirectories, cb) {
  /* istanbul ignore if  */
  if (!this.auth0) {
    // we can't import this in the constructor because it'd be a ciclic dependency
    var WebAuth = require('../web-auth/index'); // eslint-disable-line
    this.auth0 = new WebAuth(this.baseOptions);
  }
```
and here:
## src/web-auth/index.js:11
```js
var Authentication = require('../authentication');
```
- [x] Auth0.js version 9
- [x] Code snippet or sample project that reproduces the bug
## rollup.config.js
```js
export default {
  ...
  plugins: [commonjs({main: true})],
  ...
}
```
## import site 
```js
import { WebAuth } from 'auth0-js';
```

The bundle still builds, but the warnings are annoying. If it's possible to resolve the circular dependency, perhaps by extracting a common dependency out, or creating a new mutual consumer, that would be nice to have.

Thanks for providing this library.

**Comment by luisrudge** [comment]
It is not possible at this time without a massive refactor. We messed up in the latest major version and this is something we'll have to live with until the next one. It was added there to rollback an unintended breaking change we added by mistake. I'm sorry about the warnings :(
