### ISSUE TITLE
Auth0 Legacy Lock API Deprecation

### ISSUE THREAD

**Issue by KeshShan** [auth0/auth0.js#768]
I went through the Legacy Lock API Deprecation documentation provided [link][1]

I have few clarifications

Its mentioned that by July 16, 2018 deprecated services will be removed.

And the criteria are given to identify whether I will get affected or not, below listed

 - Use of `/usernamepassword/login` endpoint directly from applications
 - Use of `/user/ssodata` endpoint directly from applications

In my application I have integrated auth0-js and I been using `auth0.redirect.loginWithCredentials()` function to send the username and password along with connection (database connection).

This function actually calls `co/authenticate` REST end-point.Does my current implementation needs a migration, will I be affected by services that will be stopped by Jul 16.

Another question:
In the advanced settings of a tenant, its advised to disable the Legacy Lock API option under Migrations (see below image). If I do so I get pre-flighted error which is a CORS issue, any relation between this problem and previous question or how do I solve this issue

[![enter image description here][2]][2]

  [1]: https://auth0.com/docs/migrations/guides/legacy-lock-api-deprecation
  [2]: https://i.stack.imgur.com/eIM9W.png

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by KeshShan** [comment]
Hi @luisrudge Thanks for the guidance, I went with the approach of 'cross-origin verification page' to get rid of the legacy lock API, my tenant is still a trial one, not a paid one, so couldn't purchase custom-domain. I either don't wanna go for universal login, since I have my custom pages for login, signup and reset.

But I am concern with cross-origin verification approach when it comes to the support of the third party cookies. Its mentioned in the documentation that only few browser will only support cross-origin authentication when third-party cookies are disabled. 

What could you think is the best approach to go with

**Comment by luisrudge** [comment]
The recommended approach is using Universal Login. You can fully customize login/signup and the password reset page. If you don't want to go that route, then you'll have to use custom domains to get rid of the 3rd party cookies issue for authentication.

For further questions, please reach out at https://support.auth0.com.
