### ISSUE TITLE
Replace superagent with axios or isomorphic-fetch/whatwg-fetch

### ISSUE THREAD

**Issue by bkniffler** [auth0/auth0.js#769]
Hey, 
As a follow up to https://github.com/auth0/auth0.js/issues/446 I would like to bring this up again, since superagent is still kinda heavy for what it does, and there is good alternatives.

My preferred solution would be https://github.com/matthew-andrews/isomorphic-fetch with https://github.com/github/fetch for browsers and https://github.com/matthew-andrews/isomorphic-fetch for nodejs. 

What do you think?

**Comment by luisrudge** [comment]
In the grand schema of things, the size reduction (0.4kB ~ 2.5kB) is almost irrelevant to our scenario, which makes it not worth the rewrite.

Library | Size MINIFIED + GZIPPED
------------ | -------------
[auth0-js](https://bundlephobia.com/result?p=auth0-js@9.6.0) | 32.1kB
[superagent](https://bundlephobia.com/result?p=superagent@3.8.3) | 5.2kB
[whatwg-fetch](https://bundlephobia.com/result?p=whatwg-fetch@2.0.4) | 2.5kB
[axios](https://bundlephobia.com/result?p=axios@0.18.0) | 4.8kB

**Comment by NathanielHill** [comment]
https://bundlephobia.com/result?p=isomorphic-unfetch@2.1.1

627B MINIFIED + GZIPPED
