### ISSUE TITLE
No 'Access-Control-Allow-Origin'   when using webAuth.passwordlessVerify

### ISSUE THREAD

**Issue by cesarvarela** [auth0/auth0.js#771]
HI, I'm not being able to get the passwordless code verification to work.

I'm using this to send the code and it works:

```
webAuth.passwordlessStart({
            connection: 'sms',
            send: 'code',
            phoneNumber: phone
        }, function (err, res) {
            if (err) {
                reject(err)
            } else {
                resolve(res)
            }
        })
```

But when I try to verify it:
```
webAuth.passwordlessVerify({
            connection: 'sms',
            phoneNumber: phone,
            verificationCode: code
        }, function (err, res) {
            if (err) {
                reject(err)
            } else {
                resolve(res)
            }
        })
```

I get:

`Failed to load https://xxx.auth0.com/passwordless/verify: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.`

 And I already have domains I'm making the requests from both in `Allowed Callback URLs` and `Allowed Web Origins`

![image](https://user-images.githubusercontent.com/1172479/41125507-0d70427a-6a7b-11e8-9f5f-e970993ca332.png)

**Comment by luisrudge** [comment]
You have to use `passwordlessLogin` https://auth0.com/docs/libraries/auth0js/v9#verify-passwordless

**Comment by cesarvarela** [comment]
Thanks. Seems that method is missing from the typing definitions

**Comment by luisrudge** [comment]
We don't own the definitions, it's a community project.

**Comment by cesarvarela** [comment]
It's not here either: https://auth0.github.io/auth0.js/index.html

**Comment by luisrudge** [comment]
Ouch! Thanks for letting us know. It was a copy-paste error 😬 https://github.com/auth0/auth0.js/pull/775
