### ISSUE TITLE
winchan error thrown from popup.authorize

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#773]
On latest iOS Safari:

```js
const client = new auth0.WebAuth({
  responseType: 'token',
  domain: ...
  clientID: 
  audience:
  scope: 
})

client.popup.authorize(authOptions, cb)
```

![image](https://user-images.githubusercontent.com/251288/41187514-bcd6ab98-6b78-11e8-800c-b88f3ab6379c.png)

winchan line 188:

![image](https://user-images.githubusercontent.com/251288/41187525-edd368c6-6b78-11e8-9bf5-b2e8394c8059.png)

winchan line 194:

![image](https://user-images.githubusercontent.com/251288/41187534-0c1342d4-6b79-11e8-86d2-9d606197d459.png)

```
└─┬ auth0-js@9.4.2
  └── winchan@0.2.0
```

**Comment by luisrudge** [comment]
Can you build a repro? I just tested this in our test website (https://brucke.club) and it works: 

![image](https://user-images.githubusercontent.com/941075/41193130-bfd4debc-6bde-11e8-981a-08599fb19a23.png)

**Comment by luisrudge** [comment]
code from our test website:

```js
 $('#btn-ulp-popup').on('click', function() {
    webAuth.popup.authorize({});
  });
```
