### ISSUE TITLE
Invalid token and 'state' does not match error

### ISSUE THREAD

**Issue by DarryllRobinson** [auth0/auth0.js#777]
I am developing in React and suddenly have a problem the first time a user logs in. The error message "Invalid token and 'state' does not match error" pops up but if you try again, the process completes as expected. I have checked the logs which say the authentication was successful. I even tried using just the tutorial code to make sure it wasn't my code.

What I have noticed is if the username is pre-populated in the login widget, the process completes. If you have to enter the username and password, the error occurs.

I have updated to the latest auth0 version (9.2.2) and still the error happens. Please tell me what I need to do to get this fixed as it is causing major production issues.

**Comment by DarryllRobinson** [comment]
Hi @luisrudge 

I downloaded the tutorial for React logins [https://manage.auth0.com/#/applications/W9w3YzgENsp1zkT40TAUr7VxYVcyj6iN/quickstart](url) and only changed this line:

`callbackUrl: process.env.NODE_ENV === 'development' ? 'http://localhost:3000/callback' : 'https://www.stillproud.com/callback',`

I'm using Chrome as a browser. I haven't changed any settings for cookies.

The thing is, it used to work without any problem.

**Comment by luisrudge** [comment]
does the error happen in the stillproud.com website? can you provide me with credentials to test?

**Comment by DarryllRobinson** [comment]
Yes, it does. You're welcome to sign up through the login form. What I've noticed is the error occurs each time I open the website, i.e. the website can't be left open after you logout. Try this:

1) Sign up
2) Login
3) Logout
4) Close browser tab
5) Try login again

Every time I try to login and the form doesn't prompt me as a returning user, the error occurs.

**Comment by luisrudge** [comment]
Hi, I just tested the code from the quickstart (https://auth0.com/docs/quickstart/spa/react/01-login) and it worked as expected without errors (first time, or second time etc).

![image](https://user-images.githubusercontent.com/941075/41549224-855118ea-72fb-11e8-88f9-ceadd197b100.png)

Can you try with the quickstart and make sure it works?

**Comment by DarryllRobinson** [comment]
Sorry, it's night time on my side.

The localhost version works but the production version gives me the error.

![screen shot 2018-06-18 at 20 20 33](https://user-images.githubusercontent.com/16488006/41554487-48b06b0e-7335-11e8-92c0-79a357cf5e32.png)

**Comment by luisrudge** [comment]
what is in the console?

**Comment by DarryllRobinson** [comment]
![screen shot 2018-06-18 at 21 00 27](https://user-images.githubusercontent.com/16488006/41556330-bd439f72-733a-11e8-89de-5a5b1a89cc31.png)

**Comment by luisrudge** [comment]
Can you repro it here? https://centralized-login-sqlvqarbkk.now.sh/home

**Comment by DarryllRobinson** [comment]
Hi @luisrudge. I see now that my response didn't get through to you. I have tried the URL you provided and no error popped up.

**Comment by luisrudge** [comment]
@DarryllRobinson Then it's probably something in your project. The link I just provided is the quickstart without modifications. Can you try it again with a fresh download of the quickstart?

**Comment by luisrudge** [comment]
This is how I setup the variables by the way: https://zeit.co/luisrudge/centralized-login/sqlvqarbkk/source?f=src/Auth/auth0-variables.js

**Comment by DarryllRobinson** [comment]
@luisrudge My project was a fresh download of the quickstart but I'm happy to try again with your method of setting up the variables. Fingers crossed...

**Comment by DarryllRobinson** [comment]
@luisrudge I tried your way of setting up the variables and it worked!!! Thank you!!

**Comment by reybarcelo950** [comment]
@luisrudge I have the same problem with the state invalid, can you help me? This work fine but now is broken.

**Comment by luisrudge** [comment]
@reybarcelo950 this can happen because a variety of issues. We summarized a few of them here: https://github.com/auth0/auth0.js/issues/655#issuecomment-419966421
