### ISSUE TITLE
Needed: parameter to cause Auth0 not to persist an SSO cookie

### ISSUE THREAD

**Issue by douglas-treadwell** [auth0/auth0.js#779]
I'm using the Auth0 SDK.  I would like a user to be able to authenticate with Auth0 using passwordless auth, but then have the decision whether to remember the id_token we get in response be made within my application.  Currently, unless I call an explicit /logout, Auth0 remembers the user even if they close their browser.  This seems like it should be opt-in behavior, like a [ ] remember me button.  There seems to be no way using the current API (unless I'm not seeing something) to "uncheck the remember me button", which causes auth0 to prevent me from implementing something according to specification.

Any advice would be appreciated.  Maybe I am just not seeing something.

**Comment by luisrudge** [comment]
There's no way to control how the server manages its session. Once you authenticate, your session will be available for the server. You can try issuing a short-lived id_token. If you're using the Universal Login Page, you can also set the `rememberLastLogin: false` option to disable the "Last Time You Logged In With" screen.
