### ISSUE TITLE
Signup redirect is missing id_token

### ISSUE THREAD

**Issue by cesarvarela** [auth0/auth0.js#785]
With webAuth configured as this:

```
const webAuth = new WebAuth({
    domain: 'xxx.auth0.com',
    redirectUri: ${window.location.origin}/SignUp,
    clientID: ''xxx',
    responseType: 'token id_token',
})
```

And after calling it like this:

```
webAuth.signup({
            connection: 'email',
            email,
            password,
            signupId: 'something'
        })
```

I get the email, click on the link and get the following error:

"response_type contains `id_token`, but the parsed hash does not contain an `id_token` property"

Facebook and Google connections are already working on the same page, and parse hash gets the proper `id_token`.

edit:

Debugging a bit seems that the validations fails because `state === undefined` and `transactionState === null` 
https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L227

**Comment by luisrudge** [comment]
`webauth.signup` by itself doesn't redirect. Also, I'm not sure what link is sent in your email, but you can only authenticate a user if you start and end the authentication process in the same browser window. 

If you want to signup and login automatically, you can use `webAuth.redirect.signupAndLogin`.
