### ISSUE TITLE
Sign-in popup with social medias is not working on IE 11: `auth0.popup.authorize`

### ISSUE THREAD

**Issue by fbarbare** [auth0/auth0.js#786]
Hi guys,

There is an issue when using the popup mode when logging in using social medias such as Twitter.
Once on the callback url, the popup does not close, the communication with the opener window seems to be broken.

The steps to reproduce are:
- Just configure a button to log you in with Twitter using popup mode
- Click the button
- It will open the twitter login page in a different window/tab
- Log in
- It will redirect you to your callback page
- Use the callback function to get the token etc...
- Here the popup stays open and the opener window does not log you in.

I'm using the latest version of Auth0.js

From what I could find out, there are problems with the `postMessage` and the `doPost` functions from WinChan. The communication between the iframe and the popup window seems broken as the popup never gets a message back from the parent.

I did not really get what the flow of the `postMessage` are on the IE version with the iframes.

Thanks.

PS: The issue is not happening because of the security options of Browsers as it happens on live servers.

**Comment by MartynenkoA** [comment]
how did you use callback function to get the token etc?

**Comment by luisrudge** [comment]
Does this happen with all browsers? Can you post a snippet of code you're using?

**Comment by luisrudge** [comment]
I couldn't repro this with latest. Can you please try again?
