### ISSUE TITLE
popup authorization

### ISSUE THREAD

**Issue by MartynenkoA** [auth0/auth0.js#788]
I`m trying to authorize in salesforce by popup,

```
var options = {
      nonce: "[nonce]",
      connection: this.config.getConfig().auth.isSandbox ? 'salesforce-sandbox' : 'salesforce'
    };
    var auth = new auth0.WebAuth({
      clientID: this.config.getConfig().auth.clientID,
      domain: this.config.getConfig().auth.domain,
      responseType: 'token id_token',
      audience: this.config.getConfig().auth.audience,
      redirectUri: this.config.getConfig().auth.redirectUri,
      scope: 'offline_access openid profile'
    });

    auth.popup.authorize(options, function(err, authResult) {

    });
```

then on callback page I have 

   ```
 var auth = new auth0.WebAuth({
      clientID: this.config.getConfig().auth.clientID,
      domain: this.config.getConfig().auth.domain,
      responseType: 'token id_token',
      audience: this.config.getConfig().auth.audience,
      redirectUri: this.config.getConfig().auth.redirectUri,
      scope: 'offline_access openid profile'
    });
    auth.popup.callback({
        //nonce: "[nonce]", // if you passed one when opening popup
      });
```

when I don`t use auth.popup.callback, then I still continue working in popup, when use it, popup is closing but in parent tab I have no access_token etc, and in
auth.popup.authorize(options, function(err, authResult) 
authResult is always undefined
err - sometimes code: "invalid_token", description: "`state` does not match."}
sometimes {error: "generic_error", errorDescription: "Something went wrong"}

I need, that when I login with salesforce, popup is opening, if authorization success, popup will close and parent tab refreshing

If I don`t use popup, it works, but I need popup

**Comment by luisrudge** [comment]
Hi, does it work if you use other connection other than salesforce?

**Comment by MartynenkoA** [comment]
I am using only salesforce, but I think I found a problem

**Comment by Rome-H** [comment]
@MartynenkoA - hello, if you've found what was causing problems, could you please share it here? I'm facing the exact same errors with popup authorization. thanks in advance!

**Comment by dillonbartkus** [comment]
I'm also having the same problem. Any progress?
