### ISSUE TITLE
Documentation regarding `responseType` seems to be outdated.

### ISSUE THREAD

**Issue by juliangieseke** [auth0/auth0.js#799]
In https://github.com/auth0/auth0.js/issues/536#issuecomment-339953777 documentation was updated in github `README.md`, but https://auth0.com/docs/libraries/auth0js/v9#available-parameters is still outdated.

…we just ran into that issue while trying to upgrade from v6 (which will be shut down on monday 😱)

(once we fixed our code, I'll revisit this and can try to update the issue - just wanted to provide a quick info for others running into the same issue)

**Comment by luisrudge** [comment]
Thanks! https://github.com/auth0/docs/pull/6396
