### ISSUE TITLE
version 9.7.0 breaks angular-auth0.js. for some reason folder "build" does not exist

### ISSUE THREAD

**Issue by GuyMograbi** [auth0/auth0.js#800]
We're getting `Uncaught Error: Auth0 must be loaded.`

**Comment by zurt** [comment]
Possibly related to a problem I just hit with 9.7.0 as well. As our app was going through a deployment. Got the following error: `Uncaught TypeError: Cannot read property 'WebAuth' of undefined`. So the quick fix was specifying `"auth0-js": "9.6.1"` in the package.json. I didn't have time to look deeper.

**Comment by luisrudge** [comment]
This was fixed in 9.7.1 - sorry about that!

**Comment by benmccallum** [comment]
Did this affect other versions? Not getting a build folder in node_modules/auth0-js on versions 8.10.1 or v8 latest (8.12.1). Surely we don't have to run a build of it ourselves, though the docs do elude to that?

**Comment by benmccallum** [comment]
Disregard, see it is a known issue here: https://github.com/auth0/auth0.js/issues/632
