### ISSUE TITLE
Duplicate 'dist' and 'build' directories in published package

### ISSUE THREAD

**Issue by edmorley** [auth0/auth0.js#805]
Hi 

After #801, there appear to now be two directories in the published package containing the same content:
https://unpkg.com/auth0-js@9.7.2/build/
https://unpkg.com/auth0-js@9.7.2/dist/

Given that the `build` directory presumably needs to exist for legacy reasons, presumably the solution would be to modify the (new) rollup config to output to `build` instead of `dist`?

**Comment by luisrudge** [comment]
We want to move to dist, eventually. That’s the default for services like unpkg etc. We still need build for legacy reasons, but we want new tools to depend on dist so we can change that in the next major version.

**Comment by edmorley** [comment]
Makes sense - thank you :-)
