### ISSUE TITLE
Document accessType option

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#807]
I see a couple issues in this repo that use the option `accessType: 'offline'`, but can't find it in the docs or code. Should it work inside a popup?

In my particular circumstance, I'm trying to get an IdP refresh token (google's), which requires "the parameter access_type=offline when calling the Auth0 /authorize endpoint" ([docs](https://auth0.com/docs/tokens/idp#get-an-identity-provider-access-token)), but after doing the below `client.popup.authorize()` call and doing `getUser` on the server, the refresh token isn't in the `identities` array:

client:
```js
const client = new auth0.WebAuth({
  domain: 'foo.auth0.com',
  clientID: '...',
  responseType: 'code',
  responseMode: 'query',
  redirectUri: 'http://foo.test/auth0',
  audience: 'foo.com',
  scope: 'openid profile email offline_access foo',
  accessType: 'offline'
})

client.popup.authorize({
    connection: 'google-oauth2',
    owp: true,
    popupOptions: { height: 623 } // make tall enough for content
  }, cb)
```

server:
```js
const auth0 = new ManagementClient({
  domain: 'foo.auth0.com',
  clientId: AUTH0_SERVER_CLIENT_ID,
  clientSecret: process.env.AUTH0_SECRET,
  scope: 'read:users read:users_app_metadata read:user_idp_tokens'
})

  const auth0User = await auth0.getUser({ id })
  console.log(auth0User)
```

logs:
```
...
identities:
[ { provider: 'google-oauth2',
access_token: ...
```

- [x] Code snippet or sample project that reproduces the bug

- [ ] Screenshots when appropriate
- [x] Auth0.js version
`9.6.1`
- [x] Browser & OS
Latest Mac Chrome, Mac 10.13.5.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. I don't have an answer for you right now. Can you please reach out to our amazing support team at https://support.auth0.com so they can better assist you? I'm sure they'll have this answer for you.

**Comment by lorensr** [comment]
@luisrudge Should either of these parameters to `auth0.WebAuth` work?

```
accessType: 'offline',
access_type: 'offline',
```

If they should, there might be a bug—according to my Network tab, neither result in a request to `/authorize` with an `access_type` query param.

If they shouldn't, is there a different way to get auth0-js to add that query param?

**Comment by luisrudge** [comment]
[This is a list of parameters that are accepted](https://github.com/auth0/auth0.js/blob/master/src/helper/parameters-whitelist.js#L28) parameters are accepted, but not all of them can be used as a global value (in the constructor like you're doing). You should add that to the `authorize` method.

**Comment by lorensr** [comment]
Thanks, that works!
