### ISSUE TITLE
Is there a way to pass locale to passwordlessStart and authorize?

### ISSUE THREAD

**Issue by cloud-walker** [auth0/auth0.js#813]
As the title say, I need to pass the user locale to ensure the right translations to emails and google / facebook login pages..

Its actually possible? Or I have to use the HTTP API directly?

Thanks in advance!

**Comment by luisrudge** [comment]
In the authorize call, you can use any valid parameter according to the spec. In this case, you can use [`ui_locales`](https://github.com/auth0/auth0.js/blob/master/src/helper/parameters-whitelist.js#L54).

For the passwordlessStart, you can [see the params in our api definition](https://auth0.com/docs/api/authentication#get-code-or-link). Maybe `authParams` might work for you?

**Comment by cloud-walker** [comment]
I've discovered that I need to manipulate the `Accept-Language` header in order to make it work (at least for passwordlessStart), I've done it with the bare API's..

I think that should be an option to facilitate this, 🤔
