### ISSUE TITLE
co/verifier localStorage key is not being removed after a successful login

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#816]

**Comment by thierryMic** [comment]
@luisrudge i am using your [nextJs example](https://github.com/luisrudge/next.js-auth0) i added
`localStorage.removeItem(`com.auth0.auth.${secret}`)` to the componentDidMount function of the call-back (signed-in page).

It works well for removing the nonce after successful log-ins but nonces keep building up for log-outs.

Do you agree with the approach for removing nonces on succesful log-ins and do you have any recommendations to get rid of the nonces that are created on logout?

**Comment by luisrudge** [comment]
This has to be fixed inside our library. You can add something to remove now but, ultimately, it's a bug we'll fix.

**Comment by luisrudge** [comment]
This was fixed by switching to a cookie with a short expiration date #817
