### ISSUE TITLE
`state` does not match and __EnableIdPInitiatedLogin setting

### ISSUE THREAD

**Issue by superzadeh** [auth0/auth0.js#818]
Hi there!

First of all thank for the Service provided by Auth0, it has saved us a lot of time and helped us focus on building value for our customers instead of spending time setting up authentication systems.

We're using impersonation (and understand the risks associated with disabling CSRF checks when checking state), and we're running into an issue. Some of our users (enough to be problem for our business) keep running into an error that prevents them from logging in. We collect these errors in Sentry.io, and they are all the following:

![image](https://user-images.githubusercontent.com/11708669/43912428-7ae93100-9c02-11e8-8860-faa84b0e6ad8.png)

I've been reading the related issues on this repo, and none of them seemed to provide me an answer to my problem.

We've tracked this down, and it happens after `parseHash` is called. What is puzzling me is that this state check should by bypassed since we have impersonation enabled (using `__enableIdPInitiatedLogin`). This is how we call `parseHash` (we wrap it in a class/promise for our own use):

```js
export class Auth {
  constructor(auth0lib = auth0) {
    this.auth0 = new auth0lib.WebAuth({
        responseType: 'token',
        // our other options here
    });
    this.parseHash = this.parseHash.bind(this);
  }

  parseHash() {
    return new Promise((resolve, reject) => {
      this.auth0.parseHash(
        {
          __enableIdPInitiatedLogin: true,
        },
        (err, authResult) => {
          if (err) {
            reject(err); // this is where we get the `state` does not match error.
          }
          resolve(authResult);
        }
      );
    });
  }
``` 

[Looking at the Auth0.js code](https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L227), it seems that `__enableIdPInitiatedLogin` is intended to disable the state check, which would avoid running into this error:

```js
  var shouldBypassStateChecking = !state && !transactionState && options.__enableIdPInitiatedLogin;

  if (!shouldBypassStateChecking && !transactionStateMatchesState) {
    return cb({
      error: 'invalid_token',
      errorDescription: '`state` does not match.'
    });
  }
```

The problem is, `__enableIdPInitiatedLogin` is ignored if there's either a `state` or `transactionState` that is not falsy.

I was investigating more into this issues as some of our users seem have workflows that are not in the happy path: they login, forget they password, reset it, and navigate back and forth in the browser history, paste URLs, etc. ==> in the end, they can't login and run into this error, even though impersonation is not involved at any moment in that scenario.

I managed to reproduce one of these workflow, and this is what I see in the debugger:

![image](https://user-images.githubusercontent.com/11708669/43912268-0fce6cd2-9c02-11e8-81f4-7dde76edfd12.png)

**My questions are the following:**
- If `__enableIdPInitiatedLogin` is enabled, shouldn't the state verification be completely skipped?
- Otherwise, when running in that scenario (one of the 2 states are missing) but we're not in a CSRF attack, how to recover from it? 

Additional info:

- "auth0-js": "9.6.1"
- "auth0-lock": "11.7.2"
- Users login using an embedded lock in our website
- We have a custom domain setup
- We are using an EU based tenant
- Tested and reproduced in Chrome, Firefox, Edge, Opera (latest version, evergreen), on both OSX and Windows 10

**Comment by luisrudge** [comment]
`__enableIdPInitiatedLogin` doesn't disable state checking. It just doesn't validate the state if the *returned authentication result* doesn't contain a state (which is the case for IdP initiated logins).

There's no way to completely bypass the state check.

How did you reproduce this error?

**Comment by superzadeh** [comment]
I reproduced it by doing the simply reusing a callback URL. However I don't think that this is what our users are doing, yet they are still running into this issue, and it's been near impossible for us to figure out what (also reached out to Auth0's support).

Is there an expiration that could cause the state to become invalid for some reason? Otherwise, what additional logs should I collect to investigate this further?

**Comment by luisrudge** [comment]
Here's how state works:

- user clicks "login" in your app
- your app calls `webauth.authorize`
- at this time, auth0.js creates a state string, stores it locally and sends that as a param to the /authorize url
- when the /authorize endpoint returns the authentication result, it sends the access_token/id_token and also a state param, like this: `https://yourapp.com/#access_token=foo&id_token=bar&state=xyzxyz`
- when you call `webauth.parseHash`, it will parse this hash and check if the local state matches the state that was sent in the redirect url
- if it doesn't, it will throw that error

So, knowing that, here are a few scenarios that might cause this error to happen:

- users adding the /authorize url directly as a favorite
	- because they're not creating the local state *before* redirecting to /authorize, then the redirect to your app happens, `parseHash` won't find the state locally and will throw that error
- users starting the authentication in one browser and finishing in another browser
	- this sometimes happens with mobile users, since they can start the authentication in an in-app browser and then finish in the default os browser
- users have both cookies and localStorage disabled for your domain
	- if that's the case, we won't be able to save a local state before redirecting to /authorize

What you can do is catch this error and just start the authentication process again. If the user got this error from one of the first two scenarios I mentioned, this will fix it (because it will start the process all over again)

**Comment by superzadeh** [comment]
>What you can do is catch this error and just start the authentication process again

👍  Thanks a lot, this goes in the same direction we've taken for now. We can leave this one closed, I'll update if we find anything relevant for others.
