### ISSUE TITLE
Problems with social login on custom UI

### ISSUE THREAD

**Issue by adrianzaorski** [auth0/auth0.js#822]
```
version: v9.7.3
os: ubuntu 18.04 lts
browser: chromium 68
```

Hello, I would like to implement social login on auth0 with custom UI, but I didn't find any good resource which says how to do it properly.

 I am using angular 6, so far I tried two approaches:
`this.auth0.authorize({
      connection: 'google'
    })`
and
`this.auth0.popup.authorize({
      connection: 'google'
    });`

logging in with Username-Password works perfectly, also logging in via google using Universal Login is working, but I would like to use my user interface.

The window which popups have url like this: `http://localhost:4200/auth/callback#error=invalid_request&error_description=the%20connection%20was%20not%20found&state=removed_state_from_here`
so the error is: **The connection was not found**

Thanks in advance

**Comment by luisrudge** [comment]
Seems like you don't have that connection enabled for your client. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
