### ISSUE TITLE
Allow location bar to be hidden from the popupOptions

### ISSUE THREAD

**Issue by onelifemedia** [auth0/auth0.js#824]
I am currently building auth0 functionality in an ionic app. When the popup appears, the location bar pushes the screen down, forcing the login button off of the bottom of the screen (See attached image).

Before forking the project, is there a way to hide the location bar (similar to a `location=no` in `window.open`)?

![screenshot_20180905-182556](https://user-images.githubusercontent.com/1495062/45125142-2d89ea00-b13b-11e8-8be0-7ffab54eb52c.png)

**Comment by luisrudge** [comment]
We only allow overriding the width and height of the popup: https://github.com/auth0/auth0.js/blob/60f26b7fa811603633d11653843d51ce0c5b95b2/src/web-auth/popup.js#L191

**Comment by onelifemedia** [comment]
I know that you only allow overriding the width and height. I read the code. I can't believe that no one has complained about this before.

Is there a reason why you force the header to be there?

**Comment by onelifemedia** [comment]
As mentioned, this is a mobile app, so I'm not really worried about desktop browsers. Additionally, I tested `window.open('google.com', '_blank', 'location=no')` on a mobile device, and I didn't get a header bar. So it IS possible.

I'm guessing that this isn't high on your priority list, so I should try to find a way to adjust the css for it all to fit on the screen?

**Comment by luisrudge** [comment]
What device/browsers did you test this?

**Comment by Sungdukkang** [comment]
Is this issue still open? I'm running into a similar issue. My solution so far has been to set the submit button's css to "position: fixed" and set it to the bottom of the screen. This solution works on desktop and android phones but doesn't seem to work on iOS browsers, possibly due to webkit not supporting position fixed.  

If anyone has got a solution that works with iOS I'd love to get some help.

**Comment by onelifemedia** [comment]
@luisrudge - It's a hybrid app on iOS and Android. Safari and Chrome is the default renderers.
