### ISSUE TITLE
Auth0 returns user_id from another application 

### ISSUE THREAD

**Issue by NaumenkoSergiy** [auth0/auth0.js#827]
I have few applications in one tenant, and have user with same email and password in two applications, when I try to login in one application using this code:
```
return new Promise(function (resolve) {
    auth0.login({
      realm: 'Username-Password-Authentication', //connection name or HRD domain
      username: authCreds.email.trim(),
      password: authCreds.password.trim(),
      scope: 'openid',
      sso: true,
      clientID: [development client id]
    }, (err, authResult) => {
      if (!err) {
        resolve(authResult);
      }
    });
  });
``` 

I receive user from another application, I wrote `clientID` in `login` function, and also in initialize:

```
const auth0 = new Auth0.WebAuth({
  clientID: [development client id],
  domain: CLIENT_DOMAIN,
  responseType: 'token id_token code',
  scope: 'openid',
  prompt: 'none'
});
```

what I'm doing wrong?

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
