### ISSUE TITLE
Update login documentation

### ISSUE THREAD

**Issue by mmaddex** [auth0/auth0.js#832]
I'm confused from looking at some of the documentation for this library - https://auth0.github.io/auth0.js/global.html

1. Should this be updated to mention it will use the appropriate flow based on where it's called from, instead of saying it uses cross-origin?
https://github.com/auth0/auth0.js/blob/bea539d8cb7cb2b9eabfacdd9fc9feb93931560f/src/web-auth/index.js#L622-L626

2. Should this be updated to have `@method login` on line 37
https://github.com/auth0/auth0.js/blob/fb53e8c318416ab1b29c99907a9e3cf63fe25164/src/web-auth/hosted-pages.js#L31-L45

**Comment by luisrudge** [comment]
Thanks for bringing that to my attention. I fixed those mistakes in #833 🎉
