### ISSUE TITLE
Non-OIDC: Nonce not generated or verified under some conditions

### ISSUE THREAD

**Issue by danielrmay** [auth0/auth0.js#834]
Hi,

I searched for issues relating to this but couldn't find any -- so if this is a dupe, sorry!

**Context**
It appears that when an Application in Auth0 is **not** marked as OIDC Conformant via the toggle under  Settings>Advanced>OAuth, the `/authorize` endpoint will return both a valid `access_token` and a valid `id_token` when the requested  `responseType` is `token` and the `scope` contains `openid`.

Example:

```
    /* Embedded (cross-origin) log-in  */
    var webAuth = new auth0.WebAuth({
        domain: 'YOUR_AUTH0_DOMAIN',
        clientID: 'YOUR_CLIENT_ID',
        redirectUri: 'YOUR_REDIRECT_URI'
        scope: 'openid',
        responseType: 'token'
      });

    webAuth.login({
        email: 'YOUR_USER_EMAIL',
        password: 'YOUR_USER_PASSWORD',
        realm: 'YOUR_AUTH0_CONNECTION'
    });
 
   // Returns both a valid access_token and a valid id_token to the redirect
   // e.g. `YOUR_REDIRECT_URI#id_token=xxx&access_token=xxx&scope=openid`...
```

However, when the application **is** marked as OIDC conformant, this doesn't happen, as detailed in the adoption notes here:
> - Using response_type=token will only return an Access Token, not an ID Token. Use response_type=id_token or response_type=token id_token instead.
from https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

**Observations**
`auth0.js` contains logic in `transaction-manager.js` that purposely does not create a nonce for use in the `/authorize` call when the `scope` option does not contain `id_token`:
https://github.com/auth0/auth0.js/blob/c04d36f35e8f9b5981cee9522ae405de11f461b8/src/web-auth/transaction-manager.js#L19
https://github.com/auth0/auth0.js/blob/c04d36f35e8f9b5981cee9522ae405de11f461b8/src/web-auth/transaction-manager.js#L32-L34

Additionally, `Authentication.buildAuthorizeUrl` turns off validation for the existence of `nonce` when the `responseType` doesn't include `id_token`:
https://github.com/auth0/auth0.js/blob/c04d36f35e8f9b5981cee9522ae405de11f461b8/src/authentication/index.js#L128-L134

But as evidenced by the example above, it is possible to receive an `id_token` when it is not explicitly requested in the `responseType` -- by requesting the `openid` scope. 

So, to clarify, under these conditions, this means that the only way a nonce is provided and verified is if one is provided in the initial call to `login()`:

```
    webAuth.login({
        email: 'YOUR_USER_EMAIL',
        password: 'YOUR_USER_PASSWORD',
        realm: 'YOUR_AUTH0_CONNECTION',
        nonce: ourLoginNonce
    });
````

If this isn't done, the nonce isn't provided in the `/authorize` call, thus Auth0 doesn't return a `nonce` in the `id_token`, thus the nonce isn't verified. `state` is, obviously, unaffected.

Note: If the application is set to OIDC conformant, Auth0 will reject a nonce-less authentication request:
> - Implicit grant authentication requests made without a nonce parameter will be rejected.
from https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

**Resulting change**
This can be easily worked around by changing the responseType from `token` to `token id_token` which explicitly defines the library's user as wanting to receive an `id_token`, and this satisfies the requirements of the referenced change in the OIDC adoption docs mentioned above.

In terms of a fix for this repo, though, as said above, considering Auth0 doesn't reject nonce-less `/authorize` calls from OIDC non-conformant apps, and additionally, this issue doesn't occur if the application _is_ OIDC conformant because `/authorize` calls **without** `responseType: 'id_token'` don't return an `id_token`, and thus there's no need to verify a `nonce`  -- it could be argued that no change is required here at all.

That said, considering that `auth0-js` will happily automatically generate and verify `nonce` and `state` values, I feel like this behavior is hidden and very easy to miss. Maybe a warning would be acceptable? Also, I don't know what the plan is to support these kinds of scenarios considering the push to move to OIDC conformance.

Thoughts?

Thanks,
D

**Comment by luisrudge** [comment]
You're absolutely right in everything. It works exactly as you mentioned. Where would you expect to see the docs for this?
