### ISSUE TITLE
Infinite loop after a failed authorize using webAuth

### ISSUE THREAD

**Issue by jonatasrancan** [auth0/auth0.js#841]
Hey guys.
I have a react 16.3.1 app that is using auth0 9.4.1, also I have a custom rule, that returns a `UnauthorizedError` based in some logic, also I'm using the webAuth approach, also I have a hosted page for login/signup. I basically just copied the examples from you guys. Here is the code sample:

```js
....
this.auth0 = new auth0.WebAuth({
      domain: AUTH_CONFIG.domain,
      clientID: AUTH_CONFIG.clientId,
      redirectUri: AUTH_CONFIG.redirectUri,
      audience: AUTH_CONFIG.audience,
      responseType: "token id_token",
      scope: "openid profile"
    });
....

handleAuthentication() {
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken && authResult.idToken) {
        this.setSession(authResult);
        window.location.reload();
      } else if (err) {
        this.logout();
        this.handleError(err);
      } else {
        this.login();
      }
    });
  }

login() {
    this.auth0.authorize();
  }

logout() {
    if (window.localStorage) {
      localStorage.removeItem("access_token");
      localStorage.removeItem("id_token");
      localStorage.removeItem("expires_at");
      localStorage.removeItem("tenant");
    }
    this.auth0.logout();
  }
```

So far so good, everything works fine.

But when my rule raises the `UnauthorizedError`, I got redirect to my app, with the error information as params on my URL, that is ok is the expected behavior.
So after researching, I found out that we can pass extra params on `authorize()`, and catch them on my hosted page with `config.extraParams`. I managed to do that is some tests.

So I decided to do something like this:

```js
handleAuthentication() {
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken && authResult.idToken) {
        this.setSession(authResult);
        window.location.reload();
      } else if (err) {
        this.logout();
        this.auth0.authorize(err);
      } else {
        this.login();
      }
    });
  }
```

So with this, I would be able to catch the error on my hosted page, and show it using the `lock.flashMessages`, and everyone would be happy :smiley: 

But what is really happening, is when I hit `this.auth0.authorize(err)`, I got redirected to my auth0, but before the lock is fully loaded I got redirected back to my app, with the error information on the URL, so because of this, I hit the `else if(err)` part again, and the loop starts all over again. Looks like some cache.

I thought it was something related to the `webAuth` instance, that it may save some info, so I forced creating a new instance of `webAuth`, inside `else if(err)` and call `authorize` from it, but the same problem happens.

After spending a few days trying to solve this, I decided to reach you guys.
What am I missing?

**Comment by luisrudge** [comment]
Sending errors to the Universal Login Page is not supported and you'll see a warning if the parameters sent to the /authorize endpoint are not listed here: https://github.com/auth0/auth0.js/blob/master/src/helper/parameters-whitelist.js#L28

With that being said, what's probably happening is that you're sending the `error` parameter as well, which might trigger the redirect back to your app. Try to send only the `errorDescription` parameter. Workaround here: https://github.com/auth0/lock/issues/637#issuecomment-428354956
