### ISSUE TITLE
Not exposable anymore since 9.7.0

### ISSUE THREAD

**Issue by scipper** [auth0/auth0.js#842]
Since **auth0-js 9.6.1** I was able to expose auth0 to global scope with **webpack** and the **expose-loader** like this:
```
{
  test: require.resolve('auth0-js'),
  use: [{
    loader: 'expose-loader',
    options: 'auth0'
  }]
}
```

Then other libs like angular-auth0 are able to find it in `window.auth0`. 

Now with auth0-js >= 9.7.0 it can't be exposed anymore. No error while building with webpack. 

Versions currently using: 
- webpack: 4.17.2
- expose-loader: 0.7.5
- auth0-js: 9.6.1 <- works
- auth0-js: 9.7.0 <- broken

I don't know what more information could be useful, please tell me. 

I have created a repo with two branches: [working](https://github.com/scipper/webpack-auth0/tree/working) (with auth0-js 9.6.1) and [broken](https://github.com/scipper/webpack-auth0/tree/broken) (with auth0-js 9.7.0). This repo can be checked out and with `npm run serve` served to the browser.

**Comment by scipper** [comment]
any news?

**Comment by luisrudge** [comment]
What are the requirements for a script to be exposed? We switched from webpack to rollup and now we have a [few more builds available](https://unpkg.com/auth0-js@9.9.0/dist/), but I'm not sure what do you need from auth0.js to make it work.

**Comment by scipper** [comment]
I am not familiar with rollup.js you are seemlingly using to bundle auth0-js since 9.7.0, but I think that the library target it not UMD anymore, which it was before in the webpack build.

**Comment by luisrudge** [comment]
hmm, not sure that's the case.. both are UMD:

https://cdn.auth0.com/js/auth0/9.9/auth0.js
![image](https://user-images.githubusercontent.com/941075/51394365-5a0a3580-1b21-11e9-929f-445b2a2f251e.png)


https://cdn.auth0.com/js/auth0/9.6/auth0.js
![image](https://user-images.githubusercontent.com/941075/51394375-5f678000-1b21-11e9-9249-f4db807dea7b.png)

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
