### ISSUE TITLE
signup only supports strings in user_metadata

### ISSUE THREAD

**Issue by tomflenniken** [auth0/auth0.js#843]
Auth0.js version 9.8.0

### Issue
My use case requires saving boolean values in the user_metadata for database accounts. The `signup` method has an option parameter for user_metadata but it does not support boolean values.

The current workaround will be send a second request to update the user_metadata with the boolean fields.

**As a feature request, I would like to be able to send arbitrary JSON data as user_metadata in the initial signup request.**

---

Code that produces the validation error:
```
webAuth.signup({
    email,
    password,
    connection: 'Username-Password-Authentication',
    userMetadata: { 'booleanMetadata': true }
}
```
Error message:
```
code: "invalid user_metadata.booleanField type (only strings are allowed)"
description: "invalid user_metadata.booleanField type (only strings are allowed)"
original: Error: Bad Request at Request.<anonymous> 
statusCode: 400
statusText: "Bad Request"
```

---

#### Referenced methods:
> Documentation here indicates that only string values are supported for signup
https://auth0.com/docs/api/authentication#signup

> The patch endpoint supports full JSON types in user_metadata
https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id

**Comment by luisrudge** [comment]
> As a feature request, I would like to be able to send arbitrary JSON data as user_metadata in the initial signup request.

This is a server restriction and not something we can handle directly in auth0-js. If you want to track this publicly, you can create a post in https://community.auth0.com so we can follow up with you. If you don't want to track it, I can just create a feature request internally (you won't be notified about this). Which one do you prefer?

I faced this same issue last week. I wanted to have a complex object as metadata (`metadata: {name, phone, company: {name, segment}}`). Signup also doesn't accept that. Here's how I worked around it:

#### on signup
```
    const signupInfo = {
      email,
      password,
      user_metadata: {
        ...user_metadata,
        company_name: company.name,
        company_segment: company.segment
      }
    };
```

#### create a new rule
```
function(user, context, callback) {
  const namespace = "https://myapp.com/";
  context.idToken[namespace + "name"] = user.user_metadata.name;
  context.idToken[namespace + "phoneNumber"] = user.user_metadata.phoneNumber;
  context.idToken[namespace + "company"] = {
    name: user.user_metadata.company_name,
    segment: user.user_metadata.company_segment
  };
  callback(null, user, context);
}

```

This way, when I get my `id_token`, I get all the claims in the expected format. You can do the same and convert strings to boolean etc.

**Comment by tomflenniken** [comment]
Internal feature request is fine, I do not need to track this.

**Comment by luisrudge** [comment]
Ok, done!

internal:
idea: f8992040-d3e0-11e8-bdaf-9dff1cdc12b5

**Comment by rassokhin-s** [comment]
I faced the same issue today... I need to save boolean and number in the user_metadata on signup. It's still not possible! But update request support all types... How stupid is that...
