### ISSUE TITLE
popup.authorize throws a JSON parsing error when called progamatically

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#845]
When opening the popup programmatically (e.g., when there isn’t a user click on a button that triggers the popup), the `popup.authorize` callback errors out with the following error:

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at onMessage (auth0.min.esm.js:8)
```

**Comment by kmaida** [comment]
Additional details for reproduction:

- popup opened programmatically from front end app code
- (popup is blocked by browser at this point, but the user can enable popups in the browser)
- if the user has enabled popups for the domain, the popup _does_ open
- user goes through the login flow in the popup, it appears to work as far as user can tell
- `popup.authorize` callback throws this ambiguous JSON parsing error, and fails: therefore, user is not logged in; login failure

**Comment by luisrudge** [comment]
https://i.imgur.com/cJ1F1Es.png when opened from here, `window.opener` is null

**Comment by luisrudge** [comment]
duplicate https://github.com/auth0/auth0.js/issues/512
