### ISSUE TITLE
would be nice to be able to use some of the client features from a node application

### ISSUE THREAD

**Issue by remkoboschker** [auth0/auth0.js#85]

**Comment by cristiandouce** [comment]
@remkoboschker what feature(s) specifically?

**Comment by remkoboschker** [comment]
we have some services that authenticate to an api using jwt tokens and would like to get the tokens using the refresh token. So at the moment i'm just using the auth0.prototype.refreshToken and auth0.prototype.decodeJwt functions

**Comment by remkoboschker** [comment]
I think it is more effective to just use the appropriate api calls and node-jsonwebtoken, because the client is very much directed towards browser use and interacting with humans.
