### ISSUE TITLE
Type definitions for errors

### ISSUE THREAD

**Issue by donaldpipowitch** [auth0/auth0.js#861]
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ ] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [x] Auth0.js version: 9.8.1
- [ ] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

---

Hi 👋

I want to enhance the `@types/auth0-js` for errors and I need some help, because I couldn't found full documentation about this topic. (I really which this project would include official typings. ❤️)

The current definitions for _all_ errors are this:

```ts
export interface Auth0Error {
    error?: any;
    errorDescription?: string;
    code?: string;
    description?: string;
    name?: string;
    policy?: string;
    original?: any;
    statusCode?: number;
    statusText?: string;
}
```

[`parseHash`](https://github.com/auth0/auth0.js/blob/04a0c2a560837fc110be01ffd594d758905a9e35/src/web-auth/index.js#L157) seems to always use this interface:

```ts
{
    error: 'login_required' | 'consent_required' | 'interaction_required' | 'invalid_hash' | string;
    errorDescription: string;
    state?: string;
}
```

`validateAuthenticationResponse` seems to use this:

```ts
{
    error: 'invalid_token'; // also more?
    errorDescription: string;
}
```

`checkSession` uses:

```ts
{
    error: 'error'; // also more?
    errorDescription: string;
}
```

There is also `src/helper/response-handler.js` which defines:

```ts
{
    original: any,
    statusCode?: string;
    statusText?: string,
    code: string | null,
    description: string | null,
    error?: string | null, // like `code` for forceLegacyError
    error_description?: string | null, // like `description` for forceLegacyError
    name?: string;
    policy?: string;
}
```

Is this one used in every other case? (Every error case besides the ones from `parseHash`, `validateAuthenticationResponse` and `checkSession`.) Are there even more different errors?

I appreciate every help. Thank you!

**Comment by luisrudge** [comment]
auth0.js uses `timeout`, `request_error` and `invalid_token`. Other than that, all errors come from the server. Different tenants can have different error codes depending on a lot of settings, so I think your best bet is to use the official spec list: https://openid.net/specs/openid-connect-core-1_0.html#AuthError

**auth0.js**
timeout
request_error
invalid_token

**spec**
interaction_required
login_required
account_selection_required
consent_required
invalid_request_uri
invalid_request_object
request_not_supported
request_uri_not_supported
registration_not_supported

**Comment by donaldpipowitch** [comment]
You only refer to the `error` field in the error cases from above, right? What about the other fields? Thank you.

**Comment by luisrudge** [comment]
Yes, error (or code in some situations). Feel free to add all of them if you want. They're there mostly for compatibility reasons. Ideally, people should use only `error` and `errorDescription`.

**Comment by donaldpipowitch** [comment]
> Yes, error (or code in some situations).

That's basically what I want to figure out - what is the interface in which situation? :) 

> Feel free to add all of them if you want.

I guess they don't occur for every function call or am I mistaken? Or can `checkSession` return an error with `error: 'login_required'`? I only saw it for `parseHash` so far. (I really don't know.)

> Ideally, people should use only error and errorDescription.

So `src/helper/response-handler.js` is only used internally? That would make things easier to type 👍
But IMHO `state` which is part of the `parseHash` error is needed in some cases.

**Comment by luisrudge** [comment]
I think you're going to have a bad time if you want to have specific errors for each method 😬 In your example, `login_required` can happen in most of methods. Just create an interface that works for all of them.

`src/helper/response-handler.js` is internal, yes.

**Comment by donaldpipowitch** [comment]
When `src/helper/response-handler.js` is internal and the `error` values can basically happen everywhere, the only difference is afaik `state` which seems to be unique to `parseHash`?

So basically 

```ts
export type Auth0Error = {
    error: string;
    errorDescription: string;
}

export type Auth0ParseHashError = Auth0Error & {
    state?: string;
}
```

which would be so much correcter than the current definitions.

**Comment by donaldpipowitch** [comment]
As pointed out in https://github.com/auth0/auth0.js/issues/866 there is another case for `checkSession` which returns:


```ts
{
    error: string; // with another auth0.js lib specific error called just 'error'
    error_description: string;
   //errorDescription: string; // still present...???
}
```

See here for `checkSession`:
https://github.com/auth0/auth0.js/blob/fb53e8c318416ab1b29c99907a9e3cf63fe25164/src/web-auth/index.js#L448

And also here in the `getSSOData` (which calls `checkSession` and can set `error_description` as well): 
https://github.com/auth0/auth0.js/blob/b6e167d12956f3c56d179cfcae3e3f9bda0ff7e9/src/authentication/index.js#L383

(It looks like `getSSOData` can even return a result (even though it is just `{ sso: false }`, if an error is present. This is imho a little bit unexpected, especially if we convert callbacks to a Promise. But just as a side note.)

---

Is `error_description` a "bug"? Would you accept PRs to remove it?

**Comment by luisrudge** [comment]
Inside checkSession, it's a bug :( We have to use `responseHandler(cb, { forceLegacyError: true })` to make it right and also not break anyone. do you want to send a PR with that?

**Comment by EatonZ** [comment]
So is there a temporary workaround for this? Can I use `forceLegacyError` or is that something you are suggesting be added?

**Comment by luisrudge** [comment]
`forceLegacyError` is an internal option that we use inside Auth0. If you want to send a PR with that change, that'd be amazing 😬

**Comment by EatonZ** [comment]
Has anyone else published a fix for this yet? Unfortunately I don't really know enough about the workings of the SDK to submit a PR at this time.

**Comment by luisrudge** [comment]
@EatonZ not yet. tracking here: https://github.com/auth0/auth0.js/issues/932
