### ISSUE TITLE
Missing Property

### ISSUE THREAD

**Issue by EatonZ** [auth0/auth0.js#866]
**Auth0.js Version:** 9.8.1
**Auth0.js Types Version:** 8.11.6
Google Chrome 70 on Windows 10

There appears to be an issue with `@types/auth0-js`. The error object that comes in `WebAuth.checkSession` does not contain the correct properties.

For example, the typings indicate there should be an `errorDescription`. This is incorrect, as debugging in Chrome has it named differently (`error_description`), so the string I get is `undefined`.

I recognize that other functions, like `WebAuth.parseHash`, can come with an error with a `errorDescription` property. The solution is to either fix `checkSession` to return an `errorDescription`, or add `error_description` to the typings.

**The incorrect definition:**
![2018-10-29_19-47-08](https://user-images.githubusercontent.com/3020941/47686961-29ff6600-dbb4-11e8-876d-ccea54bb7226.png)

**Screenshot of the discrepancy:**
![2018-10-29_19-50-43](https://user-images.githubusercontent.com/3020941/47686965-2bc92980-dbb4-11e8-832a-9615c2b3604d.png)

**Comment by luisrudge** [comment]
We don’t maintain the definitions. You should probably send a PR to the definitelytyped repo.

**Comment by EatonZ** [comment]
@luisrudge Would you consider changing `checkSession` to return an `errorDescription` instead of `error_description`?

**Comment by luisrudge** [comment]
@EatonZ it's a bug 😓 I outlined the solution here: https://github.com/auth0/auth0.js/issues/861#issuecomment-434240816

**Comment by EatonZ** [comment]
Has anyone else published a fix for this yet? Unfortunately I don't really know enough about the workings of the SDK to submit a PR at this time.
