### ISSUE TITLE
return error when popup is blocked

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#868]
check if the return of `load` is null in this line: https://github.com/auth0/auth0.js/blob/master/src/web-auth/popup.js#L206

If it is, throw an error (popup blocked).

**Comment by Niladri24dutta** [comment]
@luisrudge Can I work on this? it seems we need to return the error message through the callback method passed as argument if the `load` is null from here `url = this.client.buildAuthorizeUrl(params);`

**Comment by luisrudge** [comment]
@Niladri24dutta exactly! You can use this error in the callback:

```js
{
  error: 'popup_blocked',
  errorDescription: 'The popup was blocked.'
}
```

**Comment by Niladri24dutta** [comment]
@luisrudge Ok Sure, I will make the change in my branch. Is there any unit test that I need to update for this?

**Comment by luisrudge** [comment]
You'll have to write a new one

**Comment by Niladri24dutta** [comment]
Ok .. Thank you for your feedback

**Comment by luisrudge** [comment]
https://github.com/auth0/winchan/blob/master/winchan.js#L213

winchan always returns a valid object (`window.open` will return undefined if the popup was blocked). Because of that, we can't know if the popup was blocked or not.

**Comment by mrksbnch** [comment]
@luisrudge Thanks for the update... However, I'm not sure if I understand the problem correctly. It seems like Auth0 is using it's own version of winchan? So, is it not possible to update winchan accordingly and make it possible to detect if a popup was blocked (which is quite simple in JavaScript). If that's not an option, I'm sure there are other popup libraries which can achieve such a basic functionality.

Simply closing this issue because an external library doesn't offer a possibility seems like an easy way out. I'm pretty sure there are other people as well who could really need this functionality in order to show a notification if the auth popup was blocked (UX).

**Comment by luisrudge** [comment]
Indeed, we use our [own version of winchan](https://github.com/auth0/winchan). In this specific case, I closed the issue because we didn't have enough traction on this issue to justify the extra amount of work, since it now involves an upstream fix. If you wanna send a PR to fix this, I'll review, merge and release it.

If you're using `popup.authorize`, I strongly suggest you take a look at our new sdk that is in beta and has a nicer experience overall for both popup and redirect flows: https://community.auth0.com/t/new-javascript-sdk-for-single-page-applications-in-beta/25087/2

**Comment by mrksbnch** [comment]
Sure, I can have a look at winchan. So, if I understood you correctly, you need the [open](https://github.com/auth0/winchan/blob/master/winchan.js#L101) method of winchan to return `undefined` if the pop up was blocked? If it wasn't blocked it should return an object? Or do you need the returned object to have an additional property that indicates if the popup was blocked?

**Comment by luisrudge** [comment]
I think the additional property [here](https://github.com/auth0/winchan/blob/master/winchan.js#L213) is the safest way. `originalPopup: w`, or `blocked: w===null`. What do you think?

**Comment by mrksbnch** [comment]
Yes, I think an additional property has a much better backwards
compatibility than a completely different return value. Also, I would argue
that a originalPopup property makes more sense as it's more flexible for
the future.

I'll take a look at that on the weekend.

**Comment by luisrudge** [comment]
@mrksbnch perfect. Thanks!
