### ISSUE TITLE
Impossible to renewal Token ID with Refresh Token 

### ISSUE THREAD

**Issue by STK913** [auth0/auth0.js#874]
Hello,

I want to refresh the token as explained here (to regenerate the token ID before it expires): https://auth0.com/docs/tokens/refresh-token/current#use-a-refresh-token
But I can’t get a new token ID, while “openid offline_access” is present in the scope.

My request to https://xxxx.eu.auth0.com/oauth/token : 

> {
>   "grant_type": "refresh_token",
>   "client_id": "as32ad32adef45e4fz54",
>   "client_secret": "zefgerg4e4rg",
>   "refresh_token": "98reh5rttr4h",
>   "json": true
> }

The response:

> {
> “access_token”: “s5f4ddf5h45h4”,
> “expires_in”: 86400,
> “token_type”: “Bearer”
> }
-> id_token isn't present !

And my code for recover token:

> let options = {
>   scope: 'openid profile offline_access',
>   device: 'chrome-extension'
> };
> 
> new Auth0Chrome(Variables.AUTH0_DOMAIN, Variables.AUTH0_CLIENT_ID)
> .authenticate(options)
> .then(result => {
>   // Process
> });

Do you have an explanation, please ?

**Comment by luisrudge** [comment]
Please ask this in the chrome extension repo: https://github.com/auth0-community/auth0-chrome
