### ISSUE TITLE
Error Using browser-only version of superagent in non-browser environment

### ISSUE THREAD

**Issue by MaksSlesarenko** [auth0/auth0.js#878]
When upgrading from v9.6.1 to upper versions on the server I get following error:

> Using browser-only version of superagent in non-browser environment

Node v8.8
OS: Linux/Mac

**Comment by luisrudge** [comment]
auth0.js is not meant to be used in a server environment.

**Comment by GaddMaster** [comment]
How can we only import if on client ?

**Comment by r3plica** [comment]
With auth0.js ever work in angular universal? I have no need to use it if it can't.
