### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by beno** [auth0/auth0.js#879]
I have posted an issue in the demo apps section, but decided this was the more appropriate place.

- [ ] Code snippet or sample project that reproduces the bug

Steps:

- install and run [Login app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login), click login
- show dialog, fill in credentials -> logged in
- click logout -> logged out
- click login -> logged in straight away

I expect to see the login dialog after logging out, but there seems to be no way to ever get the login dialog back (clearing storage/cookies etc). What is going on here?

 Original issue: https://github.com/auth0-samples/auth0-javascript-samples/issues/55

- [ ] Auth0.js version
  Seen with auth0-js 9.6.1 and 9.8.2
- [ ] Browser & OS
  latest Safari & Chrome on Mac

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by beno** [comment]
If this is not a bug, what use case does this support? From a user perspective (and from a programmer's too, frankly) this makes no sense. When I click logout, I expect to be logged out, right? What state am I in when I click logout?

**Comment by luisrudge** [comment]
Again, this is not a bug. If you call the logout method in auth0js, you’ll be logged out. The sample is not doing that. Let’s keep the conversation in in the sample’s repo.
