### ISSUE TITLE
Trigger renewAuth callback early when request fails with postMessage

### ISSUE THREAD

**Issue by ajm5774** [auth0/auth0.js#880]
**Requested Change:**
When using postMessage, request failures should cause the renewAuth callback to trigger early rather than waiting for timeout. 

**Use Case:**
I want to show an error page to the user ASAP so that it doesn't look like the page is hanging if any error occurs while authenticating. 

Auth0 version: 9.8.2
Browser: Chrome 70.0.3538.110

Code:
```javascript
export function authenticate() {
  return new Promise((resolve, reject) => {
    const renewAuth = auth0.renewAuth({
      usePostMessage: true,
    }, (err, authResult) => { // Only calls this callback after a timeout period even though the request 400s
      if (!err && authResult) {
        ls.setSession(authResult);
        resolve();
      } else {
        reject(err);
      }
    });
  });
}
```

```html
<html>
<head>
  <script type="text/javascript">
    window.parent.postMessage(document.location.hash, document.location.origin);
  </script>
</head>
<body></body>
</html>
```

**Comment by luisrudge** [comment]
This happens because the server error is not sent via postMessage and we can't get the resulting http status code via iframe, so there's no way the parent page knows an error happened.
