### ISSUE TITLE
Question on a specific header

### ISSUE THREAD

**Issue by callmekatootie** [auth0/auth0.js#881]
Auth0.js version - 9.5.1

Our client reported an issue where they noticed a header going out in one of the requests related to login. `Auth0-client` was the header name and it appeared to contain encoded details of the authorization version.

Client wanted to know if this could be removed. I checked the documentation out and I could not find a mention of this. I checked the source code out and found a setting named `_sendTelemetry` which when set to false, does not send the header.

What I wish to know is if its safe to set this to false. I could not find a documentation of this anywhere so I am not sure I understand the consequences of setting this to false.

**Comment by luisrudge** [comment]
Yes, you can set this to false to stop sending this information.

**Comment by callmekatootie** [comment]
Thanks for the quick response - out of curiosity, and since this isn't documented, what does `_sendTelemetry` do?

**Comment by cocojoe** [comment]
@callmekatootie The telemetry simply sends the version of the Auth0.js library e.g. 9.5.1. This helps us understand the version usage of the SDK . You can disable this if you really want to.

**Comment by luisrudge** [comment]
We use telemetry to know which versions our our sdks are being used. The telemetry is sent in the Auth0-Client header. When you disable that flag, it stops sending the telemetry. This header is only sent to your tenant's Auth0 endpoints, but we provide this flag to disable this if you really want to.

**Comment by callmekatootie** [comment]
Thanks @cocojoe @luisrudge. This is now clear.
