### ISSUE TITLE
Silent authentication with Google login fails: login_required

### ISSUE THREAD

**Issue by dodas** [auth0/auth0.js#883]
Hi!
I am trying to get Silent Authentication working and it works when using regular email/password login. However, when using google provider, call to `checkSession` fails with error of `login_required`.
I also tried example app `05-token-renewal` with same result.

`auth0-js` version: `9.8.2`
browser: google chrome `70.0.3538.110`

Thanks for any hints.

**Comment by luisrudge** [comment]
Are you using Auth0 dev keys? They'll always return login_required. I just tested with our [own example](https://github.com/auth0/auth0.js/blob/master/example/index.html#L402) (by changing this line to use `google-oauth2` instead of `facebook`) and it works as expected.

**Comment by dodas** [comment]
For sake of having response here:

Yes, this error was thrown because I was using dev keys.
It was hard to debug, though.
