### ISSUE TITLE
Don't use storage inside the HLP

### ISSUE THREAD

**Issue by nicosabena** [auth0/auth0.js#896]
We shouldn't use transactions while doing any authentication requests within the hosted login page, as there's no verification step to be done in there. Since the verification is never done, the number of transactions stored grows quickly, leading to "Headers or cookies too large" errors.

https://github.com/auth0/auth0.js/commit/9b2a98f9552a1fa845c431ffbeb3a326399f9eca from #886 fixed this partially, for the `login()` function (username/password login). But this is still an issue for other places where storage is used: `authorize()` and all the passwordless functions.

**Comment by luisrudge** [comment]
🤦‍♂️ how did I miss this? 😬

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/auth0.js/pull/899
