### ISSUE TITLE
checkSession doesn't clean up after itself

### ISSUE THREAD

**Issue by akotlar** [auth0/auth0.js#897]
Briefly, checkSession sets a cross-origin cookie of some duration. If the user refreshes the page within this window, that cookie will not be cleared, until the expiration time, which appears to be 5 hours.

- [x] Code snippet or sample project that reproduces the bug
```js
// Occurs with or without promise
function _checkSession() {
  if (!_auth0) {
    throw new Error('Auth library is not initialized in checkSession');
  }

  _checkSessionPromise = new Promise((resolve, reject) => {
    _auth0.checkSession({}, (err, authResult) => {
      if (err) {
        return reject(err);
      }

      resolve(authResult);
    });
  });

  return _checkSessionPromise;
}
```
- [x] Auth0.js version
**9.9.0**

- [x] Browser & OS
**Chrome, Firefox**

- [x] Screenshots when appropriate

<img width="2021" alt="screen shot 2019-01-20 at 5 12 28 pm" src="https://user-images.githubusercontent.com/5543229/51445749-a5197980-1cd6-11e9-8d16-2399f739587c.png">

![screen shot 2019-01-20 at 5 09 46 pm](https://user-images.githubusercontent.com/5543229/51445696-32100300-1cd6-11e9-8735-125298f4b973.png)

**Comment by luisrudge** [comment]
Cookies are cleared automatically after 15 or 30 minutes, depending on the cookie (the checkSession one is 30min). This is fine in most scenarios. Also, the checkSession cookie is always cleared when there's a valid session in Auth0. So, you should prevent a checkSession call if it's unlikely there will be a valid session in the server.
