### ISSUE TITLE
[QUESTION] How to make unit test

### ISSUE THREAD

**Issue by Sunshine168** [auth0/auth0.js#902]
Hello guys, I want to integrate the unit test , which around ```parseHash and renewToken and  or client.userInfo  method ``` with mine our logic, but I get in some trouble .  
           
I try to reference ```/test/web-auth/web-auth.test.js``` but it seem very complex .

Could you give me some suggestions or examples ?  Thx !

**Comment by luisrudge** [comment]
You should just mock our library and do your mock assertions.
