### ISSUE TITLE
How to add additional authorize arguments

### ISSUE THREAD

**Issue by Vad1mo** [auth0/auth0.js#903]
We have a multi tenant auth0 environment, when subtenat can redirect directly to the main tenant. 

This is how the `authorize` request should look like. All is usual except `connection='main-tenant-oidc'`

Eg.
https://<subtenant>.eu.auth0.com/authorize?
redirect_uri='callback url'&
client_id='id'&
audience=https://<subtenant>.eu.auth0.com/userinfo&
scope='scope'
**connection='main-tenant-oidc'&**
response_type=''

How can I add the argument `connection='main-tenant-oidc'` to new auth0.WebAut

**Comment by luisrudge** [comment]
This should work:

```
auth0.authorize({
  connection: 'main-tenant-oidc'
});
```

However, we do not recommend sending parameters that are not spec compliant. We only accept the connection parameter for legacy reasons 😬
