### ISSUE TITLE
integration with linkedin - internal server error

### ISSUE THREAD

**Issue by eijy** [auth0/auth0.js#906]
Hello guys,

I'm having some problems when i try to login with linkedin. 

The callback stay in a white page and in the url return a error=invalid_request&error_description=InternalOAuthError

and this is the log when i see in auth0.com
![screenshot from 2019-02-12 11-00-05](https://user-images.githubusercontent.com/19434005/52637156-9ed18400-2eb5-11e9-9526-f89e179be65b.png)

thanks for your attention.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
