### ISSUE TITLE
Unable to change login logo on Firefox browser

### ISSUE THREAD

**Issue by nkrTools4ERP** [auth0/auth0.js#908]
I was attempting to change the logo for the auth0 Login page because some customers may be worried when they see a logo not directly associated with our website, it works fine for changing it in Chrome and Edge, but Firefox won't replace the img src.

The code is as following: (Used in the 'Hosted Pages' section of my dashboard on Auth0)
  ```
 .auth0-lock-header-logo{
      content: url('https://website.com/img/logo.png') !important;
      display: inline-block !important;
      font-size: 0 !important;
      line-height: 0 !important;
      margin-top: 10px !important;
      height: 80px !important;
      width: 150px !important;
    }
```
I asked about it on the community board https://community.auth0.com/t/unable-to-change-login-logo-on-firefox-browser/21354 and was told it isn't supported at the moment.

**Comment by luisrudge** [comment]
Lock has its own customization options that you can use: https://github.com/auth0/lock#theming-options. You can use the `logo` option to provide any url you want.
