### ISSUE TITLE
Scope issue using auth0.WebAuth

### ISSUE THREAD

**Issue by janjanarnaldo** [auth0/auth0.js#909]
### Description

I am trying to authorize using auth0.WebAuth, here's an example.
```
return new auth0.WebAuth({
    clientID: window.M_CONFIG.AUTH0_CLIENT_ID,
    domain: window.M_CONFIG.AUTH0_DOMAIN,
    redirectUri: window.M_CONFIG.AUTH0_REDIRECT_URI,
    audience: `https://market.au.auth0.com/api/v2/`,
    scope: 'update:users update:users_app_metadata',
    responseType: 'token id_token',
  });
```
I needed to allow update:users and update:users_app_metadata because I need to update the user_metadata using management api.

But after running this and doing auth0.parseHash, the scope returns null. I also tested the token at https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id but it says I don't have any allowed scope. I tried to change the scope to update:current_user, my instance allows that scope but the management api doesn't.

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: "auth0-js": "^9.8.2",
- Browser and OS version(s) affected: Chrome / Windows 10
- Additional libraries or browser extensions being used that might affect behavior: @types/auth0-js

### Reproduction
Details are mentioned on top, it's not intermittent.

**Comment by luisrudge** [comment]
what is the scope value in the generated /authorize url?

**Comment by janjanarnaldo** [comment]
Hi @luisrudge - it's undefined, no scope value is returned. My thinking is that, they do not match with the management's supported scopes?

Authentication Docs says to use `update:current_user`
Management Api Docs says to use `update:users` or `update:users_app_metadata`
![image](https://user-images.githubusercontent.com/13392638/53063281-85a48500-34fe-11e9-803c-6b8ca603ba68.png)

**Comment by luisrudge** [comment]
What about the initial /authorize request. You’ll see the requests when you open the dev tools.

**Comment by janjanarnaldo** [comment]
that one returned 302, I can see the request payload with the scope I provided though.

**Comment by janjanarnaldo** [comment]
Hi @luisrudge I learned from here that SPA don't have access to those scopes https://auth0.com/docs/api/management/v2/get-access-tokens-for-spas. But, update:current_user_metadata is exposed instead. Now my problem is that I still get 401 invalid token error 
![image](https://user-images.githubusercontent.com/13392638/53065172-7e34aa00-3505-11e9-85ef-d46c3d3c4002.png)

**Comment by janjanarnaldo** [comment]
closing this, for some reasons it started working. new scope `openid profile read:current_user update:current_user_metadata`
