### ISSUE TITLE
publish built version on npm

### ISSUE THREAD

**Issue by bloodyowl** [auth0/auth0.js#91]
I use webpack, and the fact you're using [packageify](https://github.com/auth0/packageify/blob/master/index.js) makes me unable to require auth0-js.

would you consider publishing a built version on npm?

**Comment by cristiandouce** [comment]
@bloodyowl why does that make you unable of it?

you could try something like

```js
{
  module: {
    loaders: {
      test: /.js$/,
      include: 'auth0-js',
      loaders: ['transform?packageify']
    }
}
```

**Comment by bloodyowl** [comment]
well, the problem is that the lib should work with any bundler without extra-configuration, don't you think?

**Comment by cristiandouce** [comment]
@bloodyowl we push the built bundle on each tag/release. Doesn't that work?

https://github.com/auth0/auth0.js/tree/v6.4.2/build

**Comment by cristiandouce** [comment]
BTW, there is also the chance that by using the built bundle, you start getting stuff like this with webpack:

https://github.com/auth0/lock/issues/54#issuecomment-107427969

> Critical dependencies: 1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

**Comment by jfromaniello** [comment]
The version published to npm is meant to be used by browserify projects and in this case auth0.js is built by the host project where is installed.

You can however install from the artifact published to github as follows:

```
» npm i --save https://github.com/auth0/auth0.js/archive/v6.4.2.tar.gz
» ls node_modules/auth0-js/build/auth0.*
node_modules/auth0-js/build/auth0.js     node_modules/auth0-js/build/auth0.min.js
```
