### ISSUE TITLE
how to update userMetadata

### ISSUE THREAD

**Issue by anjumpaul** [auth0/auth0.js#916]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

[ ] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[ ] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used:
- Browser and OS version(s) affected:
- Additional libraries or browser extensions being used that might affect behavior:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippets or a sample project that reproduces the bug
- Log files (redact/remove sensitive information)
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
