### ISSUE TITLE
Wrong types definitions for `CrossOriginLoginOptions` 

### ISSUE THREAD

**Issue by bkotrys** [auth0/auth0.js#917]
There is wrong type definition for `CrossOriginLoginOptions` . Parameter `state` is missing.
It can be very misleading, because at first glance, it seems that you can not set a custom state for cross origin authentication. Finally it is possible, but the interface is wrong.

Current:
```ts
export interface CrossOriginLoginOptions {
    username?: string;
    email?: string;
    password: string;
    realm?: string;
}
```

Expected
```ts
export interface CrossOriginLoginOptions {
    username?: string;
    email?: string;
    password: string;
    realm?: string;
    state?: string;
}
```

**Comment by luisrudge** [comment]
We don't have typings in this library (yet). They're probably provided by https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by bkotrys** [comment]
@luisrudge Even that it will be good if Auth0 update the documentation: https://auth0.com/docs/libraries/auth0js/v9#webauth-login-

State is missing in available method parameters, but it's possible to set `state` with `webAuth.login` method. I tested it and it works. It seems to me that there should be such a possibility available for cross-origin authentication. We use this option, because we need to define return to url, before redirection started.

**Comment by luisrudge** [comment]
Most code editors will show you the jsdocs for that method. In the jsdocs, we're saying that the options will be relayed to the `authorize` call later: https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L639 - I agree it's not super clear though 😬

**Comment by bkotrys** [comment]
okey, thanks for clarification :)
