### ISSUE TITLE
Reset Login Attempts Brute-force protection

### ISSUE THREAD

**Issue by Divyaansh93** [auth0/auth0.js#918]
We are having a scenario where we have to do login iteratively in some time interval until user successfully login. Regard this i want to know two things:

1) Is there any way to reset login attempts? As user gets blocked after 10 login attempts. Is there any way i can control this from my App's frontend so that user don't get blocked as per app's flow?

2) After how much time login attempts count set to 0 for an IP address?

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
