### ISSUE TITLE
The following params is not allowed on /authorize endpoint, [password]

### ISSUE THREAD

**Issue by oshalygin** [auth0/auth0.js#924]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

- Trying to log in from a web client calling 
```javascript
webAuth.authorize({
 username: "email@gmail.com",
realm: "Username-Password-Authentication"
password: "someSecurePassword12345%"
}
```

I see the following in the console log:
`Following parameters are not allowed on the `/authorize` endpoint: [password]`

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

- Version of Auth0.js used: 9.10.1
- Browser and OS version(s) affected: OSX, Latest Chrome
- Additional libraries or browser extensions being used that might affect behavior:
None

**Comment by luisrudge** [comment]
That's right, you can't send this param to the /authorize endpoint

**Comment by oshalygin** [comment]
Is there any documentation on this endpoint?

**Comment by luisrudge** [comment]
https://github.com/auth0/auth0.js#api
https://auth0.github.io/auth0.js/global.html#authorize
https://auth0.com/docs/libraries/auth0js/v9#webauth-authorize-
https://auth0.com/docs/api/authentication#login
