### ISSUE TITLE
Error when used with Capacitor on iOS

### ISSUE THREAD

**Issue by nate-eisner** [auth0/auth0.js#925]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

- Trying to use auth0.js inside a [Capacitor](https://capacitor.ionicframework.com) wrapped web app on iOS
- Does not work because capactior uses `capacitor://` protocol
```
[Error] TypeError: null is not an object (evaluating 'parsed.protocol')
	getOriginFromUrl (auth0.min.esm.js:13:39039)
	run (auth0.min.esm.js:13:94850)
	checkSession (auth0.min.esm.js:13:123928)
```
here is the location of the issue: https://github.com/auth0/auth0.js/blob/99fe1a80454833368acfcf6022a5395720f5f373/src/helper/object.js#L148
it is trying to get a protocol that is null

### Prerequisites

- [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used:  9.10.1
- Browser and OS version(s) affected: iOS
- Additional libraries or browser extensions being used that might affect behavior: capacitor

### Reproduction

Have a capacitor iOS app with auth0.js in use...

Since capacitor is "hosting" the packaged web app via `capacitor://localhost`, the regex here: https://github.com/auth0/auth0.js/blob/99fe1a80454833368acfcf6022a5395720f5f373/src/helper/object.js#L127 gives a `match[1]` of `null`

When trying to use this `null` value later inside: https://github.com/auth0/auth0.js/blob/99fe1a80454833368acfcf6022a5395720f5f373/src/helper/object.js#L143
it errors out on:
```
  var parsed = getLocationFromUrl(url);
  var origin = parsed.protocol + '//' + parsed.hostname;
```

**Comment by luisrudge** [comment]
Auth0.js is meant to be used by single page applications only. native apps are not supported at this time.

**Comment by nate-eisner** [comment]
@luisrudge 
This is a single page application that is wrapped in Capacitor (cordova replacement)

**Comment by luisrudge** [comment]
cordova is considered a native app. the fact that you have javascript/html powering it doesn't mean it's a web app. This library doesn't support cordova as well.

**Comment by colingreene28** [comment]
I'm coming across the same issue. 

I know you've already stated that it's not supporting either Cordova/Capacitor. However, it's 99% way there as far as I can see. I've already managed to authenticate with auth0.js with Capacitor via the authorize call but it's _just_ the checkSession check that it assumes the origin will be `https` or a `file`.

Is there any chance of making that less restrictive? I'm not sure about the knock on effects of this but if that regex check was something akin to something below. I'm happy to make a PR?

```
function getLocationFromUrl(href) {
  var match = href.match(
    /^(([^:/?#]*):)\/\/(([^:/?#]*)(?::([0-9]+))?)([/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/
  );
  return (
    match && {
      href: href,
      protocol: match[1],
      host: match[2],
      hostname: match[3],
      port: match[4],
      pathname: match[5],
      search: match[6],
      hash: match[7]
    }
  );
}
```

**Comment by luisrudge** [comment]
@colingreene28  You can read more on why you *should not* be using Auth0.js (which uses implicit flow) for your native apps here: https://auth0.com/blog/oauth-2-best-practices-for-native-apps/https://auth0.com/blog/oauth-2-best-practices-for-native-apps/

I guess you *could* try our [new SPA SDK](https://community.auth0.com/c/auth0-beta-programs/new-javascript-sdk-for-spa-beta), which uses the Authorization Code Flow + PKCE. It will use the same flow we recommend for native apps but it's still targeted towards single page apps.

**Comment by colingreene28** [comment]
Cheers @luisrudge for responding. 

Yep, I think if we were building a pure native app from scratch we would definitely do the Code Flow + PKCE. However, the big draw of building an Ionic app, is that you write it once and run anywhere (web, PWA, iOS, Android). So with that being said, this new SPA SDK does sounds promising as we can treat native and web exactly the same!

I see that there's support provided via private channels. Is that something we can get involved in?

**Comment by luisrudge** [comment]
@colingreene28 the beta is open right now! Feel free to check our comunity post on this: https://community.auth0.com/t/new-javascript-sdk-for-single-page-applications-in-beta

**Comment by bobbydowling** [comment]
@nate-eisner @colingreene28 , what solution did you end up going with? I have the same issue with Auth Lock. Works fine for Android, but can't use it with iOS, because of the unique scheme.

@luisrudge I tried using the SPA version, which works nicely otherwise however, I could not get it to work with Capacitor. Kept getting "connection refused" on callback after successful auth. Seems to be an issue with Capacitor... or me.

**Comment by nate-eisner** [comment]
> @nate-eisner @colingreene28 , what solution did you end up going with? I have the same issue with Auth Lock. Works fine for Android, but can't use it with iOS, because of the unique scheme.
> 
> @luisrudge I tried using the SPA version, which works nicely otherwise however, I could not get it to work with Capacitor. Kept getting "connection refused" on callback after successful auth. Seems to be an issue with Capacitor... or me.

@bobbydowling I ended up having to write a native auth flow on both platforms to work around this problem. Then, passing a token to the web app. The web app was able to refresh if needed.

**Comment by brassier** [comment]
I am running across this same problem now with Capacitor and the SPA SDK.  As I understand it, the SPA SDK uses the Auth Code + PKCE flow.  @luisrudge - is it possible to adjust the code called out here now if it's not using the implicit flow?
