### ISSUE TITLE
changePassword method ignores password

### ISSUE THREAD

**Issue by ryanburr** [auth0/auth0.js#926]
### Description

According to the [Authentication API](https://auth0.com/docs/api/authentication#change-password) and the [auth0-js type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/auth0-js/index.d.ts#L616), `changePassword` should accept an optional password to attempt to reset to. But according to [responses in the community](https://community.auth0.com/t/auth0-nodejs-client-password-is-not-allowed/7540/2), this is a deprecated workflow.

When calling the `changePassword` method on the auth instance with a password, it is left off of the request.

1. Is this really a deprecated workflow? If yes, then the @types and API docs need to be updated.
2. If it is not, `'password'` should be added to the body of the [changePassword request](https://github.com/auth0/auth0.js/blob/master/src/authentication/db-connection.js#L99).

Looking for some direction on how to fix this.

### Environment

- Versions
  - auth0-js@9.10.0
  - @types/auth0-js@8.11.11

### Reproduction

**Call to library**
```js
auth0.changePassword({
  email: 'test@test.com',
  password: 'new_password',
  connection: 'my_connection'
}, cb);
```

**Request URL**
```
https://my_domain/dbconnections/change_password
```
**Network request body**
```js
{
  clientID: 'my_client_id',
  connection: 'my_connection',
  email: 'test@test.com'
}
```

**Comment by luisrudge** [comment]
We don't control the types, but I'll open a PR to update the docs. Thanks for pointing this out.

**Comment by ryanburr** [comment]
Thanks for the quick response. Sounds like this is a deprecated workflow then. I'll open a PR with the @types library

**Comment by luisrudge** [comment]
docs PR here: https://github.com/auth0/docs/pull/7532

**Comment by ryanburr** [comment]
types PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34947
