### ISSUE TITLE
Module now broken in ember

### ISSUE THREAD

**Issue by kelseythejackson** [auth0/auth0.js#927]
### Description

Potentially, some changes undet the hood of ember have cause this module to no longer work in Ember. I followed the ember quickstart tutorial and I get an route processing error.

### Environment

Please provide the following:

- Version of Auth0.js used: `"^9.10.2"`
- Browser and OS version(s) affected: All browsers affected

### Reproduction

If you follow the emberjs quickstart [here](https://auth0.com/blog/build-and-authenticate-an-emberjs-3-application/) you will get the following error:

```
Error while processing route: index Assertion Failed: You attempted to access `auth.checkLogin` (on `<(unknown mixin):ember217>`), but `auth` is a computed property.

Due to certain internal implementation details of Ember, the `auth` property previously contained a private "descriptor" object, therefore `auth.checkLogin` would have been `undefined`.

This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `auth` on this object will return the computed property's current value (see RFC #281 for more details).

If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.
```

**Comment by luisrudge** [comment]
Thanks! I'll report this to the author.

**Comment by kelseythejackson** [comment]
@luisrudge happy to help, though I just reported the issue, not fixed it. Should this be close?

**Comment by luisrudge** [comment]
I closed because it's not an SDK issue. I reported this to the Author of the blog post.

**Comment by TheKidCoder** [comment]
To anyone else that comes across this issue - this is due to an incompatiblity with ES5 getters and ember.

To get around it for now, you need to access the `auth` service using `get`. For example:
Breaks:
```
export default Controller.extend({
  auth: service('auth'),
  actions: {
    login() {
      this.auth.login();
    }
  }
});
```

Works:
```
export default Controller.extend({
  auth: service('auth'),
  actions: {
    login() {
      this.get('auth').login();
    }
  }
});
```
