### ISSUE TITLE
Bad handled Winchan result.error

### ISSUE THREAD

**Issue by cristiandouce** [auth0/auth0.js#93]
From any `winchan.open` callback we should expect an `err` from winchan and a `result.error`

That is not happening here:

![image](https://cloud.githubusercontent.com/assets/367429/8293621/24905e4e-190d-11e5-8dd6-2cfbf413cba1.png)

That is a typo unless there is any `edge` case I'm missing.

@pose Would you mind confirm this? You were the last one to modify those error handlers
https://github.com/auth0/auth0.js/blame/master/index.js#L1051
Thanks!

**Comment by pose** [comment]
https://github.com/auth0/auth0-server/blob/master/views/popup.ejs#L74

**Comment by cristiandouce** [comment]
still, the result gets an `error` instead of `err` property :stuck_out_tongue_winking_eye: 
We need to debug this because blocks the rules custom error implementation auth0/lock#86

**Comment by pose** [comment]
What error are you getting when you close the popup?

**Comment by cristiandouce** [comment]
Some error ocurred on the signin.

Some unhandled default error.

**Comment by cristiandouce** [comment]
Fixeeeeeeeeeeddddd! :dancers:
