### ISSUE TITLE
use legacyError in checksession

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#932]
The error format in the checkSession call is wrong. we need to use `forceLegacyError:true` to make sure we don't break everyone.

https://github.com/auth0/auth0.js/issues/861#issuecomment-434240816

**Comment by karelit0** [comment]
What is the status of this?

I have a wordpress application and SinglePageApplication with Angular and the session is not shared for both. 

If the user logged in wordpress and want to go to angular application he has to login again.
and the same case when the user logged in angular and want to go to wordpress

**Comment by luisrudge** [comment]
@karelit0 I'm not sure if this issue is relevant to your scenario. looks like you want single sign on in your apps instead?

**Comment by karelit0** [comment]
I am using SSO.

But for some reason when the user log in wordpress (using auth0) and then change to SPA, using the same tenant, auth0 does not recognize the previuos session.

To check the previous session I am using the checksession function, and it is returing always require_login, and on logs is fsa (Fail Salient Auth).

Let me tell you that this process was working fine last week.

I do not know if this issue affect me, but looking into the all history of this issue looks like yes

**Comment by luisrudge** [comment]
It’s unlikely this issue is affecting you. This is a client side error that causes the error response to be in a different format than expected. It has nothing to do with SSO or with the server response `login_required` that you’re receiving. I suggest you open a ticket at https://support.auth0.com so our Support team can look into it for you.
