### ISSUE TITLE
how to build a custom lock?

### ISSUE THREAD

**Issue by gex** [auth0/auth0.js#935]
### Description

we used this library to redirect our users to the hosted login page. it was confusing for them to be on a different url and see a login screen with different theming and colors than our application, etc. also that flow had too many steps like a login button on our main page then the hosted login page then the google login page. later on we decided to skip the login button and redirect them instantly to the hosted login page but it was more confusing. sometimes we got error report about an auth0 error screen when people opened the app, got redirected to the login page then left it there for hours or sometimes the whole night before they actually logged in.

we tried to migrate our solution to auth0-lock and we loved the simplified flow but we run into the [problem](https://github.com/auth0/lock/issues/113) with its size. since we use only one enterprise g suite connection it would be better for us to render that specific login button on our end. as far as i see the auth0 lock fetches the client along with the strategies to do that.

is it doable with this library? i tried to find something strategy, enterprise or connection related thing in the docs unsuccessfully. can you please guide me on a high level?

### Prerequisites

- [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

**Comment by luisrudge** [comment]
Universal login is still the best way to authenticate users. We're testing a new layout (https://auth0.com/docs/universal-login/new) that can be somewhat customized to fit your needs.

If you want to build a custom form, you'll use:
- `authorize` to login with google
- `login` to login with username/password

Also, please refer to this doc: https://auth0.com/docs/libraries/when-to-use-lock (our docs site is down right now, but should be back in a few minutes)

**Comment by gex** [comment]
hi @luisrudge, thank you for your help!

i think i was getting lost between the different versions of the documentation. the README of this package has ["full API documentation"](https://auth0.github.io/auth0.js/index.html) link (A) and ["complete reference and exmaples"](https://auth0.com/docs/libraries/auth0js/v9) link (B). on the top of that page there is also the ["full API documentation"](https://auth0.github.io/auth0.js/index.html) link (A). and there is this [Universal Login Page Customization](https://auth0.com/docs/libraries/when-to-use-lock) page which refers to the [Authentication API](https://auth0.com/docs/api/authentication) (C).

on [link A](https://auth0.github.io/auth0.js/index.html) (which seems like the most authentic docs for this package) the `connection` parameter of the `authorize()` method is not even mentioned. on [link B](https://auth0.com/docs/libraries/auth0js/v9) the description is `"Specifies the connection to use rather than presenting all connections available to the application."` on [link C](https://auth0.com/docs/api/authentication) it's `"The name of a social identity provider configured to your application, for example google-oauth2 or facebook. If null, it will redirect to the Auth0 Login Page and show the Login Widget."`.

after reading all of the pages above now it's clear that we need to specify the `connection` parameter to redirect our users to the google login page directly. to be able to provide that i'd fetch the available connections from auth0 but since the once existing`getConnections()` method [got removed](https://github.com/auth0/auth0.js/issues/196) it's not that easy.

do you have any plans to add that functionality to this package again?

**Comment by luisrudge** [comment]
@gex we don't have plans to introduce that feature again, but social connections have fixed names, so you can use `webAuth.authorize({connection: 'google-oauth2'})`.
