### ISSUE TITLE
How to change phone number associated with guardian MFA

### ISSUE THREAD

**Issue by mitch1995** [auth0/auth0.js#936]
Hello,

I want to be able to change a user's phone number that is associated with their guardian MFA. I can't see any 'update' endpoints so I figured I could just add a new authenticator, and once the new authenticator has been verified I would simply remove the old one.

The endpoint to add a new authenticator is “mfa/associate”; the documentation for this endpoint mentions “If the user has active authenticators, an Access Token with the enroll scope and the audience set to https://YOUR_DOMAIN/mfa/ is required to use this endpoint. After an authenticator is added, it must be verified. To verify the authenticator, use the response values from the /mfa/associate request in place of the values returned from the /mfa/challenge endpoint and continue with the verification flow.”

This endpoint behaves as expected and returns an object as follows. It will also send a text message to the phoneNumber provided in the request parameter. 

{
  "access_token":"eyJz93a...k4laUWw",
  "token_type":"Bearer",
  "expires_in":86400,
  "recovery_code": "abcdefg"
}

The problem is when it comes to the next step of actually verifying the phone number the verification endpoint “/oauth/token” requires a mfa_token, which we do not have (as we already have an active authenticator). This has left confusion due to the fact that the ‘add authenticator’ endpoint and documentation mentions you can use an access token in place of a mfa_token, yet when it comes to the verification step the mfa_token is suddenly required. 

The documentation for the two end points are as follows: 
•	Add Authenticator: https://auth0.com/docs/api/authentication#add-an-authenticator
•	Verify with out-of-band (OOB): https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-

Any help would be appreciated, 

Thanks,
Mitchell

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by stszap** [comment]
Hello, not sure if this problem is still relevant but I think you were going in the right direction. In my experiments, I was able to use access_token (with `https://YOUR_DOMAIN/mfa/` audience) instead of mfa_token to associate and verify new MFA devices. Here is the demo app I made to demonstrate that https://github.com/HeliosCompliance/auth0-mfa-web-example
