### ISSUE TITLE
IdTokenPayload, snake_casing has been converted to camelCasing in 9.10.3

### ISSUE THREAD

**Issue by simplenclean** [auth0/auth0.js#942]
### Description
Bug:

When our dev + stage build updated to `auth0-js` 9.10.3 from 9.10.2, the idTokenPayload has turned all snake-casing into camel-casing

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

Auth0-js: 9.10.3
Browser: Chrome (latest), Firefox(latest), Safari(latest), MacOs(latest)

### Reproduction

I've already fixed the error on our environments for now by reverting to 9.10.2 

Here are screenshots of the problem vs intended behavior however.

Problem:
<img width="752" alt="Screen Shot 2019-05-24 at 1 05 33 PM" src="https://user-images.githubusercontent.com/24517115/58350385-5a963e00-7e2b-11e9-8ad1-9291ac39cd71.png">

Intended:
<img width="751" alt="Screen Shot 2019-05-24 at 1 54 08 PM" src="https://user-images.githubusercontent.com/24517115/58350443-83b6ce80-7e2b-11e9-9fd1-fb7ee6510b96.png">

**Comment by luisrudge** [comment]
ouch! my bad. I'm patching this *right now*

**Comment by luisrudge** [comment]
This fix was released in 9.10.4. Sorry for the trouble!

**Comment by simplenclean** [comment]
@luisrudge No problem, thanks!
