### ISSUE TITLE
Reduce Bundle Size

### ISSUE THREAD

**Issue by wpitallo** [auth0/auth0.js#945]
Is there a way to reduce or only import specific modules? Currently auth0.js has the biggest footprint in my vendor bundle and it seems a bit excessive?

![image](https://user-images.githubusercontent.com/12214559/58374935-514ec380-7f48-11e9-9ca1-a1c06e68a1ba.png)

**Comment by luisrudge** [comment]
We just release the beta of the new SDK for Single Page Applications. Check it out, it's pretty small!
https://community.auth0.com/t/new-javascript-sdk-for-single-page-applications-in-beta/25087
![image](https://user-images.githubusercontent.com/941075/58375459-d8407380-7f29-11e9-99ab-e21fb2761797.png)

As for Auth0.js, it is big because it supports everything that Auth0 itself supports and it wasn't built with tree shaking in mind, since there was no such thing at the time.

**Comment by wpitallo** [comment]
Awesome thanks, when do you expect it will be ready for production?

**Comment by wpitallo** [comment]
Thanks @luisrudge, had a quick look, one question tho, how do we read the access_token using this new sdk? 

Also is there anyway to check manually in local storage etc if a user is authenticated. The old sdk had isLoggedIn flag?

**Comment by luisrudge** [comment]
> Awesome thanks, when do you expect it will be ready for production?

We don't have an ETA for the production release, we actually rely on feedback from the community to make sure it attends what the community is asking 😬 

> Thanks @luisrudge, had a quick look, one question tho, how do we read the access_token using this new sdk?

> Also is there anyway to check manually in local storage etc if a user is authenticated. The old sdk had isLoggedIn flag?

**Comment by wpitallo** [comment]
@luisrudge so I have been trying for the past 10 min to log on the community forum and just cant get in. 

I cant get past this screen: 
![image](https://user-images.githubusercontent.com/12214559/58405673-48551380-8068-11e9-911a-bbd418bf84d3.png)

Giving up now

**Comment by luisrudge** [comment]
@wpitallo  I pinged the community team about this. Give us a moment to figure this out. Thanks for the patience.

**Comment by JimCMorrison** [comment]
Hey @wpitallo, I have sent an activation email to your primary email account. When you receive the email please follow the link and you should be set! However please let me know if you have any questions on this front!

**Comment by wpitallo** [comment]
Thanks very much

**Comment by shavo007** [comment]
![Screenshot 2019-05-29 at 16 09 36](https://user-images.githubusercontent.com/5466825/58533720-974ba600-822c-11e9-9b77-6fe19b93375e.png)

+1 this dep is huuuuuggeeee...

**Comment by shavo007** [comment]
@luisrudge  so is this dep https://github.com/auth0/auth0-spa-js backwards compatiable with the old?

**Comment by luisrudge** [comment]
@shavo007 no. The migration guide is expected to land when we release the final v1.0.0. But, if the only thing you used was `webAuth.authorize`, then the migration is super easy.

**Comment by isaachinman** [comment]
@luisrudge What feedback do you need from the community in order to progress with the release?

**Comment by luisrudge** [comment]
@isaachinman we're looking for all kinds of feedback 😬 

- is the API what you'd expect?
- does it solve all your requirements?
- if not, what's missing?

**Comment by wpitallo** [comment]
Hi @luisrudge has this moved? Getting this when following the link:
![image](https://user-images.githubusercontent.com/12214559/63337526-6b2e5580-c341-11e9-8855-80c858bdcfd7.png)

https://community.auth0.com/t/new-javascript-sdk-for-single-page-applications-in-beta/25087

**Comment by luisrudge** [comment]
@wpitallo it did, but we already launched it: https://github.com/auth0/auth0-spa-js

**Comment by PepijnSenders** [comment]
Hey! Why is the bundle size of auth0-spa-js as big as the old one now?

https://bundlephobia.com/result?p=@auth0/auth0-spa-js@1.13.5
