### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by ellioseven** [auth0/auth0.js#951]
The `README.md` documents a method `patchUserAttributes` that hasn't been released yet.

I would really love to see this method released as it's going to be extremely for my current situation.

Can we get a new release to publish this method? Or can I get any information on when the next release will be?

Thanks

**Comment by luisrudge** [comment]
we're aiming for early next week.

**Comment by duartegarin** [comment]
Amazing @luisrudge , thanks for the quick turnaround.
