### ISSUE TITLE
nonce can no longer be optional

### ISSUE THREAD

**Issue by Pyrolistical** [auth0/auth0.js#953]
I don't set an optional nonce, so I was confused when I got the error `Nonce does not match.`

I tracked it down to this line in the code:
https://github.com/auth0/auth0.js/blob/8fad70ebf0eeab0629a7e9d5dd9f6d69aedde211/src/web-auth/index.js#L297

`decodedToken.payload.nonce` is `undefined` as expected
`transactionNonce` is `null` as expected

but `undefined !== null` is true. The usage of `null` in this case is the bug.

**Comment by luisrudge** [comment]
Thanks @Pyrolistical! I'm fixing this ASAP.

**Comment by luisrudge** [comment]
Fix is here: https://github.com/auth0/auth0.js/issues/953 We didn't have a test for an id_token with an empty nonce 😭 - but we do now.  Sorry about that!

**Comment by luisrudge** [comment]
released in 9.11.1
