### ISSUE TITLE
patchUserAttributes: You cannot update the following fields

### ISSUE THREAD

**Issue by ellioseven** [auth0/auth0.js#960]
### Description

I am trying to use the management API to update user attributes such as `given_name`, `family_name`, etc. in my client side app.

I have used the following resources:

- https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id
- https://github.com/auth0/auth0.js#api-2

However, I keep getting the following error message:

```
You cannot update the following fields: given_name, family_name, email
```

My scopes:

```
scopes = [
    "openid",
    "email",
    "profile",
    "app_metadata",
    "given_name",
    "family_name",
    "email",
    "read:current_user",
    "read:user_idp_tokens",
    "update:current_user_metadata",
    "update:current_user_identities"
  ]
```

My update method:

```
// Exit early if user is not authenticated.
if (!accessToken || !userId) return

// Create management object.
const management = new auth0.Management({
  domain: auth.config.domain,
  token: accessToken
})

// Format values.
const _values = Object.entries(values).reduce((values, entry) => {
  const [ key, value ] = entry
  const _key = toSnakeCase(key)
  values[_key] = value
  return values
}, {})

// Remove falsey password.
if (!_values["password"]) delete _values["password"]

self.setState({ isLoading: true })
management.patchUserAttributes(userId, _values, (err, result) => {
  console.log(_values)
  console.log(err, result)
  actions.setSubmitting(false)
  self.setState({ isLoading: false })
})
```

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: `9.11.1`

**Comment by luisrudge** [comment]
Tokens issued for SPAs still can't update those fields. We're working in adding support for this in the near future, but we have no ETAs for this yet. For now, we have a couple of suggestions:

- The user can set its `user_metadata` and the tenant admin can configure a rule to update root values or only return updated values in the token
- The tenant admin can do that through an internal endpoint on their system that calls Management API with user write scope

**Comment by picosam** [comment]
@luisrudge so this is not valid? https://community.auth0.com/t/both-spa-and-auth-js-sdks-in-a-react-app/39199
