### ISSUE TITLE
getUser return Bad Request error

### ISSUE THREAD

**Issue by whitesnow9291** [auth0/auth0.js#961]
I am going to get user info of registered in app.

What I have tried is this.
```
const auth0management = new auth0.Management({
      domain: AUTH_CONFIG.domain,
      token: accessToken
    });
    if (auth0management) {
      auth0management.getUser("auth0|5d0ae112feb0620f0a5471df", (err,res)=>{
        console.info(err)
      })
    } else {
      callback(null)
    }
```
And the err is like this

![Screen Shot 2019-07-03 at 11 17 16 AM](https://user-images.githubusercontent.com/25058760/60558428-33188680-9d84-11e9-8ef2-0656be893e1d.png)

I am using ```"auth0-js": "^9.11.1",```

Thanks

**Comment by luisrudge** [comment]
@whitesnow9291 are you trying to get your own user information? If not, do you have the necessary scopes in that access token? I'm closing the issue because it doesn't look like an SDK issue, but feel free to answer the questions in this issue anyway.
