### ISSUE TITLE
Continuous redirects in Firefox

### ISSUE THREAD

**Issue by giri-nitesh** [auth0/auth0.js#962]
I have set up a SPA with auth0 in angular. While using Firefox browser, after going to the authentication page, after entering credentials, it cannot redirect to the specified page. However, while using Chrome and Edge it works fine. Is there any known issue with FireFox Browser?
I get the following error in console:

> Object { 
error: "invalid_token", 
errorDescription: "Request has been terminated\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."
 }

### Description

```
public handleAuthentication(): void {
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken && authResult.idToken) {
        window.location.hash = '';
        this.localLogin(authResult);
        this.router.navigate(['/home']);
      } else if (err) {
        // this.router.navigate(['/home']);
        console.log(err);
      }
    });
  }
```
For Firefox, authResult is null while for other browsers, auth0 returns a valid token.

I checked on auth0 community page and see the similar problem 

> https://community.auth0.com/t/continuous-redirect-to-authentication-in-firefox/7426 

However I did not get any solution for this.
PFA screenshot for more clarity.
![Screenshot (32)_LI](https://user-images.githubusercontent.com/24621371/60582584-be0a7880-9da6-11e9-8a5c-8697182ffa57.jpg)

### Environment
- Version of Auth0.js used: 9.10.2
- Browser and OS version(s) affected: Firefox

**Comment by luisrudge** [comment]
Can you build a simple repro so I can test?

**Comment by luisrudge** [comment]
Also, a HAR file would be very valuable to debug this. This is probably 3rd party cookies being blocked, but we need more information to debug it.

**Comment by giri-nitesh** [comment]
@luisrudge Following is the link of the sample repo:
https://drive.google.com/open?id=1x6z8dpR7YNAlVujyaZ-ZyFSBZskQeZN5

**Comment by luisrudge** [comment]
Hi, this is probably a race condition in your app. I didn't dig too deep, but if I change your `auth.guard.ts` to always activate, firefox works just fine.

```
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return true;
}
```

Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by drjaat** [comment]
@luisrudge return true in authguard means we are not checking for any condition. if user is authenticated or not.

**Comment by luisrudge** [comment]
I know, I just wanted to rule out any Auth0.js specific issue. By changing that code to always return true, it becomes clear that the issue lies in your code, since the authentication happens correctly. There's probably a race condition somewhere where you set the user as authenticated or where you redirect the user.

We have an amazing quick start written with our new SDK if you want to give it a try: https://auth0.com/docs/quickstart/spa/angular2/01-login

**Comment by drjaat** [comment]
if there is issue in the code then why the race condition not happening in other browser :P

**Comment by luisrudge** [comment]
It did happen in Chrome for me, but it was just a double redirect, instead of entering a loop. Browsers work differently, so storage access etc might happen differently or at different times and that's what you're seeing.

**Comment by drjaat** [comment]
for me it is working perfectly fine in chrome

**Comment by drjaat** [comment]
isAuthenticated method is return false in case of firefox means it is not getting Authenticated

**Comment by luisrudge** [comment]
`isAuthenticated` is part of your code, that's what I'm saying. Somehow, this value is not being set in firefox. If you clone this repo and run `npm start`, you can test it in firefox and see that everything works as expected.

**Comment by drjaat** [comment]
![error](https://user-images.githubusercontent.com/22201670/60676848-8c280d80-9e9d-11e9-9b9c-881690c593e0.gif)
if you see jwks.json is not getting data
but if open in new tab it shows data

**Comment by luisrudge** [comment]
We had a similar issue before, see if it helps: https://github.com/auth0/auth0.js/issues/894#issuecomment-456829620

**Comment by tadeuhslima-fabricatrader** [comment]
> ![error](https://user-images.githubusercontent.com/22201670/60676848-8c280d80-9e9d-11e9-9b9c-881690c593e0.gif)
> if you see jwks.json is not getting data
> but if we open in new tab it shows data

@drjaat Do you get any luck solving this problem?

@luisrudge i'm getting the same issue here. Angular 9 works fine in crome, but firefox and anonymous crome tab it get false in auth problem. I can't think it's a code problem since isAuthenticated$ it returns 'true' in crome but false in firefox and anonymous. So "loggedIn" is true and false depending on the brownser....

https://community.auth0.com/t/angular-9-application-with-auth0-keeps-on-redirecting-after-successful-login-in-firefox/41394/5

Thanks for the help

**Comment by MerzDaniel** [comment]
This issue still is a thing. In my firefox I'm getting redirect loops

**Comment by falaxfala** [comment]
Bump here. Refresh token rotation can't help with this.
