### ISSUE TITLE
How to use checkSession without setting `Allowed web origins` ?

### ISSUE THREAD

**Issue by norayr93** [auth0/auth0.js#966]
### Description

I have a problem with `checkSession` method. My goal is to do a silent authentication for keeping users logged in while they are active.In order to use checkSession i need to set `Allowed web origins` in my auth0 setup, but auth0 doesn't recomend this approach as it is not secure. On the other hand, docs recommend using `Universal login` for SPA.I think it is not applicable to my situation , beacuse in universal login terms `Each time a user needs to prove their identity, your applications redirect to Universal Login and Auth0 will do what is needed to guarantee the user's identity.` But i need to make it silent. What should i use in this certain situation ?

**Comment by luisrudge** [comment]
> In order to use checkSession i need to set Allowed web origins in my auth0 setup, but auth0 doesn't recomend this approach as it is not secure.

That's not true at all. Setting your Allowed Web Origins is *the correct and secure* way of doing silent authentication. Where did you read that this is not recommended?

**Comment by norayr93** [comment]
Parts from auth0 docs .
`Auth0 strongly recommends that authentication transactions be handled via Universal Login. Doing so offers the easiest and most secure way to authenticate users. However, some situations may require that authentication forms be directly embedded in an application. Cross-origin authentication provides a way to do this however it is not recommended.`

`Cross-origin authentication is not recommended and is only necessary when authenticating against a directory using a username and password. Social IdPs and enterprise federation use a different mechanism, redirecting via standard protocols like OpenID Connect and SAML. Additionally, cross-origin authentication is only applicable to embedded login on the web (using Lock or auth0.js). Native applications using embedded login make use of the standard OAuth 2.0 token endpoint.`

Maybe i misunderstood some aspects of it?

**Comment by luisrudge** [comment]
Yeah, you misunderstood. `checkSession` is absolutely fine to use it to renew a token. https://auth0.com/docs/cross-origin-authentication this page is talking about using cross origin authentication (`webAuth.login({username, password})`). We don't recommend that because it might cause issues when 3rd party cookies are blocked.

**Comment by norayr93** [comment]
Great , thank you very much
