### ISSUE TITLE
Don't expect `window` to exist

### ISSUE THREAD

**Issue by HenrikJoreteg** [auth0/auth0.js#98]
For those of us who like to build "universal" (a.k.a. isomorphic) apps, this causes issues when doing `require('auth0-js')` in node.

Not saying everything has to work, but it'd be cool if it didn't error, something like this:

```js
if (typeof window !== 'undefined') {
  // here you can safely reference `window`
}
```

Also, would suggested testing in both browserify and webpack as they're slightly different and webpack keeps growing in popularity.

**Comment by cristiandouce** [comment]
AFAIK this lib was never intended to work on node. For that we have https://github.com/auth0/node-auth0

Same thing concluded from auth0/auth0.js/issues/85

**Comment by cristiandouce** [comment]
Sorry, replying to the webpack topic. Yes, we have intentions to try it out soon! :smile: Thanks!

**Comment by HenrikJoreteg** [comment]
For what it's worth, I'd settle for "doesn't blow up when I require it" from node :)

The reason this matters is the cases where you pre-render basic layout/html by requiring and running part of your app in node on the server-side. 

This approach is certainly a trend among folks who are building single page apps: https://blog.andyet.com/2015/05/18/lazymorphic-apps-bringing-back-static-web

I can work around it, just figured I'd raise it. /me shrugs

**Comment by cristiandouce** [comment]
Could you provide an example (code or public repo) of this way of usage you explain?

Again I tell this was never the design of this lib. And I'd be quite more difficult that a simple `typeof window !== 'undefined'` from my understanding.

**Comment by HenrikJoreteg** [comment]
Sure, so...

this repo: https://github.com/henrikjoreteg/hubtags.com
makes this app: http://hubtags.com

In the build-step on this line: 

https://github.com/HenrikJoreteg/hubtags.com/blob/master/webpack.config.js#L16 

We're rendering the `Layout` React component that's required at the top of the file. This build step gets run by node to generate all the static assets for the site, which is then deployed as a completely static set of HTML, CSS, JS files (as described in the readme of that project).

However, if inside that `Layout` there had been a `require('auth0-js')` at the top, **even if it didn't use the code from the module to do anything during the build step** it would break the build. 

I'm not saying I expect to be able to log in with Auth0 during that build step, that would be quite odd. But it would be cool if this library was tolerant of being `require`'ed during the build process without erroring even if it just exported an empty object or whatnot. 

For whatever it's worth I tweeted (non-specifically) about this type of behavior and a few folks seem to agree: https://twitter.com/HenrikJoreteg/status/629001369454710784 

Anyway, no big deal if you don't want it to work that way, I can deal with it in my app by doing the `require` inside a `if (typeof window !== 'undefined')` block. Just would be neat if I didn't have to do that.

Cheers!
