### ISSUE TITLE
Support webpack

### ISSUE THREAD

**Issue by HenrikJoreteg** [auth0/auth0.js#99]
Relying on browserify transforms like: https://github.com/auth0/packageify

means that this line https://github.com/auth0/auth0.js/blob/693119699993aa8cc81abf3dfeae3c5a6f11273a/index.js#L167 fails if using webpack.

Ideally I'd be able to just npm install it and require it from webpack too. <3

**Comment by cristiandouce** [comment]
Ain't there any browserify transform for webpack?

**Comment by jfromaniello** [comment]
What can we do to avoid packageify without including the entire package.json in the bundle and without the need of the version number in a different file?

**Comment by HenrikJoreteg** [comment]
You could have a build script just write it in dynamically.

**Comment by HenrikJoreteg** [comment]
Thanks for the quick feedback on this. I <3 auth0 and just want to help make it better so I'm reporting the issues I hit.

To answer your question @cristiandouce, there are transform-like things for webpack it's incredibly pluggable, but they don't work quite the same and basically anyone who tries to use this with webpack will hit and have to solve this issue.

**Comment by ferdinandsalis** [comment]
Yup, I am having problems with webpack. Currently getting this error

```
buffer.js:219
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:219:9)
    at Stream.<anonymous> (/Users/ferdinand/Code/bridge-webapp/node_modules/transform-loader/index.js:33:19)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at Stream.end (/Users/ferdinand/Code/bridge-webapp/node_modules/packageify/index.js:21:10)
    at _end (/Users/ferdinand/Code/bridge-webapp/node_modules/packageify/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/ferdinand/Code/bridge-webapp/node_modules/packageify/node_modules/through/index.js:74:5)
    at next (/Users/ferdinand/Code/bridge-webapp/node_modules/transform-loader/index.js:49:10)
    at /Users/ferdinand/Code/bridge-webapp/node_modules/transform-loader/index.js:21:4
    at /Users/ferdinand/Code/bridge-webapp/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
```
Setup from https://github.com/auth0/lock/blob/master/examples/webpack/webpack.config.js

Everything not very straightforward. I really like auth0 however I might need to reconsider using it. Still trying to get around that though.

**Comment by jfromaniello** [comment]
@HenrikJoreteg Hi , I removed packagify.. can you test with `6.6.4` ?

Thank you!
