### ISSUE TITLE
Sign in as User

### ISSUE THREAD

**Issue by johnstontrav** [auth0/auth0.js#998]
Hey guys,

The Auth0 "Sign in as User" function has never work for me.  Im here to table a simple solution. 

Idea:
To impersonating a user, generate a complex OTP (auto expire after 60sec) from the Auth0 Dashboard.  That OTP can be used just like a normal username/pwd ... down the same pipes etc.  Would make our job much easier.

**Comment by luisrudge** [comment]
duplicate of https://github.com/auth0/auth0.js/issues/683
