### ISSUE TITLE
appState is missed in Typescript definition

### ISSUE THREAD

**Issue by fetis** [auth0/auth0.js#999]
### Description

The library supports `appState` parameter to keep some arbitrary data during the login, but its definition is missed in `@types/auth0-js`

### Prerequisites

[x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x]  I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: 9.11.2
- Browser and OS version(s) affected: N/A
- Additional libraries or browser extensions being used that might affect behavior:
@types/auth0-js: 9.10.2

### Reproduction
<img width="357" alt="Screen Shot 2019-07-26 at 17 06 03" src="https://user-images.githubusercontent.com/577042/61961465-cfbaf680-afc7-11e9-99ac-05c29ebe962e.png">

Please include:
```
    this.auth0Client.authorize({
      appState: 'test'
    });
```

TS error
```
Error:(27, 7) TS2345: Argument of type '{ connection: string; appState: string; }' is not assignable to parameter of type 'AuthorizeOptions'.
  Object literal may only specify known properties, and 'appState' does not exist in type 'AuthorizeOptions'.
```

**Comment by luisrudge** [comment]
Those definitions are community maintained. You should probably open an issue/PR in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by fetis** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37201
